import Foundation

/// Every piece of UI copy, in both interface languages.
/// The interface language is always the learner's native language.
enum S {
    static func t(_ it: String, _ uz: String) -> Bilingual { Bilingual(it: it, uz: uz) }

    // Onboarding
    static let welcome        = t("Benvenuta in Uzbelia!", "Uzbeliaga xush kelibsiz!")
    static let welcomeSub     = t("Italiano e uzbeko, dall'A1 al B2.", "Italyancha va o'zbekcha, A1 dan B2 gacha.")
    static let pickCourse     = t("Che lingua vuoi imparare?", "Qaysi tilni o'rganmoqchisiz?")
    static let learnUz        = t("Uzbeko", "O'zbek tili")
    static let learnIt        = t("Italiano", "Italyan tili")
    static let iSpeak         = t("Parlo italiano", "Men italyancha gapiraman")
    static let iSpeakUz       = t("Parlo uzbeko", "Men o'zbekcha gapiraman")
    static let pickLevel      = t("Da dove vuoi partire?", "Qayerdan boshlaymiz?")
    static let pickLevelSub   = t("Puoi sempre cambiare più tardi.", "Keyin istalgan vaqtda o'zgartirasiz.")
    static let fromZero       = t("Parto da zero", "Noldan boshlayman")
    static let pickGoal       = t("Qual è il tuo obiettivo giornaliero?", "Kunlik maqsadingiz qanday?")
    static let goalCasual     = t("Tranquillo", "Yengil")
    static let goalRegular    = t("Costante", "Muntazam")
    static let goalSerious    = t("Serio", "Jiddiy")
    static let goalIntense    = t("Intenso", "Jadal")
    static let minPerDay      = t("min al giorno", "daqiqa/kun")
    static let start          = t("Iniziamo!", "Boshladik!")

    // Tabs
    static let tabPath        = t("Percorso", "Yo'l")
    static let tabPractice    = t("Allenati", "Mashq")
    static let tabGrammar     = t("Grammatica", "Grammatika")
    static let tabProfile     = t("Profilo", "Profil")

    // Path
    static let unit           = t("Unità", "Bo'lim")
    static let level          = t("Livello", "Daraja")
    static let continueLesson = t("Continua", "Davom etish")
    static let startLesson    = t("Inizia", "Boshlash")
    static let repeatLesson   = t("Ripeti", "Takrorlash")
    static let locked         = t("Bloccato", "Qulflangan")
    static let lockedMsg      = t("Completa la lezione precedente per sbloccarla.", "Buni ochish uchun oldingi darsni tugating.")
    static let jumpHere       = t("Sblocca questo livello", "Bu darajani ochish")
    static let jumpHereMsg    = t("Sbloccherai subito tutte le unità di questo livello. Sicura?", "Ushbu darajaning barcha bo'limlari ochiladi. Ishonchingiz komilmi?")
    static let unlockedAlready = t("Già sbloccato", "Allaqachon ochilgan")
    static let unitReview     = t("Ripasso dell'unità", "Bo'lim takrori")
    static let story          = t("Dialogo", "Dialog")
    static let guidebook      = t("Note di grammatica", "Grammatika qaydlari")
    static let keyWords       = t("Parole chiave", "Asosiy so'zlar")

    // Knowledge checks
    static let testTitle      = t("Test di verifica", "Bilim sinovi")
    static let testQuestions  = t("domande", "savol")
    static let testPassMark   = t("Serve almeno", "Kamida kerak:")
    static let testMistakes   = t("Errori consentiti:", "Ruxsat etilgan xatolar:")
    static let testNoHearts   = t("Niente cuori: puoi solo sbagliare troppo", "Yuraklar yo'q: faqat xato soni muhim")
    static let testStart      = t("Inizia il test", "Sinovni boshlash")
    static let testPassed     = t("Test superato!", "Sinovdan o'tdingiz!")
    static let testFailed     = t("Test non superato", "Sinovdan o'tilmadi")
    static let testPassedSub  = t("Sbloccato. Buon lavoro!", "Ochildi. Barakalla!")
    static let testFailedSub  = t("Riprova quando vuoi, oppure segui il percorso.", "Xohlagan vaqtda qayta urinib ko'ring yoki yo'ldan boring.")
    static let testUnlockNode = t("Sblocca con un test", "Sinov bilan ochish")
    static let testUnlockLevel = t("Sblocca il livello con un test", "Darajani sinov bilan ochish")
    static let testRetry      = t("Riprova il test", "Sinovni qayta urinish")

    // Sessions
    static let sessionOf      = t("Sessione", "Mashg'ulot")
    static let sessionPlan    = t("Le 5 sessioni di questa lezione", "Ushbu darsning 5 mashg'uloti")
    static let sessionDone    = t("Lezione completata al 100%", "Dars 100% tugallandi")

    // Unit practice
    static let unitPractice   = t("Ripassa un capitolo", "Bo'limni takrorlash")
    static let unitPracticeSub = t("Scegli un'unità già iniziata e riallenala tutta.", "Boshlangan bo'limni tanlang va to'liq takrorlang.")
    static let reviewThisUnit = t("Ripassa questa unità", "Shu bo'limni takrorlash")
    static let unitWords      = t("parole dell'unità", "bo'lim so'zlari")
    static let noUnitsYet     = t("Inizia un'unità per poterla ripassare.", "Takrorlash uchun avval bo'limni boshlang.")
    static let againAsYouLike = t("Ripeti quante volte vuoi: nessun cuore consumato.", "Xohlagancha takrorlang: yuraklar sarflanmaydi.")

    // Video call
    static let tabCall        = t("Chiama", "Qo'ng'iroq")
    static let callTitle      = t("Videochiamata", "Videoqo'ng'iroq")
    static let callSub        = t("Parla con Anorcha. Domande sempre diverse, sul capitolo a cui sei.", "Anorcha bilan gaplashing. Savollar har safar boshqacha, siz turgan bo'lim bo'yicha.")
    static let callPickLevel  = t("Scegli il livello della chiamata", "Qo'ng'iroq darajasini tanlang")
    static let callYouAreAt   = t("Sei arrivata a", "Siz shu yerdasiz:")
    static let callLevelLocked = t("Sblocca il livello per chiamare a questo livello.", "Bu darajada gaplashish uchun darajani oching.")
    static let callFreeAnswer = t("Rispondi come vuoi: nessun suggerimento, nessuna scelta.", "Xohlaganingizcha javob bering: maslahat ham, tanlov ham yo'q.")
    static let callCalling    = t("Chiamata in corso…", "Qo'ng'iroq qilinmoqda…")
    static let callHangUp     = t("Chiudi", "Tugatish")
    static let callTranslate  = t("Traduci", "Tarjima")
    static let callQuestionOf = t("Domanda", "Savol")
    static let callSpeakNow   = t("Tocca il microfono e rispondi", "Mikrofonni bosing va javob bering")
    static let callListening  = t("Ti ascolto…", "Eshityapman…")
    static let callWriteInstead = t("Scrivi la risposta", "Javobni yozing")
    static let callSkipTurn   = t("Non so rispondere", "Javob bera olmayman")
    static let callBuilding   = t("Sto rileggendo la conversazione…", "Suhbatni ko'rib chiqyapman…")
    static let callThinking   = t("Anorcha sta rispondendo…", "Anorcha javob yozyapti…")
    static let callAgain      = t("Nuova chiamata", "Yangi qo'ng'iroq")
    static let callNotReal    = t("Anorcha compone le domande dal capitolo a cui sei arrivata: cambiano a ogni chiamata.", "Anorcha savollarni siz yetgan bo'lim asosida tuzadi: har qo'ng'iroqda o'zgaradi.")
    static let callAIOn       = t("Domande e correzione scritte dall'IA", "Savollar va tuzatishlar sun'iy intellektdan")
    static let callAIOff      = t("Domande dal corso · correzione offline", "Savollar kursdan · tuzatish oflayn")

    // Call recap
    static let recapTitle     = t("Com'è andata", "Suhbat qanday o'tdi")
    static let recapAnswers   = t("Risposte", "Javoblar")
    static let recapWords     = t("Parole dette", "Aytilgan so'zlar")
    static let recapDistinct  = t("Parole diverse", "Turli so'zlar")
    static let recapTime      = t("Durata", "Davomiylik")
    static let recapTips      = t("Consigli", "Maslahatlar")
    static let recapDetail    = t("Risposta per risposta", "Javoblar bo'yicha")
    static let recapYouSaid   = t("Hai detto", "Siz aytdingiz")
    static let recapBetter    = t("Più naturale", "Tabiiyroq")
    static let recapNoIssues  = t("Niente da correggere qui.", "Bu yerda tuzatadigan narsa yo'q.")
    static let recapSkipped   = t("Saltata", "O'tkazib yuborilgan")
    static let recapShort     = t("Molto breve", "Juda qisqa")
    static let recapWrongLang = t("Lingua sbagliata", "Noto'g'ri til")
    static let recapOK        = t("Va bene", "Yaxshi")
    static let recapInstead   = t("invece di", "o'rniga")

    // Settings: optional AI
    static let aiTitle        = t("Assistente IA (facoltativo)", "Sun'iy intellekt (ixtiyoriy)")
    static let aiService      = t("Servizio", "Xizmat")
    static let aiKeyWhere     = t("Prendi la chiave su", "Kalitni bu yerdan oling:")
    static let aiKeyField     = t("Incolla qui la chiave", "Kalitni shu yerga joylashtiring")
    static let aiTest         = t("Prova la chiave", "Kalitni sinash")
    static let aiTesting      = t("Provo…", "Sinayapman…")
    static let aiWorks        = t("Funziona!", "Ishlayapti!")
    static let aiBuiltIn      = t("Chiave già inclusa nell'app: l'IA è attiva.", "Kalit ilovaga kiritilgan: sun'iy intellekt yoqilgan.")
    static let aiNote         = t("Con una chiave, domande e correzioni della videochiamata le scrive l'IA. Senza chiave l'app resta completamente offline.", "Kalit bilan videoqo'ng'iroq savollari va tuzatishlarni sun'iy intellekt yozadi. Kalitsiz ilova butunlay oflayn ishlaydi.")
    static let aiFreeHint     = t("Gemini ha un piano gratuito. Claude richiede credito a pagamento.", "Geminida bepul reja bor. Claude uchun pullik kredit kerak.")

    // Unlimited
    static let unlimited      = t("Illimitati", "Cheksiz")
    static let unlimitedRes   = t("Vite e gemme illimitate", "Cheksiz yurak va gavharlar")

    // Lesson
    static let checkAnswer    = t("Verifica", "Tekshirish")
    static let continueBtn    = t("Continua", "Davom etish")
    static let skip           = t("Salta", "O'tkazib yuborish")
    static let cantSpeak      = t("Non posso parlare ora", "Hozir gapira olmayman")
    static let correct        = t("Perfetto!", "Ajoyib!")
    static let almost         = t("Quasi! Attenzione allo spelling:", "Deyarli! Imloga e'tibor bering:")
    static let wrong          = t("Risposta corretta:", "To'g'ri javob:")
    static let alsoRight      = t("Va bene anche così!", "Bunday ham to'g'ri!")
    static let courseSays     = t("Nel corso:", "Kursda:")
    static let doubleChecking = t("Controllo…", "Tekshiryapman…")
    static let mineIsRightToo = t("Anche la mia è giusta", "Meniki ham to'g'ri")
    static let tapToSpeak     = t("Tocca e parla", "Bosing va gapiring")
    static let listening      = t("Ti ascolto…", "Eshityapman…")
    static let tapToHear      = t("Tocca per ascoltare", "Eshitish uchun bosing")
    static let heardYou       = t("Ho sentito:", "Men eshitdim:")
    static let transcribing   = t("Sto trascrivendo…", "Yozib olyapman…")
    static let yourAnswer     = t("La tua risposta:", "Sizning javobingiz:")
    static let typeHere       = t("Scrivi qui…", "Bu yerga yozing…")
    static let quitLesson     = t("Vuoi uscire dalla lezione?", "Darsdan chiqmoqchimisiz?")
    static let quitLessonMsg  = t("Perderai i progressi di questa lezione.", "Ushbu darsdagi yutuqlar yo'qoladi.")
    static let quit           = t("Esci", "Chiqish")
    static let stay           = t("Resta", "Qolish")
    static let noHearts       = t("Hai finito i cuori!", "Yuraklaringiz tugadi!")
    static let noHeartsMsg    = t("Aspetta che si ricarichino, oppure usa le gemme.", "Tiklanishini kuting yoki gavharlardan foydalaning.")
    static let refill         = t("Ricarica (100 💎)", "To'ldirish (100 💎)")
    static let practiceInstead = t("Allenati senza cuori", "Yuraksiz mashq qilish")
    static let nextHeartIn    = t("Prossimo cuore tra", "Keyingi yurak")
    static let minutesShort   = t("min", "daq")

    // Results
    static let lessonDone     = t("Lezione completata!", "Dars tugadi!")
    static let totalXP        = t("XP TOTALI", "JAMI XP")
    static let accuracy       = t("PRECISIONE", "ANIQLIK")
    static let time           = t("TEMPO", "VAQT")
    static let goodJob        = t("Bravissima!", "Barakalla!")
    static let keepGoing      = t("Continua così!", "Shu ruhda davom eting!")
    static let reviewMistakes = t("Ripassa gli errori", "Xatolarni ko'rib chiqish")

    // Practice
    static let practiceTitle  = t("Allenamento", "Mashqlar")
    static let practiceSub    = t("Rinforza quello che hai già visto.", "O'rganganingizni mustahkamlang.")
    static let mixedReview    = t("Ripasso misto", "Aralash takror")
    static let mixedReviewSub = t("Le parole che stai per dimenticare.", "Unutilish arafasidagi so'zlar.")
    static let mistakesDrill  = t("I tuoi errori", "Sizning xatolaringiz")
    static let mistakesSub    = t("Rifai quello che hai sbagliato.", "Xato qilgan narsalarni qayta ishlang.")
    static let skillDrill     = t("Allena un'abilità", "Ko'nikmani mashq qiling")
    static let noMistakes     = t("Nessun errore da ripassare. Brava!", "Takrorlaydigan xato yo'q. Barakalla!")
    static let notEnoughYet   = t("Fai qualche lezione per sbloccare l'allenamento.", "Mashqni ochish uchun bir nechta dars bajaring.")
    static let wordList       = t("Le mie parole", "Mening so'zlarim")
    static let strength       = t("Memoria", "Xotira")

    // Grammar
    static let grammarTitle   = t("Grammatica", "Grammatika")
    static let grammarSub     = t("Tutte le note del corso, sempre a portata.", "Kursdagi barcha qaydlar qo'l ostida.")
    static let examples       = t("Esempi", "Misollar")

    // Profile
    static let profileTitle   = t("Profilo", "Profil")
    static let statsStreak    = t("Giorni di fila", "Ketma-ket kun")
    static let statsXP        = t("XP totali", "Jami XP")
    static let statsWords     = t("Parole apprese", "O'rganilgan so'zlar")
    static let statsLevel     = t("Livello attuale", "Joriy daraja")
    static let weekActivity   = t("Ultimi 7 giorni", "Oxirgi 7 kun")
    static let courseProgress = t("Avanzamento del corso", "Kurs bo'yicha o'sish")
    static let settingsTitle  = t("Impostazioni", "Sozlamalar")
    static let soundsOn       = t("Effetti sonori", "Ovozli effektlar")
    static let hapticsOn      = t("Vibrazione", "Tebranish")
    static let speakingOn     = t("Esercizi di pronuncia", "Talaffuz mashqlari")
    static let listeningOn    = t("Esercizi di ascolto", "Tinglash mashqlari")
    static let speechRate     = t("Velocità dell'audio", "Audio tezligi")
    static let dailyGoal      = t("Obiettivo giornaliero", "Kunlik maqsad")
    static let reminder       = t("Promemoria giornaliero", "Kunlik eslatma")
    static let reminderTime   = t("Ora del promemoria", "Eslatma vaqti")
    static let reminderDenied = t("Notifiche non autorizzate: attivale in Impostazioni di iOS.", "Bildirishnomalarga ruxsat yo'q: iOS sozlamalaridan yoqing.")
    static let voiceInfo      = t("Voce usata", "Ishlatilayotgan ovoz")
    static let approximateVoice = t("iOS non ha una voce uzbeka: usiamo la voce più vicina disponibile.", "iOS'da o'zbek ovozi yo'q: eng yaqin mavjud ovozdan foydalanamiz.")
    static let approximateRecog = t("Il riconoscimento vocale uzbeko è approssimato con una lingua vicina.", "O'zbekcha nutqni tanish yaqin til yordamida taxminiy baholanadi.")
    static let realVoice      = t("Voce uzbeka vera", "Haqiqiy o'zbek ovozi")
    static let voiceCached    = t("Audio già scaricato:", "Yuklab olingan audio:")
    static let emptyVoiceCache = t("Svuota", "Tozalash")
    static let resetTitle     = t("Azzera i progressi", "Yutuqlarni tozalash")
    static let resetMsg       = t("Tutto tornerà a zero. Non si può annullare.", "Hammasi noldan boshlanadi. Bekor qilib bo'lmaydi.")
    static let cancel         = t("Annulla", "Bekor qilish")
    static let confirm        = t("Conferma", "Tasdiqlash")
    static let changeCourse   = t("Cambia corso", "Kursni o'zgartirish")
    static let shop           = t("Negozio", "Do'kon")
    static let buyFreeze      = t("Salva-serie (200 💎)", "Seriya muzlatgich (200 💎)")
    static let freezeOwned    = t("Salva-serie disponibili", "Mavjud muzlatgichlar")
    static let goalReached    = t("Obiettivo di oggi raggiunto!", "Bugungi maqsadga erishildi!")
    static let todayProgress  = t("Oggi", "Bugun")

    // Generic
    static let done           = t("Fatto", "Tayyor")
    static let close          = t("Chiudi", "Yopish")
    static let words          = t("parole", "so'z")
    static let lessons        = t("lezioni", "dars")
    static let of             = t("di", "/")
    static let xp             = t("XP", "XP")
    static let listenAgain    = t("Riascolta", "Qayta tinglash")
    static let slowly         = t("Lento", "Sekin")
}
