# -*- coding: utf-8 -*-
# A1 — Principiante / Boshlang'ich
# Grammar notes: the "it" text explains Uzbek to an Italian speaker,
# the "uz" text explains Italian to an Uzbek speaker.

LEVEL = "a1"

UNITS = [
 dict(id="a1u1", icon="hand.wave.fill", accent="sky",
  title=("Primi passi", "Ilk qadamlar"),
  subtitle=("Salutare, presentarsi, dire come stai", "Salomlashish, tanishish, ahvolni aytish"),
  grammar=[
    (("Il verbo «essere» non esiste al presente", "«Essere» fe'li — «bo'lmoq»"),
     ("In uzbeko il presente di «essere» non si traduce con una parola separata: si attacca una desinenza alla parola. Men italiyalik-MAN = io sono italiano. Le desinenze sono: -man (io), -san (tu), — (lui/lei), -miz (noi), -siz (voi/Lei), -lar (loro).",
      "Italyan tilida «bo'lmoq» fe'li — ESSERE — har doim aytiladi va noto'g'ri tuslanadi: io sono, tu sei, lui/lei è, noi siamo, voi siete, loro sono. O'zbekchadagi -man, -san qo'shimchalari o'rniga alohida so'z ishlatiladi."),
     [("Io sono italiano.", "Men italiyalikman."), ("Tu sei uzbeko.", "Sen o'zbeksan."), ("Noi siamo amici.", "Biz do'stmiz.")]),
    (("Tu o Lei: «sen» e «siz»", "«Tu» va «Lei»: murojaat shakllari"),
     ("«Sen» si usa con amici e familiari, «siz» è la forma di cortesia (e anche il plurale). Con «siz» il verbo prende -siz: Qalaysiz? invece di Qalaysan?",
      "«Tu» — do'stlar va oila uchun, «Lei» — hurmat shakli (uchinchi shaxs birlikda tuslanadi!): Come stai? (tu) / Come sta? (Lei). «Voi» — ko'plik."),
     [("Come stai?", "Qalaysan?"), ("Come sta, signore?", "Qalaysiz, janob?")]),
    (("L'ordine delle parole: il verbo alla fine", "So'z tartibi: fe'l qayerda?"),
     ("La frase uzbeka finisce quasi sempre con il verbo: Men Rimda yashayman = io a Roma vivo. Soggetto – complementi – verbo.",
      "Italyan tilida fe'l odatda o'rtada turadi: Io vivo a Roma (Men yashayman Rimda). O'zbekchadagidek oxirida emas."),
     [("Vivo a Roma.", "Men Rimda yashayman."), ("Parlo un po' di uzbeko.", "Men bir oz o'zbekcha gapiraman.")]),
  ],
  lessons=[
   ("a1u1l1", ("Saluti", "Salomlashish"),
    [("ciao", "salom"), ("buongiorno", "xayrli kun"), ("buon mattino", "xayrli tong"),
     ("buonasera", "xayrli kech"), ("buonanotte", "xayrli tun"), ("arrivederci", "xayr"),
     ("grazie", "rahmat"), ("prego", "arzimaydi"), ("per favore", "iltimos"),
     ("scusa", "kechirasan")],
    [("Ciao, come stai?", "Salom, qalaysan?"), ("Sto bene, grazie.", "Yaxshiman, rahmat."),
     ("E tu?", "Sen-chi?"), ("Buongiorno, signore.", "Xayrli kun, janob."),
     ("A domani!", "Ertaga ko'rishguncha!"), ("Scusi, per favore.", "Kechirasiz, iltimos.")]),
   ("a1u1l2", ("Come ti chiami?", "Isming nima?"),
    [("nome", "ism"), ("io", "men"), ("tu", "sen"), ("lui", "u"), ("noi", "biz"),
     ("voi", "siz"), ("loro", "ular"), ("signore", "janob"), ("signora", "xonim"),
     ("amico", "do'st")],
    [("Come ti chiami?", "Isming nima?"), ("Mi chiamo Claudia.", "Mening ismim Klaudiya."),
     ("Piacere!", "Tanishganimdan xursandman!"), ("Come si chiama Lei?", "Ismingiz nima?"),
     ("Questo è il mio amico.", "Bu mening do'stim."), ("Lui si chiama Aziz.", "Uning ismi Aziz.")]),
   ("a1u1l3", ("Di dove sei?", "Qayerliksan?"),
    [("paese", "davlat"), ("città", "shahar"), ("Italia", "Italiya"), ("Uzbekistan", "O'zbekiston"),
     ("italiano", "italyan"), ("uzbeko", "o'zbek"), ("lingua", "til"), ("qui", "bu yerda"),
     ("lì", "u yerda"), ("casa", "uy")],
    [("Di dove sei?", "Qayerliksan?"), ("Sono italiana.", "Men italiyalikman."),
     ("Vengo da Tashkent.", "Men Toshkentdanman."), ("Vivo a Roma.", "Men Rimda yashayman."),
     ("Parli italiano?", "Italyancha gapirasanmi?"), ("Parlo un po' di uzbeko.", "Men bir oz o'zbekcha gapiraman.")]),
   ("a1u1l4", ("Come va?", "Ishlar qalay?"),
    [("bene", "yaxshi"), ("male", "yomon"), ("così così", "o'rtacha"), ("molto", "juda"),
     ("un po'", "bir oz"), ("felice", "xursand"), ("stanco", "charchagan"), ("oggi", "bugun"),
     ("domani", "ertaga"), ("ieri", "kecha")],
    [("Come va?", "Ishlar qalay?"), ("Tutto bene!", "Hammasi yaxshi!"),
     ("Non c'è male.", "Yomon emas."), ("Sono un po' stanca.", "Men bir oz charchadim."),
     ("Ci vediamo domani.", "Ertaga ko'rishamiz."), ("Buona giornata!", "Kuningiz xayrli o'tsin!")]),
  ],
  dialogue=(("Il primo incontro", "Ilk tanishuv"), [
    ("Aziz", "Ciao! Mi chiamo Aziz.", "Salom! Mening ismim Aziz."),
    ("Giulia", "Ciao Aziz! Io sono Giulia.", "Salom Aziz! Men Giuliaman."),
    ("Aziz", "Piacere. Di dove sei?", "Tanishganimdan xursandman. Qayerliksan?"),
    ("Giulia", "Sono italiana, di Roma. E tu?", "Men italiyalikman, Rimdanman. Sen-chi?"),
    ("Aziz", "Io sono uzbeko, di Tashkent.", "Men o'zbekman, Toshkentdanman."),
    ("Giulia", "Molto bene! Parli italiano?", "Juda yaxshi! Italyancha gapirasanmi?"),
    ("Aziz", "Un po'. Ci vediamo domani!", "Bir oz. Ertaga ko'rishamiz!"),
  ])),

 dict(id="a1u2", icon="person.2.fill", accent="pink",
  title=("Famiglia e persone", "Oila va odamlar"),
  subtitle=("Parlare della famiglia e descrivere le persone", "Oila haqida gapirish va odamlarni tasvirlash"),
  grammar=[
    (("I possessivi si attaccano alla parola", "Egalik qo'shimchalari"),
     ("In uzbeko «mia madre» è una parola sola: ona + -m = onam. Le desinenze sono -(i)m (mio), -(i)ng (tuo), -(s)i (suo), -(i)miz (nostro), -(i)ngiz (vostro/Suo).",
      "Italyan tilida egalik alohida so'z bilan beriladi va artikl bilan keladi: mia madre, il mio libro, i miei amici. Egalik so'zi otning jinsi va soniga moslashadi: mio/mia/miei/mie."),
     [("mia madre", "onam"), ("tuo padre", "otang"), ("la sua casa", "uning uyi"), ("i miei amici", "do'stlarim")]),
    (("Il plurale: -lar", "Ko'plik shakli"),
     ("Il plurale uzbeko è sempre -lar, senza eccezioni: kitob → kitoblar, do'st → do'stlar. Dopo un numero però il plurale non si usa: uch kitob (tre libro).",
      "Italyan tilida ko'plik oxirgi unlini o'zgartiradi: -o → -i (libro/libri), -a → -e (casa/case), -e → -i (chiave/chiavi). Artikl ham o'zgaradi: il → i, la → le."),
     [("i libri", "kitoblar"), ("tre libri", "uch kitob"), ("le case", "uylar")]),
    (("Chi? Che cosa? — le domande", "So'roq gaplar"),
     ("Per fare una domanda «sì/no» si aggiunge -mi al verbo: Sen o'zbeksan → O'zbeksanmi? Le parole interrogative sono kim (chi), nima (che cosa), qayer (dove), qachon (quando), nega (perché).",
      "Italyan tilida so'roq gap so'z tartibi bilan emas, ohang bilan yasaladi: Sei uzbeko? So'roq so'zlar: chi, che cosa, dove, quando, perché, come."),
     [("Chi è?", "U kim?"), ("Che cos'è?", "Bu nima?"), ("Sei uzbeko?", "O'zbekmisan?")]),
  ],
  lessons=[
   ("a1u2l1", ("La mia famiglia", "Mening oilam"),
    [("famiglia", "oila"), ("madre", "ona"), ("padre", "ota"), ("figlio", "o'g'il"),
     ("figlia", "qiz"), ("fratello", "aka"), ("sorella", "opa"), ("nonno", "bobo"),
     ("nonna", "buvi"), ("marito", "er")],
    [("Questa è la mia famiglia.", "Bu mening oilam."), ("Ho due fratelli.", "Mening ikkita akam bor."),
     ("Mia madre si chiama Nigora.", "Onamning ismi Nigora."), ("Non ho sorelle.", "Mening opam yo'q."),
     ("Mio padre lavora a Tashkent.", "Otam Toshkentda ishlaydi."), ("Amo la mia famiglia.", "Men oilamni sevaman.")]),
   ("a1u2l2", ("Persone", "Odamlar"),
    [("uomo", "erkak"), ("donna", "ayol"), ("bambino", "bola"), ("ragazzo", "yigit"),
     ("ragazza", "qiz"), ("persona", "odam"), ("moglie", "xotin"), ("vicino", "qo'shni"),
     ("collega", "hamkasb"), ("ospite", "mehmon")],
    [("Chi è quella donna?", "U ayol kim?"), ("È la mia vicina.", "U mening qo'shnim."),
     ("Ho un bambino piccolo.", "Mening kichkina bolam bor."), ("Sono sposata.", "Men turmush qurganman."),
     ("Lui è un mio collega.", "U mening hamkasbim."), ("Abbiamo ospiti oggi.", "Bugun bizda mehmonlar bor.")]),
   ("a1u2l3", ("Com'è?", "U qanday?"),
    [("alto", "baland bo'yli"), ("basso", "past bo'yli"), ("giovane", "yosh"), ("vecchio", "keksa"),
     ("bello", "chiroyli"), ("simpatico", "yoqimtoy"), ("gentile", "mehribon"), ("allegro", "quvnoq"),
     ("serio", "jiddiy"), ("intelligente", "aqlli")],
    [("Com'è tuo fratello?", "Akang qanday?"), ("È molto gentile.", "U juda mehribon."),
     ("Mia sorella è alta.", "Opam baland bo'yli."), ("Sei molto simpatico!", "Sen juda yoqimtoysan!"),
     ("Sono una persona allegra.", "Men quvnoq odamman."), ("Lui non è vecchio.", "U keksa emas.")]),
   ("a1u2l4", ("Quanti anni hai?", "Necha yoshdasan?"),
    [("anno", "yil"), ("età", "yosh"), ("compleanno", "tug'ilgan kun"), ("nome proprio", "ism"),
     ("cognome", "familiya"), ("amica", "dugona"), ("fidanzato", "yigit"), ("genitori", "ota-ona"),
     ("bambina", "qizcha"), ("zio", "tog'a")],
    [("Quanti anni hai?", "Necha yoshdasan?"), ("Ho venticinque anni.", "Men yigirma besh yoshdaman."),
     ("Quando è il tuo compleanno?", "Tug'ilgan kuning qachon?"), ("Anche lui ha vent'anni.", "U ham yigirma yoshda."),
     ("I miei genitori vivono qui.", "Ota-onam shu yerda yashaydi."), ("Lei è la mia amica.", "U mening dugonam.")]),
  ],
  dialogue=(("La foto di famiglia", "Oilaviy surat"), [
    ("Giulia", "Chi sono queste persone?", "Bu odamlar kim?"),
    ("Aziz", "Questa è la mia famiglia. Questa è mia madre.", "Bu mening oilam. Bu onam."),
    ("Giulia", "È molto bella. E quel ragazzo?", "U juda chiroyli. Anavi yigit-chi?"),
    ("Aziz", "È mio fratello. Ha diciotto anni.", "U mening ukam. U o'n sakkiz yoshda."),
    ("Giulia", "Hai sorelle?", "Opa-singling bormi?"),
    ("Aziz", "Sì, una sorella. Si chiama Dilnoza.", "Ha, bitta singlim bor. Uning ismi Dilnoza."),
    ("Giulia", "Che bella famiglia!", "Qanday ajoyib oila!"),
  ])),

 dict(id="a1u3", icon="number", accent="amber",
  title=("Numeri, ora e giorni", "Sonlar, vaqt va kunlar"),
  subtitle=("Contare, dire l'ora e parlare del calendario", "Sanash, vaqtni aytish va kalendar"),
  grammar=[
    (("I numeri", "Sonlar"),
     ("I numeri uzbeki sono regolari: 11 = o'n bir (dieci-uno), 21 = yigirma bir. Le decine: o'n (10), yigirma (20), o'ttiz (30), qirq (40), ellik (50), oltmish (60), yetmish (70), sakson (80), to'qson (90), yuz (100).",
      "Italyan sonlari: 11-16 alohida (undici, dodici…), 17-19 teskari tartibda (diciassette). O'nliklar: venti, trenta, quaranta, cinquanta, sessanta, settanta, ottanta, novanta, cento. venti + uno = ventuno (unli tushadi)."),
     [("ventuno", "yigirma bir"), ("cento", "yuz"), ("mille", "ming")]),
    (("Che ore sono?", "Soat necha?"),
     ("L'ora in uzbeko si dice con «soat»: Soat uch = le tre. «Mezz'ora dopo» è yarim: uch yarim = tre e mezza. I minuti dopo si dicono con -dan o'tdi: uchdan o'n daqiqa o'tdi.",
      "Italyan tilida soat ko'plikda aytiladi: Sono le tre. Faqat «È l'una», «È mezzogiorno», «È mezzanotte» birlikda. Daqiqalar: le tre e dieci, le tre e mezza, le quattro meno dieci."),
     [("Sono le tre.", "Soat uch."), ("Sono le tre e mezza.", "Soat uch yarim."), ("È l'una.", "Soat bir.")]),
    (("Il locativo -da: dove e quando", "«-da» qo'shimchasi"),
     ("La desinenza -da indica sia il luogo sia il tempo: uyda (a casa), soat beshda (alle cinque), dushanbada (lunedì).",
      "Italyan tilida joy va vaqt uchun har xil predloglar bor: a casa, alle cinque, il lunedì, a marzo, nel 2025."),
     [("a casa", "uyda"), ("alle cinque", "soat beshda"), ("lunedì", "dushanbada")]),
  ],
  lessons=[
   ("a1u3l1", ("Da uno a dieci", "Birdan o'ngacha"),
    [("uno", "bir"), ("due", "ikki"), ("tre", "uch"), ("quattro", "to'rt"), ("cinque", "besh"),
     ("sei", "olti"), ("sette", "yetti"), ("otto", "sakkiz"), ("nove", "to'qqiz"), ("dieci", "o'n")],
    [("Quanto costa?", "Qancha turadi?"), ("Costa cinque euro.", "Besh yevro turadi."),
     ("Ho tre libri.", "Mening uchta kitobim bor."), ("Siamo in quattro.", "Biz to'rt kishimiz."),
     ("Dammi due, per favore.", "Ikkita ber, iltimos."), ("Quanti ne vuoi?", "Nechta xohlaysan?")]),
   ("a1u3l2", ("Numeri grandi", "Katta sonlar"),
    [("undici", "o'n bir"), ("quindici", "o'n besh"), ("venti", "yigirma"), ("trenta", "o'ttiz"),
     ("quaranta", "qirq"), ("cinquanta", "ellik"), ("cento", "yuz"), ("mille", "ming"),
     ("numero", "raqam"), ("quanto", "qancha")],
    [("Qual è il tuo numero?", "Raqaming nechchi?"), ("Ho venti anni.", "Men yigirma yoshdaman."),
     ("Costa cento euro.", "Yuz yevro turadi."), ("Ci sono trenta studenti.", "O'ttizta talaba bor."),
     ("Quante persone ci sono?", "Necha kishi bor?"), ("Più o meno cinquanta.", "Taxminan ellik.")]),
   ("a1u3l3", ("Che ore sono?", "Soat necha?"),
    [("ora", "soat"), ("minuto", "daqiqa"), ("mezzogiorno", "tush payti"), ("mattina", "ertalab"),
     ("pomeriggio", "tushdan keyin"), ("sera", "kechqurun"), ("notte", "tun"), ("presto", "erta"),
     ("tardi", "kech"), ("adesso", "hozir")],
    [("Che ore sono?", "Soat necha?"), ("Sono le otto.", "Soat sakkiz."),
     ("È l'una e mezza.", "Soat bir yarim."), ("A che ora inizia?", "Soat nechada boshlanadi?"),
     ("Alle nove di mattina.", "Ertalab soat to'qqizda."), ("È tardi, devo andare.", "Kech bo'ldi, men ketishim kerak.")]),
   ("a1u3l4", ("I giorni della settimana", "Hafta kunlari"),
    [("lunedì", "dushanba"), ("martedì", "seshanba"), ("mercoledì", "chorshanba"), ("giovedì", "payshanba"),
     ("venerdì", "juma"), ("sabato", "shanba"), ("domenica", "yakshanba"), ("settimana", "hafta"),
     ("mese", "oy"), ("fine settimana", "dam olish kunlari")],
    [("Che giorno è oggi?", "Bugun qaysi kun?"), ("Oggi è mercoledì.", "Bugun chorshanba."),
     ("Ci vediamo sabato.", "Shanbada ko'rishamiz."), ("Lavoro cinque giorni a settimana.", "Men haftasiga besh kun ishlayman."),
     ("La domenica riposo.", "Yakshanba kuni dam olaman."), ("Il mese prossimo parto.", "Kelasi oy ketaman.")]),
  ],
  dialogue=(("Un appuntamento", "Uchrashuv"), [
    ("Dilnoza", "Sei libera domani?", "Ertaga bo'shmisan?"),
    ("Giulia", "Domani è giovedì… sì, dopo le cinque.", "Ertaga payshanba… ha, beshdan keyin."),
    ("Dilnoza", "Allora alle sei al bar?", "Unda soat oltida kafeda?"),
    ("Giulia", "Va bene. Dov'è il bar?", "Yaxshi. Kafe qayerda?"),
    ("Dilnoza", "Vicino alla stazione. Dieci minuti a piedi.", "Bekat yonida. Piyoda o'n daqiqa."),
    ("Giulia", "Perfetto, a domani!", "Zo'r, ertaga ko'rishguncha!"),
  ])),

 dict(id="a1u4", icon="fork.knife", accent="green",
  title=("Cibo e bevande", "Ovqat va ichimliklar"),
  subtitle=("Ordinare, fare la spesa, parlare di gusti", "Buyurtma berish, xarid va ta'mlar"),
  grammar=[
    (("«Bor» e «yo'q»: c'è e non c'è", "«C'è» va «non c'è»"),
     ("Per dire «ho» o «c'è» l'uzbeko usa bor (c'è) e yo'q (non c'è), messi alla fine: Menda pul bor = io ho soldi. Suvi yo'q = non c'è acqua.",
      "Italyan tilida «bor» o'rniga ikki xil ifoda bor: c'è / ci sono (mavjudlik) va avere (egalik): Ho dei soldi. C'è dell'acqua. Inkor: non c'è, non ho."),
     [("Ho soldi.", "Menda pul bor."), ("Non c'è acqua.", "Suv yo'q."), ("C'è il pane?", "Non bormi?")]),
    (("L'accusativo -ni", "Tushum kelishigi «-ni»"),
     ("Quando l'oggetto è preciso prende -ni: Men nonni yeyman = mangio IL pane. Se è generico non prende nulla: Men non yeyman = mangio pane.",
      "Italyan tilida bu farq artikl bilan beriladi: mangio il pane (aniq) / mangio del pane (noaniq). Otdan keyin qo'shimcha qo'shilmaydi."),
     [("Mangio il pane.", "Men nonni yeyman."), ("Mangio pane.", "Men non yeyman.")]),
    (("Mi piace: «yoqadi»", "«Mi piace» qurilishi"),
     ("«Mi piace» in uzbeko è menga yoqadi (letteralmente: a me piace). La persona va al dativo -ga: senga yoqadi, unga yoqadi.",
      "«Yoqmoq» italyan tilida piacere fe'li bilan beriladi va teskari qurilishga ega: Mi piace il tè (menga choy yoqadi). Ko'plikda mi piacciono: Mi piacciono i dolci."),
     [("Mi piace il tè.", "Menga choy yoqadi."), ("Ti piace?", "Senga yoqadimi?"), ("Mi piacciono i dolci.", "Menga shirinliklar yoqadi.")]),
  ],
  lessons=[
   ("a1u4l1", ("Al mercato", "Bozorda"),
    [("pane", "non"), ("acqua", "suv"), ("carne", "go'sht"), ("riso", "guruch"), ("frutta", "meva"),
     ("verdura", "sabzavot"), ("mela", "olma"), ("uva", "uzum"), ("pomodoro", "pomidor"),
     ("cipolla", "piyoz")],
    [("Quanto costa il pane?", "Non qancha turadi?"), ("Vorrei un chilo di mele.", "Bir kilo olma bering."),
     ("Avete del riso?", "Guruch bormi?"), ("È troppo caro.", "Bu juda qimmat."),
     ("Mi dia due pomodori.", "Ikkita pomidor bering."), ("Basta così, grazie.", "Shuning o'zi yetarli, rahmat.")]),
   ("a1u4l2", ("Bevande", "Ichimliklar"),
    [("tè", "choy"), ("caffè", "qahva"), ("latte", "sut"), ("succo", "sharbat"), ("vino", "vino"),
     ("birra", "pivo"), ("zucchero", "shakar"), ("caldo", "issiq"), ("freddo", "sovuq"),
     ("bicchiere", "stakan")],
    [("Vorrei un tè, per favore.", "Bir choy bering, iltimos."), ("Con o senza zucchero?", "Shakar bilanmi yoki shakarsizmi?"),
     ("Preferisco il caffè.", "Men qahvani afzal ko'raman."), ("Un bicchiere d'acqua fredda.", "Bir stakan sovuq suv."),
     ("Il tè è troppo caldo.", "Choy juda issiq."), ("Non bevo alcol.", "Men spirtli ichimlik ichmayman.")]),
   ("a1u4l3", ("Al ristorante", "Restoranda"),
    [("ristorante", "restoran"), ("menu", "menyu"), ("piatto", "taom"), ("zuppa", "sho'rva"),
     ("insalata", "salat"), ("dolce", "shirinlik"), ("conto", "hisob"), ("cameriere", "ofitsiant"),
     ("colazione", "nonushta"), ("cena", "kechki ovqat")],
    [("Un tavolo per due, per favore.", "Ikki kishilik stol, iltimos."), ("Che cosa consiglia?", "Nimani tavsiya qilasiz?"),
     ("Vorrei ordinare.", "Buyurtma bermoqchiman."), ("Il conto, per favore.", "Hisobni bering, iltimos."),
     ("Era molto buono!", "Juda mazali edi!"), ("Sono vegetariana.", "Men vegetarianman.")]),
   ("a1u4l4", ("Mi piace!", "Menga yoqadi!"),
    [("buono", "mazali"), ("salato", "sho'r"), ("dolce (agg.)", "shirin"), ("piccante", "achchiq"),
     ("fame", "ochlik"), ("sete", "chanqoq"), ("mangiare", "yemoq"), ("bere", "ichmoq"),
     ("cucinare", "ovqat pishirmoq"), ("piatto tipico", "milliy taom")],
    [("Ho fame.", "Men qornim och."), ("Ho sete.", "Men chanqadim."),
     ("Mi piace il plov.", "Menga palov yoqadi."), ("Non mi piace il piccante.", "Menga achchiq yoqmaydi."),
     ("Mia madre cucina bene.", "Onam yaxshi ovqat pishiradi."), ("Che cosa mangi di solito?", "Odatda nima yeysan?")]),
  ],
  dialogue=(("Al ristorante", "Restoranda"), [
    ("Ofitsiant", "Buonasera! Un tavolo per quante persone?", "Xayrli kech! Necha kishilik stol?"),
    ("Giulia", "Per due, grazie.", "Ikki kishilik, rahmat."),
    ("Ofitsiant", "Ecco il menu. Che cosa desidera?", "Mana menyu. Nima istaysiz?"),
    ("Giulia", "Che cosa consiglia?", "Nimani tavsiya qilasiz?"),
    ("Ofitsiant", "Il plov è il nostro piatto tipico.", "Palov — bizning milliy taomimiz."),
    ("Giulia", "Allora due plov e due tè verdi.", "Unda ikkita palov va ikkita ko'k choy."),
    ("Ofitsiant", "Subito!", "Hozir!"),
  ])),

 dict(id="a1u5", icon="house.fill", accent="teal",
  title=("Casa e oggetti", "Uy va buyumlar"),
  subtitle=("Descrivere dove vivi e cosa c'è in casa", "Uyingizni va uydagi narsalarni tasvirlash"),
  grammar=[
    (("Dove? Le desinenze di luogo", "Joy qo'shimchalari"),
     ("Tre desinenze fanno il lavoro delle preposizioni italiane: -da (in, a: uyda = a casa), -ga (verso, a: uyga = a casa, moto), -dan (da: uydan = da casa).",
      "Italyan tilida joy predloglar bilan beriladi: in casa, a casa, da casa, sul tavolo, sotto il letto. Predlog artikl bilan qo'shilib ketadi: in + il = nel, su + il = sul."),
     [("in casa", "uyda"), ("verso casa", "uyga"), ("da casa", "uydan"), ("sul tavolo", "stol ustida")]),
    (("Aggettivo prima del nome", "Sifat va ot tartibi"),
     ("In uzbeko l'aggettivo sta sempre prima del nome e non cambia mai: katta uy (casa grande), katta uylar (case grandi).",
      "Italyan tilida sifat odatda otdan KEYIN keladi va ot bilan moslashadi: una casa grande, delle case grandi, un libro nuovo, dei libri nuovi."),
     [("una casa grande", "katta uy"), ("case grandi", "katta uylar"), ("un libro nuovo", "yangi kitob")]),
  ],
  lessons=[
   ("a1u5l1", ("La mia casa", "Mening uyim"),
    [("appartamento", "kvartira"), ("stanza", "xona"), ("cucina", "oshxona"), ("bagno", "hammom"),
     ("camera da letto", "yotoqxona"), ("porta", "eshik"), ("finestra", "deraza"), ("piano", "qavat"),
     ("giardino", "bog'"), ("chiave", "kalit")],
    [("Dove abiti?", "Qayerda yashaysan?"), ("Abito in un appartamento.", "Men kvartirada yashayman."),
     ("La mia casa ha tre stanze.", "Mening uyimda uchta xona bor."), ("Al terzo piano.", "Uchinchi qavatda."),
     ("Ho perso le chiavi.", "Kalitlarimni yo'qotdim."), ("La finestra è aperta.", "Deraza ochiq.")]),
   ("a1u5l2", ("I mobili", "Mebel"),
    [("tavolo", "stol"), ("sedia", "stul"), ("letto", "karavot"), ("armadio", "shkaf"),
     ("divano", "divan"), ("specchio", "oyna"), ("tappeto", "gilam"), ("lampada", "chiroq"),
     ("frigorifero", "muzlatgich"), ("cuscino", "yostiq")],
    [("Il libro è sul tavolo.", "Kitob stol ustida."), ("La sedia è rotta.", "Stul singan."),
     ("Metti il cuscino sul divano.", "Yostiqni divanga qo'y."), ("C'è un tappeto uzbeko.", "O'zbek gilami bor."),
     ("Il frigorifero è vuoto.", "Muzlatgich bo'sh."), ("Accendi la lampada.", "Chiroqni yoq.")]),
   ("a1u5l3", ("Oggetti di ogni giorno", "Kundalik buyumlar"),
    [("telefono", "telefon"), ("libro", "kitob"), ("borsa", "sumka"), ("orologio", "soat"),
     ("penna", "ruchka"), ("carta", "qog'oz"), ("soldi", "pul"), ("occhiali", "ko'zoynak"),
     ("valigia", "chamadon"), ("regalo", "sovg'a")],
    [("Dov'è il mio telefono?", "Telefonim qayerda?"), ("È nella borsa.", "U sumkada."),
     ("Ho dimenticato gli occhiali.", "Ko'zoynagimni unutibman."), ("Questo è un regalo per te.", "Bu senga sovg'a."),
     ("Mi presti una penna?", "Ruchka berib turasanmi?"), ("Non ho soldi con me.", "Yonimda pul yo'q.")]),
   ("a1u5l4", ("Dov'è?", "Qayerda?"),
    [("sopra", "ustida"), ("sotto", "ostida"), ("dentro", "ichida"), ("fuori", "tashqarida"),
     ("davanti", "oldida"), ("dietro", "orqasida"), ("vicino", "yonida"), ("lontano", "uzoqda"),
     ("a destra", "o'ngda"), ("a sinistra", "chapda")],
    [("Il gatto è sotto il tavolo.", "Mushuk stol ostida."), ("Il negozio è vicino a casa.", "Do'kon uy yonida."),
     ("Aspetto fuori.", "Men tashqarida kutaman."), ("La scuola è lontana?", "Maktab uzoqmi?"),
     ("Gira a destra.", "O'ngga buriling."), ("Chi è dietro la porta?", "Eshik orqasida kim bor?")]),
  ],
  dialogue=(("Il nuovo appartamento", "Yangi kvartira"), [
    ("Aziz", "Com'è il tuo nuovo appartamento?", "Yangi kvartirang qanday?"),
    ("Giulia", "Piccolo ma molto luminoso.", "Kichkina, lekin juda yorug'."),
    ("Aziz", "Quante stanze ci sono?", "Nechta xona bor?"),
    ("Giulia", "Due: una camera e una cucina grande.", "Ikkita: bitta yotoqxona va katta oshxona."),
    ("Aziz", "C'è un balcone?", "Balkon bormi?"),
    ("Giulia", "Sì, e dal balcone vedo il parco.", "Ha, balkondan bog'ni ko'raman."),
    ("Aziz", "Che bello! Vengo a trovarti.", "Zo'r ekan! Men senikiga boraman."),
  ])),

 dict(id="a1u6", icon="map.fill", accent="purple",
  title=("In città", "Shaharda"),
  subtitle=("Chiedere la strada, usare i mezzi, fare compere", "Yo'l so'rash, transport va xarid"),
  grammar=[
    (("L'imperativo: dare istruzioni", "Buyruq gaplar"),
     ("L'imperativo informale è la radice nuda del verbo: bormoq → bor! (vai), kelmoq → kel! (vieni). Con la forma di cortesia si aggiunge -ing: boring, keling.",
      "Italyan buyruq shakli shaxsga qarab o'zgaradi: va' / vada (tu / Lei), vieni / venga, gira / giri. Inkor «tu» uchun: non andare!"),
     [("Vai!", "Bor!"), ("Venga, prego.", "Keling, marhamat."), ("Gira a destra.", "O'ngga buriling.")]),
    (("Come si chiede la strada", "Yo'l qanday so'raladi"),
     ("La domanda tipo è: ...ga qanday boraman? (come arrivo a…?). «Dov'è» si dice qayerda: Bekat qayerda?",
      "Italyancha savollar: Dov'è la stazione? Come si arriva al centro? Scusi, per il museo? «Scusi» so'zi bilan boshlash odobli hisoblanadi."),
     [("Dov'è la stazione?", "Bekat qayerda?"), ("Come arrivo al centro?", "Markazga qanday boraman?")]),
  ],
  lessons=[
   ("a1u6l1", ("Luoghi della città", "Shahar joylari"),
    [("strada", "ko'cha"), ("piazza", "maydon"), ("negozio", "do'kon"), ("mercato", "bozor"),
     ("scuola", "maktab"), ("ospedale", "shifoxona"), ("banca", "bank"), ("farmacia", "dorixona"),
     ("parco", "bog'"), ("museo", "muzey")],
    [("Dov'è la farmacia?", "Dorixona qayerda?"), ("C'è una banca qui vicino?", "Yaqin atrofda bank bormi?"),
     ("Il mercato è in centro.", "Bozor markazda."), ("Vado al parco.", "Men bog'ga boraman."),
     ("Il museo è chiuso oggi.", "Muzey bugun yopiq."), ("Questa strada è lunga.", "Bu ko'cha uzun.")]),
   ("a1u6l2", ("I mezzi di trasporto", "Transport"),
    [("autobus", "avtobus"), ("metropolitana", "metro"), ("taxi", "taksi"), ("treno", "poyezd"),
     ("macchina", "mashina"), ("bicicletta", "velosiped"), ("fermata", "bekat"), ("biglietto", "chipta"),
     ("a piedi", "piyoda"), ("aeroporto", "aeroport")],
    [("Dov'è la fermata dell'autobus?", "Avtobus bekati qayerda?"), ("Quanto costa un biglietto?", "Chipta qancha turadi?"),
     ("Vado a lavoro in metro.", "Men ishga metroda boraman."), ("Prendiamo un taxi.", "Keling, taksi olamiz."),
     ("Il treno parte alle otto.", "Poyezd soat sakkizda jo'naydi."), ("Vado a piedi, è vicino.", "Piyoda boraman, yaqin.")]),
   ("a1u6l3", ("Chiedere indicazioni", "Yo'l so'rash"),
    [("dritto", "to'g'ri"), ("angolo", "burchak"), ("semaforo", "svetofor"), ("ponte", "ko'prik"),
     ("centro", "markaz"), ("indirizzo", "manzil"), ("mappa", "xarita"), ("perso", "adashgan"),
     ("girare", "burilmoq"), ("attraversare", "kesib o'tmoq")],
    [("Scusi, dov'è il centro?", "Kechirasiz, markaz qayerda?"), ("Vada dritto.", "To'g'riga yuring."),
     ("Giri al semaforo.", "Svetoforda buriling."), ("Mi sono persa.", "Men adashdim."),
     ("È lontano da qui?", "Bu yerdan uzoqmi?"), ("Dieci minuti a piedi.", "Piyoda o'n daqiqa.")]),
   ("a1u6l4", ("Fare compere", "Xarid qilish"),
    [("comprare", "sotib olmoq"), ("vendere", "sotmoq"), ("prezzo", "narx"), ("caro", "qimmat"),
     ("economico", "arzon"), ("sconto", "chegirma"), ("vestiti", "kiyim"), ("scarpe", "poyabzal"),
     ("taglia", "o'lcham"), ("cassa", "kassa")],
    [("Quanto costa questo?", "Bu qancha turadi?"), ("È troppo caro.", "Bu juda qimmat."),
     ("Avete una taglia più grande?", "Kattaroq o'lcham bormi?"), ("Posso provarlo?", "Kiyib ko'rsam bo'ladimi?"),
     ("Lo prendo!", "Shuni olaman!"), ("Posso pagare con la carta?", "Karta bilan to'lasam bo'ladimi?")]),
  ],
  dialogue=(("Per il bazar, per favore", "Bozorga qanday boraman?"), [
    ("Giulia", "Scusi, come arrivo al bazar Chorsu?", "Kechirasiz, Chorsu bozoriga qanday boraman?"),
    ("O'tkinchi", "Prenda la metro, due fermate.", "Metroda boring, ikki bekat."),
    ("Giulia", "Dov'è la stazione della metro?", "Metro bekati qayerda?"),
    ("O'tkinchi", "Vada dritto e giri a sinistra al semaforo.", "To'g'riga yuring va svetoforda chapga buriling."),
    ("Giulia", "È lontano?", "Uzoqmi?"),
    ("O'tkinchi", "No, cinque minuti a piedi.", "Yo'q, piyoda besh daqiqa."),
    ("Giulia", "Grazie mille!", "Katta rahmat!"),
  ])),

 dict(id="a1u7", icon="clock.fill", accent="red",
  title=("La giornata", "Kunlik ishlar"),
  subtitle=("Raccontare la routine di tutti i giorni", "Kundalik tartibni aytib berish"),
  grammar=[
    (("Il presente: -aman, -asan, -adi", "Hozirgi-kelasi zamon"),
     ("Il presente abituale si forma con la radice + -a- + la persona: bor-a-man (vado), bor-a-san (vai), bor-a-di (va), bor-a-miz, bor-a-siz, bor-a-di(lar). Se la radice finisce per vocale si usa -y-: ishla-y-man.",
      "Italyan tilida uch xil tuslanish bor: -are (parlare → parlo, parli, parla, parliamo, parlate, parlano), -ere (prendere → prendo…), -ire (dormire → dormo…). Shaxs olmoshini tushirib qoldirsa ham bo'ladi."),
     [("Vado a lavoro.", "Men ishga boraman."), ("Tu lavori molto.", "Sen ko'p ishlaysan."), ("Lei dorme.", "U uxlaydi.")]),
    (("Adesso: -yapman", "Hozirgi davom fe'li"),
     ("Per l'azione in corso si usa -yap- + persona: ishla-yap-man (sto lavorando), bor-yap-san (stai andando).",
      "Italyan tilida davom etayotgan ish uchun stare + gerundio ishlatiladi: sto lavorando, stai andando, sta mangiando. Oddiy hozirgi zamon ham ko'p ishlatiladi."),
     [("Sto lavorando.", "Men ishlayapman."), ("Che cosa stai facendo?", "Nima qilyapsan?")]),
    (("La negazione: -ma-", "Inkor shakli"),
     ("Il verbo si nega inserendo -ma- prima della desinenza: bor-ma-y-man (non vado), bil-ma-y-man (non so). Per i nomi si usa emas: Men talaba emasman.",
      "Italyan tilida inkor fe'ldan oldin «non» so'zi bilan yasaladi: non vado, non so, non sono studente. Juda oddiy!"),
     [("Non vado.", "Men bormayman."), ("Non lo so.", "Men bilmayman."), ("Non sono studente.", "Men talaba emasman.")]),
  ],
  lessons=[
   ("a1u7l1", ("La mattina", "Ertalab"),
    [("svegliarsi", "uyg'onmoq"), ("alzarsi", "turmoq"), ("lavarsi", "yuvinmoq"), ("vestirsi", "kiyinmoq"),
     ("fare colazione", "nonushta qilmoq"), ("uscire", "chiqmoq"), ("presto (agg.)", "erta"),
     ("sveglia", "budilnik"), ("doccia", "dush"), ("denti", "tishlar")],
    [("Mi sveglio alle sette.", "Men soat yettida uyg'onaman."), ("Faccio colazione a casa.", "Men uyda nonushta qilaman."),
     ("Esco alle otto.", "Soat sakkizda chiqaman."), ("Mi lavo i denti.", "Tishlarimni yuvaman."),
     ("Di solito mi alzo presto.", "Odatda erta turaman."), ("Oggi mi sono svegliata tardi.", "Bugun kech uyg'ondim.")]),
   ("a1u7l2", ("Il lavoro e lo studio", "Ish va o'qish"),
    [("lavoro", "ish"), ("ufficio", "ofis"), ("studente", "talaba"), ("insegnante", "o'qituvchi"),
     ("medico", "shifokor"), ("università", "universitet"), ("lezione", "dars"), ("compito", "vazifa"),
     ("collega (donna)", "hamkasb ayol"), ("riunione", "yig'ilish")],
    [("Che lavoro fai?", "Nima ish qilasan?"), ("Sono insegnante.", "Men o'qituvchiman."),
     ("Lavoro in un ufficio.", "Men ofisda ishlayman."), ("Studio all'università.", "Men universitetda o'qiyman."),
     ("La lezione inizia alle nove.", "Dars soat to'qqizda boshlanadi."), ("Oggi ho una riunione.", "Bugun yig'ilishim bor.")]),
   ("a1u7l3", ("La sera", "Kechqurun"),
    [("tornare", "qaytmoq"), ("riposare", "dam olmoq"), ("guardare", "ko'rmoq"), ("leggere", "o'qimoq"),
     ("dormire", "uxlamoq"), ("cena (pasto)", "kechki ovqat"), ("televisione", "televizor"),
     ("film", "kino"), ("musica", "musiqa"), ("passeggiata", "sayr")],
    [("Torno a casa alle sei.", "Soat oltida uyga qaytaman."), ("La sera guardo un film.", "Kechqurun kino ko'raman."),
     ("Leggo prima di dormire.", "Uxlashdan oldin o'qiyman."), ("Andiamo a fare una passeggiata.", "Keling, sayr qilamiz."),
     ("Vado a letto alle undici.", "Soat o'n birda uxlayman."), ("Ascolto musica.", "Men musiqa tinglayman.")]),
   ("a1u7l4", ("Quante volte?", "Necha marta?"),
    [("sempre", "doim"), ("spesso", "tez-tez"), ("a volte", "ba'zan"), ("raramente", "kamdan-kam"),
     ("mai", "hech qachon"), ("ogni giorno", "har kuni"), ("di solito", "odatda"), ("subito", "darhol"),
     ("ancora", "yana"), ("già", "allaqachon")],
    [("Vado sempre a piedi.", "Men doim piyoda boraman."), ("A volte lavoro il sabato.", "Ba'zan shanba kuni ishlayman."),
     ("Non bevo mai caffè.", "Men hech qachon qahva ichmayman."), ("Di solito ceno alle otto.", "Odatda soat sakkizda kechki ovqat qilaman."),
     ("Ogni giorno studio uzbeko.", "Har kuni o'zbek tilini o'rganaman."), ("Ho già mangiato.", "Men allaqachon ovqatlandim.")]),
  ],
  dialogue=(("Una giornata tipo", "Odatdagi kun"), [
    ("Dilnoza", "A che ora ti svegli?", "Soat nechada uyg'onasan?"),
    ("Giulia", "Alle sette. E tu?", "Yettida. Sen-chi?"),
    ("Dilnoza", "Io alle sei, lavoro lontano.", "Men oltida, ishim uzoq."),
    ("Giulia", "Come vai al lavoro?", "Ishga qanday borasan?"),
    ("Dilnoza", "In metro, poi dieci minuti a piedi.", "Metroda, keyin o'n daqiqa piyoda."),
    ("Giulia", "E la sera che cosa fai?", "Kechqurun nima qilasan?"),
    ("Dilnoza", "Di solito leggo o guardo un film.", "Odatda o'qiyman yoki kino ko'raman."),
  ])),

 dict(id="a1u8", icon="sun.max.fill", accent="amber",
  title=("Tempo libero e meteo", "Bo'sh vaqt va ob-havo"),
  subtitle=("Hobby, stagioni, inviti", "Sevimli mashg'ulot, fasllar, taklif"),
  grammar=[
    (("Voglio, posso, devo", "«Xohlayman, bilaman, kerak»"),
     ("Volere: verbo + -moqchiman (bormoqchiman = voglio andare). Potere: radice + -a olaman (bora olaman = posso andare). Dovere: verbo all'infinito + kerak (borishim kerak = devo andare).",
      "Italyan tilida uchta modal fe'l bor: volere (voglio), potere (posso), dovere (devo). Ulardan keyin fe'l infinitivda keladi: voglio andare, posso venire, devo studiare."),
     [("Voglio andare.", "Men bormoqchiman."), ("Posso venire?", "Kelsam bo'ladimi?"), ("Devo studiare.", "Men o'qishim kerak.")]),
    (("Il futuro vicino", "Kelasi zamon"),
     ("L'uzbeko usa lo stesso tempo per presente e futuro: Ertaga boraman = domani vado/andrò. Il contesto chiarisce.",
      "Italyan tilida kelasi zamon alohida shakl: andrò, sarà, faremo. Lekin kundalik nutqda hozirgi zamon ham ishlatiladi: Domani vado a Roma."),
     [("Domani vado a Roma.", "Ertaga Rimga boraman."), ("La settimana prossima lavorerò.", "Kelasi hafta ishlayman.")]),
  ],
  lessons=[
   ("a1u8l1", ("Hobby", "Sevimli mashg'ulot"),
    [("sport", "sport"), ("calcio", "futbol"), ("nuotare", "suzmoq"), ("correre", "yugurmoq"),
     ("ballare", "raqsga tushmoq"), ("cantare", "qo'shiq aytmoq"), ("disegnare", "rasm chizmoq"),
     ("viaggiare", "sayohat qilmoq"), ("giocare", "o'ynamoq"), ("tempo libero", "bo'sh vaqt")],
    [("Che cosa fai nel tempo libero?", "Bo'sh vaqtingda nima qilasan?"), ("Mi piace nuotare.", "Menga suzish yoqadi."),
     ("Gioco a calcio la domenica.", "Yakshanba kuni futbol o'ynayman."), ("Non so ballare.", "Men raqsga tusha olmayman."),
     ("Voglio imparare a cantare.", "Men qo'shiq aytishni o'rganmoqchiman."), ("Viaggio spesso.", "Men tez-tez sayohat qilaman.")]),
   ("a1u8l2", ("Il tempo che fa", "Ob-havo"),
    [("sole", "quyosh"), ("pioggia", "yomg'ir"), ("neve", "qor"), ("vento", "shamol"),
     ("nuvola", "bulut"), ("caldo (nome)", "issiq"), ("freddo (nome)", "sovuq"), ("cielo", "osmon"),
     ("temperatura", "harorat"), ("ombrello", "soyabon")],
    [("Che tempo fa?", "Ob-havo qanday?"), ("Oggi c'è il sole.", "Bugun quyoshli."),
     ("Piove molto.", "Kuchli yomg'ir yog'yapti."), ("Fa freddo oggi.", "Bugun sovuq."),
     ("Domani nevicherà.", "Ertaga qor yog'adi."), ("Prendi l'ombrello!", "Soyabonni ol!")]),
   ("a1u8l3", ("Le stagioni", "Fasllar"),
    [("primavera", "bahor"), ("estate", "yoz"), ("autunno", "kuz"), ("inverno", "qish"),
     ("vacanza", "ta'til"), ("mare", "dengiz"), ("montagna", "tog'"), ("festa", "bayram"),
     ("caldo d'estate", "yozgi issiq"), ("albero", "daraxt")],
    [("Qual è la tua stagione preferita?", "Sevimli fasling qaysi?"), ("Amo la primavera.", "Men bahorni yaxshi ko'raman."),
     ("D'estate fa molto caldo.", "Yozda juda issiq bo'ladi."), ("In inverno andiamo in montagna.", "Qishda tog'ga boramiz."),
     ("Le vacanze iniziano a giugno.", "Ta'til iyunda boshlanadi."), ("Il Navruz è a marzo.", "Navro'z martda.")]),
   ("a1u8l4", ("Facciamo qualcosa?", "Biror narsa qilaylikmi?"),
    [("invitare", "taklif qilmoq"), ("insieme", "birga"), ("libero", "bo'sh"), ("occupato", "band"),
     ("idea", "fikr"), ("volentieri", "mamnuniyat bilan"), ("magari", "balki"), ("appuntamento", "uchrashuv"),
     ("compleanno (festa)", "tug'ilgan kun"), ("cinema", "kinoteatr")],
    [("Sei libero stasera?", "Bugun kechqurun bo'shmisan?"), ("Andiamo al cinema?", "Kinoteatrga boramizmi?"),
     ("Volentieri!", "Mamnuniyat bilan!"), ("Mi dispiace, sono occupata.", "Kechirasan, men bandman."),
     ("Ti invito a casa mia.", "Seni uyimga taklif qilaman."), ("Che bella idea!", "Qanday yaxshi fikr!")]),
  ],
  dialogue=(("Il fine settimana", "Dam olish kunlari"), [
    ("Aziz", "Che fai questo weekend?", "Bu dam olish kunlari nima qilasan?"),
    ("Giulia", "Non lo so ancora. Tu hai un'idea?", "Hali bilmayman. Sening fikring bormi?"),
    ("Aziz", "Se c'è il sole, andiamo in montagna.", "Agar quyoshli bo'lsa, tog'ga boramiz."),
    ("Giulia", "Volentieri! A che ora?", "Mamnuniyat bilan! Soat nechada?"),
    ("Aziz", "Presto, alle sette di mattina.", "Erta, ertalab soat yettida."),
    ("Giulia", "Va bene. Ma se piove?", "Mayli. Agar yomg'ir yog'sa-chi?"),
    ("Aziz", "Allora andiamo al cinema.", "Unda kinoteatrga boramiz."),
  ])),
]
