# -*- coding: utf-8 -*-
# A2 — Elementare / Elementar

LEVEL = "a2"

UNITS = [
 dict(id="a2u1", icon="clock.arrow.circlepath", accent="sky",
  title=("Raccontare il passato", "O'tgan zamon"),
  subtitle=("Dire che cosa hai fatto ieri, la settimana scorsa", "Kecha, o'tgan hafta nima qilganingizni aytish"),
  grammar=[
    (("Il passato: -di", "O'tgan zamon: -di"),
     ("Il passato uzbeko si forma con -di + persona: bor-di-m (sono andato), bor-di-ng (sei andato), bor-di (è andato), bor-di-k (siamo andati), bor-di-ngiz, bor-di-lar. Dopo consonante sorda diventa -ti: ket-ti-m.",
      "Italyan tilida o'tgan zamonning ikki asosiy shakli bor. Passato prossimo tugallangan ish uchun: avere/essere + participio (ho mangiato, sono andato). Ko'chish va holat fe'llari essere bilan keladi va oxiri jinsga moslashadi: sono andata."),
     [("Sono andato al mercato.", "Men bozorga bordim."), ("Ieri ho lavorato.", "Kecha ishladim."), ("Siamo tornati tardi.", "Biz kech qaytdik.")]),
    (("Passato prossimo o imperfetto?", "Tugallangan va davomli o'tmish"),
     ("In uzbeko l'azione ripetuta o abituale nel passato si esprime con -ardi/-rdi: borardim = andavo (di solito). Il -di semplice indica un fatto concluso.",
      "Italyan tilida imperfetto odat va tasvir uchun: da bambino andavo al mare, faceva freddo. Passato prossimo esa bir marta bo'lgan tugallangan ish uchun: ieri sono andato al mare."),
     [("Da bambino andavo al mare.", "Bolaligimda dengizga borardim."), ("Faceva freddo.", "Sovuq edi."), ("Ieri sono andato al mare.", "Kecha dengizga bordim.")]),
    (("Ieri, la settimana scorsa…", "Vaqt ifodalari"),
     ("Per collocare l'azione nel passato: kecha (ieri), o'tgan hafta (la settimana scorsa), o'tgan yili (l'anno scorso), bir necha kun oldin (qualche giorno fa).",
      "Vaqt ifodalari: ieri, l'altro ieri, la settimana scorsa, il mese scorso, l'anno scorso, due giorni fa, poco fa."),
     [("la settimana scorsa", "o'tgan hafta"), ("due giorni fa", "ikki kun oldin"), ("l'anno scorso", "o'tgan yili")]),
  ],
  lessons=[
   ("a2u1l1", ("Ieri", "Kecha"),
    [("ieri", "kecha"), ("l'altro ieri", "indinga"), ("scorso", "o'tgan"), ("fa (tempo)", "oldin"),
     ("succedere", "sodir bo'lmoq"), ("finire", "tugatmoq"), ("cominciare", "boshlamoq"),
     ("incontrare", "uchrashmoq"), ("dimenticare", "unutmoq"), ("ricordare", "eslamoq")],
    [("Che cosa hai fatto ieri?", "Kecha nima qilding?"), ("Ho lavorato tutto il giorno.", "Kun bo'yi ishladim."),
     ("Ho incontrato un amico.", "Bir do'stimni uchratdim."), ("Ho dimenticato il telefono a casa.", "Telefonimni uyda unutibman."),
     ("Il film è finito tardi.", "Kino kech tugadi."), ("Non è successo niente.", "Hech narsa sodir bo'lmadi.")]),
   ("a2u1l2", ("Il fine settimana scorso", "O'tgan dam olish kunlari"),
    [("visitare", "ziyorat qilmoq"), ("restare", "qolmoq"), ("partire", "jo'namoq"), ("arrivare", "yetib kelmoq"),
     ("comprare (pass.)", "sotib oldim"), ("divertirsi", "ko'ngil ochmoq"), ("riposarsi", "dam olmoq"),
     ("pranzo", "tushlik"), ("insieme a", "bilan birga"), ("poi", "keyin")],
    [("Dove sei stato il fine settimana?", "Dam olish kunlari qayerda bo'lding?"), ("Sono rimasta a casa.", "Uyda qoldim."),
     ("Siamo andati a Samarcanda.", "Biz Samarqandga bordik."), ("Ci siamo divertiti molto.", "Juda ko'ngil ochdik."),
     ("Poi abbiamo pranzato insieme.", "Keyin birga tushlik qildik."), ("Sono tornato domenica sera.", "Yakshanba kechqurun qaytdim.")]),
   ("a2u1l3", ("Quando ero piccolo", "Bolaligimda"),
    [("infanzia", "bolalik"), ("da bambino", "bolaligida"), ("crescere", "o'smoq"), ("villaggio", "qishloq"),
     ("giocare (pass.)", "o'ynardim"), ("scuola elementare", "boshlang'ich maktab"), ("compagno", "sinfdosh"),
     ("nonni", "buvi-bobo"), ("estate (di allora)", "o'sha yoz"), ("felice (pass.)", "baxtli edim")],
    [("Da bambina vivevo in campagna.", "Bolaligimda qishloqda yashardim."), ("Giocavamo in strada.", "Ko'chada o'ynardik."),
     ("Andavo dai nonni ogni estate.", "Har yoz buvimnikiga borardim."), ("Non mi piaceva la scuola.", "Menga maktab yoqmasdi."),
     ("Eravamo molto felici.", "Biz juda baxtli edik."), ("Che cosa facevi da piccolo?", "Bolaligingda nima qilarding?")]),
   ("a2u1l4", ("Racconti", "Hikoyalar"),
    [("storia", "hikoya"), ("all'inizio", "avvaliga"), ("alla fine", "oxirida"), ("all'improvviso", "to'satdan"),
     ("dopo", "keyin"), ("prima", "oldin"), ("perché", "chunki"), ("però", "lekin"),
     ("purtroppo", "afsuski"), ("per fortuna", "yaxshiyamki")],
    [("Ti racconto una storia.", "Senga bir hikoya aytib beraman."), ("All'inizio non capivo niente.", "Avvaliga hech narsa tushunmasdim."),
     ("All'improvviso è arrivato.", "To'satdan u keldi."), ("Purtroppo ho perso il treno.", "Afsuski, poyezdga kechikdim."),
     ("Per fortuna c'era un taxi.", "Yaxshiyamki, taksi bor edi."), ("Alla fine è andata bene.", "Oxirida hammasi yaxshi bo'ldi.")]),
  ],
  dialogue=(("Com'è andato il viaggio?", "Sayohat qanday o'tdi?"), [
    ("Dilnoza", "Allora, com'è andato il viaggio?", "Xo'sh, sayohat qanday o'tdi?"),
    ("Giulia", "Benissimo! Siamo partiti venerdì sera.", "Juda zo'r! Juma kechqurun jo'nadik."),
    ("Dilnoza", "Dove siete andati?", "Qayerga bordingiz?"),
    ("Giulia", "A Samarcanda. Abbiamo visto il Registan.", "Samarqandga. Registonni ko'rdik."),
    ("Dilnoza", "Vi è piaciuto?", "Yoqdimi?"),
    ("Giulia", "Tantissimo. Però faceva molto caldo.", "Juda ham. Lekin havo juda issiq edi."),
    ("Dilnoza", "E quando siete tornati?", "Qachon qaytdingiz?"),
    ("Giulia", "Domenica notte, stanchi ma felici.", "Yakshanba tunda, charchagan lekin baxtli."),
  ])),

 dict(id="a2u2", icon="airplane", accent="teal",
  title=("Viaggi e trasporti", "Sayohat va transport"),
  subtitle=("Prenotare, viaggiare, alloggiare", "Bron qilish, sayohat, mehmonxona"),
  grammar=[
    (("Le postposizioni: bilan, uchun, keyin", "Ko'makchilar"),
     ("L'uzbeko mette le «preposizioni» dopo la parola: do'stim bilan (con il mio amico), sen uchun (per te), darsdan keyin (dopo la lezione), ovqatdan oldin (prima del pasto).",
      "Italyan tilida ular so'zdan OLDIN keladi: con il mio amico, per te, dopo la lezione, prima del pasto. Ba'zilari artikl bilan qo'shiladi: dopo il, prima della."),
     [("con il mio amico", "do'stim bilan"), ("per te", "sen uchun"), ("dopo la lezione", "darsdan keyin")]),
    (("Il dativo -ga e l'ablativo -dan", "Yo'nalish va chiqish kelishiklari"),
     ("-ga indica la destinazione (Rimga boraman = vado a Roma), -dan la provenienza (Rimdan kelaman = vengo da Roma).",
      "Italyan tilida yo'nalish uchun a/in (vado a Roma, vado in Italia), chiqish uchun da (vengo da Roma). Shahar bilan «a», davlat bilan «in» ishlatiladi."),
     [("Vado a Roma.", "Rimga boraman."), ("Vengo dall'Italia.", "Italiyadan kelaman."), ("Vado in Uzbekistan.", "O'zbekistonga boraman.")]),
  ],
  lessons=[
   ("a2u2l1", ("In viaggio", "Sayohatda"),
    [("viaggio", "sayohat"), ("volo", "parvoz"), ("passaporto", "pasport"), ("visto", "viza"),
     ("bagaglio", "yuk"), ("partenza", "jo'nash"), ("arrivo", "kelish"), ("ritardo", "kechikish"),
     ("frontiera", "chegara"), ("dogana", "bojxona")],
    [("A che ora parte il volo?", "Parvoz soat nechada?"), ("Il treno è in ritardo.", "Poyezd kechikyapti."),
     ("Ho perso il volo.", "Men parvozga kechikdim."), ("Dov'è il ritiro bagagli?", "Yuk olish joyi qayerda?"),
     ("Quanto dura il viaggio?", "Sayohat qancha davom etadi?"), ("Buon viaggio!", "Oq yo'l!")]),
   ("a2u2l2", ("In albergo", "Mehmonxonada"),
    [("albergo", "mehmonxona"), ("camera singola", "bir kishilik xona"), ("prenotazione", "bron"),
     ("chiave (camera)", "xona kaliti"), ("reception", "qabulxona"), ("notte (soggiorno)", "kecha"),
     ("colazione inclusa", "nonushta bilan"), ("asciugamano", "sochiq"), ("pulire", "tozalamoq"),
     ("rumoroso", "shovqinli")],
    [("Ho una prenotazione.", "Menda bron bor."), ("Vorrei una camera per due notti.", "Ikki kechalik xona kerak."),
     ("La colazione è inclusa?", "Nonushta narxga kiradimi?"), ("La camera è rumorosa.", "Xona shovqinli."),
     ("A che ora è il check-out?", "Xonani soat nechada bo'shatish kerak?"), ("Il wifi non funziona.", "Wifi ishlamayapti.")]),
   ("a2u2l3", ("Alla stazione", "Bekatda"),
    [("stazione", "vokzal"), ("binario", "yo'lak"), ("andata", "boradigan"), ("ritorno", "qaytadigan"),
     ("biglietteria", "kassa"), ("posto", "joy"), ("coincidenza", "ulanish"), ("orario", "jadval"),
     ("salire", "chiqmoq"), ("scendere", "tushmoq")],
    [("Un biglietto di andata e ritorno.", "Borib-kelish chiptasi."), ("Da quale binario parte?", "Qaysi yo'lakdan jo'naydi?"),
     ("Questo posto è libero?", "Bu joy bo'shmi?"), ("Devo cambiare treno?", "Poyezdni almashtirishim kerakmi?"),
     ("Scendo alla prossima.", "Keyingi bekatda tushaman."), ("Dov'è l'orario dei treni?", "Poyezd jadvali qayerda?")]),
   ("a2u2l4", ("Paesi e nazionalità", "Mamlakatlar va millatlar"),
    [("straniero", "chet ellik"), ("estero", "chet el"), ("confine", "chegara"), ("mappa (paese)", "xarita"),
     ("capitale", "poytaxt"), ("nord", "shimol"), ("sud", "janub"), ("est", "sharq"),
     ("ovest", "g'arb"), ("popolo", "xalq")],
    [("Sei mai stato all'estero?", "Chet elda bo'lganmisan?"), ("Tashkent è la capitale.", "Toshkent — poytaxt."),
     ("Vivo al nord dell'Italia.", "Men Italiyaning shimolida yashayman."), ("Quante lingue parli?", "Nechta til bilasan?"),
     ("Sono straniera qui.", "Men bu yerda chet ellikman."), ("Vorrei visitare l'Uzbekistan.", "O'zbekistonga borishni xohlayman.")]),
  ],
  dialogue=(("Alla reception", "Qabulxonada"), [
    ("Giulia", "Buonasera, ho una prenotazione.", "Xayrli kech, menda bron bor."),
    ("Xodim", "A che nome, prego?", "Kimning nomiga?"),
    ("Giulia", "Giulia Rossi, due notti.", "Giulia Rossi, ikki kecha."),
    ("Xodim", "Perfetto. Camera 305, terzo piano.", "Zo'r. 305-xona, uchinchi qavat."),
    ("Giulia", "La colazione è inclusa?", "Nonushta narxga kiradimi?"),
    ("Xodim", "Sì, dalle sette alle dieci.", "Ha, yettidan o'ngacha."),
    ("Giulia", "E il wifi?", "Wifi-chi?"),
    ("Xodim", "La password è sulla chiave.", "Parol kalitning ustida yozilgan."),
  ])),

 dict(id="a2u3", icon="heart.text.square.fill", accent="red",
  title=("Corpo e salute", "Tana va salomatlik"),
  subtitle=("Dal medico, in farmacia, stare bene", "Shifokorda, dorixonada, sog'lik"),
  grammar=[
    (("Mi fa male: «og'riyapti»", "«Og'rimoq» fe'li"),
     ("«Mi fa male la testa» si dice boshim og'riyapti (la mia testa sta dolendo): la parte del corpo prende il possessivo e il verbo og'rimoq.",
      "Italyan tilida «fare male» qurilishi ishlatiladi: mi fa male la testa, mi fanno male i denti. Tana a'zosi artikl bilan keladi, egalik qo'shimchasi qo'yilmaydi."),
     [("Mi fa male la testa.", "Boshim og'riyapti."), ("Mi fanno male i denti.", "Tishlarim og'riyapti.")]),
    (("Devo, bisogna: «kerak»", "«Kerak» va «lozim»"),
     ("Per l'obbligo si usa kerak dopo il verbo alla forma -(i)sh + possessivo: dam olishim kerak = devo riposare; dam olish kerak = bisogna riposare (impersonale).",
      "Italyan tilida shaxsli majburiyat uchun dovere (devo riposare), shaxssiz uchun bisogna + infinito (bisogna riposare) yoki è necessario ishlatiladi."),
     [("Devo riposare.", "Dam olishim kerak."), ("Bisogna bere molta acqua.", "Ko'p suv ichish kerak.")]),
  ],
  lessons=[
   ("a2u3l1", ("Il corpo", "Tana"),
    [("testa", "bosh"), ("occhio", "ko'z"), ("orecchio", "quloq"), ("bocca", "og'iz"),
     ("mano", "qo'l"), ("piede", "oyoq"), ("schiena", "bel"), ("stomaco", "oshqozon"),
     ("cuore", "yurak"), ("gola", "tomoq")],
    [("Mi fa male la testa.", "Boshim og'riyapti."), ("Ho mal di gola.", "Tomog'im og'riyapti."),
     ("Mi sono fatto male alla mano.", "Qo'limni lat yedirdim."), ("Ho mal di stomaco.", "Oshqozonim og'riyapti."),
     ("Mi fanno male i piedi.", "Oyoqlarim og'riyapti."), ("Il cuore batte forte.", "Yurak tez uryapti.")]),
   ("a2u3l2", ("Dal medico", "Shifokorda"),
    [("medico (dott.)", "shifokor"), ("malato", "kasal"), ("febbre", "isitma"), ("raffreddore", "shamollash"),
     ("tosse", "yo'tal"), ("influenza", "gripp"), ("dolore", "og'riq"), ("ricetta", "retsept"),
     ("visita", "ko'rik"), ("guarire", "tuzalmoq")],
    [("Non mi sento bene.", "O'zimni yaxshi his qilmayapman."), ("Ho la febbre alta.", "Isitmam baland."),
     ("Da quanto tempo stai male?", "Qachondan beri kasalsan?"), ("Devo prendere una medicina?", "Dori ichishim kerakmi?"),
     ("Riposa e bevi molto.", "Dam ol va ko'p ich."), ("Spero che guarisca presto.", "Tezroq tuzalib ketishingizni tilayman.")]),
   ("a2u3l3", ("In farmacia", "Dorixonada"),
    [("farmacia (luogo)", "dorixona"), ("medicina", "dori"), ("pastiglia", "tabletka"), ("sciroppo", "sirop"),
     ("cerotto", "plastir"), ("allergia", "allergiya"), ("dose", "doza"), ("tre volte al giorno", "kuniga uch marta"),
     ("consiglio", "maslahat"), ("sicuro", "xavfsiz")],
    [("Avete qualcosa per il mal di testa?", "Bosh og'rig'iga biror narsa bormi?"),
     ("Prenda una pastiglia dopo i pasti.", "Ovqatdan keyin bitta tabletka iching."),
     ("Sono allergica alla penicillina.", "Menda penitsillinga allergiya bor."),
     ("Quante volte al giorno?", "Kuniga necha marta?"), ("Serve la ricetta?", "Retsept kerakmi?"),
     ("Grazie del consiglio.", "Maslahat uchun rahmat.")]),
   ("a2u3l4", ("Stare bene", "Sog'lom bo'lish"),
    [("salute", "salomatlik"), ("sano", "sog'lom"), ("sport (attività)", "sport bilan shug'ullanish"),
     ("dieta", "parhez"), ("dormire bene", "yaxshi uxlamoq"), ("stress", "stress"),
     ("stanchezza", "charchoq"), ("camminare", "yurmoq"), ("respirare", "nafas olmoq"), ("forte", "kuchli")],
    [("Bisogna dormire otto ore.", "Sakkiz soat uxlash kerak."), ("Faccio sport tre volte a settimana.", "Haftada uch marta sport bilan shug'ullanaman."),
     ("Sono molto stressata.", "Men juda stressdaman."), ("Cammino ogni giorno.", "Har kuni yuraman."),
     ("Mangio poco zucchero.", "Kam shakar yeyman."), ("La salute viene prima di tutto.", "Salomatlik hammasidan muhim.")]),
  ],
  dialogue=(("Non mi sento bene", "O'zimni yomon his qilyapman"), [
    ("Shifokor", "Buongiorno, che cosa c'è che non va?", "Xayrli kun, nima bo'ldi?"),
    ("Giulia", "Ho mal di gola e un po' di febbre.", "Tomog'im og'riyapti va biroz isitmam bor."),
    ("Shifokor", "Da quanti giorni?", "Necha kundan beri?"),
    ("Giulia", "Da tre giorni.", "Uch kundan beri."),
    ("Shifokor", "Apra la bocca, per favore… È solo un'influenza.", "Og'zingizni oching, iltimos… Bu oddiy gripp."),
    ("Giulia", "Devo prendere qualcosa?", "Biror dori ichishim kerakmi?"),
    ("Shifokor", "Questo sciroppo, tre volte al giorno. E riposi.", "Bu siropni kuniga uch marta iching. Va dam oling."),
    ("Giulia", "Grazie mille, dottore.", "Katta rahmat, doktor."),
  ])),

 dict(id="a2u4", icon="briefcase.fill", accent="purple",
  title=("Lavoro e studio", "Ish va ta'lim"),
  subtitle=("Parlare di professioni, colloqui, università", "Kasblar, suhbat, universitet"),
  grammar=[
    (("Il participio -gan: «che ha fatto»", "«-gan» sifatdoshi"),
     ("Con -gan si costruiscono le frasi relative, che in uzbeko precedono il nome: men o'qigan kitob = il libro che ho letto (lett. io letto libro).",
      "Italyan tilida ergash gap otdan KEYIN keladi va «che» bog'lovchisi bilan boshlanadi: il libro che ho letto, la ragazza che lavora qui."),
     [("il libro che ho letto", "men o'qigan kitob"), ("la ragazza che lavora qui", "bu yerda ishlaydigan qiz")]),
    (("Saper fare: -a olmoq", "Imkoniyat shakli"),
     ("La capacità si esprime con -a/-y + olmoq: gapira olaman (so parlare / posso parlare), bora olmayman (non posso andare).",
      "Italyan tilida ikki fe'l bor: sapere — o'rganilgan ko'nikma (so parlare italiano), potere — imkoniyat/ruxsat (posso venire domani)."),
     [("So parlare italiano.", "Italyancha gapira olaman."), ("Non posso venire.", "Kela olmayman.")]),
  ],
  lessons=[
   ("a2u4l1", ("Le professioni", "Kasblar"),
    [("ingegnere", "muhandis"), ("avvocato", "advokat"), ("cuoco", "oshpaz"), ("commesso", "sotuvchi"),
     ("autista", "haydovchi"), ("infermiera", "hamshira"), ("giornalista", "jurnalist"),
     ("impiegato", "xizmatchi"), ("operaio", "ishchi"), ("disoccupato", "ishsiz")],
    [("Che lavoro fa tuo padre?", "Otang nima ish qiladi?"), ("Fa l'ingegnere.", "U muhandis."),
     ("Lavoro come insegnante.", "Men o'qituvchi bo'lib ishlayman."), ("Sto cercando lavoro.", "Men ish qidiryapman."),
     ("Mi piace il mio lavoro.", "Menga ishim yoqadi."), ("Guadagna bene.", "U yaxshi maosh oladi.")]),
   ("a2u4l2", ("In ufficio", "Ofisda"),
    [("capo", "boshliq"), ("stipendio", "maosh"), ("contratto", "shartnoma"), ("orario di lavoro", "ish vaqti"),
     ("pausa", "tanaffus"), ("ferie", "ta'til"), ("email", "elektron xat"), ("computer", "kompyuter"),
     ("documento", "hujjat"), ("scadenza", "muddat")],
    [("Lavoro dalle nove alle sei.", "To'qqizdan oltigacha ishlayman."), ("Devo finire entro venerdì.", "Jumagacha tugatishim kerak."),
     ("Ho mandato l'email al capo.", "Boshliqqa xat yubordim."), ("Prendo una pausa.", "Tanaffus qilaman."),
     ("Quando vai in ferie?", "Qachon ta'tilga chiqasan?"), ("Ho troppo lavoro.", "Ishim juda ko'p.")]),
   ("a2u4l3", ("All'università", "Universitetda"),
    [("facoltà", "fakultet"), ("esame", "imtihon"), ("voto", "baho"), ("laurea", "diplom"),
     ("corso", "kurs"), ("biblioteca", "kutubxona"), ("borsa di studio", "stipendiya"),
     ("ricerca", "tadqiqot"), ("professore", "professor"), ("iscriversi", "ro'yxatdan o'tmoq")],
    [("Che cosa studi?", "Nima o'qiyapsan?"), ("Studio economia.", "Men iqtisod o'qiyapman."),
     ("Ho passato l'esame.", "Imtihondan o'tdim."), ("Sono al secondo anno.", "Men ikkinchi kursdaman."),
     ("Devo studiare in biblioteca.", "Kutubxonada o'qishim kerak."), ("Mi sono laureata l'anno scorso.", "O'tgan yili diplom oldim.")]),
   ("a2u4l4", ("Il colloquio", "Suhbat"),
    [("curriculum", "rezyume"), ("esperienza", "tajriba"), ("competenza", "malaka"), ("candidato", "nomzod"),
     ("assumere", "ishga olmoq"), ("licenziare", "ishdan bo'shatmoq"), ("motivazione", "motivatsiya"),
     ("puntuale", "vaqtida"), ("responsabile", "mas'ul"), ("squadra", "jamoa")],
    [("Ho tre anni di esperienza.", "Uch yillik tajribam bor."), ("So usare il computer.", "Kompyuterdan foydalana olaman."),
     ("Perché vuole lavorare qui?", "Nega bu yerda ishlamoqchisiz?"), ("Sono una persona responsabile.", "Men mas'uliyatli odamman."),
     ("Lavoro bene in squadra.", "Jamoada yaxshi ishlayman."), ("Quando posso iniziare?", "Qachon boshlashim mumkin?")]),
  ],
  dialogue=(("Il colloquio di lavoro", "Ish suhbati"), [
    ("Boshliq", "Buongiorno, si accomodi. Mi parli di lei.", "Xayrli kun, o'tiring. O'zingiz haqingizda gapiring."),
    ("Aziz", "Mi chiamo Aziz, ho ventotto anni e sono ingegnere.", "Ismim Aziz, yigirma sakkiz yoshdaman, muhandisman."),
    ("Boshliq", "Che esperienza ha?", "Qanday tajribangiz bor?"),
    ("Aziz", "Ho lavorato tre anni in una ditta italiana.", "Uch yil italyan kompaniyasida ishladim."),
    ("Boshliq", "Parla italiano?", "Italyancha gapirasizmi?"),
    ("Aziz", "Sì, lo studio da due anni.", "Ha, ikki yildan beri o'rganyapman."),
    ("Boshliq", "Bene. Quando può iniziare?", "Yaxshi. Qachon boshlay olasiz?"),
    ("Aziz", "Dal mese prossimo.", "Kelasi oydan."),
  ])),

 dict(id="a2u5", icon="washer.fill", accent="green",
  title=("Casa e faccende", "Uy yumushlari"),
  subtitle=("Vivere insieme, pulizie, problemi pratici", "Birga yashash, tozalik, muammolar"),
  grammar=[
    (("Il gerundio -ib: «facendo»", "«-ib» ravishdoshi"),
     ("La desinenza -ib collega due azioni dello stesso soggetto: uyga borib, ovqat pishirdim = tornato a casa, ho cucinato.",
      "Italyan tilida bu gerundio yoki «e poi» bilan beriladi: tornando a casa ho cucinato / sono tornato a casa e ho cucinato."),
     [("Tornando a casa ho cucinato.", "Uyga borib, ovqat pishirdim."), ("Si è seduto e ha letto.", "U o'tirib, o'qidi.")]),
    (("I pronomi diretti", "To'ldiruvchi olmoshlar"),
     ("In uzbeko il pronome oggetto è una parola piena con -ni: meni (me), seni (te), uni (lo/la), bizni, sizni, ularni.",
      "Italyan tilida qisqa olmoshlar fe'ldan OLDIN turadi: mi, ti, lo, la, ci, vi, li, le. Masalan: Lo conosco. Ti chiamo domani. Buyruq bilan fe'lga qo'shiladi: chiamami!"),
     [("Lo conosco.", "Men uni taniyman."), ("Ti chiamo domani.", "Ertaga senga qo'ng'iroq qilaman."), ("Chiamami!", "Menga qo'ng'iroq qil!")]),
  ],
  lessons=[
   ("a2u5l1", ("Le faccende", "Uy ishlari"),
    [("pulire (casa)", "yig'ishtirmoq"), ("lavare", "yuvmoq"), ("stirare", "dazmollamoq"),
     ("spazzare", "supurmoq"), ("cucinare (pasto)", "pishirmoq"), ("apparecchiare", "dasturxon yozmoq"),
     ("spazzatura", "axlat"), ("bucato", "kir"), ("ordine", "tartib"), ("sporco", "iflos")],
    [("Devo pulire la casa.", "Uyni yig'ishtirishim kerak."), ("Chi lava i piatti?", "Idishlarni kim yuvadi?"),
     ("Ho fatto il bucato.", "Kir yuvdim."), ("Porta fuori la spazzatura.", "Axlatni chiqarib tashla."),
     ("La cucina è sporca.", "Oshxona iflos."), ("Facciamo le pulizie insieme.", "Keling, birga tozalaymiz.")]),
   ("a2u5l2", ("Problemi di casa", "Uy muammolari"),
    [("rotto", "buzuq"), ("riparare", "tuzatmoq"), ("perdita d'acqua", "suv oqishi"), ("luce (corrente)", "elektr"),
     ("riscaldamento", "isitish"), ("idraulico", "santexnik"), ("affitto", "ijara"),
     ("bolletta", "hisob"), ("padrone di casa", "uy egasi"), ("vicino rumoroso", "shovqinli qo'shni")],
    [("Il riscaldamento non funziona.", "Isitish ishlamayapti."), ("C'è una perdita d'acqua.", "Suv oqyapti."),
     ("Devo chiamare l'idraulico.", "Santexnikni chaqirishim kerak."), ("Quanto è l'affitto?", "Ijara qancha?"),
     ("Ho pagato la bolletta.", "Hisobni to'ladim."), ("Non c'è la luce.", "Elektr yo'q.")]),
   ("a2u5l3", ("Vivere insieme", "Birga yashash"),
    [("coinquilino", "sherik"), ("regola", "qoida"), ("turno", "navbat"), ("aiutare", "yordam bermoq"),
     ("chiedere", "so'ramoq"), ("permesso", "ruxsat"), ("disturbare", "bezovta qilmoq"),
     ("rispettare", "hurmat qilmoq"), ("litigare", "janjallashmoq"), ("accordo", "kelishuv")],
    [("Posso usare la cucina?", "Oshxonadan foydalansam bo'ladimi?"), ("Oggi tocca a te.", "Bugun sening navbating."),
     ("Scusa se ti disturbo.", "Bezovta qilsam, kechir."), ("Mi puoi aiutare?", "Menga yordam bera olasanmi?"),
     ("Siamo d'accordo.", "Kelishdik."), ("Rispetta le regole, per favore.", "Qoidalarga rioya qil, iltimos.")]),
   ("a2u5l4", ("Fare la spesa", "Oziq-ovqat xaridi"),
    [("supermercato", "supermarket"), ("lista", "ro'yxat"), ("carrello", "arava"), ("etichetta", "yorliq"),
     ("scadenza (data)", "yaroqlilik muddati"), ("offerta", "aksiya"), ("sacchetto", "paket"),
     ("pesare", "tortmoq"), ("fresco", "yangi"), ("surgelato", "muzlatilgan")],
    [("Ho fatto la lista della spesa.", "Xarid ro'yxatini tuzdim."), ("Questo è in offerta.", "Bu aksiyada."),
     ("Controlla la scadenza.", "Yaroqlilik muddatini tekshir."), ("Il pane è fresco?", "Non yangimi?"),
     ("Mi serve un sacchetto.", "Menga paket kerak."), ("Abbiamo finito il latte.", "Sutimiz tugadi.")]),
  ],
  dialogue=(("Turni di pulizia", "Tozalash navbati"), [
    ("Dilnoza", "Senti, dobbiamo parlare delle pulizie.", "Eshit, tozalash haqida gaplashishimiz kerak."),
    ("Giulia", "Hai ragione, la cucina è un disastro.", "To'g'ri aytasan, oshxona juda iflos."),
    ("Dilnoza", "Facciamo dei turni? Io il lunedì, tu il giovedì.", "Navbat qilaylikmi? Men dushanba, sen payshanba."),
    ("Giulia", "Va bene. E la spazzatura?", "Mayli. Axlat-chi?"),
    ("Dilnoza", "La porta fuori chi cucina.", "Kim ovqat pishirsa, o'sha chiqaradi."),
    ("Giulia", "Perfetto, siamo d'accordo.", "Zo'r, kelishdik."),
  ])),

 dict(id="a2u6", icon="rectangle.3.group.fill", accent="pink",
  title=("Descrivere e confrontare", "Tasvirlash va taqqoslash"),
  subtitle=("Colori, forme, opinioni su cose e persone", "Ranglar, shakllar, taqqoslash"),
  grammar=[
    (("Il comparativo: -roq", "Qiyosiy daraja"),
     ("Per dire «più…» si aggiunge -roq: katta → kattaroq (più grande). Il termine di paragone prende -dan: Bu uy o'shadan kattaroq = questa casa è più grande di quella.",
      "Italyan tilida «più/meno … di»: questa casa è più grande di quella. Ba'zi sifatlarning maxsus shakli bor: buono → migliore, cattivo → peggiore, grande → maggiore."),
     [("più grande di", "…dan kattaroq"), ("Questa casa è più grande.", "Bu uy kattaroq."), ("è migliore", "yaxshiroq")]),
    (("Il superlativo: eng", "Orttirma daraja"),
     ("Il superlativo si forma con eng davanti all'aggettivo: eng katta (il più grande), eng yaxshi (il migliore).",
      "Italyan tilida orttirma daraja artikl bilan yasaladi: il più grande, la più bella, i migliori. «Juda» ma'nosida -issimo qo'shimchasi ham bor: bellissimo, grandissimo."),
     [("il più grande", "eng katta"), ("il migliore", "eng yaxshi"), ("bellissimo", "juda chiroyli")]),
  ],
  lessons=[
   ("a2u6l1", ("I colori", "Ranglar"),
    [("bianco", "oq"), ("nero", "qora"), ("rosso", "qizil"), ("blu", "ko'k"), ("verde", "yashil"),
     ("giallo", "sariq"), ("marrone", "jigarrang"), ("grigio", "kulrang"), ("chiaro", "och"),
     ("scuro", "to'q")],
    [("Di che colore è?", "Rangi qanday?"), ("È blu scuro.", "To'q ko'k."),
     ("Mi piace il verde.", "Menga yashil rang yoqadi."), ("Vorrei quello rosso.", "Qizilini xohlayman."),
     ("Ha i capelli neri.", "Uning sochi qora."), ("Il cielo è grigio oggi.", "Bugun osmon kulrang.")]),
   ("a2u6l2", ("Forme e dimensioni", "Shakl va o'lcham"),
    [("grande", "katta"), ("piccolo", "kichik"), ("lungo", "uzun"), ("corto", "qisqa"),
     ("largo", "keng"), ("stretto", "tor"), ("pesante", "og'ir"), ("leggero", "yengil"),
     ("rotondo", "dumaloq"), ("quadrato", "to'rtburchak")],
    [("È troppo stretto.", "Bu juda tor."), ("Questa borsa è pesante.", "Bu sumka og'ir."),
     ("Ho bisogno di una taglia più grande.", "Menga kattaroq o'lcham kerak."), ("La strada è molto lunga.", "Yo'l juda uzun."),
     ("È leggero come una piuma.", "Pat kabi yengil."), ("Un tavolo rotondo, per favore.", "Dumaloq stol, iltimos.")]),
   ("a2u6l3", ("Confronti", "Taqqoslash"),
    [("più", "ko'proq"), ("meno", "kamroq"), ("come", "kabi"), ("uguale", "bir xil"),
     ("diverso", "boshqacha"), ("migliore", "yaxshiroq"), ("peggiore", "yomonroq"),
     ("il migliore", "eng yaxshi"), ("simile", "o'xshash"), ("differenza", "farq")],
    [("Tashkent è più grande di Bukhara.", "Toshkent Buxorodan kattaroq."), ("Questo è meno caro.", "Bu arzonroq."),
     ("Sono uguali.", "Ular bir xil."), ("Il tuo è migliore del mio.", "Seniki menikidan yaxshiroq."),
     ("Qual è la differenza?", "Farqi nima?"), ("È il ristorante migliore della città.", "Bu shahardagi eng yaxshi restoran.")]),
   ("a2u6l4", ("Opinioni", "Fikrlar"),
    [("pensare", "o'ylamoq"), ("secondo me", "menimcha"), ("d'accordo", "roziman"),
     ("vero", "to'g'ri"), ("falso", "noto'g'ri"), ("forse", "balki"), ("certo", "albatta"),
     ("interessante", "qiziqarli"), ("noioso", "zerikarli"), ("strano", "g'alati")],
    [("Che ne pensi?", "Sen nima deb o'ylaysan?"), ("Secondo me è una buona idea.", "Menimcha, bu yaxshi fikr."),
     ("Sono d'accordo con te.", "Men sen bilan roziman."), ("Non sono d'accordo.", "Men rozi emasman."),
     ("È molto interessante.", "Bu juda qiziqarli."), ("Forse hai ragione.", "Balki sen haqlisan.")]),
  ],
  dialogue=(("Quale compriamo?", "Qaysi birini olamiz?"), [
    ("Giulia", "Guarda queste due borse. Quale ti piace?", "Bu ikki sumkaga qara. Qaysi biri yoqadi?"),
    ("Dilnoza", "La nera è più elegante.", "Qorasi chiroyliroq."),
    ("Giulia", "Sì, ma quella marrone è più grande.", "Ha, lekin jigarrangi kattaroq."),
    ("Dilnoza", "E quanto costano?", "Narxi qancha?"),
    ("Giulia", "La nera è più cara di venti euro.", "Qorasi yigirma yevro qimmatroq."),
    ("Dilnoza", "Allora prendi quella marrone: è la migliore per il prezzo.", "Unda jigarrangini ol: narxiga yarasha eng yaxshisi."),
  ])),

 dict(id="a2u7", icon="calendar.badge.clock", accent="amber",
  title=("Progetti e futuro", "Rejalar va kelajak"),
  subtitle=("Fare piani, esprimere intenzioni e condizioni", "Reja tuzish, niyat va shart"),
  grammar=[
    (("Il futuro certo: -ajak / -moqchi", "Kelasi zamon shakllari"),
     ("Oltre al presente-futuro esiste il futuro «di intenzione» -moqchi (bormoqchiman = ho intenzione di andare) e il futuro formale -ajak (boradi → borajak).",
      "Italyan kelasi zamoni: -are/-ere → -erò (parlerò, prenderò), -ire → -irò (partirò). Noto'g'ri shakllar: essere → sarò, avere → avrò, andare → andrò, fare → farò."),
     [("Andrò a Roma.", "Rimga boraman."), ("Ho intenzione di studiare.", "O'qimoqchiman."), ("Sarà difficile.", "Qiyin bo'ladi.")]),
    (("Se…: «agar … -sa»", "Shart gaplar"),
     ("La condizione si costruisce con agar (facoltativo) + verbo in -sa: Agar vaqtim bo'lsa, boraman = se ho tempo, vado.",
      "Italyan tilida shart gap «se» bilan: Se ho tempo, vengo. Real shart uchun indicativo ishlatiladi: se piove, resto a casa."),
     [("Se ho tempo, vengo.", "Agar vaqtim bo'lsa, kelaman."), ("Se piove, resto a casa.", "Agar yomg'ir yog'sa, uyda qolaman.")]),
  ],
  lessons=[
   ("a2u7l1", ("Fare progetti", "Reja tuzish"),
    [("piano", "reja"), ("futuro", "kelajak"), ("sperare", "umid qilmoq"), ("decidere", "qaror qilmoq"),
     ("provare", "urinib ko'rmoq"), ("cambiare", "o'zgartirmoq"), ("sicuro (certo)", "ishonchli"),
     ("possibile", "mumkin"), ("impossibile", "imkonsiz"), ("prossimo", "keyingi")],
    [("Quali sono i tuoi piani?", "Rejalaring qanday?"), ("Voglio cambiare lavoro.", "Ishimni o'zgartirmoqchiman."),
     ("Spero di trovare una casa.", "Uy topishga umid qilaman."), ("Ho deciso di partire.", "Ketishga qaror qildim."),
     ("L'anno prossimo mi sposo.", "Kelasi yili turmush quraman."), ("Non è possibile adesso.", "Hozir bu mumkin emas.")]),
   ("a2u7l2", ("Se…", "Agar…"),
    [("se", "agar"), ("quando (temp.)", "qachonki"), ("appena", "…ishi bilan"), ("finché", "…gacha"),
     ("condizione", "shart"), ("risultato", "natija"), ("dipendere", "bog'liq bo'lmoq"),
     ("altrimenti", "aks holda"), ("comunque", "baribir"), ("in ogni caso", "har holda")],
    [("Se posso, ti aiuto.", "Agar imkonim bo'lsa, senga yordam beraman."),
     ("Se non piove, usciamo.", "Agar yomg'ir yog'masa, chiqamiz."),
     ("Ti chiamo appena arrivo.", "Yetib borishim bilan qo'ng'iroq qilaman."),
     ("Dipende dal tempo.", "Ob-havoga bog'liq."), ("Altrimenti restiamo a casa.", "Aks holda uyda qolamiz."),
     ("In ogni caso ti scrivo.", "Har holda senga yozaman.")]),
   ("a2u7l3", ("Sogni e desideri", "Orzular"),
    [("sogno", "orzu"), ("desiderio", "istak"), ("vorrei", "xohlardim"), ("obiettivo", "maqsad"),
     ("riuscire", "erisha olmoq"), ("provarci", "harakat qilmoq"), ("paura", "qo'rquv"),
     ("coraggio", "jasorat"), ("occasione", "imkoniyat"), ("successo", "muvaffaqiyat")],
    [("Il mio sogno è vivere in Italia.", "Mening orzuim — Italiyada yashash."),
     ("Vorrei imparare tre lingue.", "Uchta tilni o'rganishni xohlardim."),
     ("Il mio obiettivo è il livello B2.", "Maqsadim — B2 darajasi."),
     ("Ho paura di sbagliare.", "Xato qilishdan qo'rqaman."),
     ("Ci proverò comunque.", "Baribir harakat qilaman."), ("Ti auguro successo!", "Sizga muvaffaqiyat tilayman!")]),
   ("a2u7l4", ("Appuntamenti", "Uchrashuvlar"),
    [("fissare", "belgilamoq"), ("rimandare", "keyinga qoldirmoq"), ("annullare", "bekor qilmoq"),
     ("in anticipo", "oldindan"), ("in ritardo (pers.)", "kechikib"), ("aspettare", "kutmoq"),
     ("confermare", "tasdiqlamoq"), ("disponibile", "bo'sh"), ("impegno", "majburiyat"), ("agenda", "kundalik")],
    [("Possiamo fissare un appuntamento?", "Uchrashuv belgilasak bo'ladimi?"),
     ("Devo rimandare a domani.", "Ertaga qoldirishim kerak."),
     ("Scusa, sarò un po' in ritardo.", "Kechir, biroz kechikaman."),
     ("Ti confermo domani mattina.", "Ertaga ertalab tasdiqlayman."),
     ("Sono disponibile giovedì.", "Payshanba kuni bo'shman."), ("Mi dispiace, devo annullare.", "Kechirasan, bekor qilishim kerak.")]),
  ],
  dialogue=(("Progetti per l'estate", "Yozgi rejalar"), [
    ("Aziz", "Che farai quest'estate?", "Bu yozda nima qilasan?"),
    ("Giulia", "Se trovo i biglietti, vado in Uzbekistan.", "Agar chipta topsam, O'zbekistonga boraman."),
    ("Aziz", "Davvero? Per quanto tempo?", "Rostdanmi? Qancha vaqtga?"),
    ("Giulia", "Due settimane. Vorrei vedere Bukhara e Khiva.", "Ikki haftaga. Buxoro va Xivani ko'rmoqchiman."),
    ("Aziz", "Ti farò da guida!", "Men senga yo'lboshchi bo'laman!"),
    ("Giulia", "Sarebbe fantastico. Ma dipende dal lavoro.", "Bu ajoyib bo'lardi. Lekin ishga bog'liq."),
    ("Aziz", "Speriamo di sì. Fammi sapere presto.", "Umid qilamiz. Tezroq xabar ber."),
  ])),

 dict(id="a2u8", icon="bubble.left.and.bubble.right.fill", accent="sky",
  title=("Comunicare", "Muloqot"),
  subtitle=("Telefono, messaggi, email, cortesia", "Telefon, xabar, xat, odob"),
  grammar=[
    (("Il discorso indiretto con «deb»", "«Deb» bilan ko'chirma gap"),
     ("L'uzbeko riporta le parole così come sono, chiudendole con deb: «Kelaman», deb aytdi = ha detto che verrà (lett.: «vengo», dicendo, ha detto).",
      "Italyan tilida ko'chirma gap «che» bilan beriladi va fe'l zamoni o'zgaradi: Ha detto che sarebbe venuto. Ma'ruzada ko'pincha: dice che viene."),
     [("Ha detto che viene.", "«Kelaman», dedi."), ("Mi ha chiesto dov'ero.", "Qayerda ekanimni so'radi.")]),
    (("Le formule di cortesia", "Odob shakllari"),
     ("Con estranei e persone più anziane si usa siz e le forme in -ing/-ingiz: Keling (venga), o'tiring (si accomodi), marhamat (prego).",
      "Italyan tilida hurmat shakli «Lei» — uchinchi shaxs: Venga, si accomodi, mi dica. Xat oxirida: Cordiali saluti, Distinti saluti."),
     [("Si accomodi.", "O'tiring."), ("Mi dica.", "Ayting."), ("Cordiali saluti", "Hurmat bilan")]),
  ],
  lessons=[
   ("a2u8l1", ("Al telefono", "Telefonda"),
    [("chiamare", "qo'ng'iroq qilmoq"), ("rispondere", "javob bermoq"), ("richiamare", "qayta qo'ng'iroq qilmoq"),
     ("pronto?", "allo?"), ("linea", "aloqa"), ("numero (tel.)", "raqam"), ("occupato (tel.)", "band"),
     ("messaggio vocale", "ovozli xabar"), ("squillare", "jiringlamoq"), ("riattaccare", "go'shakni qo'ymoq")],
    [("Pronto, chi parla?", "Allo, kim gapiryapti?"), ("Posso parlare con Aziz?", "Aziz bilan gaplashsam bo'ladimi?"),
     ("Ti richiamo più tardi.", "Keyinroq qayta qo'ng'iroq qilaman."), ("Non ti sento bene.", "Seni yaxshi eshitmayapman."),
     ("La linea è disturbata.", "Aloqa yomon."), ("Mi ha chiamato tre volte.", "U menga uch marta qo'ng'iroq qildi.")]),
   ("a2u8l2", ("Messaggi ed email", "Xabar va xatlar"),
    [("scrivere", "yozmoq"), ("inviare", "yubormoq"), ("ricevere", "olmoq"), ("allegato", "ilova"),
     ("oggetto (email)", "mavzu"), ("rispondere (mail)", "javob yozmoq"), ("firma", "imzo"),
     ("gentile", "hurmatli"), ("saluti", "salomlar"), ("urgente", "shoshilinch")],
    [("Ti ho mandato un messaggio.", "Senga xabar yubordim."), ("Non ho ricevuto l'email.", "Xatni olmadim."),
     ("Ti scrivo più tardi.", "Keyinroq yozaman."), ("È urgente, rispondi presto.", "Shoshilinch, tezroq javob ber."),
     ("Trovi il file in allegato.", "Faylni ilovada topasiz."), ("Cordiali saluti.", "Hurmat bilan.")]),
   ("a2u8l3", ("Chiedere e ringraziare", "So'rash va minnatdorchilik"),
    [("favore", "iltimos"), ("aiuto", "yordam"), ("disturbo", "bezovtalik"), ("ringraziare", "rahmat aytmoq"),
     ("scusarsi", "uzr so'ramoq"), ("permesso (chiedere)", "ruxsat"), ("volentieri (risp.)", "mamnuniyat bilan"),
     ("nessun problema", "muammo yo'q"), ("figurati", "arzimaydi"), ("gentilissimo", "juda mehribon")],
    [("Posso chiederti un favore?", "Bir iltimos qilsam bo'ladimi?"), ("Certo, dimmi.", "Albatta, ayt."),
     ("Ti ringrazio davvero.", "Chin dildan rahmat."), ("Scusami per il disturbo.", "Bezovta qilganim uchun uzr."),
     ("Nessun problema.", "Muammo yo'q."), ("Sei stato gentilissimo.", "Juda mehribon bo'ldingiz.")]),
   ("a2u8l4", ("Capire e farsi capire", "Tushunish va tushuntirish"),
    [("capire", "tushunmoq"), ("ripetere", "takrorlamoq"), ("spiegare", "tushuntirmoq"),
     ("significare", "anglatmoq"), ("parola", "so'z"), ("frase", "jumla"), ("lentamente", "sekin"),
     ("come si dice", "qanday aytiladi"), ("esempio", "misol"), ("dubbio", "shubha")],
    [("Non ho capito, scusi.", "Tushunmadim, kechirasiz."), ("Può ripetere più lentamente?", "Sekinroq takrorlay olasizmi?"),
     ("Che cosa significa questa parola?", "Bu so'z nimani anglatadi?"), ("Come si dice in uzbeko?", "O'zbekchada qanday aytiladi?"),
     ("Me lo puoi spiegare?", "Buni menga tushuntira olasanmi?"), ("Puoi farmi un esempio?", "Misol keltira olasanmi?")]),
  ],
  dialogue=(("Una telefonata", "Telefon suhbati"), [
    ("Giulia", "Pronto, sono Giulia. C'è Dilnoza?", "Allo, men Giuliaman. Dilnoza bormi?"),
    ("Ona", "Un momento, la chiamo… Non risponde.", "Bir daqiqa, chaqiraman… Javob bermayapti."),
    ("Giulia", "Può dirle di richiamarmi?", "Menga qayta qo'ng'iroq qilishini ayta olasizmi?"),
    ("Ona", "Certo. Le lascio un messaggio.", "Albatta. Xabar qoldiraman."),
    ("Giulia", "Grazie mille, gentilissima.", "Katta rahmat, juda mehribonsiz."),
    ("Ona", "Figurati, cara. Buona giornata.", "Arzimaydi, qizim. Kuningiz xayrli."),
  ])),
]
