# -*- coding: utf-8 -*-
# B1 — Intermedio / O'rta daraja

LEVEL = "b1"

UNITS = [
 dict(id="b1u1", icon="quote.bubble.fill", accent="purple",
  title=("Opinioni e discussioni", "Fikr va bahs"),
  subtitle=("Esprimere il proprio punto di vista e argomentare", "O'z nuqtai nazarini bildirish va asoslash"),
  grammar=[
    (("Il congiuntivo dopo «penso che»", "«Deb o'ylayman» qurilishi"),
     ("L'uzbeko non ha il congiuntivo: la frase dipendente si nominalizza con -ligi(ni) oppure si chiude con deb: U kelishini o'ylayman / «Keladi», deb o'ylayman = penso che venga.",
      "Italyan tilida fikr, shubha, his-tuyg'u bildiruvchi fe'llardan keyin CONGIUNTIVO keladi: penso che sia, credo che venga, spero che tu stia bene. Shakli: -are → -i (parli), -ere/-ire → -a (prenda, parta)."),
     [("Penso che sia giusto.", "Menimcha, bu to'g'ri."), ("Credo che venga domani.", "Menimcha, u ertaga keladi."),
      ("Spero che tu stia bene.", "Yaxshi ekaningizga umid qilaman.")]),
    (("Concessive: «anche se» / «-sa ham»", "To'siqsiz gaplar"),
     ("La concessione si esprime con -sa ham: Charchagan bo'lsam ham, ishladim = anche se ero stanco, ho lavorato.",
      "Italyan tilida «anche se» + indicativo (haqiqiy fakt) yoki «benché/sebbene» + congiuntivo (kitobiy uslub): anche se ero stanco, ho lavorato; benché fosse tardi, siamo usciti."),
     [("Anche se ero stanco, ho lavorato.", "Charchagan bo'lsam ham, ishladim."),
      ("Benché fosse tardi, siamo usciti.", "Kech bo'lsa ham, chiqdik.")]),
    (("Connettivi del discorso", "Bog'lovchilar"),
     ("Per argomentare: birinchidan (in primo luogo), bundan tashqari (inoltre), shunga qaramay (tuttavia), demak (quindi), chunki (perché), natijada (di conseguenza).",
      "Bahsda foydali bog'lovchilar: innanzitutto, inoltre, tuttavia, quindi, perché, di conseguenza, da una parte… dall'altra."),
     [("in primo luogo", "birinchidan"), ("tuttavia", "shunga qaramay"), ("di conseguenza", "natijada")]),
  ],
  lessons=[
   ("b1u1l1", ("Dire la propria", "Fikr bildirish"),
    [("opinione", "fikr"), ("punto di vista", "nuqtai nazar"), ("sostenere", "qo'llab-quvvatlamoq"),
     ("dubitare", "shubhalanmoq"), ("convincere", "ishontirmoq"), ("ammettere", "tan olmoq"),
     ("esagerare", "bo'rttirmoq"), ("obiettare", "e'tiroz bildirmoq"), ("sinceramente", "ochig'ini aytganda"),
     ("a mio parere", "mening fikrimcha")],
    [("A mio parere non è così semplice.", "Mening fikrimcha, bu unchalik oddiy emas."),
     ("Sono convinta che funzionerà.", "Ishonchim komilki, bu ishlaydi."),
     ("Non sono del tutto d'accordo.", "To'liq rozi emasman."),
     ("Devo ammettere che avevi ragione.", "Tan olishim kerak, sen haq eding."),
     ("Secondo me stai esagerando.", "Menimcha, sen bo'rttiryapsan."),
     ("Sinceramente, preferisco l'altra opzione.", "Ochig'ini aytganda, boshqa variantni afzal ko'raman.")]),
   ("b1u1l2", ("Essere d'accordo o no", "Rozi bo'lish va bo'lmaslik"),
    [("condividere", "baham ko'rmoq"), ("contrario", "qarshi"), ("favorevole", "tarafdor"),
     ("compromesso", "murosa"), ("discutere", "bahslashmoq"), ("litigio", "janjal"),
     ("ragione", "haqlik"), ("torto", "nohaqlik"), ("in parte", "qisman"), ("assolutamente", "mutlaqo")],
    [("Su questo hai assolutamente ragione.", "Bunda sen mutlaqo haqlisan."),
     ("In parte sono d'accordo con te.", "Qisman sen bilan roziman."),
     ("Sono contrario a questa idea.", "Men bu fikrga qarshiman."),
     ("Troviamo un compromesso.", "Keling, murosa topaylik."),
     ("Non voglio discutere adesso.", "Hozir bahslashmoqchi emasman."),
     ("Forse ho torto io.", "Balki men nohaqman.")]),
   ("b1u1l3", ("Argomentare", "Asoslash"),
    [("motivo", "sabab"), ("conseguenza", "oqibat"), ("esempio (arg.)", "misol"), ("prova", "dalil"),
     ("vantaggio", "afzallik"), ("svantaggio", "kamchilik"), ("soluzione", "yechim"),
     ("problema", "muammo"), ("dipendere da", "bog'liq"), ("infatti", "darhaqiqat")],
    [("Ci sono vantaggi e svantaggi.", "Afzalliklari ham, kamchiliklari ham bor."),
     ("Il motivo principale è il costo.", "Asosiy sabab — narx."),
     ("Ti faccio un esempio concreto.", "Aniq bir misol keltiraman."),
     ("Di conseguenza abbiamo perso tempo.", "Natijada vaqt yo'qotdik."),
     ("Questa non è una vera soluzione.", "Bu haqiqiy yechim emas."),
     ("Tutto dipende dal contesto.", "Hammasi vaziyatga bog'liq.")]),
   ("b1u1l4", ("Il dibattito", "Munozara"),
    [("dibattito", "munozara"), ("interrompere", "bo'lmoq"), ("intervenire", "so'z olmoq"),
     ("concludere", "xulosa qilmoq"), ("riassumere", "qisqacha aytmoq"), ("chiarire", "aniqlashtirmoq"),
     ("aggiungere", "qo'shimcha qilmoq"), ("insomma", "xullas"), ("comunque sia", "nima bo'lganda ham"),
     ("in conclusione", "xulosa qilib")],
    [("Posso aggiungere una cosa?", "Bir narsa qo'shsam bo'ladimi?"),
     ("Scusa se ti interrompo.", "Gapingni bo'lganim uchun kechir."),
     ("Vorrei chiarire un punto.", "Bir jihatni aniqlashtirmoqchiman."),
     ("In conclusione, il progetto è valido.", "Xulosa qilib aytganda, loyiha yaxshi."),
     ("Insomma, non è cambiato nulla.", "Xullas, hech narsa o'zgarmadi."),
     ("Comunque sia, dobbiamo decidere.", "Nima bo'lganda ham, qaror qilishimiz kerak.")]),
  ],
  dialogue=(("Città o campagna?", "Shaharmi yoki qishloq?"), [
    ("Aziz", "Secondo me vivere in città è meglio.", "Menimcha, shaharda yashash yaxshiroq."),
    ("Giulia", "Perché? In campagna l'aria è più pulita.", "Nega? Qishloqda havo tozaroq."),
    ("Aziz", "Sì, ma in città ci sono più opportunità di lavoro.", "Ha, lekin shaharda ish imkoniyatlari ko'proq."),
    ("Giulia", "Sono d'accordo in parte. Però il costo della vita è alto.", "Qisman roziman. Lekin turmush qimmat."),
    ("Aziz", "Questo è vero. Tutto dipende dalle priorità.", "Bu to'g'ri. Hammasi ustuvorliklarga bog'liq."),
    ("Giulia", "Esatto. Io scelgo la tranquillità.", "Aynan. Men xotirjamlikni tanlayman."),
    ("Aziz", "Allora troviamo un compromesso: periferia!", "Unda murosa topamiz: shahar chekkasi!"),
  ])),

 dict(id="b1u2", icon="book.pages.fill", accent="sky",
  title=("Esperienze e racconti", "Tajriba va hikoyalar"),
  subtitle=("Narrare eventi complessi, ricordi, aneddoti", "Murakkab voqealarni hikoya qilish"),
  grammar=[
    (("Il passato narrativo: -gan edi", "«-gan edi» — o'tmishdan oldingi o'tmish"),
     ("Per un'azione anteriore a un'altra nel passato si usa -gan edi: Men kelganimda, u ketgan edi = quando sono arrivato, lui era già andato via.",
      "Italyan tilida bu trapassato prossimo: avevo/ero + participio. Quando sono arrivato, lui era già andato via."),
     [("Lui era già uscito.", "U allaqachon chiqib ketgan edi."),
      ("Avevo già mangiato.", "Men allaqachon ovqatlangan edim.")]),
    (("L'evidenziale «ekan»: «pare che»", "«Ekan» — bilvosita ma'lumot"),
     ("Ekan segnala che l'informazione è di seconda mano o una scoperta: U kelmas ekan = a quanto pare non viene. È molto usato nel parlato.",
      "Italyan tilida bu ma'no «a quanto pare», «pare che», «sembra che» bilan beriladi: pare che non venga, sembrava stanco, a quanto pare è partito."),
     [("A quanto pare non viene.", "U kelmas ekan."), ("Sembrava stanco.", "U charchagan ekan.")]),
    (("Le congiunzioni del racconto", "Hikoya bog'lovchilari"),
     ("Utili per narrare: …gach (dopo che), …guncha (finché), …dan keyin (dopo), birdan (all'improvviso), o'sha paytda (in quel momento).",
      "Hikoya uchun: dopo che, mentre, finché, all'improvviso, in quel momento, alla fine, da allora."),
     [("dopo che sono arrivato", "kelganimdan keyin"), ("mentre parlavo", "gapirayotganimda"), ("all'improvviso", "birdan")]),
  ],
  lessons=[
   ("b1u2l1", ("Un'esperienza indimenticabile", "Unutilmas tajriba"),
    [("esperienza", "tajriba"), ("ricordo", "xotira"), ("emozionante", "hayajonli"),
     ("indimenticabile", "unutilmas"), ("avventura", "sarguzasht"), ("imprevisto", "kutilmagan hodisa"),
     ("accadere", "yuz bermoq"), ("rendersi conto", "anglab yetmoq"), ("proprio allora", "aynan o'shanda"),
     ("da allora", "o'shandan beri")],
    [("È stata un'esperienza indimenticabile.", "Bu unutilmas tajriba bo'ldi."),
     ("Non dimenticherò mai quel giorno.", "O'sha kunni hech qachon unutmayman."),
     ("Solo dopo mi sono reso conto del pericolo.", "Faqat keyin xavfni anglab yetdim."),
     ("Da allora non ci siamo più visti.", "O'shandan beri ko'rishmadik."),
     ("È successo tutto in un minuto.", "Hammasi bir daqiqada yuz berdi."),
     ("Fu un momento davvero emozionante.", "Bu juda hayajonli daqiqa edi.")]),
   ("b1u2l2", ("Viaggi memorabili", "Esda qolgan sayohatlar"),
    [("itinerario", "yo'nalish"), ("meta", "manzil"), ("paesaggio", "manzara"), ("guida turistica", "yo'lboshchi"),
     ("perdersi", "adashmoq"), ("scoprire", "kashf qilmoq"), ("tramonto", "quyosh botishi"),
     ("deserto", "cho'l"), ("moschea", "masjid"), ("rovine", "xarobalar")],
    [("Abbiamo attraversato il deserto in treno.", "Cho'lni poyezdda kesib o'tdik."),
     ("Il paesaggio era mozzafiato.", "Manzara nafas oladigan darajada go'zal edi."),
     ("Ci siamo persi nel centro storico.", "Eski shaharda adashib qoldik."),
     ("Ho scoperto un piccolo ristorante locale.", "Kichkina mahalliy restoranni topdim."),
     ("Il tramonto sul Registan era magnifico.", "Registon uzra quyosh botishi ajoyib edi."),
     ("Consiglio a tutti questo itinerario.", "Bu yo'nalishni hammaga tavsiya qilaman.")]),
   ("b1u2l3", ("Imprevisti", "Kutilmagan holatlar"),
    [("incidente", "baxtsiz hodisa"), ("guasto", "nosozlik"), ("ritardo (grave)", "katta kechikish"),
     ("smarrire", "yo'qotmoq"), ("furto", "o'g'irlik"), ("denunciare", "ariza bermoq"),
     ("assicurazione", "sug'urta"), ("fortunatamente", "yaxshiyamki"), ("rimediare", "chorasini topmoq"),
     ("panico", "vahima")],
    [("Mi hanno rubato il portafoglio.", "Hamyonimni o'g'irlab ketishdi."),
     ("Ho dovuto fare denuncia alla polizia.", "Politsiyaga ariza berishim kerak bo'ldi."),
     ("L'auto ha avuto un guasto in autostrada.", "Mashina yo'lda buzilib qoldi."),
     ("Fortunatamente non si è fatto male nessuno.", "Yaxshiyamki, hech kim jabrlanmadi."),
     ("Ho perso la coincidenza per due minuti.", "Ikki daqiqa bilan ulanishga kechikdim."),
     ("Alla fine abbiamo rimediato.", "Oxirida chorasini topdik.")]),
   ("b1u2l4", ("Raccontare un aneddoto", "Latifa aytish"),
    [("aneddoto", "latifa"), ("divertente", "kulgili"), ("imbarazzante", "noqulay"),
     ("figuraccia", "sharmandalik"), ("ridere", "kulmoq"), ("scherzo", "hazil"),
     ("per caso", "tasodifan"), ("addirittura", "hatto"), ("insomma (narr.)", "qisqasi"),
     ("il bello è che", "eng qizig'i shuki")],
    [("Ti racconto una cosa divertente.", "Senga kulgili bir voqeani aytib beraman."),
     ("Il bello è che non mi aveva riconosciuto.", "Eng qizig'i, u meni tanimagan edi."),
     ("È stato davvero imbarazzante.", "Bu juda noqulay bo'ldi."),
     ("Ci siamo incontrati per caso al mercato.", "Bozorda tasodifan uchrashib qoldik."),
     ("Abbiamo riso per mezz'ora.", "Yarim soat kuldik."),
     ("Insomma, è finita bene.", "Qisqasi, yaxshi tugadi.")]),
  ],
  dialogue=(("Il treno perso", "O'tkazib yuborilgan poyezd"), [
    ("Dilnoza", "Sei arrivata tardi ieri, che è successo?", "Kecha kech kelding, nima bo'ldi?"),
    ("Giulia", "Una storia assurda. Avevo il treno alle sette.", "Bema'ni voqea. Poyezdim soat yettida edi."),
    ("Dilnoza", "E non l'hai preso?", "Va unga yetib bormadingmi?"),
    ("Giulia", "No. Quando sono arrivata in stazione, era già partito.", "Yo'q. Vokzalga yetganimda, u allaqachon jo'nab ketgan edi."),
    ("Dilnoza", "Per quanto?", "Qancha farq bilan?"),
    ("Giulia", "Due minuti! Il bello è che l'avevo prenotato un mese fa.", "Ikki daqiqa! Eng qizig'i, bir oy oldin bron qilgan edim."),
    ("Dilnoza", "Che sfortuna. E poi?", "Qanday baxtsizlik. Keyin-chi?"),
    ("Giulia", "Fortunatamente ne è passato un altro dopo due ore.", "Yaxshiyamki, ikki soatdan keyin boshqasi bor ekan."),
  ])),

 dict(id="b1u3", icon="chart.line.uptrend.xyaxis", accent="teal",
  title=("Lavoro e carriera", "Ish va karyera"),
  subtitle=("Candidature, riunioni, crescita professionale", "Ariza, yig'ilish, kasbiy o'sish"),
  grammar=[
    (("Il passivo: -il- / -in-", "Majhul nisbat"),
     ("Il passivo uzbeko si forma con -il- (o -in- dopo l) dentro il verbo: yozmoq → yozilmoq (essere scritto). L'agente si esprime raramente: Xat yozildi = la lettera è stata scritta.",
      "Italyan majhul nisbati: essere + participio (la lettera è stata scritta da Marco) yoki «si» bilan (si scrivono molte lettere). Rasmiy uslubda «venire» ham ishlatiladi: viene firmato."),
     [("La lettera è stata scritta.", "Xat yozildi."), ("Il contratto viene firmato oggi.", "Shartnoma bugun imzolanadi.")]),
    (("Il «si» impersonale", "Shaxssiz gaplar"),
     ("In uzbeko l'impersonale si rende con la terza persona plurale o con -adi: Bu yerda o'zbekcha gapiriladi = qui si parla uzbeko.",
      "Italyan tilida shaxssiz gap «si» bilan yasaladi: qui si parla italiano, si lavora molto, non si può fumare."),
     [("Qui si parla italiano.", "Bu yerda italyancha gapiriladi."), ("Non si può fumare.", "Chekish mumkin emas.")]),
  ],
  lessons=[
   ("b1u3l1", ("Cercare lavoro", "Ish qidirish"),
    [("annuncio", "e'lon"), ("candidatura", "nomzodlik"), ("selezione", "tanlov"),
     ("requisito", "talab"), ("referenze", "tavsiyanoma"), ("prova (periodo)", "sinov muddati"),
     ("tempo pieno", "to'liq stavka"), ("part time", "yarim stavka"), ("a tempo determinato", "muddatli"),
     ("settore", "soha")],
    [("Ho risposto a un annuncio di lavoro.", "Ish e'loniga ariza yubordim."),
     ("Cercano una persona con esperienza.", "Tajribali odam qidirishyapti."),
     ("Il contratto è a tempo determinato.", "Shartnoma muddatli."),
     ("Lavoro nel settore turistico.", "Men turizm sohasida ishlayman."),
     ("Il periodo di prova dura tre mesi.", "Sinov muddati uch oy davom etadi."),
     ("Mi hanno chiesto le referenze.", "Mendan tavsiyanoma so'rashdi.")]),
   ("b1u3l2", ("In riunione", "Yig'ilishda"),
    [("ordine del giorno", "kun tartibi"), ("presentare", "taqdim etmoq"), ("proporre", "taklif qilmoq"),
     ("approvare", "ma'qullamoq"), ("rinviare", "keyinga surmoq"), ("verbale", "bayonnoma"),
     ("obiettivo (lavoro)", "maqsad"), ("scadenza (progetto)", "muddat"), ("budget", "byudjet"),
     ("priorità", "ustuvorlik")],
    [("Vorrei presentare la mia proposta.", "Taklifimni taqdim etmoqchiman."),
     ("Questo punto è stato approvato.", "Bu masala ma'qullandi."),
     ("Dobbiamo rispettare la scadenza.", "Muddatga rioya qilishimiz kerak."),
     ("Il budget è troppo limitato.", "Byudjet juda cheklangan."),
     ("Rinviamo la decisione a lunedì.", "Qarorni dushanbaga suramiz."),
     ("Qual è la nostra priorità?", "Bizning ustuvorligimiz nima?")]),
   ("b1u3l3", ("Crescita professionale", "Kasbiy o'sish"),
    [("carriera", "karyera"), ("promozione", "lavozimga ko'tarilish"), ("formazione", "malaka oshirish"),
     ("corso di aggiornamento", "qayta tayyorlash kursi"), ("competenza (skill)", "ko'nikma"),
     ("responsabilità", "mas'uliyat"), ("stipendio (aumento)", "maosh oshishi"),
     ("dimettersi", "iste'foga chiqmoq"), ("trasferirsi", "ko'chmoq"), ("opportunità", "imkoniyat")],
    [("Mi hanno offerto una promozione.", "Menga lavozim taklif qilishdi."),
     ("Voglio migliorare le mie competenze.", "Ko'nikmalarimni oshirmoqchiman."),
     ("Ho chiesto un aumento di stipendio.", "Maosh oshirishni so'radim."),
     ("Sto pensando di dimettermi.", "Iste'foga chiqishni o'ylayapman."),
     ("È un'opportunità da non perdere.", "Bu qo'ldan boy bermaydigan imkoniyat."),
     ("Frequento un corso di aggiornamento.", "Men malaka oshirish kursiga qatnayapman.")]),
   ("b1u3l4", ("Rapporti in ufficio", "Ofisdagi munosabatlar"),
    [("collaborare", "hamkorlik qilmoq"), ("delegare", "topshirmoq"), ("sostegno", "qo'llab-quvvatlash"),
     ("conflitto", "nizo"), ("malinteso", "tushunmovchilik"), ("chiarimento", "aniqlik"),
     ("fiducia", "ishonch"), ("ambiente di lavoro", "ish muhiti"), ("sovraccarico", "ortiqcha yuk"),
     ("equilibrio", "muvozanat")],
    [("Collaboriamo bene insieme.", "Biz yaxshi hamkorlik qilamiz."),
     ("C'è stato un malinteso.", "Tushunmovchilik bo'ldi."),
     ("L'ambiente di lavoro è sereno.", "Ish muhiti xotirjam."),
     ("Ho troppo lavoro, sono sovraccarica.", "Ishim juda ko'p, ortiqcha yuklanganman."),
     ("Cerco un equilibrio tra lavoro e vita privata.", "Ish va shaxsiy hayot o'rtasida muvozanat izlayapman."),
     ("Mi fido del mio collega.", "Men hamkasbimga ishonaman.")]),
  ],
  dialogue=(("La riunione del lunedì", "Dushanba yig'ilishi"), [
    ("Boshliq", "Iniziamo. Il primo punto è il nuovo progetto.", "Boshlaymiz. Birinchi masala — yangi loyiha."),
    ("Aziz", "Vorrei presentare la mia proposta, se posso.", "Ruxsat bersangiz, taklifimni taqdim etmoqchiman."),
    ("Boshliq", "Prego, ha cinque minuti.", "Marhamat, besh daqiqangiz bor."),
    ("Aziz", "Secondo me dovremmo concentrarci sui clienti locali.", "Menimcha, mahalliy mijozlarga e'tibor qaratishimiz kerak."),
    ("Boshliq", "Interessante. Ma il budget è limitato.", "Qiziq. Lekin byudjet cheklangan."),
    ("Aziz", "Proprio per questo costerebbe meno.", "Aynan shuning uchun arzonroq tushadi."),
    ("Boshliq", "Va bene, prepari i numeri per giovedì.", "Yaxshi, payshanbagacha raqamlarni tayyorlang."),
  ])),

 dict(id="b1u4", icon="desktopcomputer", accent="sky",
  title=("Tecnologia e media", "Texnologiya va media"),
  subtitle=("Internet, social, notizie, dispositivi", "Internet, ijtimoiy tarmoq, yangiliklar"),
  grammar=[
    (("Il participio -adigan: «che fa abitualmente»", "«-adigan» sifatdoshi"),
     ("-adigan forma un aggettivo verbale abituale: ishlaydigan odam (una persona che lavora), o'qiydigan kitob (un libro da leggere).",
      "Italyan tilida bu ma'no «che» ergash gapi yoki «da + infinito» bilan beriladi: una persona che lavora, un libro da leggere."),
     [("una persona che lavora", "ishlaydigan odam"), ("un libro da leggere", "o'qiydigan kitob")]),
    (("Verbi con pronomi combinati", "Qo'shma olmoshlar"),
     ("In uzbeko i complementi restano parole separate con le loro desinenze: Men uni senga beraman = te lo do.",
      "Italyan tilida ikki olmosh qo'shilib ketadi: me lo, te lo, glielo, ce lo, ve lo. Masalan: Te lo do domani. Glielo ho detto."),
     [("Te lo do domani.", "Ertaga uni senga beraman."), ("Gliel'ho detto.", "Men unga aytdim.")]),
  ],
  lessons=[
   ("b1u4l1", ("Dispositivi e internet", "Qurilmalar va internet"),
    [("schermo", "ekran"), ("tastiera", "klaviatura"), ("password", "parol"), ("account", "hisob"),
     ("connessione", "ulanish"), ("rete", "tarmoq"), ("caricare", "yuklamoq"),
     ("scaricare", "yuklab olmoq"), ("aggiornamento", "yangilanish"), ("batteria", "batareya")],
    [("La connessione è lenta.", "Ulanish sekin."),
     ("Ho dimenticato la password.", "Parolni unutdim."),
     ("Devo aggiornare l'applicazione.", "Ilovani yangilashim kerak."),
     ("La batteria si scarica in fretta.", "Batareya tez tugaydi."),
     ("Puoi scaricare il file da qui.", "Faylni shu yerdan yuklab olishing mumkin."),
     ("Il telefono si è bloccato.", "Telefon qotib qoldi.")]),
   ("b1u4l2", ("Social e messaggistica", "Ijtimoiy tarmoqlar"),
    [("social network", "ijtimoiy tarmoq"), ("profilo", "profil"), ("pubblicare", "chop etmoq"),
     ("condividere (post)", "ulashmoq"), ("commento", "izoh"), ("seguire", "kuzatmoq"),
     ("bloccare", "bloklamoq"), ("privacy", "maxfiylik"), ("dipendenza", "qaramlik"),
     ("notifica", "bildirishnoma")],
    [("Ho pubblicato le foto del viaggio.", "Sayohat suratlarini chop etdim."),
     ("Passo troppo tempo sui social.", "Ijtimoiy tarmoqlarda juda ko'p vaqt o'tkazaman."),
     ("Ho disattivato le notifiche.", "Bildirishnomalarni o'chirdim."),
     ("La privacy è un tema importante.", "Maxfiylik muhim mavzu."),
     ("Ti ho mandato il link in privato.", "Havolani shaxsiyga yubordim."),
     ("Non leggo mai i commenti.", "Men hech qachon izohlarni o'qimayman.")]),
   ("b1u4l3", ("Notizie e media", "Yangiliklar va ommaviy axborot"),
    [("notizia", "yangilik"), ("giornale", "gazeta"), ("telegiornale", "axborot dasturi"),
     ("fonte", "manba"), ("attendibile", "ishonchli"), ("titolo", "sarlavha"),
     ("intervista", "intervyu"), ("cronaca", "xronika"), ("pubblicità", "reklama"),
     ("notizia falsa", "yolg'on xabar")],
    [("Hai sentito la notizia?", "Yangilikni eshitdingmi?"),
     ("Da quale fonte viene?", "Bu qaysi manbadan?"),
     ("Non tutte le notizie sono attendibili.", "Hamma yangilik ham ishonchli emas."),
     ("Leggo i giornali online la mattina.", "Ertalab onlayn gazeta o'qiyman."),
     ("Hanno intervistato il sindaco.", "Ular hokim bilan intervyu o'tkazishdi."),
     ("Ci sono troppe pubblicità.", "Reklama juda ko'p.")]),
   ("b1u4l4", ("Tecnologia e vita", "Texnologiya va hayot"),
    [("intelligenza artificiale", "sun'iy intellekt"), ("progresso", "taraqqiyot"),
     ("utile", "foydali"), ("dannoso", "zararli"), ("sostituire", "almashtirmoq"),
     ("semplificare", "soddalashtirmoq"), ("rischio", "xavf"), ("controllo", "nazorat"),
     ("innovazione", "innovatsiya"), ("futuro digitale", "raqamli kelajak")],
    [("La tecnologia ci semplifica la vita.", "Texnologiya hayotimizni osonlashtiradi."),
     ("Alcuni lavori saranno sostituiti dalle macchine.", "Ba'zi ishlar mashinalar bilan almashtiriladi."),
     ("Ci sono anche dei rischi.", "Xavflar ham bor."),
     ("Uso l'intelligenza artificiale per studiare.", "O'qish uchun sun'iy intellektdan foydalanaman."),
     ("Bisogna trovare un equilibrio.", "Muvozanat topish kerak."),
     ("Il progresso non si ferma.", "Taraqqiyot to'xtamaydi.")]),
  ],
  dialogue=(("Troppo tempo sul telefono", "Telefonda juda ko'p vaqt"), [
    ("Dilnoza", "Sai quanto tempo passo sul telefono? Cinque ore al giorno.", "Bilasanmi, telefonda qancha vaqt o'tkazaman? Kuniga besh soat."),
    ("Giulia", "Addirittura? Ma che cosa fai?", "Shunchami? Nima qilasan?"),
    ("Dilnoza", "Social, messaggi, video… Non me ne accorgo nemmeno.", "Ijtimoiy tarmoq, xabarlar, video… Sezmayman ham."),
    ("Giulia", "Anch'io ho lo stesso problema. Ho disattivato le notifiche.", "Menda ham shu muammo. Men bildirishnomalarni o'chirdim."),
    ("Dilnoza", "E ha funzionato?", "Va yordam berdimi?"),
    ("Giulia", "Sì, in parte. Adesso leggo di più.", "Ha, qisman. Endi ko'proq o'qiyman."),
    ("Dilnoza", "Dovrei provare anch'io.", "Men ham sinab ko'rishim kerak."),
  ])),

 dict(id="b1u5", icon="leaf.fill", accent="green",
  title=("Ambiente e società", "Atrof-muhit va jamiyat"),
  subtitle=("Clima, città sostenibili, vita collettiva", "Iqlim, barqaror shahar, jamiyat hayoti"),
  grammar=[
    (("Il causativo -tir- / -dir-", "Orttirma nisbat"),
     ("Il causativo indica «far fare»: o'qimoq (leggere) → o'qitmoq (far leggere, insegnare); bilmoq (sapere) → bildirmoq (far sapere).",
      "Italyan tilida bu ma'no «fare + infinito» bilan beriladi: far leggere, far sapere, far costruire una casa."),
     [("far sapere", "bildirmoq"), ("Ho fatto costruire una casa.", "Men uy qurdirdim.")]),
    (("Il futuro nel passato e il condizionale", "Shart mayli"),
     ("«Andrei» si rende con -sa edim o con -(a)r edim: Vaqtim bo'lsa, borardim = se avessi tempo, andrei.",
      "Italyan shart mayli (condizionale): andrei, farei, sarebbe, potrei. Ikkinchi turdagi shart gapda: se avessi tempo, andrei."),
     [("Se avessi tempo, andrei.", "Vaqtim bo'lsa, borardim."), ("Potrei aiutarti.", "Senga yordam bera olardim.")]),
  ],
  lessons=[
   ("b1u5l1", ("Ambiente", "Atrof-muhit"),
    [("inquinamento", "ifloslanish"), ("rifiuti", "chiqindi"), ("riciclare", "qayta ishlamoq"),
     ("energia", "energiya"), ("rinnovabile", "qayta tiklanuvchi"), ("risparmiare", "tejamoq"),
     ("clima", "iqlim"), ("siccità", "qurg'oqchilik"), ("proteggere", "himoya qilmoq"),
     ("sostenibile", "barqaror")],
    [("L'inquinamento dell'aria è aumentato.", "Havo ifloslanishi ortdi."),
     ("Dobbiamo riciclare di più.", "Ko'proq qayta ishlashimiz kerak."),
     ("Uso l'energia solare.", "Men quyosh energiyasidan foydalanaman."),
     ("Il cambiamento climatico ci riguarda tutti.", "Iqlim o'zgarishi hammamizga tegishli."),
     ("Bisogna risparmiare acqua.", "Suvni tejash kerak."),
     ("Il lago si sta prosciugando.", "Ko'l qurib bormoqda.")]),
   ("b1u5l2", ("Vita in città", "Shahar hayoti"),
    [("traffico", "tirbandlik"), ("trasporto pubblico", "jamoat transporti"), ("pedone", "piyoda"),
     ("pista ciclabile", "velosiped yo'lagi"), ("verde pubblico", "yashil hudud"),
     ("rumore", "shovqin"), ("quartiere", "mahalla"), ("servizi", "xizmatlar"),
     ("affollato", "gavjum"), ("vivibile", "yashash uchun qulay")],
    [("Il traffico è insopportabile la mattina.", "Ertalab tirbandlik chidab bo'lmas darajada."),
     ("Il mio quartiere è tranquillo.", "Mening mahallam tinch."),
     ("Servono più piste ciclabili.", "Ko'proq velosiped yo'laklari kerak."),
     ("La città è più vivibile di prima.", "Shahar avvalgidan qulayroq bo'ldi."),
     ("Il trasporto pubblico funziona bene.", "Jamoat transporti yaxshi ishlaydi."),
     ("C'è troppo rumore di notte.", "Kechasi shovqin juda ko'p.")]),
   ("b1u5l3", ("Vivere insieme agli altri", "Jamiyatda yashash"),
    [("società", "jamiyat"), ("comunità", "jamoa"), ("volontariato", "ko'ngillilik"),
     ("solidarietà", "hamjihatlik"), ("diritto", "huquq"), ("dovere", "burch"),
     ("uguaglianza", "tenglik"), ("povertà", "qashshoqlik"), ("integrazione", "integratsiya"),
     ("rispetto", "hurmat")],
    [("Faccio volontariato il sabato.", "Shanba kuni ko'ngilli bo'lib ishlayman."),
     ("Tutti hanno gli stessi diritti.", "Hammaning huquqlari teng."),
     ("La solidarietà è importante nella mia mahalla.", "Mahallamizda hamjihatlik muhim."),
     ("Bisogna rispettare le differenze.", "Farqlarni hurmat qilish kerak."),
     ("Ci sono ancora molte disuguaglianze.", "Hali ko'p tengsizliklar bor."),
     ("La comunità aiuta le famiglie in difficoltà.", "Jamoa qiyin ahvoldagi oilalarga yordam beradi.")]),
   ("b1u5l4", ("Cambiare abitudini", "Odatlarni o'zgartirish"),
    [("abitudine", "odat"), ("consumo", "iste'mol"), ("spreco", "isrof"), ("plastica", "plastik"),
     ("borraccia", "suv idishi"), ("locale (prodotto)", "mahalliy"), ("stagionale", "mavsumiy"),
     ("ridurre", "kamaytirmoq"), ("evitare", "oldini olmoq"), ("impatto", "ta'sir")],
    [("Ho ridotto il consumo di plastica.", "Plastik iste'molini kamaytirdim."),
     ("Compro prodotti locali e di stagione.", "Mahalliy va mavsumiy mahsulot sotib olaman."),
     ("Cerco di evitare gli sprechi.", "Isrofdan qochishga harakat qilaman."),
     ("Piccoli gesti hanno un grande impatto.", "Kichik ishlar katta ta'sir qiladi."),
     ("Ho cambiato abitudini l'anno scorso.", "O'tgan yili odatlarimni o'zgartirdim."),
     ("Ognuno può fare la sua parte.", "Har kim o'z hissasini qo'shishi mumkin.")]),
  ],
  dialogue=(("Meno plastica", "Kamroq plastik"), [
    ("Giulia", "Ho deciso di non comprare più bottiglie di plastica.", "Endi plastik shishalar sotib olmaslikka qaror qildim."),
    ("Aziz", "Bella idea. E come fai fuori casa?", "Yaxshi fikr. Uydan tashqarida qanday qilasan?"),
    ("Giulia", "Porto sempre una borraccia con me.", "Doim yonimda suv idishi olib yuraman."),
    ("Aziz", "Se tutti facessimo così, ci sarebbe meno inquinamento.", "Agar hamma shunday qilsa, ifloslanish kamayardi."),
    ("Giulia", "Esatto. E si risparmia anche.", "Aynan. Pul ham tejaladi."),
    ("Aziz", "Da domani provo anch'io.", "Ertadan men ham sinab ko'raman."),
  ])),

 dict(id="b1u6", icon="heart.circle.fill", accent="pink",
  title=("Emozioni e relazioni", "His-tuyg'u va munosabatlar"),
  subtitle=("Sentimenti, amicizia, amore, conflitti", "Tuyg'ular, do'stlik, sevgi, nizolar"),
  grammar=[
    (("Esprimere sentimenti: -ganim uchun", "Sabab shakllari"),
     ("Per dire «sono felice che…» si usa la nominalizzazione: Kelganing uchun xursandman = sono contento che tu sia venuto.",
      "Italyan tilida his-tuyg'udan keyin congiuntivo keladi: sono contento che tu sia venuto, mi dispiace che tu stia male."),
     [("Sono contento che tu sia venuto.", "Kelganing uchun xursandman."),
      ("Mi dispiace che tu stia male.", "Kasal bo'lganingdan afsusdaman.")]),
    (("I verbi riflessivi e reciproci", "O'zlik va birgalik nisbati"),
     ("Riflessivo: -(i)n- (yuvinmoq = lavarsi). Reciproco: -(i)sh- (ko'rishmoq = vedersi, yozishmoq = scriversi).",
      "Italyan tilida o'zlik fe'llari «si» olmoshi bilan: lavarsi, vestirsi. O'zaro harakat uchun ko'plikda: ci vediamo, si scrivono, vi conoscete."),
     [("Ci vediamo domani.", "Ertaga ko'rishamiz."), ("Ci scriviamo spesso.", "Biz tez-tez yozishamiz.")]),
  ],
  lessons=[
   ("b1u6l1", ("Sentimenti", "Tuyg'ular"),
    [("gioia", "quvonch"), ("tristezza", "g'am"), ("rabbia", "jahl"), ("paura (emoz.)", "qo'rquv"),
     ("sorpresa", "hayrat"), ("delusione", "hafsala pir bo'lishi"), ("orgoglio", "faxr"),
     ("gelosia", "rashk"), ("nostalgia", "sog'inch"), ("sollievo", "yengillik")],
    [("Sono davvero orgogliosa di te.", "Men sendan chinakam faxrlanaman."),
     ("Mi manca la mia famiglia.", "Oilamni sog'indim."),
     ("Ero molto deluso da quella risposta.", "O'sha javobdan hafsalam pir bo'ldi."),
     ("Non riesco a nascondere la gioia.", "Quvonchimni yashira olmayapman."),
     ("Ho provato un grande sollievo.", "Katta yengillik his qildim."),
     ("A volte mi arrabbio troppo.", "Ba'zan juda jahlim chiqadi.")]),
   ("b1u6l2", ("Amicizia", "Do'stlik"),
    [("amicizia", "do'stlik"), ("fidarsi", "ishonmoq"), ("sostenere (qcn)", "qo'llab-quvvatlamoq"),
     ("confidare", "sirini aytmoq"), ("tradire", "xiyonat qilmoq"), ("perdonare", "kechirmoq"),
     ("sincero", "samimiy"), ("egoista", "xudbin"), ("generoso", "saxiy"), ("legame", "rishta")],
    [("È un'amicizia di vecchia data.", "Bu eski do'stlik."),
     ("Mi fido ciecamente di lei.", "Men unga so'zsiz ishonaman."),
     ("Mi ha sostenuto nei momenti difficili.", "Qiyin paytlarda u meni qo'llab-quvvatladi."),
     ("Non è stato sincero con me.", "U men bilan samimiy bo'lmadi."),
     ("Alla fine l'ho perdonato.", "Oxir-oqibat uni kechirdim."),
     ("Il nostro legame è molto forte.", "Bizning rishtamiz juda mustahkam.")]),
   ("b1u6l3", ("Amore e famiglia", "Sevgi va oila"),
    [("innamorarsi", "oshiq bo'lmoq"), ("fidanzarsi", "unashtirilmoq"), ("sposarsi", "turmush qurmoq"),
     ("matrimonio", "to'y"), ("coppia", "juftlik"), ("convivere", "birga yashamoq"),
     ("separarsi", "ajrashmoq"), ("figli", "farzandlar"), ("suocera", "qaynona"),
     ("parenti", "qarindoshlar")],
    [("Ci siamo conosciuti a una festa.", "Biz bir bazmda tanishganmiz."),
     ("Si sono sposati l'anno scorso.", "Ular o'tgan yili turmush qurishdi."),
     ("Il matrimonio uzbeko dura due giorni.", "O'zbek to'yi ikki kun davom etadi."),
     ("Vivono insieme da tre anni.", "Ular uch yildan beri birga yashaydi."),
     ("Ho molti parenti a Bukhara.", "Buxoroda ko'p qarindoshlarim bor."),
     ("Vogliono avere dei figli.", "Ular farzand ko'rishni xohlashadi.")]),
   ("b1u6l4", ("Conflitti e riconciliazione", "Nizo va yarashuv"),
    [("discutere (litigare)", "tortishmoq"), ("offendere", "xafa qilmoq"), ("scusarsi (form.)", "uzr so'ramoq"),
     ("chiarirsi", "tushunishmoq"), ("riconciliarsi", "yarashmoq"), ("tensione", "keskinlik"),
     ("silenzio", "sukunat"), ("pazienza", "sabr"), ("compromesso (pers.)", "murosa"),
     ("sincerità", "samimiylik")],
    [("Non volevo offenderti.", "Seni xafa qilmoqchi emasdim."),
     ("Chiariamoci una volta per tutte.", "Keling, bir yo'la tushunishib olaylik."),
     ("Ci vuole molta pazienza.", "Ko'p sabr kerak."),
     ("Alla fine ci siamo riconciliati.", "Oxirida yarashib oldik."),
     ("La tensione è scesa.", "Keskinlik pasaydi."),
     ("Ti chiedo scusa sinceramente.", "Sendan chin dildan uzr so'rayman.")]),
  ],
  dialogue=(("Una scusa sincera", "Samimiy uzr"), [
    ("Aziz", "Senti… volevo scusarmi per ieri.", "Eshit… kechagi voqea uchun uzr so'ramoqchi edim."),
    ("Giulia", "Mi hai ferita, sinceramente.", "Rostini aytsam, meni xafa qilding."),
    ("Aziz", "Lo so. Ero stanco e ho detto cose stupide.", "Bilaman. Charchagan edim va ahmoqona gaplar aytdim."),
    ("Giulia", "Capisco, ma la prossima volta parliamone prima.", "Tushunaman, lekin keyingi safar avval gaplashaylik."),
    ("Aziz", "Hai ragione. Mi dispiace davvero.", "Haqsan. Chinakam afsusdaman."),
    ("Giulia", "Va bene. Non parliamone più.", "Mayli. Bu haqda boshqa gapirmaylik."),
  ])),

 dict(id="b1u7", icon="theatermasks.fill", accent="amber",
  title=("Cultura e tradizioni", "Madaniyat va an'analar"),
  subtitle=("Feste, cucina, ospitalità, arte popolare", "Bayramlar, taomlar, mehmondo'stlik"),
  grammar=[
    (("Il verbo composto: -ib + verbo", "Qo'shma fe'llar"),
     ("Molti significati sfumati si ottengono con -ib + un verbo ausiliare: olib kelmoq (portare), yozib chiqmoq (scrivere fino in fondo), aytib bermoq (raccontare).",
      "Italyan tilida bunday nozik ma'nolar alohida fe'l yoki qo'shimcha so'z bilan beriladi: portare, raccontare, finire di scrivere, andare avanti."),
     [("portare (qui)", "olib kelmoq"), ("raccontare", "aytib bermoq"), ("finire di leggere", "o'qib chiqmoq")]),
    (("Formule tradizionali", "An'anaviy iboralar"),
     ("La cultura uzbeka usa formule fisse: Xush kelibsiz (benvenuto), Yoqimli ishtaha (buon appetito), Omad tilayman (in bocca al lupo), Bayramingiz muborak (buona festa).",
      "Italyan an'anaviy iboralari: Benvenuto!, Buon appetito!, In bocca al lupo!, Auguri!, Buone feste!, Salute! (aksirganda)."),
     [("Benvenuto!", "Xush kelibsiz!"), ("Buon appetito!", "Yoqimli ishtaha!"), ("Auguri!", "Tabriklayman!")]),
  ],
  lessons=[
   ("b1u7l1", ("Feste e ricorrenze", "Bayramlar"),
    [("festa (ricorrenza)", "bayram"), ("tradizione", "an'ana"), ("Navruz", "Navro'z"),
     ("Capodanno", "Yangi yil"), ("festeggiare", "nishonlamoq"), ("augurio", "tabrik"),
     ("regalo (festa)", "sovg'a"), ("invitato", "taklif qilingan"), ("banchetto", "ziyofat"),
     ("usanza", "urf-odat")],
    [("Come festeggiate il Navruz?", "Navro'zni qanday nishonlaysizlar?"),
     ("È una tradizione molto antica.", "Bu juda qadimiy an'ana."),
     ("Tutta la famiglia si riunisce.", "Butun oila yig'iladi."),
     ("Auguri di cuore!", "Chin dildan tabriklayman!"),
     ("Prepariamo il sumalak insieme.", "Sumalakni birga tayyorlaymiz."),
     ("In Italia si scambiano i regali a Natale.", "Italiyada Rojdestvoda sovg'a almashiladi.")]),
   ("b1u7l2", ("A tavola", "Dasturxonda"),
    [("ospitalità", "mehmondo'stlik"), ("ospite (invitato)", "mehmon"), ("padrone di casa", "uy egasi"),
     ("servire", "tortmoq"), ("assaggiare", "totib ko'rmoq"), ("ricetta (cucina)", "retsept"),
     ("ingrediente", "masalliq"), ("pietanza", "taom"), ("brindisi", "qadah so'zi"),
     ("abbondante", "to'kin")],
    [("L'ospitalità è sacra da noi.", "Bizda mehmondo'stlik muqaddas."),
     ("Assaggia questo, è fatto in casa.", "Buni totib ko'r, uyda tayyorlangan."),
     ("Mi dai la ricetta del plov?", "Palov retseptini berasanmi?"),
     ("La tavola era abbondante.", "Dasturxon to'kin edi."),
     ("Vorrei fare un brindisi.", "Qadah so'zi aytmoqchiman."),
     ("Non posso mangiare più niente!", "Boshqa hech narsa yeya olmayman!")]),
   ("b1u7l3", ("Arte e artigianato", "San'at va hunarmandchilik"),
    [("artigiano", "hunarmand"), ("ceramica", "sopol"), ("seta", "ipak"), ("tappeto (arte)", "gilam"),
     ("ricamo", "kashta"), ("miniatura", "miniatyura"), ("architettura", "me'morchilik"),
     ("restauro", "ta'mirlash"), ("patrimonio", "meros"), ("mostra", "ko'rgazma")],
    [("Samarcanda è famosa per la sua architettura.", "Samarqand me'morchiligi bilan mashhur."),
     ("Questi tappeti sono fatti a mano.", "Bu gilamlar qo'lda to'qilgan."),
     ("La seta di Margilan è pregiata.", "Marg'ilon ipagi qadrlanadi."),
     ("Abbiamo visitato una mostra di ceramiche.", "Sopol buyumlar ko'rgazmasiga bordik."),
     ("È patrimonio dell'umanità.", "Bu insoniyat merosi."),
     ("Il restauro è durato dieci anni.", "Ta'mirlash o'n yil davom etdi.")]),
   ("b1u7l4", ("Differenze culturali", "Madaniy farqlar"),
    [("abitudine culturale", "madaniy odat"), ("galateo", "odob qoidalari"), ("puntualità", "vaqtga rioya"),
     ("gesto", "imo-ishora"), ("tabù", "taqiq"), ("malinteso culturale", "madaniy tushunmovchilik"),
     ("adattarsi", "moslashmoq"), ("sorprendere", "hayratlantirmoq"), ("normale", "odatiy"),
     ("maleducato", "odobsiz")],
    [("All'inizio mi ha sorpreso molto.", "Avvaliga bu meni juda hayratlantirdi."),
     ("Da noi si tolgono le scarpe in casa.", "Bizda uyga kirganda oyoq kiyim yechiladi."),
     ("In Italia si arriva puntuali.", "Italiyada vaqtida kelish odat."),
     ("Non sapevo che fosse maleducato.", "Bu odobsizlik ekanini bilmasdim."),
     ("Ci si adatta con il tempo.", "Vaqt o'tib moslashib ketiladi."),
     ("Ogni cultura ha le sue regole.", "Har bir madaniyatning o'z qoidalari bor.")]),
  ],
  dialogue=(("Invito a casa", "Uyga taklif"), [
    ("Dilnoza", "Sabato vieni da noi per il Navruz?", "Shanbada Navro'zga biznikiga kelasanmi?"),
    ("Giulia", "Con piacere! Devo portare qualcosa?", "Mamnuniyat bilan! Biror narsa olib kelaymi?"),
    ("Dilnoza", "Assolutamente no. Solo te stessa.", "Umuman kerak emas. Faqat o'zing kel."),
    ("Giulia", "In Italia si porta sempre un dolce o dei fiori.", "Italiyada doim shirinlik yoki gul olib boriladi."),
    ("Dilnoza", "Allora porta un dolce italiano, così lo assaggiamo!", "Unda italyan shirinligi olib kel, totib ko'ramiz!"),
    ("Giulia", "Perfetto. A che ora?", "Zo'r. Soat nechada?"),
    ("Dilnoza", "Verso mezzogiorno. E toglietevi le scarpe all'ingresso!", "Tush payti. Kiraverishda oyoq kiyimni yeching!"),
  ])),

 dict(id="b1u8", icon="doc.text.fill", accent="red",
  title=("Pratiche e burocrazia", "Rasmiy ishlar"),
  subtitle=("Documenti, banca, servizi, reclami", "Hujjatlar, bank, xizmatlar, shikoyat"),
  grammar=[
    (("Il registro formale", "Rasmiy uslub"),
     ("Nei documenti si usano forme come -ilishi kerak (deve essere fatto), murojaat qilmoq (rivolgersi), taqdim etmoq (presentare). Il verbo è spesso al passivo.",
      "Rasmiy italyan tilida shakllar: si prega di, è necessario presentare, viene richiesto, La invitiamo a. Ko'pincha majhul nisbat va «Lei» shakli ishlatiladi."),
     [("Si prega di compilare il modulo.", "Iltimos, shaklni to'ldiring."),
      ("È necessario presentare il documento.", "Hujjatni taqdim etish kerak.")]),
    (("Fare reclami con garbo", "Xushmuomala shikoyat"),
     ("Per lamentarsi educatamente: Kechirasiz, bir muammo bor (scusi, c'è un problema), …ni tekshirib bera olasizmi? (potrebbe controllare…?).",
      "Odobli shikoyat uchun: Scusi, c'è un problema. Potrebbe controllare, per favore? Vorrei parlare con il responsabile."),
     [("C'è un problema con il mio ordine.", "Buyurtmamda muammo bor."),
      ("Vorrei parlare con il responsabile.", "Mas'ul shaxs bilan gaplashmoqchiman.")]),
  ],
  lessons=[
   ("b1u8l1", ("Documenti", "Hujjatlar"),
    [("modulo", "shakl"), ("compilare", "to'ldirmoq"), ("firma (atto)", "imzo"), ("timbro", "muhr"),
     ("certificato", "guvohnoma"), ("residenza", "yashash joyi"), ("permesso di soggiorno", "yashash ruxsatnomasi"),
     ("scadere", "muddati tugamoq"), ("rinnovare", "yangilamoq"), ("ufficio pubblico", "davlat idorasi")],
    [("Devo rinnovare il passaporto.", "Pasportimni yangilashim kerak."),
     ("Il documento è scaduto il mese scorso.", "Hujjatning muddati o'tgan oy tugadi."),
     ("Compili il modulo in stampatello.", "Shaklni bosma harflarda to'ldiring."),
     ("Serve una copia del certificato.", "Guvohnomaning nusxasi kerak."),
     ("Dove devo firmare?", "Qayerga imzo chekishim kerak?"),
     ("Quanto tempo ci vuole?", "Qancha vaqt ketadi?")]),
   ("b1u8l2", ("In banca", "Bankda"),
    [("conto corrente", "hisob raqami"), ("bonifico", "pul o'tkazmasi"), ("prelevare", "yechib olmoq"),
     ("versare", "kiritmoq"), ("carta di credito", "kredit karta"), ("commissione", "komissiya"),
     ("saldo", "qoldiq"), ("prestito", "kredit"), ("interesse", "foiz"), ("sportello", "kassa")],
    [("Vorrei aprire un conto corrente.", "Hisob raqami ochmoqchiman."),
     ("Devo fare un bonifico all'estero.", "Chet elga pul o'tkazishim kerak."),
     ("Qual è la commissione?", "Komissiya qancha?"),
     ("Posso prelevare qui?", "Shu yerdan pul yechsam bo'ladimi?"),
     ("Vorrei controllare il saldo.", "Qoldiqni tekshirmoqchiman."),
     ("Ho chiesto un prestito alla banca.", "Bankdan kredit so'radim.")]),
   ("b1u8l3", ("Servizi e appuntamenti", "Xizmatlar va navbat"),
    [("prenotare (servizio)", "navbat olmoq"), ("coda", "navbat"), ("sportello aperto", "ochiq kassa"),
     ("orario di apertura", "ish vaqti"), ("modulo online", "onlayn ariza"), ("ricevuta", "kvitansiya"),
     ("pagamento", "to'lov"), ("bolletta (utenza)", "kommunal hisob"), ("contratto (servizio)", "shartnoma"),
     ("disdetta", "bekor qilish")],
    [("Ho prenotato un appuntamento online.", "Onlayn navbat oldim."),
     ("C'era una coda lunghissima.", "Juda uzun navbat bor edi."),
     ("Conservi la ricevuta, per favore.", "Kvitansiyani saqlang, iltimos."),
     ("Qual è l'orario di apertura?", "Ish vaqti qanday?"),
     ("Vorrei disdire il contratto.", "Shartnomani bekor qilmoqchiman."),
     ("Il pagamento non è andato a buon fine.", "To'lov amalga oshmadi.")]),
   ("b1u8l4", ("Reclami", "Shikoyatlar"),
    [("reclamo", "shikoyat"), ("rimborso", "pulni qaytarish"), ("garanzia", "kafolat"),
     ("difetto", "nuqson"), ("sostituire (prodotto)", "almashtirmoq"), ("responsabile", "mas'ul"),
     ("inaccettabile", "qabul qilib bo'lmaydigan"), ("risolvere", "hal qilmoq"),
     ("assistenza", "yordam xizmati"), ("pazienza (attesa)", "sabr")],
    [("Vorrei fare un reclamo.", "Shikoyat qilmoqchiman."),
     ("Il prodotto ha un difetto.", "Mahsulotda nuqson bor."),
     ("Posso avere un rimborso?", "Pulimni qaytarib olsam bo'ladimi?"),
     ("È ancora in garanzia.", "Hali kafolat muddatida."),
     ("Questa situazione è inaccettabile.", "Bu holat qabul qilib bo'lmaydigan darajada."),
     ("Spero che si possa risolvere subito.", "Umid qilamanki, tezda hal bo'ladi.")]),
  ],
  dialogue=(("Allo sportello", "Kassada"), [
    ("Xodim", "Buongiorno, mi dica.", "Xayrli kun, eshitaman."),
    ("Giulia", "Vorrei rinnovare il permesso di soggiorno.", "Yashash ruxsatnomasini yangilamoqchiman."),
    ("Xodim", "Ha il modulo compilato?", "To'ldirilgan shakl bormi?"),
    ("Giulia", "Sì, e anche una copia del passaporto.", "Ha, pasport nusxasi ham bor."),
    ("Xodim", "Manca la ricevuta del pagamento.", "To'lov kvitansiyasi yetishmayapti."),
    ("Giulia", "Posso pagare qui?", "Shu yerda to'lasam bo'ladimi?"),
    ("Xodim", "Allo sportello 4. Poi torni da me.", "4-kassada. Keyin menga qayting."),
    ("Giulia", "Va bene, grazie della pazienza.", "Yaxshi, sabringiz uchun rahmat."),
  ])),
]
