# -*- coding: utf-8 -*-
# B2 — Intermedio superiore / Yuqori o'rta daraja

LEVEL = "b2"

UNITS = [
 dict(id="b2u1", icon="person.wave.2.fill", accent="purple",
  title=("Argomentare e persuadere", "Bahs va ishontirish"),
  subtitle=("Sostenere una tesi, confutare, negoziare", "Fikrni himoya qilish, rad etish, kelishuv"),
  grammar=[
    (("Il periodo ipotetico dell'irrealtà", "Amalga oshmagan shart"),
     ("Per l'ipotesi irreale l'uzbeko usa -sa edi / -ganda edi + bo'lar edi: Agar bilganimda edi, aytgan bo'lar edim = se l'avessi saputo, l'avrei detto.",
      "Italyan tilida uchinchi tur shart gap: se + congiuntivo trapassato, condizionale passato: Se l'avessi saputo, te l'avrei detto. Ikkinchi tur: Se avessi tempo, verrei."),
     [("Se l'avessi saputo, te l'avrei detto.", "Bilganimda edi, senga aytgan bo'lardim."),
      ("Se avessi tempo, verrei.", "Vaqtim bo'lsa edi, kelardim.")]),
    (("Confutare con eleganza", "Xushmuomala rad etish"),
     ("Formule utili: Gapingizda jon bor, lekin… (c'è del vero, ma…), Aksincha (al contrario), Buni boshqacha ko'raman (la vedo diversamente).",
      "Foydali iboralar: C'è del vero in quello che dice, però… / Al contrario… / La vedo diversamente / Mi permetta di dissentire."),
     [("C'è del vero, però…", "Gapingizda jon bor, lekin…"), ("Al contrario…", "Aksincha…"),
      ("Mi permetta di dissentire.", "Rozi emasligimga ruxsat bering.")]),
    (("Connettivi avanzati", "Murakkab bog'lovchilar"),
     ("Per un discorso strutturato: bir tomondan… ikkinchi tomondan (da un lato… dall'altro), shuni ta'kidlash joizki (va sottolineato che), boshqacha aytganda (in altre parole), xulosa o'rnida (per concludere).",
      "Ilmiy uslub uchun: da un lato… dall'altro, va sottolineato che, in altre parole, per concludere, nonostante ciò, in tal senso."),
     [("da un lato… dall'altro", "bir tomondan… ikkinchi tomondan"),
      ("in altre parole", "boshqacha aytganda"), ("nonostante ciò", "shunga qaramay")]),
  ],
  lessons=[
   ("b2u1l1", ("Sostenere una tesi", "Fikrni himoya qilish"),
    [("tesi", "tezis"), ("argomento (arg.)", "dalil"), ("premessa", "muqaddima"),
     ("presupporre", "taxmin qilmoq"), ("dimostrare", "isbotlamoq"), ("evidenziare", "ta'kidlamoq"),
     ("fondato", "asosli"), ("infondato", "asossiz"), ("plausibile", "ishonarli"),
     ("in base a", "…ga asoslanib")],
    [("La mia tesi si fonda su tre argomenti.", "Mening tezisim uch dalilga asoslanadi."),
     ("I dati dimostrano il contrario.", "Ma'lumotlar buning aksini isbotlaydi."),
     ("Vorrei evidenziare un aspetto trascurato.", "E'tibordan chetda qolgan jihatni ta'kidlamoqchiman."),
     ("È un'affermazione del tutto infondata.", "Bu mutlaqo asossiz da'vo."),
     ("In base alle ricerche più recenti…", "Eng so'nggi tadqiqotlarga asoslanib…"),
     ("Mi sembra un'ipotesi plausibile.", "Bu menga ishonarli faraz bo'lib tuyuladi.")]),
   ("b2u1l2", ("Confutare", "Rad etish"),
    [("obiezione", "e'tiroz"), ("contraddizione", "ziddiyat"), ("smentire", "rad etmoq"),
     ("fraintendere", "noto'g'ri tushunmoq"), ("generalizzare", "umumlashtirmoq"),
     ("sfumatura", "nozik jihat"), ("eccezione", "istisno"), ("discutibile", "bahsli"),
     ("al contrario", "aksincha"), ("tuttavia", "shunga qaramay")],
    [("Mi permetta un'obiezione.", "E'tiroz bildirishga ruxsat bering."),
     ("Credo che lei mi abbia frainteso.", "Menimcha, siz meni noto'g'ri tushundingiz."),
     ("Non si può generalizzare così.", "Bunday umumlashtirib bo'lmaydi."),
     ("C'è una contraddizione nel suo ragionamento.", "Mulohazangizda ziddiyat bor."),
     ("È un punto quanto meno discutibile.", "Bu, eng kamida, bahsli masala."),
     ("Tuttavia i fatti dicono altro.", "Shunga qaramay, faktlar boshqacha ko'rsatadi.")]),
   ("b2u1l3", ("Negoziare", "Muzokara"),
    [("trattativa", "muzokara"), ("condizione (accordo)", "shart"), ("cedere", "yon bosmoq"),
     ("insistere", "qat'iy turmoq"), ("proposta", "taklif"), ("controproposta", "qarshi taklif"),
     ("vincolo", "cheklov"), ("margine", "imkon"), ("accordo (finale)", "kelishuv"),
     ("reciproco", "o'zaro")],
    [("Siamo aperti a una controproposta.", "Biz qarshi taklifga ochiqmiz."),
     ("Su questo punto non possiamo cedere.", "Bu masalada yon bera olmaymiz."),
     ("C'è un margine di trattativa?", "Muzokara uchun imkon bormi?"),
     ("Cerchiamo una soluzione reciprocamente vantaggiosa.", "O'zaro manfaatli yechim izlaylik."),
     ("Accetto a una condizione.", "Bir shart bilan roziman."),
     ("Mettiamo per iscritto l'accordo.", "Kelishuvni yozma rasmiylashtiraylik.")]),
   ("b2u1l4", ("Persuadere", "Ishontirish"),
    [("persuadere", "ko'ndirmoq"), ("retorica", "notiqlik"), ("credibilità", "ishonchlilik"),
     ("appello", "murojaat"), ("enfatizzare", "urg'u bermoq"), ("ridimensionare", "kichraytirmoq"),
     ("manipolare", "manipulyatsiya qilmoq"), ("obiettivo (imparziale)", "xolis"),
     ("convincente", "ishontiruvchi"), ("efficace", "samarali")],
    [("Il suo discorso è stato molto convincente.", "Uning nutqi juda ishontiruvchi bo'ldi."),
     ("Cerco di restare il più obiettivo possibile.", "Iloji boricha xolis qolishga harakat qilaman."),
     ("Non voglio manipolare i dati.", "Ma'lumotlarni buzib ko'rsatmoqchi emasman."),
     ("Ha enfatizzato solo gli aspetti positivi.", "U faqat ijobiy jihatlarga urg'u berdi."),
     ("Un argomento efficace vale più di dieci deboli.", "Bitta samarali dalil o'nta zaifidan afzal."),
     ("La credibilità si costruisce nel tempo.", "Ishonch vaqt bilan quriladi.")]),
  ],
  dialogue=(("Una trattativa difficile", "Qiyin muzokara"), [
    ("Aziz", "Se accettassimo il vostro prezzo, andremmo in perdita.", "Sizning narxingizni qabul qilsak, zarar ko'ramiz."),
    ("Mijoz", "Capisco, però il nostro budget è vincolato.", "Tushunaman, lekin byudjetimiz cheklangan."),
    ("Aziz", "C'è del vero, però consideri la qualità del servizio.", "Gapingizda jon bor, lekin xizmat sifatini hisobga oling."),
    ("Mijoz", "Su questo non discuto. Che margine avete?", "Bunda bahslashmayman. Qanday imkoningiz bor?"),
    ("Aziz", "Potremmo cedere sul cinque per cento, non di più.", "Besh foizga yon bera olamiz, undan ortiq emas."),
    ("Mijoz", "Se aggiungeste la formazione, accetterei subito.", "Agar o'qitishni qo'shsangiz, darrov rozi bo'lardim."),
    ("Aziz", "Su questa base possiamo trovare un accordo.", "Shu asosda kelishuvga erisha olamiz."),
  ])),

 dict(id="b2u2", icon="building.columns.fill", accent="teal",
  title=("Economia e lavoro", "Iqtisod va mehnat"),
  subtitle=("Mercato, impresa, diritti, economia domestica", "Bozor, tadbirkorlik, huquqlar"),
  grammar=[
    (("La nominalizzazione: -lik, -chilik", "Ot yasovchi qo'shimchalar"),
     ("Dai nomi e dagli aggettivi si formano concetti astratti: ish → ishsizlik (disoccupazione), do'st → do'stlik (amicizia), dehqon → dehqonchilik (agricoltura).",
      "Italyan tilida mavhum otlar -zione, -mento, -tà, -ezza qo'shimchalari bilan yasaladi: disoccupazione, investimento, povertà, ricchezza."),
     [("disoccupazione", "ishsizlik"), ("ricchezza", "boylik"), ("agricoltura", "dehqonchilik")]),
    (("Il linguaggio economico", "Iqtisodiy uslub"),
     ("La stampa economica usa forme passive e nominali: narxlar oshdi (i prezzi sono saliti), o'sish kuzatildi (è stata osservata una crescita).",
      "Iqtisodiy matnlarda: i prezzi sono aumentati, si è registrata una crescita, il PIL è cresciuto del 3%, il mercato ha reagito."),
     [("I prezzi sono aumentati.", "Narxlar oshdi."), ("Si è registrata una crescita.", "O'sish qayd etildi.")]),
  ],
  lessons=[
   ("b2u2l1", ("Mercato ed economia", "Bozor va iqtisod"),
    [("economia", "iqtisodiyot"), ("mercato", "bozor"), ("domanda", "talab"), ("offerta (econ.)", "taklif"),
     ("inflazione", "inflyatsiya"), ("crescita", "o'sish"), ("crisi", "inqiroz"),
     ("investimento", "investitsiya"), ("concorrenza", "raqobat"), ("consumatore", "iste'molchi")],
    [("L'inflazione ha superato il dieci per cento.", "Inflyatsiya o'n foizdan oshdi."),
     ("La domanda supera l'offerta.", "Talab taklifdan ustun."),
     ("Il mercato è molto competitivo.", "Bozorda raqobat kuchli."),
     ("Gli investimenti stranieri sono aumentati.", "Xorijiy investitsiyalar ko'paydi."),
     ("I consumatori sono più attenti ai prezzi.", "Iste'molchilar narxlarga e'tiborliroq."),
     ("La crisi ha colpito soprattutto le piccole imprese.", "Inqiroz ayniqsa kichik korxonalarga zarba berdi.")]),
   ("b2u2l2", ("Fare impresa", "Tadbirkorlik"),
    [("impresa", "korxona"), ("imprenditore", "tadbirkor"), ("fatturato", "aylanma"),
     ("costi", "xarajatlar"), ("profitto", "foyda"), ("perdita", "zarar"), ("cliente", "mijoz"),
     ("fornitore", "yetkazib beruvchi"), ("strategia", "strategiya"), ("rischio (impresa)", "tavakkal")],
    [("Ho avviato un'attività due anni fa.", "Ikki yil oldin biznes boshladim."),
     ("I costi sono cresciuti più del fatturato.", "Xarajatlar aylanmadan tezroq o'sdi."),
     ("Dobbiamo diversificare i fornitori.", "Yetkazib beruvchilarni xilma-xil qilishimiz kerak."),
     ("Il primo anno abbiamo chiuso in perdita.", "Birinchi yilni zarar bilan yopdik."),
     ("Ogni impresa comporta dei rischi.", "Har bir biznes tavakkal bilan bog'liq."),
     ("La fedeltà dei clienti è fondamentale.", "Mijozlar sodiqligi hal qiluvchi ahamiyatga ega.")]),
   ("b2u2l3", ("Diritti dei lavoratori", "Mehnat huquqlari"),
    [("sindacato", "kasaba uyushmasi"), ("sciopero", "ish tashlash"), ("tutela", "himoya"),
     ("contratto collettivo", "jamoa shartnomasi"), ("straordinario", "qo'shimcha ish"),
     ("licenziamento", "ishdan bo'shatish"), ("indennità", "nafaqa"), ("sicurezza sul lavoro", "mehnat xavfsizligi"),
     ("discriminazione", "kamsitish"), ("parità", "tenglik")],
    [("I lavoratori hanno indetto uno sciopero.", "Ishchilar ish tashlash e'lon qilishdi."),
     ("Gli straordinari devono essere pagati.", "Qo'shimcha ish haqi to'lanishi kerak."),
     ("La sicurezza sul lavoro non è negoziabile.", "Mehnat xavfsizligi muhokama qilinmaydi."),
     ("È stato licenziato senza preavviso.", "U ogohlantirishsiz ishdan bo'shatildi."),
     ("Chiediamo parità di trattamento.", "Biz teng munosabat talab qilamiz."),
     ("Il contratto tutela entrambe le parti.", "Shartnoma ikkala tomonni himoya qiladi.")]),
   ("b2u2l4", ("Soldi e risparmio", "Pul va jamg'arma"),
    [("bilancio familiare", "oila byudjeti"), ("risparmio", "jamg'arma"), ("spesa fissa", "doimiy xarajat"),
     ("debito", "qarz"), ("rata", "bo'lib to'lash"), ("mutuo", "ipoteka"), ("tassa", "soliq"),
     ("reddito", "daromad"), ("potere d'acquisto", "sotib olish qobiliyati"), ("permettersi", "qurbi yetmoq")],
    [("Non riusciamo a risparmiare niente.", "Hech narsa jamg'ara olmayapmiz."),
     ("Metà del reddito va in affitto.", "Daromadning yarmi ijaraga ketadi."),
     ("Non posso permettermi una macchina nuova.", "Yangi mashinaga qurbim yetmaydi."),
     ("Pago il mutuo da dieci anni.", "O'n yildan beri ipoteka to'layman."),
     ("Il potere d'acquisto è diminuito.", "Sotib olish qobiliyati pasaydi."),
     ("Ho estinto il debito in anticipo.", "Qarzni muddatidan oldin yopdim.")]),
  ],
  dialogue=(("Il bilancio familiare", "Oila byudjeti"), [
    ("Giulia", "Se continuiamo così, non risparmieremo mai.", "Shunday davom etsak, hech qachon jamg'arolmaymiz."),
    ("Aziz", "Il problema sono le spese fisse: affitto, bollette, trasporti.", "Muammo doimiy xarajatlarda: ijara, kommunal, transport."),
    ("Giulia", "Avremmo dovuto cercare una casa più piccola.", "Kichikroq uy qidirishimiz kerak edi."),
    ("Aziz", "Forse. Però il quartiere è comodo per il lavoro.", "Balki. Lekin mahalla ishga qulay."),
    ("Giulia", "Proviamo a tagliare le spese superflue per tre mesi.", "Uch oy ortiqcha xarajatlarni qisqartirib ko'raylik."),
    ("Aziz", "D'accordo. Facciamo un bilancio dettagliato ogni mese.", "Roziman. Har oy batafsil hisob yuritamiz."),
  ])),

 dict(id="b2u3", icon="atom", accent="sky",
  title=("Scienza e innovazione", "Fan va innovatsiya"),
  subtitle=("Ricerca, salute pubblica, etica tecnologica", "Tadqiqot, sog'liqni saqlash, etika"),
  grammar=[
    (("Il registro scientifico", "Ilmiy uslub"),
     ("Nei testi scientifici l'uzbeko usa il passivo e forme come aniqlandi (è stato accertato), ko'rsatildi (è stato dimostrato), deb hisoblanadi (si ritiene che).",
      "Ilmiy italyan tilida: è stato dimostrato che, si ritiene che, risulta evidente che, i dati suggeriscono che. Majhul nisbat va shaxssiz «si» keng ishlatiladi."),
     [("È stato dimostrato che…", "…isbotlandi."), ("Si ritiene che…", "…deb hisoblanadi.")]),
    (("La probabilità e la cautela", "Ehtimol va ehtiyotkorlik"),
     ("Per esprimere cautela: ehtimol (probabilmente), -sa kerak (dovrebbe essere), taxminan (all'incirca), bo'lishi mumkin (è possibile che).",
      "Ehtiyotkor ifodalar: probabilmente, è possibile che + congiuntivo, dovrebbe essere, sembrerebbe che, non è escluso che."),
     [("È possibile che sia così.", "Shunday bo'lishi mumkin."), ("Sembrerebbe di sì.", "Shunday bo'lsa kerak.")]),
  ],
  lessons=[
   ("b2u3l1", ("Ricerca scientifica", "Ilmiy tadqiqot"),
    [("ricerca (studio)", "tadqiqot"), ("ipotesi", "faraz"), ("esperimento", "tajriba"),
     ("dato", "ma'lumot"), ("risultato", "natija"), ("campione", "namuna"),
     ("verificare", "tekshirmoq"), ("pubblicare (studio)", "e'lon qilmoq"),
     ("peer review", "taqriz"), ("finanziamento", "moliyalashtirish")],
    [("Lo studio è stato pubblicato su una rivista scientifica.", "Tadqiqot ilmiy jurnalda e'lon qilindi."),
     ("I risultati confermano l'ipotesi iniziale.", "Natijalar dastlabki farazni tasdiqlaydi."),
     ("Il campione era troppo ristretto.", "Namuna hajmi juda kichik edi."),
     ("Serve un finanziamento pubblico.", "Davlat moliyalashtiruvi kerak."),
     ("Ogni dato va verificato in modo indipendente.", "Har bir ma'lumot mustaqil tekshirilishi kerak."),
     ("La ricerca richiede tempo e pazienza.", "Tadqiqot vaqt va sabr talab qiladi.")]),
   ("b2u3l2", ("Salute e medicina", "Tibbiyot"),
    [("prevenzione", "profilaktika"), ("diagnosi", "tashxis"), ("terapia", "davolash"),
     ("vaccino", "vaksina"), ("effetto collaterale", "nojo'ya ta'sir"), ("cronico", "surunkali"),
     ("epidemia", "epidemiya"), ("sistema sanitario", "sog'liqni saqlash tizimi"),
     ("aspettativa di vita", "o'rtacha umr"), ("benessere", "farovonlik")],
    [("La prevenzione è più efficace della cura.", "Profilaktika davolashdan samaraliroq."),
     ("La diagnosi precoce salva vite.", "Erta tashxis hayot saqlaydi."),
     ("Il sistema sanitario è sotto pressione.", "Sog'liqni saqlash tizimi zo'riqishda."),
     ("L'aspettativa di vita è cresciuta.", "O'rtacha umr ko'rish oshdi."),
     ("Gli effetti collaterali sono rari.", "Nojo'ya ta'sirlar kam uchraydi."),
     ("Si tratta di una malattia cronica.", "Bu surunkali kasallik.")]),
   ("b2u3l3", ("Tecnologia ed etica", "Texnologiya va axloq"),
    [("etica", "axloq"), ("algoritmo", "algoritm"), ("automazione", "avtomatlashtirish"),
     ("sorveglianza", "kuzatuv"), ("dati personali", "shaxsiy ma'lumot"), ("trasparenza", "shaffoflik"),
     ("responsabilità (etica)", "javobgarlik"), ("regolamentare", "tartibga solmoq"),
     ("bias (pregiudizio)", "xolislik yo'qligi"), ("impatto sociale", "ijtimoiy ta'sir")],
    [("Gli algoritmi non sono neutrali.", "Algoritmlar betaraf emas."),
     ("Chi è responsabile di una decisione automatica?", "Avtomatik qaror uchun kim javobgar?"),
     ("Serve maggiore trasparenza.", "Ko'proq shaffoflik kerak."),
     ("I dati personali vanno protetti.", "Shaxsiy ma'lumotlar himoyalanishi kerak."),
     ("L'automazione cambierà molti mestieri.", "Avtomatlashtirish ko'p kasblarni o'zgartiradi."),
     ("Bisogna regolamentare senza bloccare l'innovazione.", "Innovatsiyani to'xtatmasdan tartibga solish kerak.")]),
   ("b2u3l4", ("Spazio e futuro", "Kelajak texnologiyalari"),
    [("scoperta", "kashfiyot"), ("brevetto", "patent"), ("prototipo", "prototip"),
     ("sostenibilità", "barqarorlik"), ("energia pulita", "toza energiya"), ("rivoluzione", "inqilob"),
     ("applicazione pratica", "amaliy qo'llash"), ("a lungo termine", "uzoq muddatli"),
     ("previsione", "bashorat"), ("scenario", "stsenariy")],
    [("È una scoperta destinata a cambiare tutto.", "Bu hamma narsani o'zgartiradigan kashfiyot."),
     ("Il prototipo sarà pronto l'anno prossimo.", "Prototip kelasi yili tayyor bo'ladi."),
     ("Le previsioni a lungo termine sono incerte.", "Uzoq muddatli bashoratlar noaniq."),
     ("L'energia pulita è ormai competitiva.", "Toza energiya endi raqobatbardosh."),
     ("Consideriamo lo scenario peggiore.", "Eng yomon stsenariyni ko'rib chiqaylik."),
     ("Dall'idea all'applicazione pratica il passo è lungo.", "G'oyadan amaliyotgacha yo'l uzoq.")]),
  ],
  dialogue=(("Un articolo controverso", "Bahsli maqola"), [
    ("Dilnoza", "Hai letto l'articolo sull'intelligenza artificiale in medicina?", "Tibbiyotdagi sun'iy intellekt haqidagi maqolani o'qidingmi?"),
    ("Giulia", "Sì, ma il campione mi sembrava piccolo.", "Ha, lekin namuna menga kichikdek tuyuldi."),
    ("Dilnoza", "Anche a me. Però i risultati sono interessanti.", "Menga ham. Lekin natijalar qiziqarli."),
    ("Giulia", "Interessanti sì, ma non ancora conclusivi.", "Qiziqarli, lekin hali yakuniy emas."),
    ("Dilnoza", "Se lo studio fosse stato replicato, sarebbe più credibile.", "Agar tadqiqot takrorlanganda edi, ishonchliroq bo'lardi."),
    ("Giulia", "Esatto. Aspettiamo la revisione dei colleghi.", "Aynan. Hamkasblar taqrizini kutaylik."),
  ])),

 dict(id="b2u4", icon="paintpalette.fill", accent="pink",
  title=("Arte, cinema e letteratura", "San'at, kino va adabiyot"),
  subtitle=("Recensire, interpretare, parlare di stile", "Taqriz, talqin va uslub"),
  grammar=[
    (("I pronomi relativi complessi", "Murakkab nisbiy olmoshlar"),
     ("Dove l'italiano usa «di cui, in cui, per il quale», l'uzbeko ricorre a participi e possessivi: muallifi mashhur bo'lgan kitob = il libro il cui autore è famoso.",
      "Italyan tilida: il libro di cui ti ho parlato, la casa in cui vivo, l'autore al quale mi riferisco. «Cui» predlogdan keyin keladi, «che» esa ega yoki to'ldiruvchi bo'ladi."),
     [("il libro di cui ti ho parlato", "men senga aytgan kitob"),
      ("la casa in cui vivo", "men yashaydigan uy")]),
    (("Descrivere impressioni", "Taassurot ifodalash"),
     ("Per commentare un'opera: menda kuchli taassurot qoldirdi (mi ha colpito molto), meni befarq qoldirmadi (non mi ha lasciato indifferente).",
      "San'at haqida: mi ha colpito molto, mi ha lasciato senza parole, non mi ha convinto del tutto, è sopravvalutato."),
     [("Mi ha colpito molto.", "Menda kuchli taassurot qoldirdi."),
      ("Non mi ha convinto del tutto.", "Meni to'liq ishontirmadi.")]),
  ],
  lessons=[
   ("b2u4l1", ("Cinema", "Kino"),
    [("regista", "rejissor"), ("sceneggiatura", "stsenariy"), ("trama", "syujet"),
     ("personaggio", "qahramon"), ("interpretazione", "ijro"), ("colonna sonora", "musiqa"),
     ("sottotitoli", "subtitrlar"), ("doppiaggio", "dublyaj"), ("premiato", "mukofotlangan"),
     ("noioso (film)", "cho'zilgan")],
    [("Il film è tratto da un romanzo.", "Film romandan olingan."),
     ("L'interpretazione dell'attrice è straordinaria.", "Aktrisaning ijrosi ajoyib."),
     ("La trama è prevedibile ma i dialoghi sono ottimi.", "Syujet oldindan aniq, lekin dialoglar zo'r."),
     ("Preferisco i film in lingua originale con i sottotitoli.", "Men filmlarni asl tilda subtitr bilan ko'rishni afzal ko'raman."),
     ("Il finale mi ha lasciato senza parole.", "Yakuni meni lol qoldirdi."),
     ("Ha vinto il premio come miglior regia.", "Eng yaxshi rejissyorlik mukofotini oldi.")]),
   ("b2u4l2", ("Letteratura", "Adabiyot"),
    [("romanzo", "roman"), ("racconto", "hikoya"), ("poesia", "she'r"), ("autore", "muallif"),
     ("stile", "uslub"), ("metafora", "metafora"), ("traduzione", "tarjima"),
     ("capitolo", "bob"), ("protagonista", "bosh qahramon"), ("classico", "klassik")],
    [("Sto leggendo un romanzo di Cholpon.", "Men Cho'lponning romanini o'qiyapman."),
     ("La traduzione non rende la poesia originale.", "Tarjima asl she'r ta'sirini bermaydi."),
     ("Il suo stile è asciutto ma potente.", "Uning uslubi quruq, lekin kuchli."),
     ("Il protagonista cambia completamente nel finale.", "Bosh qahramon yakunda butunlay o'zgaradi."),
     ("È considerato un classico della letteratura uzbeka.", "U o'zbek adabiyoti klassigi hisoblanadi."),
     ("Ho sottolineato molte frasi.", "Ko'p jumlalarning tagiga chizdim.")]),
   ("b2u4l3", ("Musica e spettacolo", "Musiqa va tomosha"),
    [("concerto", "konsert"), ("strumento", "cholg'u"), ("melodia", "kuy"), ("testo (canzone)", "qo'shiq matni"),
     ("esibizione", "chiqish"), ("palcoscenico", "sahna"), ("pubblico", "tomoshabin"),
     ("applauso", "qarsak"), ("tradizionale (musica)", "an'anaviy"), ("contemporaneo", "zamonaviy")],
    [("Il concerto è stato sold out.", "Konsert chiptalari sotilib ketdi."),
     ("Mescolano musica tradizionale e contemporanea.", "Ular an'anaviy va zamonaviy musiqani aralashtiradi."),
     ("Il pubblico si è alzato in piedi.", "Tomoshabinlar o'rnidan turib ketdi."),
     ("Il testo della canzone è poetico.", "Qo'shiq matni she'riy."),
     ("Suona il dutar da quando aveva sei anni.", "U olti yoshdan beri dutor chaladi."),
     ("È stata un'esibizione memorabile.", "Bu esda qolarli chiqish bo'ldi.")]),
   ("b2u4l4", ("Recensire", "Taqriz yozish"),
    [("recensione", "taqriz"), ("giudizio", "baho"), ("consigliare", "tavsiya qilmoq"),
     ("sconsigliare", "tavsiya qilmaslik"), ("sopravvalutato", "haddan ortiq maqtalgan"),
     ("originale", "o'ziga xos"), ("banale", "oddiy"), ("profondo", "chuqur"),
     ("ritmo (narr.)", "sur'at"), ("nel complesso", "umuman olganda")],
    [("Nel complesso lo consiglio.", "Umuman olganda, tavsiya qilaman."),
     ("È a mio avviso sopravvalutato.", "Menimcha, u haddan ortiq maqtalgan."),
     ("Il ritmo cala nella seconda parte.", "Ikkinchi qismda sur'at pasayadi."),
     ("Un'opera originale e profonda.", "O'ziga xos va chuqur asar."),
     ("Non lo consiglierei a chi cerca azione.", "Harakat qidiruvchilarga tavsiya qilmagan bo'lardim."),
     ("Merita almeno una visione.", "Kamida bir marta ko'rishga arziydi.")]),
  ],
  dialogue=(("Dopo il film", "Kinodan keyin"), [
    ("Giulia", "Allora? Che ne pensi?", "Xo'sh? Nima deysan?"),
    ("Aziz", "Bello, però mi aspettavo di più dal finale.", "Yaxshi, lekin yakunidan ko'proq kutgandim."),
    ("Giulia", "A me ha colpito soprattutto la fotografia.", "Meni ayniqsa tasvir hayratlantirdi."),
    ("Aziz", "Su quello siamo d'accordo. E la colonna sonora?", "Bunda roziman. Musiqasi-chi?"),
    ("Giulia", "Splendida. Anche se a tratti troppo presente.", "Ajoyib. Garchi ba'zan haddan ortiq baland bo'lsa ham."),
    ("Aziz", "Nel complesso lo consiglierei.", "Umuman olganda, tavsiya qilardim."),
  ])),

 dict(id="b2u5", icon="globe.europe.africa.fill", accent="green",
  title=("Società e attualità", "Jamiyat va dolzarb mavzular"),
  subtitle=("Migrazione, istruzione, diritti, informazione", "Migratsiya, ta'lim, huquq, axborot"),
  grammar=[
    (("Il discorso indiretto completo", "To'liq ko'chirma gap"),
     ("Passando al discorso indiretto l'uzbeko usa -ganini/-ishini + il verbo dire: U kelishini aytdi = ha detto che sarebbe venuto. Il pronome cambia, il tempo di norma no.",
      "Italyan tilida ko'chirma gapda zamon ham o'zgaradi: «Vengo» → ha detto che veniva / sarebbe venuto; «Ho finito» → ha detto che aveva finito."),
     [("Ha detto che sarebbe venuto.", "U kelishini aytdi."),
      ("Ha detto che aveva finito.", "U tugatganini aytdi.")]),
    (("Impersonale e generalizzante", "Umumlashtirish"),
     ("Per parlare in generale: odamlar (la gente), ko'pchilik (la maggioranza), aytishlaricha (a quanto si dice), ma'lumotlarga ko'ra (secondo i dati).",
      "Umumiy gaplar uchun: la gente, la maggior parte, si dice che, secondo i dati, in generale, di norma."),
     [("Si dice che…", "Aytishlaricha…"), ("Secondo i dati…", "Ma'lumotlarga ko'ra…")]),
  ],
  lessons=[
   ("b2u5l1", ("Migrazione e identità", "Migratsiya va o'ziga xoslik"),
    [("migrazione", "migratsiya"), ("emigrare", "chet elga ketmoq"), ("immigrato", "muhojir"),
     ("integrazione (soc.)", "moslashuv"), ("radici", "ildizlar"), ("nostalgia di casa", "vatan sog'inchi"),
     ("cittadinanza", "fuqarolik"), ("pregiudizio", "xurofot"), ("accoglienza", "qabul qilish"),
     ("appartenenza", "mansublik")],
    [("Molti giovani emigrano per lavoro.", "Ko'p yoshlar ish uchun chet elga ketadi."),
     ("L'integrazione richiede sforzi da entrambe le parti.", "Moslashuv ikki tomondan ham harakat talab qiladi."),
     ("Ho ottenuto la cittadinanza dopo dieci anni.", "O'n yildan keyin fuqarolik oldim."),
     ("Ci sono ancora molti pregiudizi.", "Hali ko'p xurofotlar bor."),
     ("Non voglio perdere le mie radici.", "Ildizlarimni yo'qotmoqchi emasman."),
     ("Mi sento a metà tra due culture.", "O'zimni ikki madaniyat orasida his qilaman.")]),
   ("b2u5l2", ("Istruzione", "Ta'lim"),
    [("sistema scolastico", "ta'lim tizimi"), ("obbligatorio", "majburiy"), ("gratuito", "bepul"),
     ("abbandono scolastico", "maktabni tashlab ketish"), ("merito", "iste'dod"),
     ("formazione continua", "uzluksiz ta'lim"), ("competenze digitali", "raqamli ko'nikmalar"),
     ("insegnamento", "o'qitish"), ("valutazione", "baholash"), ("riforma", "islohot")],
    [("L'istruzione dovrebbe essere accessibile a tutti.", "Ta'lim hamma uchun ochiq bo'lishi kerak."),
     ("La riforma ha diviso l'opinione pubblica.", "Islohot jamoatchilik fikrini ikkiga bo'ldi."),
     ("Servono più investimenti nella scuola.", "Maktabga ko'proq sarmoya kerak."),
     ("Le competenze digitali sono ormai indispensabili.", "Raqamli ko'nikmalar endi zarur."),
     ("Il tasso di abbandono è diminuito.", "Maktabni tashlab ketish darajasi kamaydi."),
     ("La valutazione non misura tutto.", "Baholash hamma narsani o'lchamaydi.")]),
   ("b2u5l3", ("Diritti e giustizia", "Huquq va adolat"),
    [("legge", "qonun"), ("giustizia", "adolat"), ("tribunale", "sud"), ("avvocato (dif.)", "himoyachi"),
     ("colpevole", "aybdor"), ("innocente", "aybsiz"), ("testimone", "guvoh"),
     ("libertà di espressione", "so'z erkinligi"), ("censura", "senzura"), ("corruzione", "korrupsiya")],
    [("Tutti sono uguali davanti alla legge.", "Qonun oldida hamma teng."),
     ("Il processo è durato tre anni.", "Sud jarayoni uch yil davom etdi."),
     ("La libertà di espressione ha dei limiti.", "So'z erkinligining chegaralari bor."),
     ("È stato assolto per mancanza di prove.", "Dalil yetishmagani uchun oqlandi."),
     ("La lotta alla corruzione è una priorità.", "Korrupsiyaga qarshi kurash ustuvor vazifa."),
     ("Ha testimoniato davanti al giudice.", "U sudya oldida guvohlik berdi.")]),
   ("b2u5l4", ("Informazione e opinione pubblica", "Axborot va jamoatchilik fikri"),
    [("opinione pubblica", "jamoatchilik fikri"), ("sondaggio", "so'rov"), ("manipolazione", "manipulyatsiya"),
     ("verifica dei fatti", "faktlarni tekshirish"), ("polarizzazione", "qutblanish"),
     ("dibattito pubblico", "ommaviy munozara"), ("influenzare", "ta'sir qilmoq"),
     ("imparziale", "xolis"), ("propaganda", "targ'ibot"), ("consapevolezza", "ongli munosabat")],
    [("I sondaggi vanno letti con cautela.", "So'rovlarni ehtiyotkorlik bilan o'qish kerak."),
     ("Il dibattito è sempre più polarizzato.", "Munozara tobora qutblanmoqda."),
     ("Verifico sempre le fonti prima di condividere.", "Ulashishdan oldin manbalarni doim tekshiraman."),
     ("I media influenzano l'opinione pubblica.", "OAV jamoatchilik fikriga ta'sir qiladi."),
     ("Serve più consapevolezza digitale.", "Ko'proq raqamli savodxonlik kerak."),
     ("Un giornalismo imparziale è difficile ma necessario.", "Xolis jurnalistika qiyin, lekin zarur.")]),
  ],
  dialogue=(("Restare o partire?", "Qolishmi yoki ketish?"), [
    ("Aziz", "Mio cugino vuole emigrare in Europa.", "Amakivachchamning Yevropaga ketgisi bor."),
    ("Giulia", "Per lavoro o per studio?", "Ish uchunmi yoki o'qish uchun?"),
    ("Aziz", "Per lavoro. Dice che qui non ci sono prospettive.", "Ish uchun. Bu yerda istiqbol yo'q, deydi."),
    ("Giulia", "Capisco, però anche là non è facile come sembra.", "Tushunaman, lekin u yerda ham ko'ringandek oson emas."),
    ("Aziz", "Lo so. Se partisse senza la lingua, farebbe fatica.", "Bilaman. Tilni bilmay ketsa, qiynaladi."),
    ("Giulia", "Digli di studiare prima. Ha fatto la differenza per me.", "Avval o'rgansin, deb ayt. Menga bu juda ko'p narsani o'zgartirdi."),
    ("Aziz", "Glielo dirò. In fondo hai ragione.", "Aytaman. Aslida sen haqsan."),
  ])),

 dict(id="b2u6", icon="text.quote", accent="amber",
  title=("Sfumature e modi di dire", "Nozikliklar va iboralar"),
  subtitle=("Registro, ironia, espressioni idiomatiche", "Uslub, kinoya, frazeologik birliklar"),
  grammar=[
    (("Registro formale e informale", "Rasmiy va norasmiy uslub"),
     ("Nel parlato si contraggono le forme (nima qilyapsan → nima qivossan) e si usano particelle come -ku, -da, -chi. Nello scritto formale si preferiscono forme piene e il passivo.",
      "Italyan tilida norasmiy nutqda: che fai? cioè, boh, mica male. Rasmiy uslubda: che cosa fa? in effetti, tuttavia. Farqni his qilish B2 darajasining muhim belgisidir."),
     [("Che fai?", "Nima qilyapsan?"), ("Che cosa desidera?", "Nima istaysiz?")]),
    (("Le espressioni idiomatiche", "Frazeologizmlar"),
     ("Le espressioni non si traducono parola per parola: qo'lidan ish keladi (è capace, lett. dalla sua mano viene lavoro), og'zi qulog'ida (è felicissimo, lett. la bocca è all'orecchio).",
      "Italyan iboralari ham so'zma-so'z tarjima qilinmaydi: in bocca al lupo (omad tilash), avere le mani bucate (isrofgar), costare un occhio della testa (juda qimmat)."),
     [("In bocca al lupo!", "Omad tilayman!"), ("Costa un occhio della testa.", "Juda qimmat turadi."),
      ("È felicissimo.", "Og'zi qulog'ida.")]),
  ],
  lessons=[
   ("b2u6l1", ("Parlare informale", "Norasmiy nutq"),
    [("insomma (dubbio)", "xullas"), ("cioè", "ya'ni"), ("mica", "aslo"), ("magari (desid.)", "koshki"),
     ("boh", "bilmadim"), ("dai!", "qani!"), ("figurati (risp.)", "arzimaydi"),
     ("che palle!", "juda zerikarli!"), ("roba", "narsa"), ("un sacco", "juda ko'p")],
    [("Ho un sacco di cose da fare.", "Qiladigan ishim juda ko'p."),
     ("Dai, non fare così!", "Qani, unday qilma!"),
     ("Magari fosse vero!", "Koshki rost bo'lsa!"),
     ("Non è mica facile.", "Bu aslo oson emas."),
     ("Insomma, alla fine non è venuto.", "Xullas, oxiri u kelmadi."),
     ("Cioè, volevo dire un'altra cosa.", "Ya'ni, men boshqa narsani aytmoqchi edim.")]),
   ("b2u6l2", ("Modi di dire", "Iboralar"),
    [("in bocca al lupo", "omad tilayman"), ("costare un occhio", "juda qimmat"),
     ("essere al verde", "puli yo'q"), ("prendere in giro", "kalaka qilmoq"),
     ("avere la testa tra le nuvole", "xayoli boshqa yoqda"), ("non vedere l'ora", "sabrsizlik bilan kutmoq"),
     ("farsi in quattro", "jon kuydirmoq"), ("a occhio", "chamalab"),
     ("piove sul bagnato", "kuydi-pishdi"), ("in un batter d'occhio", "ko'z ochib yumguncha")],
    [("Non vedo l'ora di rivederti.", "Seni ko'rishni sabrsizlik bilan kutyapman."),
     ("Questo mese sono al verde.", "Bu oy pulim yo'q."),
     ("Mi stai prendendo in giro?", "Meni kalaka qilyapsanmi?"),
     ("Si è fatto in quattro per aiutarmi.", "Menga yordam berish uchun jon kuydirdi."),
     ("È finito tutto in un batter d'occhio.", "Hammasi ko'z ochib yumguncha tugadi."),
     ("Oggi ho la testa tra le nuvole.", "Bugun xayolim boshqa yoqda.")]),
   ("b2u6l3", ("Ironia e umorismo", "Kinoya va hazil"),
    [("ironia", "kinoya"), ("sarcasmo", "kesatiq"), ("battuta", "hazil"), ("doppio senso", "ikki ma'no"),
     ("prendere sul serio", "jiddiy qabul qilmoq"), ("offendersi", "xafa bo'lmoq"),
     ("autoironia", "o'zini hazil qilish"), ("fraintendimento", "noto'g'ri tushunish"),
     ("scherzare", "hazillashmoq"), ("tono", "ohang")],
    [("Stavo scherzando, non offenderti.", "Hazillashdim, xafa bo'lma."),
     ("L'ironia non si capisce bene per iscritto.", "Kinoya yozuvda yaxshi tushunilmaydi."),
     ("Non prenderla sul serio.", "Buni jiddiy qabul qilma."),
     ("Ha un grande senso dell'umorismo.", "Uning hazil tuyg'usi juda kuchli."),
     ("Il tono cambia tutto il significato.", "Ohang butun ma'noni o'zgartiradi."),
     ("È stato un fraintendimento.", "Bu noto'g'ri tushunish bo'ldi.")]),
   ("b2u6l4", ("Attenuare e rafforzare", "Yumshatish va kuchaytirish"),
    [("attenuare", "yumshatmoq"), ("rafforzare", "kuchaytirmoq"), ("piuttosto", "ancha"),
     ("abbastanza", "yetarlicha"), ("del tutto", "butunlay"), ("affatto", "umuman"),
     ("in qualche modo", "qandaydir tarzda"), ("tendenzialmente", "odatda"),
     ("a dir poco", "eng kamida"), ("senza mezzi termini", "ochiqchasiga")],
    [("È stato, a dir poco, sorprendente.", "Bu, eng kamida, hayratlanarli bo'ldi."),
     ("Non sono del tutto convinta.", "Men butunlay ishonganim yo'q."),
     ("Diciamolo senza mezzi termini.", "Ochiqchasiga aytaylik."),
     ("La proposta è piuttosto interessante.", "Taklif ancha qiziqarli."),
     ("Non mi disturba affatto.", "Bu meni umuman bezovta qilmaydi."),
     ("Tendenzialmente sono d'accordo.", "Odatda men roziman.")]),
  ],
  dialogue=(("Tra amici", "Do'stlar davrasida"), [
    ("Aziz", "Allora, com'è andato il colloquio?", "Xo'sh, suhbat qanday o'tdi?"),
    ("Giulia", "Boh… insomma. Non malissimo.", "Bilmadim… xullas. Unchalik yomon emas."),
    ("Aziz", "Cioè? Dai, racconta.", "Ya'ni? Qani, aytib ber."),
    ("Giulia", "Mi hanno fatto domande a raffica. Ero con la testa tra le nuvole.", "Savollarni ketma-ket berishdi. Xayolim boshqa yoqda edi."),
    ("Aziz", "Mica facile. Ma tu sei in gamba.", "Oson emas-da. Lekin sen uddaburonsan."),
    ("Giulia", "Speriamo. Non vedo l'ora di sapere l'esito.", "Umid qilamiz. Natijani bilishni sabrsizlik bilan kutyapman."),
    ("Aziz", "In bocca al lupo!", "Omad tilayman!"),
  ])),

 dict(id="b2u7", icon="figure.mind.and.body", accent="sky",
  title=("Benessere e stile di vita", "Farovonlik va turmush tarzi"),
  subtitle=("Salute mentale, equilibrio, abitudini", "Ruhiy salomatlik, muvozanat, odatlar"),
  grammar=[
    (("Verbi pronominali e costruzioni idiomatiche", "Olmoshli fe'l qurilmalari"),
     ("Dove l'italiano usa farcela, andarsene, metterci, l'uzbeko usa verbi composti: uddasidan chiqmoq (farcela), ketib qolmoq (andarsene), vaqt ketmoq (metterci tempo).",
      "Italyan tilida shunday fe'llar ko'p: farcela (uddasidan chiqmoq), andarsene (ketib qolmoq), metterci (vaqt sarflamoq), volerci (kerak bo'lmoq). Ularni yod olish kerak."),
     [("Ce la faccio.", "Uddasidan chiqaman."), ("Me ne vado.", "Men ketdim."),
      ("Ci vuole tempo.", "Vaqt kerak.")]),
    (("Consigli e suggerimenti", "Maslahat berish"),
     ("Per consigliare con garbo: …ganing ma'qul (faresti bene a…), …ib ko'rsang-chi? (perché non provi a…?), …ishing kerak (dovresti).",
      "Odobli maslahat: faresti bene a riposare, perché non provi a…?, dovresti dormire di più, se fossi in te…"),
     [("Dovresti riposare di più.", "Ko'proq dam olishing kerak."),
      ("Se fossi in te, direi di no.", "Sening o'rningda bo'lsam, yo'q derdim.")]),
  ],
  lessons=[
   ("b2u7l1", ("Salute mentale", "Ruhiy salomatlik"),
    [("stress cronico", "surunkali stress"), ("ansia", "xavotir"), ("esaurimento", "holdan toyish"),
     ("terapia (psic.)", "psixoterapiya"), ("stigma", "tamg'a"), ("sostegno psicologico", "psixologik yordam"),
     ("consapevolezza (mind)", "hushyorlik"), ("autostima", "o'ziga ishonch"),
     ("sfogarsi", "dardini to'kmoq"), ("ricaricarsi", "quvvat olmoq")],
    [("Parlare con qualcuno aiuta davvero.", "Kimdir bilan gaplashish chindan yordam beradi."),
     ("Lo stress cronico ha effetti fisici.", "Surunkali stress jismoniy ta'sir ko'rsatadi."),
     ("Chiedere aiuto non è una debolezza.", "Yordam so'rash — zaiflik emas."),
     ("Ho bisogno di staccare qualche giorno.", "Bir necha kun uzilishim kerak."),
     ("Sto lavorando sulla mia autostima.", "O'zimga ishonch ustida ishlayapman."),
     ("Il fine settimana mi ricarico in montagna.", "Dam olish kunlari tog'da quvvat olaman.")]),
   ("b2u7l2", ("Equilibrio vita-lavoro", "Ish va hayot muvozanati"),
    [("orario flessibile", "moslashuvchan ish vaqti"), ("lavoro da remoto", "masofaviy ish"),
     ("straripare (impegni)", "ish bosib ketmoq"), ("confine", "chegara"), ("disconnettersi", "uzilmoq"),
     ("produttività", "samaradorlik"), ("pausa vera", "haqiqiy tanaffus"),
     ("delegare (compiti)", "vazifani topshirmoq"), ("priorità (vita)", "hayotiy ustuvorlik"),
     ("burnout", "kasbiy tanazzul")],
    [("Lavoro da remoto tre giorni a settimana.", "Haftada uch kun masofadan ishlayman."),
     ("È difficile mettere dei confini chiari.", "Aniq chegara qo'yish qiyin."),
     ("La produttività non è fare più ore.", "Samaradorlik — ko'proq soat ishlash emas."),
     ("Ho imparato a delegare.", "Vazifani topshirishni o'rgandim."),
     ("La sera spengo le notifiche di lavoro.", "Kechqurun ish bildirishnomalarini o'chiraman."),
     ("Il burnout è più comune di quanto si pensi.", "Kasbiy tanazzul o'ylanganidan ko'ra ko'proq uchraydi.")]),
   ("b2u7l3", ("Corpo e movimento", "Tana va harakat"),
    [("allenamento", "mashg'ulot"), ("resistenza", "chidamlilik"), ("postura", "gavda holati"),
     ("recupero", "tiklanish"), ("infortunio", "jarohat"), ("costanza", "izchillik"),
     ("riscaldamento", "qizdirish"), ("sedentario", "harakatsiz"), ("energia (fisica)", "quvvat"),
     ("routine sana", "sog'lom tartib")],
    [("La costanza conta più dell'intensità.", "Izchillik shiddatdan muhimroq."),
     ("Ho una vita troppo sedentaria.", "Hayotim juda harakatsiz."),
     ("Mi sono infortunato al ginocchio.", "Tizzamni jarohatladim."),
     ("Il recupero fa parte dell'allenamento.", "Tiklanish ham mashg'ulotning bir qismi."),
     ("Cammino almeno otto mila passi al giorno.", "Kuniga kamida sakkiz ming qadam yuraman."),
     ("Una buona postura previene molti dolori.", "To'g'ri gavda holati ko'p og'riqlarning oldini oladi.")]),
   ("b2u7l4", ("Alimentazione e abitudini", "Ovqatlanish va odatlar"),
    [("equilibrato", "muvozanatli"), ("porzione", "ulush"), ("integrale", "butun donli"),
     ("zuccheri aggiunti", "qo'shilgan shakar"), ("idratarsi", "suv ichmoq"), ("digiuno", "ro'za"),
     ("etichetta (alim.)", "yorliq"), ("moderazione", "me'yor"), ("rinunciare", "voz kechmoq"),
     ("sgarro", "istisno kun")],
    [("Cerco di mangiare in modo equilibrato.", "Muvozanatli ovqatlanishga harakat qilaman."),
     ("Ho ridotto gli zuccheri aggiunti.", "Qo'shilgan shakarni kamaytirdim."),
     ("Tutto con moderazione.", "Hamma narsa me'yorida."),
     ("Non voglio rinunciare completamente ai dolci.", "Shirinliklardan butunlay voz kechmoqchi emasman."),
     ("Leggo sempre le etichette.", "Doim yorliqlarni o'qiyman."),
     ("Bevo due litri d'acqua al giorno.", "Kuniga ikki litr suv ichaman.")]),
  ],
  dialogue=(("Troppo lavoro", "Ish haddan ziyod"), [
    ("Dilnoza", "Ti vedo stanchissima ultimamente.", "So'nggi paytlarda juda charchagansan."),
    ("Giulia", "Non ce la faccio più. Lavoro anche il sabato.", "Endi chidayolmayapman. Shanbada ham ishlayapman."),
    ("Dilnoza", "Se fossi in te, parlerei con il capo.", "Sening o'rningda bo'lsam, boshliq bilan gaplashardim."),
    ("Giulia", "Ho paura che lo prenda male.", "U yomon qabul qilishidan qo'rqaman."),
    ("Dilnoza", "Faresti bene a spiegare i numeri, non le emozioni.", "Tuyg'ularni emas, raqamlarni tushuntirganing ma'qul."),
    ("Giulia", "Hai ragione. Ci vuole solo un po' di coraggio.", "Haqsan. Faqat bir oz jasorat kerak."),
    ("Dilnoza", "Ce la farai. E intanto stacca almeno la domenica.", "Uddasidan chiqasan. Shu orada hech bo'lmasa yakshanbada dam ol."),
  ])),

 dict(id="b2u8", icon="graduationcap.fill", accent="red",
  title=("Studiare e lavorare all'estero", "Chet elda o'qish va ishlash"),
  subtitle=("Candidature accademiche, presentazioni, vita da expat", "Akademik ariza, taqdimot, muhojir hayoti"),
  grammar=[
    (("Lo stile accademico", "Akademik uslub"),
     ("Nei testi accademici uzbeki dominano nominalizzazioni e passivi: tahlil qilindi (è stato analizzato), o'rganish maqsad qilingan (si è inteso studiare).",
      "Akademik italyan tilida: il presente lavoro si propone di, sono stati analizzati, ne consegue che, si evince che. Birinchi shaxs kamdan-kam ishlatiladi."),
     [("Il presente lavoro si propone di…", "Ushbu ish …ni maqsad qilgan."),
      ("Ne consegue che…", "Bundan kelib chiqadiki…")]),
    (("Presentazioni orali", "Og'zaki taqdimot"),
     ("Struttura utile: Avvalo… (innanzitutto), Keyingi qismda… (nella parte successiva), Xulosa qilib aytganda… (per concludere), Savollaringiz bo'lsa… (se avete domande).",
      "Taqdimot tuzilishi: innanzitutto, passiamo ora a, come si vede dal grafico, per concludere, sono a disposizione per domande."),
     [("Come si vede dal grafico…", "Grafikdan ko'rinib turibdiki…"),
      ("Sono a disposizione per domande.", "Savollaringizga javob berishga tayyorman.")]),
  ],
  lessons=[
   ("b2u8l1", ("Candidature accademiche", "Akademik ariza"),
    [("bando", "tanlov e'loni"), ("requisiti (accad.)", "talablar"), ("lettera motivazionale", "motivatsion xat"),
     ("lettera di referenze", "tavsiyanoma"), ("piano di studi", "o'quv reja"),
     ("scadenza (bando)", "topshirish muddati"), ("ammissione", "qabul"), ("graduatoria", "reyting ro'yxati"),
     ("tassa universitaria", "o'qish to'lovi"), ("esenzione", "imtiyoz")],
    [("Ho presentato domanda per una borsa di studio.", "Stipendiya uchun ariza topshirdim."),
     ("La scadenza è il trenta aprile.", "Topshirish muddati o'ttizinchi aprel."),
     ("Sto scrivendo la lettera motivazionale.", "Motivatsion xat yozyapman."),
     ("Sono stato ammesso al master.", "Magistraturaga qabul qilindim."),
     ("Ho ottenuto l'esenzione dalle tasse.", "To'lovdan imtiyoz oldim."),
     ("Il mio nome è in graduatoria.", "Ismim reyting ro'yxatida bor.")]),
   ("b2u8l2", ("Presentare un progetto", "Loyihani taqdim etish"),
    [("presentazione", "taqdimot"), ("diapositiva", "slayd"), ("grafico", "grafik"),
     ("dati a supporto", "asoslovchi ma'lumot"), ("metodologia", "metodologiya"),
     ("limite (studio)", "cheklov"), ("conclusione", "xulosa"), ("domanda (pubblico)", "savol"),
     ("tempo a disposizione", "berilgan vaqt"), ("chiarezza", "aniqlik")],
    [("La mia presentazione dura quindici minuti.", "Taqdimotim o'n besh daqiqa davom etadi."),
     ("Come si vede dal grafico, il trend è positivo.", "Grafikdan ko'rinishicha, tendensiya ijobiy."),
     ("Ogni conclusione è sostenuta dai dati.", "Har bir xulosa ma'lumotlar bilan asoslangan."),
     ("Il principale limite dello studio è il campione.", "Tadqiqotning asosiy cheklovi — namuna hajmi."),
     ("Passiamo ora alla metodologia.", "Endi metodologiyaga o'tamiz."),
     ("Sono a disposizione per eventuali domande.", "Savollaringizga javob berishga tayyorman.")]),
   ("b2u8l3", ("Vita da expat", "Chet eldagi hayot"),
    [("trasferirsi (paese)", "boshqa davlatga ko'chmoq"), ("ambientarsi", "ko'nikmoq"),
     ("burocrazia (estero)", "byurokratiya"), ("codice fiscale", "soliq raqami"),
     ("assicurazione sanitaria", "tibbiy sug'urta"), ("alloggio", "turar joy"),
     ("rete di conoscenze", "tanishlar doirasi"), ("solitudine", "yolg'izlik"),
     ("fuso orario", "vaqt mintaqasi"), ("radici (nostalgia)", "vatan")],
    [("Mi sono trasferita a Milano sei mesi fa.", "Olti oy oldin Milanga ko'chdim."),
     ("All'inizio è stato durissimo ambientarsi.", "Avvaliga ko'nikish juda qiyin bo'ldi."),
     ("La burocrazia è stata l'ostacolo maggiore.", "Byurokratiya eng katta to'siq bo'ldi."),
     ("Il fuso orario complica le videochiamate.", "Vaqt farqi video qo'ng'iroqlarni qiyinlashtiradi."),
     ("Piano piano mi sono creata una rete di amici.", "Sekin-asta do'stlar doirasini yaratdim."),
     ("Torno a casa due volte l'anno.", "Yiliga ikki marta uyga qaytaman.")]),
   ("b2u8l4", ("Il colloquio internazionale", "Xalqaro suhbat"),
    [("punti di forza", "kuchli tomonlar"), ("punti deboli", "zaif tomonlar"),
     ("adattabilità", "moslashuvchanlik"), ("lavorare sotto pressione", "bosim ostida ishlash"),
     ("gestire un team", "jamoani boshqarish"), ("problem solving", "muammo yechish"),
     ("aspettative", "kutilmalar"), ("disponibilità a trasferirsi", "ko'chishga tayyorlik"),
     ("retribuzione", "ish haqi"), ("crescita (personale)", "shaxsiy o'sish")],
    [("Il mio punto di forza è l'adattabilità.", "Mening kuchli tomonim — moslashuvchanlik."),
     ("Lavoro bene sotto pressione.", "Bosim ostida yaxshi ishlayman."),
     ("Ho gestito un team di otto persone.", "Sakkiz kishilik jamoani boshqarganman."),
     ("Sono disponibile a trasferirmi all'estero.", "Chet elga ko'chishga tayyorman."),
     ("Quali sono le vostre aspettative per questo ruolo?", "Bu lavozimdan kutilmalaringiz qanday?"),
     ("Cerco soprattutto crescita professionale.", "Men avvalo kasbiy o'sishni izlayapman.")]),
  ],
  dialogue=(("Il colloquio finale", "Yakuniy suhbat"), [
    ("HR", "Ci parli dei suoi punti di forza.", "Kuchli tomonlaringiz haqida gapiring."),
    ("Giulia", "Direi l'adattabilità e la capacità di gestire progetti complessi.", "Moslashuvchanlik va murakkab loyihalarni boshqarish qobiliyati, deb o'ylayman."),
    ("HR", "E un punto debole?", "Zaif tomoningiz-chi?"),
    ("Giulia", "Tendo a essere troppo perfezionista, ci sto lavorando.", "Haddan ortiq mukammallikka intilaman, ustida ishlayapman."),
    ("HR", "Sarebbe disposta a trasferirsi a Tashkent?", "Toshkentga ko'chishga rozimisiz?"),
    ("Giulia", "Assolutamente sì. Parlo già un po' di uzbeko.", "Albatta. Men allaqachon bir oz o'zbekcha gapiraman."),
    ("HR", "Ottimo. Le faremo sapere entro la settimana.", "Ajoyib. Hafta ichida xabar beramiz."),
    ("Giulia", "La ringrazio per il tempo che mi ha dedicato.", "Ajratgan vaqtingiz uchun rahmat."),
  ])),
]
