# -*- coding: utf-8 -*-
# B2 — vocabulary packs, units 4-6.

EXTRA = {
 "b2u4": [
  ("Generi letterari", "Adabiy janrlar",
   [("romanzo storico", "tarixiy roman"), ("romanzo di formazione", "tarbiyaviy roman"),
    ("giallo", "detektiv"), ("fantascienza", "ilmiy fantastika"), ("saggio", "esse"),
    ("biografia", "tarjimai hol"), ("autobiografia", "avtobiografiya"), ("diario (genere)", "kundalik (janr)"),
    ("novella", "qissa"), ("poema", "doston"), ("lirica", "lirika"), ("satira", "satira"),
    ("epica", "epos"), ("tragedia", "fojia"), ("commedia", "komediya"),
    ("narrativa", "nasriy asar"), ("saggistica", "ilmiy-ommabop adabiyot"),
    ("classico (opera)", "klassik asar"), ("contemporaneo (autore)", "zamonaviy muallif"),
    ("bestseller", "eng ko'p sotilgan kitob"), ("opera prima", "ilk asar")],
   [("È un romanzo di formazione molto noto.", "Bu juda mashhur tarbiyaviy roman."),
    ("Preferisco la saggistica alla narrativa.", "Nasrga qaraganda ilmiy-ommabop adabiyotni afzal ko'raman.")]),
  ("Analizzare un testo", "Matn tahlili",
   [("trama (analisi)", "syujet (tahlil)"), ("intreccio", "voqealar bog'lanishi"),
    ("personaggio principale", "bosh qahramon (asar)"), ("personaggio secondario", "ikkinchi darajali qahramon"),
    ("narratore", "hikoyachi"), ("punto di vista (narrativo)", "hikoya nuqtai nazari"),
    ("flashback", "o'tmishga qaytish"), ("ambientazione", "voqea joyi"),
    ("tema (opera)", "asar mavzusi"), ("messaggio (opera)", "asar g'oyasi"),
    ("simbolo", "ramz"), ("allegoria", "allegoriya"), ("stile (autore)", "muallif uslubi"),
    ("registro (testo)", "matn uslubi"), ("ritmo narrativo", "hikoya sur'ati"),
    ("dialogo (testo)", "dialog (matn)"), ("monologo", "monolog"), ("finale aperto", "ochiq yakun"),
    ("colpo di scena", "kutilmagan burilish"), ("interpretazione critica", "tanqidiy talqin"),
    ("contesto storico", "tarixiy kontekst")],
   [("Il narratore è inaffidabile.", "Hikoyachiga ishonib bo'lmaydi."),
    ("Il finale è volutamente aperto.", "Yakun ataylab ochiq qoldirilgan.")]),
  ("Poesia", "She'riyat",
   [("verso", "misra"), ("strofa", "band"), ("rima", "qofiya"), ("metrica", "vazn"),
    ("immagine poetica", "she'riy obraz"), ("similitudine", "tashbeh"),
    ("personificazione", "jonlantirish"), ("musicalità", "ohangdorlik"),
    ("suono (poesia)", "tovush (she'r)"), ("silenzio (poesia)", "sukut (she'r)"),
    ("emozione (poesia)", "she'riy hissiyot"), ("ghazal", "g'azal"), ("rubai", "ruboiy"),
    ("poeta classico", "klassik shoir"), ("poesia contemporanea", "zamonaviy she'riyat"),
    ("traduzione poetica", "she'riy tarjima"), ("intraducibile", "tarjima qilib bo'lmaydigan"),
    ("recitare", "yod aytmoq"), ("declamazione", "she'rxonlik"), ("antologia", "to'plam"),
    ("verso libero", "erkin she'r")],
   [("Questa poesia è quasi intraducibile.", "Bu she'rni tarjima qilish deyarli mumkin emas."),
    ("Ha recitato a memoria un ghazal.", "U yoddan bir g'azal aytdi.")]),
  ("Il linguaggio del cinema", "Kino tili",
   [("inquadratura", "kadr"), ("primo piano", "yaqin plan"), ("campo lungo", "umumiy plan"),
    ("movimento di macchina", "kamera harakati"), ("montaggio", "montaj"),
    ("regia (lavoro)", "rejissyorlik"), ("sceneggiatore", "stsenariynavis"),
    ("fotografia (cinema)", "operatorlik ishi"), ("luce (cinema)", "yoritish"),
    ("scenografia", "dekoratsiya"), ("costumi", "liboslar (film)"), ("effetti speciali", "maxsus effektlar"),
    ("colonna sonora (b2)", "film musiqasi"), ("suono (film)", "ovoz (film)"),
    ("ritmo (film)", "film sur'ati"), ("cast", "aktyorlar tarkibi"), ("provino", "kasting"),
    ("interpretazione (attore)", "aktyor ijrosi"), ("controfigura", "dublyor"),
    ("produzione (film)", "film ishlab chiqarish"), ("distribuzione", "prokat")],
   [("Il montaggio è molto ritmato.", "Montaj juda ritmli."),
    ("La fotografia del film è splendida.", "Filmning operatorlik ishi ajoyib.")]),
  ("Recensire", "Taqriz yozish",
   [("recensione critica", "tanqidiy taqriz"), ("giudizio complessivo", "umumiy baho"),
    ("punto di forza (opera)", "kuchli jihat"), ("punto debole (opera)", "zaif jihat"),
    ("originalità", "o'ziga xoslik"), ("prevedibile", "oldindan aniq"),
    ("sorprendente", "hayratlanarli"), ("coinvolgente", "o'ziga tortadigan"),
    ("lento (ritmo)", "cho'zilgan"), ("denso", "mazmunga boy"), ("superficiale", "yuzaki"),
    ("profondo (opera)", "chuqur mazmunli"), ("sopravvalutato (b2)", "ortiqcha ulug'langan"),
    ("sottovalutato", "e'tibordan chetda qolgan"), ("consigliato", "tavsiya etiladi"),
    ("sconsigliato", "tavsiya etilmaydi"), ("adatto a", "…uchun mos"),
    ("pubblico di riferimento", "maqsadli tomoshabin"), ("spoiler", "syujetni oshkor qilish"),
    ("valutazione (voto)", "baho (ball)"), ("verdetto", "hukm (baho)")],
   [("È un film denso ma un po' lento.", "Bu mazmunga boy, lekin biroz cho'zilgan film."),
    ("Nel complesso lo considero sottovalutato.", "Umuman olganda, u e'tibordan chetda qolgan deb hisoblayman.")]),
  ("Teatro", "Teatr",
   [("palcoscenico", "sahna (teatr)"), ("sipario", "parda"), ("atto", "parda (akt)"),
    ("scena (teatro)", "ko'rinish"), ("battuta (teatro)", "replika"), ("copione", "stsenariy (teatr)"),
    ("regista teatrale", "teatr rejissyori"), ("attore protagonista", "bosh rol ijrochisi"),
    ("comparsa", "statist"), ("prova generale", "bosh mashq"), ("prima (spettacolo)", "premyera"),
    ("replica (spettacolo)", "takroriy namoyish"), ("tournée", "gastrol"),
    ("platea (teatro)", "parter"), ("galleria", "balkon (teatr)"), ("applauso finale", "yakuniy olqish"),
    ("improvvisazione", "improvizatsiya"), ("mimo", "pantomima"), ("maschera", "niqob (teatr)"),
    ("teatro sperimentale", "eksperimental teatr"), ("messa in scena", "sahnalashtirish")],
   [("La prima è andata benissimo.", "Premyera juda yaxshi o'tdi."),
    ("Gli attori hanno improvvisato una scena.", "Aktyorlar bir ko'rinishni improvizatsiya qilishdi.")]),
  ("Arti visive", "Tasviriy san'at",
   [("pittura", "rangtasvir"), ("scultura", "haykaltaroshlik"), ("disegno", "chizmachilik"),
    ("acquerello", "akvarel"), ("olio (pittura)", "moybo'yoq"), ("tela", "tuval"),
    ("pennello", "mo'yqalam"), ("prospettiva", "istiqbol (chizma)"), ("composizione (arte)", "kompozitsiya"),
    ("chiaroscuro", "soya-yorug'"), ("ritratto", "portret"), ("paesaggio (quadro)", "manzara (asar)"),
    ("natura morta", "natyurmort"), ("astratto", "abstrakt"), ("figurativo", "tasviriy"),
    ("installazione", "installyatsiya"), ("mostra personale", "shaxsiy ko'rgazma"),
    ("collettiva", "jamoaviy ko'rgazma"), ("galleria d'arte", "san'at galereyasi"),
    ("collezionista", "kolleksioner"), ("restauro (opera)", "asarni tiklash")],
   [("Preferisco l'arte astratta.", "Men abstrakt san'atni afzal ko'raman."),
    ("La mostra personale apre giovedì.", "Shaxsiy ko'rgazma payshanba kuni ochiladi.")]),
  ("Musica in profondità", "Musiqa haqida chuqurroq",
   [("compositore", "bastakor"), ("direttore d'orchestra", "dirijyor"), ("spartito", "nota"),
    ("armonia", "garmoniya"), ("melodia (b2)", "kuy (b2)"), ("tonalità", "tonallik"),
    ("improvvisazione (musica)", "musiqiy improvizatsiya"), ("virtuoso", "virtuoz"),
    ("interpretazione (musica)", "ijro talqini"), ("repertorio", "repertuar"),
    ("classica (musica)", "klassik musiqa"), ("folk", "xalq musiqasi"),
    ("maqom", "maqom"), ("strumento a corda", "torli cholg'u"),
    ("strumento a fiato", "puflama cholg'u"), ("percussioni", "urma cholg'ular"),
    ("acustica", "akustika"), ("registrazione in studio", "studiyada yozish"),
    ("produttore musicale", "musiqiy prodyuser"), ("diritti d'autore", "mualliflik huquqi"),
    ("streaming musicale", "musiqa oqimi")],
   [("Il maqom è un repertorio classico uzbeko.", "Maqom — o'zbek klassik repertuari."),
    ("L'acustica della sala è eccellente.", "Zalning akustikasi a'lo darajada.")]),
  ("Il mercato della cultura", "Madaniyat bozori",
   [("editore", "noshir"), ("casa editrice", "nashriyot"), ("tiratura", "nashr adadi"),
    ("diritti di traduzione", "tarjima huquqlari"), ("agente letterario", "adabiy agent"),
    ("anticipo (editoria)", "avans"), ("royalty", "muallif hissasi"),
    ("fiera del libro", "kitob ko'rgazmasi"), ("premio letterario", "adabiy mukofot"),
    ("recensione sui giornali", "matbuotdagi taqriz"), ("passaparola (cultura)", "og'zaki tavsiya"),
    ("pubblico di nicchia", "tor doiradagi auditoriya"), ("grande pubblico", "keng ommaviy auditoriya"),
    ("finanziamento pubblico (cultura)", "madaniyatga davlat yordami"), ("sponsor", "homiy"),
    ("biglietteria", "kassa (tomosha)"), ("incasso", "tushum (tomosha)"),
    ("piattaforma di streaming", "oqim platformasi"), ("pirateria", "qaroqchilik (nusxa)"),
    ("industria culturale", "madaniyat sanoati"), ("politica culturale", "madaniyat siyosati")],
   [("Il libro ha vinto un premio letterario.", "Kitob adabiy mukofotni qo'lga kiritdi."),
    ("La pirateria danneggia gli autori.", "Qaroqchilik mualliflarga zarar keltiradi.")]),
  ("Il gusto e la critica", "Did va tanqid",
   [("gusto personale", "shaxsiy did"), ("canone", "adabiy me'yor"), ("moda (tendenza)", "modaga aylangan"),
    ("kitsch", "did buzuqligi"), ("avanguardia", "avangard"), ("tradizione (arte)", "an'ana (san'at)"),
    ("rottura", "an'anani buzish"), ("influenza (artistica)", "ta'sir (ijodiy)"),
    ("citazione (arte)", "iqtibos (san'atda)"), ("omaggio", "ehtirom (asar)"),
    ("imitazione", "taqlid"), ("plagio (arte)", "o'zlashtirish (asar)"),
    ("autenticità", "haqqoniylik"), ("provocazione", "chaqiriq (san'atda)"),
    ("scandalo", "janjal (san'at)"), ("censura (arte)", "taqiq (san'at)"),
    ("libertà artistica", "ijod erkinligi"), ("interpretazione soggettiva", "sub'ektiv talqin"),
    ("consenso della critica", "tanqidchilar fikri"), ("successo di pubblico", "omma e'tirofi"),
    ("riscoperta", "qayta kashf etilish")],
   [("È un omaggio evidente a un classico.", "Bu klassikaga ochiq ehtirom."),
    ("Ha avuto successo di pubblico ma non di critica.", "U omma e'tirofini oldi, lekin tanqidchilarnikini emas.")]),
 ],

 "b2u5": [
  ("Migrazione", "Migratsiya",
   [("flusso migratorio", "migratsiya oqimi"), ("paese d'origine", "kelib chiqqan davlat"),
    ("paese d'accoglienza", "qabul qiluvchi davlat"), ("permesso di lavoro", "ishlash ruxsatnomasi"),
    ("ricongiungimento familiare", "oila birlashuvi"), ("rifugiato", "qochqin"),
    ("richiedente asilo", "boshpana so'rovchi"), ("protezione internazionale", "xalqaro himoya"),
    ("frontiera (b2)", "davlat chegarasi"), ("rimpatrio", "vatanga qaytarish"),
    ("rimessa (soldi)", "vatanga pul jo'natish"), ("diaspora", "diaspora"),
    ("seconda generazione", "ikkinchi avlod"), ("integrazione linguistica", "til orqali moslashuv"),
    ("riconoscimento del titolo", "diplomni tan olish"), ("lavoro sottoqualificato", "malakadan past ish"),
    ("discriminazione (lavoro)", "ishda kamsitish"), ("xenofobia", "begonaga dushmanlik"),
    ("accoglienza (politica)", "qabul qilish siyosati"), ("cittadinanza (ottenere)", "fuqarolik olish"),
    ("appartenenza (b2)", "mansublik hissi")],
   [("Le rimesse sostengono molte famiglie.", "Vatanga jo'natilgan pul ko'p oilani boqadi."),
    ("Il riconoscimento del titolo richiede tempo.", "Diplomni tan olish vaqt talab qiladi.")]),
  ("Istruzione", "Ta'lim tizimi",
   [("sistema educativo", "ta'lim tizimi"), ("obbligo scolastico", "majburiy ta'lim"),
    ("dispersione scolastica", "o'qishni tashlab ketish"), ("didattica", "o'qitish metodikasi"),
    ("programma (scuola)", "o'quv dasturi"), ("valutazione (studenti)", "o'quvchilarni baholash"),
    ("esame di maturità", "attestat imtihoni"), ("orientamento", "kasb tanlashga yo'naltirish"),
    ("formazione professionale", "kasb-hunar ta'limi"), ("università pubblica", "davlat universiteti"),
    ("ateneo privato", "xususiy oliygoh"), ("retta", "o'qish to'lovi"),
    ("borsa di studio (b2)", "stipendiya (grant)"), ("merito (studio)", "iqtidor"),
    ("classe numerosa", "katta sinf"), ("rapporto docenti-studenti", "o'qituvchi-talaba nisbati"),
    ("aggiornamento dei docenti", "o'qituvchilar malakasini oshirish"),
    ("didattica a distanza", "masofaviy ta'lim"), ("divario digitale", "raqamli tafovut"),
    ("inclusione scolastica", "inklyuziv ta'lim"), ("riforma della scuola", "ta'lim islohoti")],
   [("La dispersione scolastica è calata.", "O'qishni tashlab ketish kamaydi."),
    ("Il divario digitale penalizza le zone rurali.", "Raqamli tafovut qishloqlarga zarar qiladi.")]),
  ("Giustizia", "Adliya",
   [("codice penale", "jinoyat kodeksi"), ("codice civile", "fuqarolik kodeksi"),
    ("reato", "jinoyat"), ("imputato", "ayblanuvchi"), ("pubblico ministero", "prokuror"),
    ("difesa (legale)", "himoya (sudda)"), ("giudice", "sudya"), ("giuria", "hakamlar hay'ati"),
    ("prova (giudiziaria)", "isbot (sud)"), ("testimone (b2)", "guvoh (sud)"),
    ("indagine", "tergov"), ("arresto", "hibsga olish"), ("custodia cautelare", "ehtiyot chorasi"),
    ("processo (giudiziario)", "sud jarayoni"), ("assoluzione", "oqlov"),
    ("condanna", "hukm (jazo)"), ("pena", "jazo muddati"), ("libertà condizionale", "shartli ozodlik"),
    ("ricorso in appello", "apellyatsiya shikoyati"), ("prescrizione", "muddatning o'tishi"),
    ("presunzione d'innocenza", "aybsizlik prezumpsiyasi")],
   [("Vale la presunzione d'innocenza.", "Aybsizlik prezumpsiyasi amal qiladi."),
    ("L'imputato è stato assolto.", "Ayblanuvchi oqlandi.")]),
  ("Media e potere", "Media va hokimiyat",
   [("libertà di informazione", "axborot erkinligi"), ("pluralismo", "plyuralizm"),
    ("editore (media)", "media egasi"), ("linea editoriale", "tahririyat yo'nalishi"),
    ("agenda setting", "mavzuni belgilash"), ("titolo a effetto", "ta'sirchan sarlavha"),
    ("clickbait", "bosishga undovchi sarlavha"), ("fonte anonima", "anonim manba"),
    ("inchiesta", "jurnalistik tekshiruv"), ("whistleblower", "oshkor qiluvchi"),
    ("segreto professionale", "kasbiy sir"), ("querela", "da'vo (tuhmat)"),
    ("diffamazione", "tuhmat"), ("rettifica", "tuzatish (nashr)"), ("autocensura", "o'z-o'zini cheklash"),
    ("propaganda di stato", "davlat targ'iboti"), ("controinformazione", "muqobil axborot"),
    ("bolla informativa", "axborot pufagi"), ("polarizzazione (b2)", "qutblanish (b2)"),
    ("alfabetizzazione mediatica", "media savodxonlik"), ("responsabilità editoriale", "tahririy javobgarlik")],
   [("L'inchiesta ha avuto grande impatto.", "Tekshiruv katta ta'sir ko'rsatdi."),
    ("Il pluralismo dell'informazione è fondamentale.", "Axborot plyuralizmi juda muhim.")]),
  ("Politica", "Siyosat",
   [("democrazia", "demokratiya"), ("costituzione", "konstitutsiya"), ("parlamento", "parlament"),
    ("governo", "hukumat"), ("opposizione", "muxolifat"), ("maggioranza", "ko'pchilik"),
    ("coalizione", "koalitsiya"), ("partito", "partiya"), ("programma elettorale", "saylovoldi dasturi"),
    ("campagna elettorale", "saylov kampaniyasi"), ("astensione", "saylovga bormaslik"),
    ("affluenza", "saylovchilar faolligi"), ("riforma (politica)", "islohot (siyosiy)"),
    ("legge di bilancio", "byudjet qonuni"), ("decreto", "farmon"), ("emendamento", "tuzatish (qonun)"),
    ("dibattito parlamentare", "parlament muhokamasi"), ("fiducia (governo)", "ishonch (hukumatga)"),
    ("corruzione (b2)", "korrupsiya (b2)"), ("trasparenza pubblica", "davlat shaffofligi"),
    ("partecipazione civica", "fuqarolik ishtiroki")],
   [("Il governo ha ottenuto la fiducia.", "Hukumat ishonch oldi."),
    ("L'affluenza alle urne è stata bassa.", "Saylovchilar faolligi past bo'ldi.")]),
  ("Popolazione", "Aholi",
   [("demografia", "demografiya"), ("natalità", "tug'ilish darajasi"), ("mortalità (b2)", "o'lim ko'rsatkichi"),
    ("invecchiamento", "aholining qarishi"), ("età media", "o'rtacha yosh"),
    ("speranza di vita", "umr ko'rish davomiyligi"), ("crescita demografica", "aholi o'sishi"),
    ("calo demografico", "aholi kamayishi"), ("densità (popolazione)", "aholi zichligi (b2)"),
    ("urbanizzazione", "urbanizatsiya"), ("spopolamento", "aholining ketib qolishi"),
    ("famiglia numerosa", "ko'p bolali oila"), ("nucleo familiare", "oila birligi"),
    ("censimento", "aholi ro'yxati"), ("previsione demografica", "demografik bashorat"),
    ("forza lavoro futura", "kelajakdagi ishchi kuchi"), ("sistema pensionistico", "pensiya tizimi"),
    ("sostenibilità sociale", "ijtimoiy barqarorlik"), ("politiche familiari", "oila siyosati"),
    ("congedo retribuito", "haq to'lanadigan ta'til"), ("asilo nido", "yaslilar")],
   [("L'invecchiamento pesa sul sistema pensionistico.", "Aholining qarishi pensiya tizimiga yuk bo'lmoqda."),
    ("Il censimento si fa ogni dieci anni.", "Aholi ro'yxati har o'n yilda o'tkaziladi.")]),
  ("Città e società", "Shahar va jamiyat",
   [("quartiere popolare", "oddiy xalq mahallasi"), ("gentrificazione", "mahallaning qimmatlashuvi"),
    ("speculazione edilizia", "qurilish chayqovchiligi"), ("edilizia popolare", "ijtimoiy uy-joy"),
    ("affitto insostenibile", "ko'tarib bo'lmas ijara"), ("sfratto", "uydan chiqarish"),
    ("periferia (sociale)", "chekka hudud (ijtimoiy)"), ("servizi essenziali", "asosiy xizmatlar"),
    ("trasporto pubblico (b2)", "jamoat transporti (b2)"), ("mobilità dolce", "yengil transport"),
    ("sicurezza urbana", "shahar xavfsizligi"), ("vivibilità", "yashash qulayligi"),
    ("spazio condiviso", "umumiy makon"), ("centro sociale", "ijtimoiy markaz"),
    ("biblioteca di quartiere", "mahalla kutubxonasi"), ("associazionismo", "uyushmalar faoliyati"),
    ("partecipazione dal basso", "quyidan tashabbus"), ("bilancio partecipativo", "ishtirokchi byudjet"),
    ("degrado urbano", "shahar qarovsizligi"), ("riqualificazione urbana", "shaharni obodonlashtirish"),
    ("identità di quartiere", "mahalla o'ziga xosligi")],
   [("La gentrificazione ha cambiato il quartiere.", "Mahalla qimmatlashib, o'zgarib ketdi."),
    ("Serve più edilizia popolare.", "Ko'proq ijtimoiy uy-joy kerak.")]),
  ("Convivenza e valori", "Birga yashash va qadriyatlar",
   [("laicità", "dunyoviylik"), ("libertà religiosa", "din erkinligi"), ("credente", "dindor"),
    ("non credente", "dinga e'tiqod qilmaydigan"), ("tolleranza", "bag'rikenglik"),
    ("intolleranza", "murosasizlik"), ("dialogo interculturale", "madaniyatlararo muloqot"),
    ("pluralismo culturale", "madaniy rang-baranglik"), ("valori condivisi", "umumiy qadriyatlar"),
    ("norma sociale", "ijtimoiy me'yor"), ("convenzione", "odat-qoida"),
    ("tradizione e modernità", "an'ana va zamonaviylik"), ("ruolo della donna", "ayolning o'rni"),
    ("parità (b2)", "tenglik (b2)"), ("generazioni a confronto", "avlodlar farqi"),
    ("rispetto delle minoranze", "ozchiliklarga hurmat"), ("coesione sociale", "ijtimoiy jipslik"),
    ("senso civico", "fuqarolik ongi"), ("bene pubblico", "umumiy mol-mulk"),
    ("responsabilità individuale", "shaxsiy javobgarlik"), ("solidarietà intergenerazionale", "avlodlararo hamjihatlik")],
   [("La coesione sociale si costruisce ogni giorno.", "Ijtimoiy jipslik har kuni quriladi."),
    ("Il dialogo interculturale è essenziale.", "Madaniyatlararo muloqot juda zarur.")]),
  ("Sicurezza e rischi", "Xavfsizlik va tahdidlar",
   [("prevenzione (rischi)", "xavflarni oldini olish"), ("protezione civile", "fuqaro muhofazasi"),
    ("calamità naturale", "tabiiy ofat"), ("terremoto", "zilzila"), ("evacuazione", "evakuatsiya"),
    ("piano di emergenza", "favqulodda reja"), ("allarme", "ogohlantirish signali"),
    ("soccorso", "qutqaruv"), ("volontari (emergenza)", "qutqaruv ko'ngillilari"),
    ("danno (materiale)", "moddiy zarar"), ("ricostruzione", "qayta qurish"),
    ("criminalità", "jinoyatchilik"), ("furto (reato)", "o'g'rilik (jinoyat)"),
    ("truffa (reato)", "firibgarlik (jinoyat)"), ("sicurezza informatica", "kiberxavfsizlik"),
    ("attacco informatico", "kiberhujum"), ("dati sensibili", "nozik ma'lumotlar"),
    ("videosorveglianza", "videokuzatuv"), ("privacy vs sicurezza", "maxfiylik va xavfsizlik"),
    ("percezione del rischio", "xavfni his qilish"), ("cultura della sicurezza", "xavfsizlik madaniyati")],
   [("Il piano di emergenza ha funzionato.", "Favqulodda reja ishladi."),
    ("Gli attacchi informatici sono aumentati.", "Kiberhujumlar ko'paydi.")]),
  ("Il mondo insieme", "Dunyo birgalikda",
   [("organizzazione internazionale", "xalqaro tashkilot"), ("trattato", "shartnoma (xalqaro)"),
    ("diplomazia", "diplomatiya"), ("ambasciata", "elchixona"), ("consolato", "konsullik"),
    ("visto (documento)", "viza (hujjat)"), ("cooperazione", "hamkorlik (xalqaro)"),
    ("aiuto umanitario", "insonparvarlik yordami"), ("sviluppo sostenibile", "barqaror rivojlanish"),
    ("obiettivi globali", "global maqsadlar"), ("sanzione (internazionale)", "xalqaro sanksiya"),
    ("conflitto armato", "qurolli mojaro"), ("negoziato di pace", "tinchlik muzokarasi"),
    ("tregua", "sulh"), ("missione di pace", "tinchlikparvar missiya"),
    ("diritti umani", "inson huquqlari"), ("corte internazionale", "xalqaro sud"),
    ("globalizzazione", "globallashuv"), ("interdipendenza", "o'zaro bog'liqlik"),
    ("catena globale del valore", "global qiymat zanjiri"), ("multilateralismo", "ko'p tomonlamalik")],
   [("I negoziati di pace sono ripresi.", "Tinchlik muzokaralari qayta boshlandi."),
    ("La globalizzazione ha effetti contrastanti.", "Globallashuvning ta'siri qarama-qarshi.")]),
 ],

 "b2u6": [
  ("Modi di dire con il corpo", "Tana bilan bog'liq iboralar",
   [("avere le mani in pasta", "hamma ishga aralashmoq"), ("mettere una mano sul fuoco", "kafolat bermoq"),
    ("costare un occhio (b2)", "juda qimmatga tushmoq"), ("avere la testa dura", "qaysar bo'lmoq"),
    ("perdere la testa", "boshini yo'qotmoq"), ("essere tutt'orecchi", "diqqat bilan tinglamoq"),
    ("chiudere un occhio", "ko'z yummoq"), ("avere la lingua lunga", "ko'p gapiradigan bo'lmoq"),
    ("mordersi la lingua", "tilini tishlamoq"), ("a occhio e croce", "chamalab (taxminan)"),
    ("dare una mano (b2)", "yelka tutmoq"), ("stringere i denti", "tishni tishga qo'ymoq"),
    ("alzare le mani", "qo'l ko'tarmoq (taslim)"), ("avere il cuore in gola", "yuragi hapriqmoq"),
    ("prendere di petto", "yuzma-yuz hal qilmoq"), ("voltare le spalle", "yuz o'girmoq"),
    ("camminare sulle uova", "ehtiyot bo'lib qadam bosmoq"), ("essere di manica larga", "kechirimli bo'lmoq"),
    ("a braccia aperte", "quchoq ochib"), ("con le mani legate", "qo'li bog'langan holda"),
    ("a testa alta", "boshini baland tutib")],
   [("Ci ho messo la mano sul fuoco.", "Men unga kafolat bergandim."),
    ("Ci ha accolti a braccia aperte.", "U bizni quchoq ochib kutib oldi.")]),
  ("Modi di dire con gli animali", "Hayvonlar bilan iboralar",
   [("essere un pesce fuor d'acqua", "o'zini begona his qilmoq"), ("prendere due piccioni", "bir o'q bilan ikki quyon"),
    ("avere una fame da lupi", "juda qorni ochmoq"), ("essere una volpe", "ayyor bo'lmoq"),
    ("fare il pesce in barile", "befarq ko'rinmoq"), ("essere un asino", "o'qishga uquvsiz bo'lmoq"),
    ("avere un cane sciolto", "yolg'iz ish qilmoq"), ("mosca bianca", "kamyob hodisa"),
    ("pecora nera", "oilaning tanbali"), ("dormire come un ghiro", "o'lik uyqu"),
    ("essere un coniglio", "qo'rqoq bo'lmoq"), ("furbo come una volpe", "tulkidek ayyor"),
    ("lento come una lumaca", "toshbaqadek sekin"), ("libero come un uccello", "qushdek erkin"),
    ("testardo come un mulo", "eshakdek qaysar"), ("sano come un pesce", "buqadek sog'lom"),
    ("in bocca al lupo (b2)", "ishing o'ngidan kelsin"), ("cane che abbaia non morde", "hurgan it qopmas"),
    ("cavallo di battaglia", "eng kuchli tomoni"), ("la gatta frettolosa", "shoshgan ish"),
    ("gettare perle ai porci", "qadrini bilmasga bermoq")],
   [("Ho una fame da lupi!", "Qornim juda och!"),
    ("È il suo cavallo di battaglia.", "Bu uning eng kuchli tomoni.")]),
  ("Modi di dire con il cibo", "Ovqat bilan iboralar",
   [("andare a fagioli", "ko'ngildagidek bo'lmoq"), ("essere pane e cacio", "juda apoq-chapoq"),
    ("buono come il pane", "juda yaxshi odam"), ("avere la botte piena", "ikkalasini birga xohlamoq"),
    ("far venire l'acquolina", "og'zini suvini keltirmoq"), ("essere una pizza", "juda zerikarli"),
    ("rendere pan per focaccia", "qarzini qaytarmoq"), ("cadere a fagiolo", "aynan o'z vaqtida"),
    ("bere come una spugna", "ko'p ichmoq"), ("essere il sale della terra", "eng qadrli odam"),
    ("mettere il carico da novanta", "ustiga ustak"), ("come il cacio sui maccheroni", "juda mos tushmoq"),
    ("avere fegato", "jur'ati bo'lmoq"), ("far bollire in pentola", "ish pishirmoq"),
    ("essere uno zuccone", "o'jar bo'lmoq"), ("non essere farina del tuo sacco", "o'z bilganing emas"),
    ("tutto fa brodo", "har narsa asqotadi"), ("a tavola non si invecchia", "dasturxonda vaqt sezilmaydi"),
    ("chi dorme non piglia pesci", "uxlagan omad topmas"), ("l'appetito vien mangiando", "ishtaha ovqat bilan keladi"),
    ("meglio un uovo oggi", "bugungi tuxum yaxshi")],
   [("Quell'invito è caduto a fagiolo.", "O'sha taklif aynan o'z vaqtida keldi."),
    ("Sono pane e cacio da anni.", "Ular yillardan beri apoq-chapoq.")]),
  ("Parlato quotidiano", "Kundalik og'zaki nutq",
   [("roba da matti", "aqlga sig'maydi"), ("che casino", "qanday tartibsizlik"),
    ("un casino di", "juda ko'p (og'zaki)"), ("sto morendo (di fame)", "o'lay deyapman"),
    ("da paura", "zo'r (og'zaki)"), ("una cifra", "juda ko'p (miqdor)"),
    ("tipo (circa)", "shunaqa-da"), ("nel senso che", "ya'ni shuki"),
    ("vabbè", "mayli-da"), ("boh (non so)", "kim biladi"), ("magari! (desiderio)", "koshki edi!"),
    ("figurati (nessun problema)", "arzimaydi-da"), ("dai su", "qani endi"),
    ("ma va'", "qo'ysang-chi"), ("non ci penso proprio", "xayolimga ham kelmaydi"),
    ("me ne frego", "menga farqi yo'q"), ("che palle (b2)", "zerikarli-ya"),
    ("alla grande", "zo'r ketyapti"), ("alla buona", "oddiygina"), ("all'ultimo", "oxirgi daqiqada"),
    ("in un attimo", "bir zumda")],
   [("C'era un casino di gente.", "Juda ko'p odam bor edi."),
    ("Vabbè, ne parliamo domani.", "Mayli-da, ertaga gaplashamiz.")]),
  ("Ironia e umorismo", "Kinoya va yumor",
   [("battuta pungente", "zaharxanda hazil"), ("umorismo nero", "qora yumor"),
    ("presa in giro", "masxara"), ("scherzo pesante", "og'ir hazil"),
    ("fare il simpatico", "o'zini shirin ko'rsatmoq"), ("prendersi in giro da soli", "o'zini o'zi hazil qilmoq"),
    ("non fa ridere", "kulgili emas"), ("fuori luogo", "o'rinsiz"),
    ("tempismo", "hazilning payti"), ("doppio senso (b2)", "ikki ma'noli gap"),
    ("gioco di parole", "so'z o'yini"), ("freddura", "quruq hazil"),
    ("risata contagiosa", "yuqumli kulgi"), ("sorriso forzato", "sun'iy tabassum"),
    ("sarcasmo (b2)", "achchiq kesatiq"), ("ironia sottile", "nozik kinoya"),
    ("capire l'antifona", "ishorani tushunmoq"), ("stare al gioco", "hazilga hamroh bo'lmoq"),
    ("offendersi facilmente", "tez xafa bo'lmoq"), ("saperci ridere su", "kulib qo'ya olmoq"),
    ("autoironia (b2)", "o'ziga kulish")],
   [("È stata una battuta fuori luogo.", "Bu o'rinsiz hazil bo'ldi."),
    ("Bisogna saperci ridere su.", "Bunga kulib qo'ya olish kerak.")]),
  ("Registro alto", "Yuqori uslub",
   [("codesto", "mazkur"), ("altresì", "shuningdek"), ("nondimeno", "shunga qaramasdan"),
    ("affinché", "toki"), ("onde evitare", "oldini olish maqsadida"),
    ("in virtù di", "…kuchi bilan"), ("a fronte di", "…ga nisbatan"),
    ("previa autorizzazione", "oldindan ruxsat bilan"), ("ove possibile", "imkon qadar"),
    ("de facto", "amalda"), ("de iure", "qonunan"), ("in primis", "eng avvalo"),
    ("a posteriori", "keyingi tajribadan"), ("a priori", "oldindan"),
    ("status quo", "mavjud holat"), ("iter", "jarayon tartibi"), ("prassi", "amaliyot (odat)"),
    ("consuetudine", "urf-odat (huquqiy)"), ("competenza (giuridica)", "vakolat doirasi"),
    ("ratificare", "ratifikatsiya qilmoq"), ("deliberare", "qaror qabul qilmoq")],
   [("La commissione ha deliberato all'unanimità.", "Komissiya bir ovozdan qaror qabul qildi."),
    ("Onde evitare equivoci, mettiamolo per iscritto.", "Tushunmovchilik oldini olish uchun yozma qilaylik.")]),
  ("Dire le cose con garbo", "Gapni odob bilan aytish",
   [("eufemismo", "yumshatib aytish"), ("giro di parole (b2)", "aylanma ifoda"),
    ("con tutto il rispetto", "hurmat bilan aytganda"), ("se posso permettermi", "ruxsat bersangiz"),
    ("non vorrei sbagliarmi", "adashmasam"), ("mi permetta di dire", "aytishga izn bering"),
    ("temo che", "afsuski, shekilli"), ("purtroppo devo", "afsuski, majburman"),
    ("non è proprio così", "unchalik unday emas"), ("diciamo che", "aytaylik"),
    ("in un certo senso", "ma'lum ma'noda"), ("più o meno (b2)", "u yoki bu darajada"),
    ("non del tutto", "to'liq emas"), ("forse converrebbe", "ehtimol ma'qulroq"),
    ("sarebbe opportuno", "maqsadga muvofiq bo'lardi"), ("le dispiacerebbe", "malol kelmasa"),
    ("se non le è di disturbo", "bezovta qilmasa"), ("la ringrazio per la pazienza", "sabringiz uchun rahmat"),
    ("mi scuso per il disagio", "noqulaylik uchun uzr"), ("resto a disposizione", "xizmatga tayyorman"),
    ("in attesa di riscontro", "javobingizni kutib")],
   [("Con tutto il rispetto, non sono d'accordo.", "Hurmat bilan aytganda, rozi emasman."),
    ("Resto a disposizione per chiarimenti.", "Izoh uchun xizmatga tayyorman.")]),
  ("Rafforzare e attenuare", "Kuchaytirish va yumshatish",
   [("assolutamente (b2)", "mutlaqo (b2)"), ("decisamente", "qat'iyan"), ("estremamente", "nihoyatda"),
    ("particolarmente", "ayniqsa"), ("notevolmente", "sezilarli darajada"),
    ("leggermente", "sal"), ("appena appena", "arang"), ("piuttosto (b2)", "ancha-muncha"),
    ("relativamente", "nisbatan"), ("tendenzialmente (b2)", "asosan"),
    ("sostanzialmente", "mohiyatan"), ("praticamente", "amalda deyarli"),
    ("quasi del tutto", "deyarli butunlay"), ("neanche un po'", "zarracha ham"),
    ("affatto (b2)", "aslo (b2)"), ("del tutto (b2)", "tamomila"),
    ("a malapena", "zo'rg'a"), ("più che altro", "ko'proq"), ("se non addirittura", "hatto shu darajada"),
    ("per lo meno", "hech qursa"), ("ben oltre", "ancha ortiq")],
   [("È estremamente complicato.", "Bu nihoyatda murakkab."),
    ("Non mi convince neanche un po'.", "Meni zarracha ham ishontirmayapti.")]),
  ("Connettivi del parlato", "Og'zaki bog'lovchilar",
   [("insomma (riassumere)", "xullas kalom"), ("comunque (cambio tema)", "xo'sh, mayli"),
    ("a proposito", "aytgancha"), ("tra l'altro", "aytmoqchi"), ("piuttosto che", "…dan ko'ra"),
    ("anziché", "o'rniga"), ("tanto (rassegnazione)", "baribir"), ("almeno (b2)", "hech bo'lmasa"),
    ("del resto", "qolaversa"), ("in fondo (b2)", "aslida"), ("dopotutto", "axir"),
    ("guarda caso", "qiziq tasodif"), ("chissà", "kim bilsin"), ("sinceramente (b2)", "ochig'i"),
    ("onestamente", "rostini aytsam"), ("francamente", "to'g'risini aytganda"),
    ("a dire il vero", "haqiqatni aytsam"), ("in effetti", "darvoqe"),
    ("sta di fatto che", "gap shundaki"), ("il punto è che", "asosiysi shuki"),
    ("morale", "xullasi kalom")],
   [("A proposito, hai visto Aziz?", "Aytgancha, Azizni ko'rdingmi?"),
    ("Il punto è che non abbiamo tempo.", "Asosiysi shuki, vaqtimiz yo'q.")]),
  ("Proverbi e saggezza", "Maqollar va hikmat",
   [("chi va piano va sano", "shoshgan qizga er topilmas"), ("meglio tardi che mai", "kech bo'lsa ham"),
    ("tra il dire e il fare", "gap bilan ish orasida"), ("non è tutto oro", "yaltiragan oltin emas"),
    ("l'unione fa la forza", "birlikda kuch bor"), ("chi cerca trova", "izlagan topadi"),
    ("ride bene chi ride ultimo", "oxirida kulgan yaxshi kuladi"),
    ("l'abito non fa il monaco", "kiyim odamni belgilamaydi"),
    ("una rondine non fa primavera", "bir gul bahor keltirmas"),
    ("chi semina vento", "shamol ekkan"), ("aiutati che il ciel ti aiuta", "harakatda barakat"),
    ("occhio non vede", "ko'z ko'rmasa"), ("paese che vai, usanza che trovi", "har yurtning o'z odati"),
    ("il tempo è galantuomo", "vaqt haqiqatni ko'rsatadi"), ("chi tace acconsente", "sukut alomati rizo"),
    ("a caval donato", "sovg'a otning tishiga qaralmaydi"),
    ("batti il ferro finché è caldo", "temirni qizig'ida bos"),
    ("chi fa da sé fa per tre", "o'zi qilgan ish puxta"),
    ("rosso di sera bel tempo si spera", "kechki shafaq — yaxshi havo"),
    ("non tutti i mali vengono per nuocere", "har ishda hikmat bor"),
    ("chi ben comincia è a metà dell'opera", "yaxshi boshlangan ish yarim bitgan")],
   [("Batti il ferro finché è caldo.", "Temirni qizig'ida bos."),
    ("L'unione fa la forza.", "Birlikda kuch bor.")]),
 ],
}
