# -*- coding: utf-8 -*-
# B1 — vocabulary packs, units 1-4 (CEFR band 2000-5000 cumulative words).

EXTRA = {
 "b1u1": [
  ("Verbi dell'opinione", "Fikr fe'llari",
   [("affermare", "ta'kidlab aytmoq"), ("negare", "inkor etmoq"), ("supporre", "faraz qilmoq"),
    ("immaginare", "tasavvur qilmoq"), ("considerare", "hisobga olmoq"), ("valutare", "baholamoq"),
    ("riconoscere", "e'tirof etmoq"), ("insistere", "qat'iy turmoq"), ("precisare", "aniqlik kiritmoq"),
    ("sottolineare", "alohida ta'kidlamoq"), ("aggiungere (dire)", "qo'shimcha aytmoq"),
    ("ripetere (concetto)", "qaytarib aytmoq"), ("riassumere (dire)", "qisqacha bayon qilmoq"),
    ("concludere (dire)", "yakunlamoq"), ("proporre (idea)", "g'oya taklif qilmoq"),
    ("suggerire", "maslahat bermoq"), ("criticare", "tanqid qilmoq"),
    ("difendere (idea)", "himoya qilmoq (fikrni)"), ("giustificare", "asoslab bermoq"),
    ("chiarire (posizione)", "oydinlashtirmoq"), ("interpretare", "talqin qilmoq")],
   [("Vorrei sottolineare un punto.", "Bir jihatni alohida ta'kidlamoqchiman."),
    ("Non nego che sia difficile.", "Qiyinligini inkor etmayman.")]),
  ("Accordo e disaccordo", "Rozilik va e'tiroz",
   [("essere d'accordo (form.)", "rozilik bildirmoq"), ("condividere un'idea", "fikrga qo'shilmoq"),
    ("dissentire", "rozi bo'lmaslik"), ("obiezione (fare)", "e'tiroz bildirish"),
    ("punto di vista opposto", "qarama-qarshi qarash"), ("compromesso (trovare)", "murosaga kelmoq"),
    ("mediare", "vositachilik qilmoq"), ("convincersi", "ishonch hosil qilmoq"),
    ("restare della propria idea", "o'z fikrida qolmoq"), ("cambiare posizione", "qarashini o'zgartirmoq"),
    ("parzialmente", "qisman ravishda"), ("totalmente", "butunlay"),
    ("in linea di massima", "umuman olganda"), ("in teoria", "nazariy jihatdan"),
    ("in pratica", "amalda"), ("dal mio punto di vista", "mening nazarimda"),
    ("a differenza di", "…dan farqli o'laroq"), ("allo stesso modo", "xuddi shu tarzda"),
    ("al contrario di", "…ning aksincha"), ("d'altra parte", "boshqa tomondan"),
    ("comunque (concessione)", "har holda")],
   [("Su questo punto dissento.", "Bu masalada rozi emasman."),
    ("In teoria sì, in pratica no.", "Nazariy jihatdan ha, amalda yo'q.")]),
  ("Certezza e dubbio", "Ishonch va shubha",
   [("certo (sicuro)", "aniq"), ("probabile", "ehtimol tutilgan"), ("improbabile", "ehtimoldan yiroq"),
    ("possibile (agg.)", "bo'lishi mumkin bo'lgan"), ("impossibile (agg.)", "amalga oshmaydigan"),
    ("evidente", "ayon"), ("discutibile (b1)", "munozarali"), ("incerto", "noaniq"),
    ("presumibilmente", "taxminan aytganda"), ("senza dubbio", "shubhasiz"),
    ("forse (formale)", "ehtimol"), ("magari (dubbio)", "balkim"),
    ("dipende (risposta)", "vaziyatga qarab"), ("non necessariamente", "shart emas"),
    ("in ogni caso (b1)", "qanday bo'lmasin"), ("a quanto pare", "ko'rinishidan"),
    ("secondo alcuni", "ba'zilarning fikricha"), ("si dice che", "aytishlaricha"),
    ("sembra che", "shunday tuyuladi"), ("risulta che", "ma'lum bo'lishicha"),
    ("è chiaro che", "aniqki")],
   [("È probabile che piova.", "Yomg'ir yog'ishi ehtimoldan yiroq emas."),
    ("A quanto pare hanno deciso.", "Ko'rinishidan, ular qaror qilishibdi.")]),
  ("Argomenti e prove", "Dalil va isbot",
   [("tesi (idea)", "asosiy fikr"), ("argomento forte", "kuchli dalil"), ("argomento debole", "zaif dalil"),
    ("prova concreta", "aniq isbot"), ("esempio pratico", "amaliy misol"), ("dato (numero)", "raqamli ma'lumot"),
    ("statistica", "statistika"), ("percentuale", "foiz ko'rsatkichi"), ("ricerca (indagine)", "so'rov-tadqiqot"),
    ("fonte affidabile", "ishonchli manba"), ("testimonianza", "guvohlik"),
    ("esperienza personale", "shaxsiy tajriba"), ("caso concreto", "aniq holat"),
    ("contro-esempio", "aksincha misol"), ("generalizzazione", "umumlashtirish"),
    ("eccezione (regola)", "qoidadan istisno"), ("confronto (analisi)", "qiyoslash"),
    ("analisi", "tahlil"), ("conclusione logica", "mantiqiy xulosa"),
    ("motivazione (ragione)", "sabab-asos"), ("causa principale", "asosiy sabab")],
   [("Ci sono prove concrete?", "Aniq isbot bormi?"),
    ("Le statistiche dicono il contrario.", "Statistika buning aksini ko'rsatadi.")]),
  ("Il tono del discorso", "Nutq ohangi",
   [("serio (tono)", "jiddiy ohang"), ("ironico", "kinoyali"), ("polemico", "keskin"),
    ("diplomatico", "diplomatik"), ("diretto (modo)", "to'g'ridan-to'g'ri"),
    ("indiretto", "bilvosita"), ("gentile (tono)", "muloyim"), ("brusco", "qo'pol"),
    ("formale (registro)", "rasmiy uslub"), ("informale", "norasmiy"),
    ("rispettoso", "hurmatli"), ("arrogante", "manman"), ("modesto", "kamtar"),
    ("sarcastico", "kesatiqli"), ("neutro", "betaraf"), ("appassionato", "ehtirosli"),
    ("freddo (tono)", "sovuq ohang"), ("convincente (tono)", "ishonarli"),
    ("confuso (discorso)", "chalkash nutq"), ("chiaro (discorso)", "ravon"),
    ("sintetico", "lo'nda")],
   [("Ha usato un tono molto diplomatico.", "U juda diplomatik ohangda gapirdi."),
    ("Sii più diretto, per favore.", "Iltimos, to'g'ridan-to'g'ri gapir.")]),
  ("Collegare le idee", "Fikrlarni bog'lash",
   [("innanzitutto", "birinchi navbatda"), ("inoltre", "bundan tashqari"),
    ("tuttavia", "shunga qaramay"), ("perciò", "shu bois"), ("dunque", "demak"),
    ("infatti", "darhaqiqat"), ("anzi", "aksincha (aniqroq)"), ("cioè (precisare)", "ya'ni"),
    ("ad esempio", "misol uchun"), ("in particolare", "xususan"),
    ("in generale", "umuman"), ("da un lato", "bir tomondan"), ("dall'altro", "ikkinchi tomondan"),
    ("mentre (contrasto)", "…bo'lsa"), ("nonostante", "…ga qaramay"),
    ("grazie a", "…tufayli"), ("a causa di", "…sababli"), ("al fine di", "…maqsadida"),
    ("in modo che", "…shunday qilib"), ("in conclusione (b1)", "xulosa o'rnida"),
    ("riassumendo", "qisqasi")],
   [("Inoltre, il costo è troppo alto.", "Bundan tashqari, narx juda baland."),
    ("Nonostante tutto, ha funzionato.", "Hammasiga qaramay, ishladi.")]),
  ("Valutare", "Baholash",
   [("efficace", "samarali"), ("inefficace", "samarasiz"), ("adeguato", "mos"),
    ("insufficiente", "yetarli emas"), ("eccessivo", "haddan ortiq"), ("equilibrato (b1)", "muvozanatli"),
    ("ragionevole", "oqilona"), ("assurdo", "bema'ni"), ("logico", "mantiqiy"),
    ("illogico", "mantiqsiz"), ("realistico", "real"), ("irrealistico", "xayoliy"),
    ("urgente (priorità)", "kechiktirib bo'lmas"), ("secondario", "ikkinchi darajali"),
    ("fondamentale", "tub"), ("marginale", "arzimas"), ("positivo (esito)", "ijobiy"),
    ("negativo (esito)", "salbiy"), ("neutro (esito)", "o'rtacha"),
    ("promettente", "istiqbolli"), ("deludente", "ko'ngilni cho'ktiradigan")],
   [("La proposta mi sembra ragionevole.", "Taklif menga oqilona tuyuladi."),
    ("Il risultato è stato deludente.", "Natija ko'ngilni cho'ktirdi.")]),
  ("Convincere", "Ko'ndirish",
   [("persuadere (b1)", "ishontirib ko'ndirmoq"), ("influenzare (opinione)", "fikrga ta'sir qilmoq"),
    ("promettere", "va'da bermoq"), ("garantire", "kafolat bermoq"), ("rassicurare", "tinchlantirmoq"),
    ("avvertire", "ogohlantirmoq"), ("minacciare", "do'q qilmoq"), ("negoziare (b1)", "muzokara olib bormoq"),
    ("cedere (b1)", "yon berishga rozi bo'lmoq"), ("ottenere", "erishmoq"),
    ("rinunciare a (b1)", "…dan voz kechmoq"), ("accordarsi", "kelishib olmoq"),
    ("firmare un accordo", "kelishuvni imzolamoq"), ("rispettare i patti", "shartga amal qilmoq"),
    ("tradire la fiducia", "ishonchni oqlamaslik"), ("chiedere scusa (form.)", "rasmiy uzr so'ramoq"),
    ("fare un favore", "yaxshilik qilmoq"), ("restituire il favore", "yaxshilikni qaytarmoq"),
    ("insistere gentilmente", "muloyimlik bilan qistamoq"), ("lasciar perdere", "qo'yib yubormoq"),
    ("trovare un punto d'incontro", "umumiy nuqta topmoq")],
   [("Mi ha convinto in cinque minuti.", "U meni besh daqiqada ko'ndirdi."),
    ("Ti garantisco che funziona.", "Ishlashiga kafolat beraman.")]),
 ],

 "b1u2": [
  ("Narrare", "Hikoya qilish",
   [("raccontare in dettaglio", "batafsil so'zlab bermoq"), ("descrivere", "tasvirlab bermoq"),
    ("ricordare (episodio)", "voqeani eslamoq"), ("dimenticare (episodio)", "voqeani unutmoq"),
    ("accorgersi", "payqamoq"), ("notare", "e'tibor bermoq"), ("scoprire (verità)", "fosh qilmoq"),
    ("nascondere", "yashirmoq"), ("confessare", "tan olib aytmoq"), ("mentire", "yolg'on gapirmoq"),
    ("esagerare (racconto)", "oshirib yubormoq"), ("interrompere (racconto)", "gapni bo'lmoq"),
    ("continuare a raccontare", "davom ettirmoq"), ("saltare una parte", "bir qismini tashlab ketmoq"),
    ("tornare indietro (racconto)", "orqaga qaytmoq (hikoyada)"), ("anticipare (racconto)", "oldindan aytmoq"),
    ("il protagonista (storia)", "voqea qahramoni"), ("la scena", "manzara (voqea)"),
    ("l'inizio", "boshlanish"), ("lo svolgimento", "voqealar rivoji"), ("il finale", "yakun")],
   [("Raccontamelo in dettaglio.", "Menga batafsil so'zlab ber."),
    ("Solo dopo mi sono accorta dell'errore.", "Faqat keyin xatoni payqadim.")]),
  ("Emozioni nel racconto", "Hikoyadagi tuyg'ular",
   [("sorpresa (forte)", "kutilmagan hayrat"), ("shock", "larza"), ("sollievo (b1)", "yengil tortish"),
    ("tensione", "zo'riqish"), ("angoscia", "iztirob"), ("entusiasmo", "shijoat"),
    ("curiosità", "qiziquvchanlik"), ("noia", "zerikish"), ("vergogna", "uyat"),
    ("colpa (senso di)", "aybdorlik hissi"), ("rimpianto", "afsus"), ("gratitudine", "minnatdorlik"),
    ("invidia", "hasad"), ("compassione", "rahm"), ("orgoglio (b1)", "g'urur"),
    ("umiliazione", "xo'rlik"), ("euforia", "quvonch to'lqini"), ("malinconia", "g'amginlik"),
    ("speranza (racconto)", "ilinj"), ("disperazione", "umidsizlik"), ("serenità", "osoyishtalik")],
   [("Ho provato un grande sollievo.", "Katta yengillik his qildim."),
    ("La tensione era altissima.", "Zo'riqish juda kuchli edi.")]),
  ("Viaggi memorabili", "Esda qolgan sayohatlar",
   [("itinerario (percorso)", "sayohat yo'nalishi"), ("tappa", "bekat (sayohat)"),
    ("escursione", "ekskursiya"), ("gita di un giorno", "bir kunlik sayr"),
    ("zaino in spalla", "yelkadagi ryukzak"), ("ostello (b1)", "arzon yotoqxona"),
    ("prenotazione online", "onlayn bron"), ("compagno di viaggio", "sayohat hamrohi"),
    ("guida locale", "mahalliy yo'lboshchi"), ("mappa cartacea", "qog'oz xarita"),
    ("sentiero", "so'qmoq"), ("panorama", "manzara (keng)"), ("alba", "tong"),
    ("tramonto (b1)", "shom"), ("silenzio della natura", "tabiat sukunati"),
    ("fotografia di viaggio", "sayohat surati"), ("diario di viaggio", "sayohat kundaligi"),
    ("imprevisto di viaggio", "yo'ldagi kutilmagan holat"), ("ritorno a casa", "uyga qaytish"),
    ("nostalgia del viaggio", "sayohat sog'inchi"), ("prossima meta", "keyingi manzil")],
   [("Abbiamo visto l'alba dalla montagna.", "Tog'dan tongni ko'rdik."),
    ("Il panorama era indimenticabile.", "Manzara unutilmas edi.")]),
  ("Quando qualcosa va storto", "Ishlar chappasiga ketganda",
   [("guasto (macchina)", "nosozlik (mashina)"), ("ritardo lungo", "uzoq kechikish"),
    ("sciopero (trasporti)", "transport ish tashlashi"), ("coincidenza persa", "o'tkazib yuborilgan ulanish"),
    ("bagaglio smarrito", "yo'qolgan yuk"), ("documento perso", "yo'qolgan hujjat"),
    ("portafoglio rubato", "o'g'irlangan hamyon"), ("truffa", "firibgarlik"),
    ("malinteso (b1)", "noto'g'ri tushunish"), ("litigio (viaggio)", "janjal (yo'lda)"),
    ("prenotazione annullata", "bekor qilingan bron"), ("albergo sbagliato", "noto'g'ri mehmonxona"),
    ("strada sbagliata", "noto'g'ri yo'l"), ("perdersi (b1)", "yo'ldan adashib qolmoq"),
    ("chiedere aiuto (strada)", "yo'lda yordam so'ramoq"), ("polizia (denuncia)", "politsiyaga murojaat"),
    ("assicurazione di viaggio", "sayohat sug'urtasi"), ("rimborso (viaggio)", "pulni qaytarish (sayohat)"),
    ("soluzione improvvisata", "shoshilinch yechim"), ("fortuna (colpo di)", "omad kulib boqdi"),
    ("finire bene", "yaxshilik bilan tugamoq")],
   [("Hanno perso il mio bagaglio.", "Ular yukimni yo'qotib qo'yishdi."),
    ("Alla fine è finita bene.", "Oxir-oqibat yaxshilik bilan tugadi.")]),
  ("Luoghi e atmosfere", "Joylar va muhit",
   [("centro storico", "eski shahar"), ("periferia", "shahar chekkasi"), ("borgo", "qasaba"),
    ("piazza principale", "bosh maydon"), ("vicolo stretto", "tor ko'cha (eski)"),
    ("quartiere vivace", "gavjum mahalla"), ("zona tranquilla", "tinch hudud"),
    ("affollato (b1)", "odam gavjum"), ("deserto (vuoto)", "kimsasiz"),
    ("accogliente", "qulay va iliq"), ("caotico", "tartibsiz"), ("pittoresco", "ko'zni quvontiradigan"),
    ("moderno (luogo)", "zamonaviy (joy)"), ("antico", "qadimiy"), ("restaurato", "ta'mirlangan"),
    ("abbandonato", "tashlandiq"), ("verde (zona)", "yashil hudud"),
    ("rumore di fondo", "shovqin-suron"), ("odore (luogo)", "hid"), ("luce (atmosfera)", "yorug'lik"),
    ("atmosfera", "muhit")],
   [("Il centro storico è molto pittoresco.", "Eski shahar juda go'zal."),
    ("È un quartiere tranquillo e accogliente.", "Bu tinch va qulay mahalla.")]),
  ("Tempo e durata", "Vaqt va davomiylik",
   [("durare", "davom etmoq"), ("richiedere tempo", "vaqt talab qilmoq"),
    ("passare (tempo)", "o'tmoq (vaqt)"), ("perdere tempo (b1)", "vaqtni boy bermoq"),
    ("guadagnare tempo", "vaqt yutmoq"), ("in anticipo (b1)", "belgilangandan oldin"),
    ("in orario", "vaqtida (jadval bo'yicha)"), ("in ritardo (b1)", "kechikkan holda"),
    ("a lungo", "uzoq vaqt"), ("brevemente", "qisqa vaqt"), ("all'inizio (b1)", "dastlab"),
    ("nel frattempo", "shu orada (rasmiy)"), ("da allora (b1)", "o'sha vaqtdan buyon"),
    ("fino ad ora", "shu paytgacha"), ("d'ora in poi", "bundan buyon"),
    ("una volta (passato)", "bir paytlar"), ("ogni volta", "har safar"),
    ("la maggior parte del tempo", "ko'pincha"), ("raramente (b1)", "juda kam"),
    ("di tanto in tanto", "goh-goh"), ("per sempre", "abadiy")],
   [("Il viaggio è durato tre ore.", "Sayohat uch soat davom etdi."),
    ("D'ora in poi farò diversamente.", "Bundan buyon boshqacha qilaman.")]),
  ("Dettagli e sensazioni", "Tafsilot va sezgilar",
   [("rumore forte", "kuchli shovqin"), ("sussurro", "pichirlash"), ("grido", "qichqiriq"),
    ("silenzio improvviso", "to'satdan sukunat"), ("profumo (buono)", "yoqimli hid"),
    ("puzza", "qo'lansa hid"), ("sapore intenso", "kuchli ta'm"), ("morbidezza", "yumshoqlik"),
    ("freddo pungente", "qattiq sovuq"), ("caldo soffocante", "jazirama issiq"),
    ("luce forte", "keskin yorug'lik"), ("penombra", "yarim qorong'ilik"),
    ("colore vivace", "yorqin rang"), ("colore spento", "xira rang"),
    ("movimento", "harakat"), ("immobile", "qimirlamay"), ("veloce (scena)", "shitob bilan"),
    ("lentamente (scena)", "sekin-asta"), ("all'improvviso (b1)", "tasodifan"),
    ("piano piano", "asta-sekin"), ("di colpo", "birdaniga")],
   [("C'era un profumo di pane appena fatto.", "Yangi yopilgan non hidi kelardi."),
    ("Di colpo tutto è diventato silenzioso.", "Birdaniga hamma yoq jimjit bo'ldi.")]),
  ("Finali e morali", "Yakun va saboq",
   [("lezione (morale)", "saboq"), ("esperienza utile", "foydali tajriba"),
    ("errore da evitare", "takrorlamaslik kerak bo'lgan xato"), ("insegnamento", "o'git"),
    ("consiglio (finale)", "so'nggi maslahat"), ("cambiare abitudine", "odatni o'zgartirmoq"),
    ("crescere (maturare)", "yetilmoq"), ("maturità", "yetuklik"), ("consapevolezza (b1)", "anglash"),
    ("rimettersi in gioco", "qaytadan urinmoq"), ("voltare pagina", "yangi sahifa ochmoq"),
    ("perdonare (b1)", "kechirib yubormoq"), ("dimenticare il passato", "o'tmishni unutmoq"),
    ("ricominciare", "qaytadan boshlamoq"), ("accettare (situazione)", "vaziyatni qabul qilmoq"),
    ("essere grato", "minnatdor bo'lmoq"), ("guardare avanti", "oldinga qaramoq"),
    ("morale della storia", "hikoyaning mag'zi"), ("in fin dei conti", "oxir-oqibatda"),
    ("col senno di poi", "keyin o'ylab qaralsa"), ("lieto fine", "baxtli yakun")],
   [("La morale della storia è semplice.", "Hikoyaning mag'zi oddiy."),
    ("Col senno di poi avrei fatto diversamente.", "Keyin o'ylab qarasam, boshqacha qilardim.")]),
 ],

 "b1u3": [
  ("Cercare lavoro", "Ish izlash",
   [("offerta di lavoro", "ish taklifi"), ("posizione aperta", "bo'sh o'rin"),
    ("profilo professionale", "kasbiy profil"), ("esperienza richiesta", "talab qilinadigan tajriba"),
    ("titolo di studio", "ma'lumot darajasi"), ("lettera di presentazione", "tanishtiruv xati"),
    ("colloquio telefonico", "telefon suhbati"), ("secondo colloquio", "ikkinchi suhbat"),
    ("prova pratica", "amaliy sinov"), ("selezione (fase)", "saralash bosqichi"),
    ("candidato ideale", "ideal nomzod"), ("concorrenza (candidati)", "nomzodlar raqobati"),
    ("risposta negativa", "rad javobi"), ("essere assunto", "ishga qabul qilinmoq"),
    ("firmare il contratto", "shartnomani imzolamoq"), ("periodo di prova (b1)", "sinov davri"),
    ("stage", "amaliyot"), ("tirocinante", "amaliyotchi"), ("raccomandazione", "tavsiya"),
    ("rete di contatti", "tanishlar tarmog'i"), ("aggiornare il curriculum", "rezyumeni yangilamoq")],
   [("Ho ricevuto una risposta negativa.", "Menga rad javobi keldi."),
    ("Il periodo di prova dura sei mesi.", "Sinov davri olti oy davom etadi.")]),
  ("Contratti e condizioni", "Shartnoma va shartlar",
   [("contratto a tempo indeterminato", "muddatsiz shartnoma"), ("part time (b1)", "qisman bandlik"),
    ("orario flessibile (b1)", "moslashuvchan jadval"), ("turni notturni", "tungi smenalar"),
    ("retribuzione lorda", "yalpi ish haqi"), ("netto (stipendio)", "qo'lga tegadigan maosh"),
    ("bonus", "mukofot puli"), ("tredicesima", "yillik qo'shimcha to'lov"),
    ("rimborso spese", "xarajat qoplamasi"), ("ferie pagate", "haq to'lanadigan ta'til"),
    ("congedo", "ta'til (uzoq)"), ("preavviso", "oldindan ogohlantirish"),
    ("dimissioni", "iste'fo"), ("licenziamento (b1)", "ishdan bo'shatilish"),
    ("sindacato (b1)", "kasaba uyushma"), ("contributi", "badallar"),
    ("pensione", "nafaqa (pensiya)"), ("assicurazione (lavoro)", "mehnat sug'urtasi"),
    ("sicurezza (lavoro)", "mehnat xavfsizligi qoidalari"), ("mansione", "vazifa (lavozim)"),
    ("responsabilità (ruolo)", "javobgarlik doirasi")],
   [("Ho un contratto a tempo indeterminato.", "Menda muddatsiz shartnoma bor."),
    ("Bisogna dare un mese di preavviso.", "Bir oy oldin ogohlantirish kerak.")]),
  ("Competenze", "Ko'nikmalar",
   [("competenza tecnica", "texnik malaka"), ("competenza trasversale", "umumiy ko'nikma"),
    ("capacità organizzativa", "tashkilotchilik qobiliyati"), ("problem solving (b1)", "muammoni hal qilish"),
    ("pensiero critico", "tanqidiy fikrlash"), ("creatività", "ijodkorlik"),
    ("flessibilità", "moslashuvchanlik"), ("precisione", "aniqlik (ishda)"),
    ("puntualità (b1)", "vaqtga rioya"), ("autonomia", "mustaqillik"),
    ("spirito di squadra", "jamoaviylik"), ("leadership", "yetakchilik"),
    ("gestione del tempo", "vaqtni boshqarish"), ("gestione dello stress", "stressni boshqarish"),
    ("capacità comunicative", "muloqot qobiliyati"), ("ascolto attivo", "faol tinglash"),
    ("negoziazione", "muzokara olib borish"), ("attenzione ai dettagli", "tafsilotlarga e'tibor"),
    ("apprendimento rapido", "tez o'rganish"), ("multitasking", "bir vaqtda bir necha ish"),
    ("certificazione", "sertifikat")],
   [("La mia competenza principale è l'organizzazione.", "Asosiy ko'nikmam — tashkilotchilik."),
    ("Ho una certificazione di inglese.", "Menda ingliz tili sertifikati bor.")]),
  ("Riunioni e progetti", "Yig'ilish va loyihalar",
   [("convocare", "chaqirmoq (yig'ilishga)"), ("partecipare", "ishtirok etmoq"),
    ("moderare", "boshqarib bormoq"), ("prendere appunti", "qayd qilib bormoq"),
    ("verbale (riunione)", "yig'ilish bayoni"), ("punto all'ordine del giorno", "kun tartibi masalasi"),
    ("proposta operativa", "amaliy taklif"), ("votazione", "ovoz berish"),
    ("approvazione", "tasdiqlash"), ("rinvio", "kechiktirish"),
    ("progetto in corso", "davom etayotgan loyiha"), ("fase del progetto", "loyiha bosqichi"),
    ("responsabile di progetto", "loyiha rahbari"), ("risorse", "resurslar"),
    ("tempistiche", "muddatlar jadvali"), ("monitoraggio", "kuzatuv"),
    ("relazione finale", "yakuniy hisobot"), ("risultato atteso", "kutilayotgan natija"),
    ("imprevisto (progetto)", "kutilmagan to'siq"), ("priorità (progetto)", "birinchi galdagi vazifa"),
    ("consegna (progetto)", "topshirish")],
   [("Chi prende appunti oggi?", "Bugun kim qayd qilib boradi?"),
    ("Il progetto è alla seconda fase.", "Loyiha ikkinchi bosqichda.")]),
  ("Chi è chi in azienda", "Kompaniyada kim kim",
   [("direttore", "direktor (rahbar)"), ("dirigente", "boshqaruvchi"),
    ("responsabile di reparto", "bo'lim boshlig'i"), ("supervisore", "nazoratchi"),
    ("dipendente", "xodim"), ("assistente", "yordamchi"), ("stagista", "amaliyotchi (talaba)"),
    ("consulente", "maslahatchi"), ("fornitore (azienda)", "yetkazib beruvchi kompaniya"),
    ("cliente aziendale", "korporativ mijoz"), ("reparto", "bo'lim"),
    ("ufficio risorse umane", "kadrlar bo'limi"), ("amministrazione", "ma'muriyat"),
    ("contabilità", "buxgalteriya"), ("magazzino", "ombor (korxona)"),
    ("produzione", "ishlab chiqarish"), ("vendite", "savdo bo'limi"),
    ("assistenza clienti", "mijozlarga yordam"), ("sede centrale", "bosh ofis"),
    ("filiale", "filial"), ("organigramma", "tuzilma")],
   [("Parla con il responsabile di reparto.", "Bo'lim boshlig'i bilan gaplash."),
    ("Lavoro nell'ufficio risorse umane.", "Men kadrlar bo'limida ishlayman.")]),
  ("Rapporti sul lavoro", "Ishdagi munosabatlar",
   [("collaborazione", "hamkorlik"), ("competizione (colleghi)", "raqobat (hamkasblar)"),
    ("pettegolezzo", "g'iybat"), ("favoritismo", "tanish-bilishchilik"),
    ("mobbing", "ish joyidagi bosim"), ("rispetto reciproco", "o'zaro hurmat"),
    ("fiducia (colleghi)", "hamkasblar ishonchi"), ("delega", "vakolat berish"),
    ("feedback", "fikr-mulohaza"), ("critica costruttiva", "quruvchi tanqid"),
    ("riconoscimento", "e'tirof"), ("merito (lavoro)", "xizmat (mehnat)"),
    ("colpa (lavoro)", "aybdorlik (ishda)"), ("scusa (lavoro)", "uzr (ishda)"),
    ("conflitto aperto", "ochiq nizo"), ("mediazione", "vositachilik"),
    ("clima aziendale", "jamoa muhiti"), ("motivazione del team", "jamoa ruhi"),
    ("turnover", "kadrlar almashinuvi"), ("colloquio di valutazione", "baholash suhbati"),
    ("obiettivo condiviso", "umumiy maqsad")],
   [("Ho ricevuto un feedback positivo.", "Menga ijobiy fikr bildirishdi."),
    ("Il clima aziendale è ottimo.", "Jamoa muhiti a'lo darajada.")]),
  ("Crescere professionalmente", "Kasbiy o'sish",
   [("avanzamento di carriera", "lavozimda ko'tarilish"), ("aumento (stipendio)", "maosh oshishi"),
    ("nuova mansione", "yangi vazifa"), ("trasferimento", "boshqa joyga o'tkazish"),
    ("formazione interna", "ichki o'quv"), ("corso professionale", "kasbiy kurs"),
    ("master (studio)", "magistratura"), ("specializzazione", "ixtisoslashuv"),
    ("mentore", "ustoz"), ("obiettivo di carriera", "karyera maqsadi"),
    ("cambiare settore", "sohani o'zgartirmoq"), ("reinventarsi", "o'zini qayta kashf etmoq"),
    ("mettersi in proprio", "o'z ishini ochmoq"), ("libera professione", "erkin kasb"),
    ("lavoro da remoto (b1)", "masofaviy ish (b1)"), ("equilibrio (lavoro-vita)", "ish-hayot muvozanati"),
    ("soddisfazione lavorativa", "ishdan qoniqish"), ("insoddisfazione", "norozilik"),
    ("stress da lavoro", "ish stressi"), ("pausa dalla carriera", "karyeradagi tanaffus"),
    ("nuovo inizio", "yangi boshlanish")],
   [("Vorrei cambiare settore.", "Men sohani o'zgartirmoqchiman."),
    ("Ha chiesto un aumento.", "U maosh oshirishni so'radi.")]),
  ("Quando il lavoro pesa", "Ish og'ir kelganda",
   [("carico di lavoro", "ish yuki"), ("scadenze ravvicinate", "zich muddatlar"),
    ("pressione (capo)", "rahbar bosimi"), ("orari lunghi", "uzoq ish soatlari"),
    ("straordinario non pagato", "to'lanmagan qo'shimcha ish"), ("stanchezza cronica", "surunkali charchoq"),
    ("errore grave", "jiddiy xato"), ("richiamo", "tanbeh"), ("provvedimento", "chora ko'rish"),
    ("tensione con il capo", "rahbar bilan keskinlik"), ("chiedere un colloquio", "suhbat so'ramoq"),
    ("spiegare la situazione", "vaziyatni tushuntirmoq"), ("chiedere supporto", "ko'mak so'ramoq"),
    ("ridurre l'orario", "ish vaqtini qisqartirmoq"), ("prendere ferie", "ta'tilga chiqmoq"),
    ("staccare la spina", "ishdan uzilmoq"), ("valutare alternative", "muqobilni ko'rib chiqmoq"),
    ("cercare altro", "boshqa ish qidirmoq"), ("dare le dimissioni", "iste'foga chiqmoq"),
    ("ultimo giorno", "oxirgi ish kuni"), ("saluto ai colleghi", "hamkasblar bilan xayrlashuv")],
   [("Il carico di lavoro è troppo alto.", "Ish yuki juda og'ir."),
    ("Ho chiesto un colloquio con il capo.", "Rahbar bilan suhbat so'radim.")]),
 ],

 "b1u4": [
  ("Dispositivi", "Qurilmalar",
   [("portatile", "noutbuk"), ("tablet", "planshet"), ("smartphone", "smartfon"),
    ("cuffie", "quloqchin"), ("altoparlante", "karnay"), ("microfono (device)", "mikrofon"),
    ("webcam", "veb-kamera"), ("mouse", "sichqoncha"), ("stampante (b1)", "chop etish qurilmasi"),
    ("scanner", "skaner"), ("hard disk", "qattiq disk"), ("memoria", "xotira"),
    ("processore", "protsessor"), ("schermo touch", "sensorli ekran"),
    ("caricabatterie (b1)", "zaryadlovchi"), ("presa USB", "USB uyasi"),
    ("accendere (device)", "ishga tushirmoq"), ("spegnere (device)", "o'chirib qo'ymoq"),
    ("riavviare", "qayta ishga tushirmoq"), ("collegare", "ulamoq"), ("configurare", "sozlamoq")],
   [("Devo riavviare il computer.", "Kompyuterni qayta ishga tushirishim kerak."),
    ("Le cuffie non si collegano.", "Quloqchin ulanmayapti.")]),
  ("Internet", "Internet",
   [("sito web", "veb-sayt"), ("pagina web", "veb-sahifa"), ("motore di ricerca", "qidiruv tizimi"),
    ("browser", "brauzer"), ("cronologia", "tarix (brauzer)"), ("segnalibro", "xatcho'p"),
    ("scheda (browser)", "varaq (brauzer)"), ("finestra", "oyna (dastur)"),
    ("caricamento", "yuklanish"), ("connessione lenta", "sekin ulanish"),
    ("banda larga", "keng polosali internet"), ("router", "router"),
    ("rete wireless", "simsiz tarmoq"), ("indirizzo web", "veb-manzil"),
    ("dominio", "domen"), ("server", "server"), ("cloud", "bulutli xotira"),
    ("backup", "zaxira nusxa"), ("sincronizzare", "sinxronlamoq"),
    ("registrarsi (sito)", "ro'yxatdan o'tmoq (sayt)"), ("disconnettersi", "chiqib ketmoq")],
   [("La connessione è troppo lenta.", "Ulanish juda sekin."),
    ("Ho fatto un backup dei file.", "Fayllarning zaxira nusxasini oldim.")]),
  ("Social network", "Ijtimoiy tarmoqlar",
   [("post", "post"), ("storia (social)", "stories"), ("reel", "qisqa video"),
    ("hashtag", "xeshteg"), ("follower", "obunachi"), ("seguire (account)", "obuna bo'lmoq"),
    ("smettere di seguire", "obunani bekor qilmoq"), ("mi piace", "layk"),
    ("condivisione", "ulashish"), ("commento (social)", "izoh (post)"),
    ("influencer", "influenser"), ("contenuto", "kontent"), ("algoritmo (feed)", "tavsiya algoritmi"),
    ("visualizzazioni", "ko'rishlar soni"), ("profilo pubblico", "ochiq profil"),
    ("profilo privato", "yopiq profil"), ("segnalare", "shikoyat qilmoq"),
    ("bloccare (utente)", "foydalanuvchini bloklamoq"), ("dipendenza dai social", "tarmoqqa qaramlik"),
    ("detox digitale", "raqamli dam"), ("reputazione online", "onlayn obro'")],
   [("Ha pubblicato una storia ieri.", "U kecha stories joyladi."),
    ("Il mio profilo è privato.", "Mening profilim yopiq.")]),
  ("Notizie e informazione", "Yangilik va axborot",
   [("testata giornalistica", "nashr"), ("cronista", "muxbir"), ("inviato", "maxsus muxbir"),
    ("titolo (notizia)", "sarlavha (xabar)"), ("articolo di fondo", "bosh maqola"),
    ("intervista (b1)", "suhbat (intervyu)"), ("conferenza stampa", "matbuot anjumani"),
    ("comunicato", "bayonot"), ("notizia in diretta", "jonli efirdagi xabar"),
    ("approfondimento", "tahliliy material"), ("opinione (giornale)", "muallif fikri"),
    ("fatto (notizia)", "fakt (xabar)"), ("verifica delle fonti", "manbalarni tekshirish"),
    ("disinformazione", "noto'g'ri axborot"), ("titolo sensazionalistico", "shov-shuvli sarlavha"),
    ("censura (b1)", "taqiq (matbuot)"), ("libertà di stampa", "matbuot erkinligi"),
    ("abbonamento (giornale)", "obuna (nashrga)"), ("edicola online", "onlayn kiosk"),
    ("podcast", "podkast"), ("newsletter", "axborot xati")],
   [("Verifico sempre le fonti.", "Men doim manbalarni tekshiraman."),
    ("È solo un titolo sensazionalistico.", "Bu shunchaki shov-shuvli sarlavha.")]),
  ("Privacy e sicurezza", "Maxfiylik va xavfsizlik",
   [("dati personali (b1)", "shaxsiy ma'lumotlar"), ("consenso", "rozilik"),
    ("informativa", "ogohnoma"), ("cookie", "cookie fayllari"), ("tracciamento", "kuzatuv (onlayn)"),
    ("pubblicità mirata", "maqsadli reklama"), ("truffa online", "onlayn firibgarlik"),
    ("phishing", "fishing"), ("virus (informatico)", "kompyuter virusi"),
    ("antivirus", "antivirus"), ("firewall", "himoya devori"), ("password sicura", "kuchli parol"),
    ("autenticazione a due fattori", "ikki bosqichli tasdiqlash"),
    ("account compromesso", "buzilgan hisob"), ("furto d'identità", "shaxsni o'g'irlash"),
    ("crittografia", "shifrlash"), ("aggiornamento di sicurezza", "xavfsizlik yangilanishi"),
    ("permessi dell'app", "ilova ruxsatlari"), ("cancellare i dati", "ma'lumotlarni o'chirmoq"),
    ("diritto all'oblio", "unutilish huquqi"), ("navigazione anonima", "anonim rejim")],
   [("Usa una password sicura.", "Kuchli paroldan foydalan."),
    ("Ho attivato l'autenticazione a due fattori.", "Ikki bosqichli tasdiqlashni yoqdim.")]),
  ("Programmi e app", "Dastur va ilovalar",
   [("applicazione (app)", "ilova"), ("programma (software)", "dastur"),
    ("installare", "o'rnatmoq"), ("disinstallare", "o'chirib tashlamoq"),
    ("versione", "versiya"), ("aggiornamento (app)", "ilova yangilanishi"),
    ("impostazioni (app)", "sozlamalar"), ("notifica (app)", "bildirishnoma (ilova)"),
    ("account (app)", "hisob (ilova)"), ("abbonamento (app)", "obuna (ilova)"),
    ("versione gratuita", "bepul versiya"), ("versione a pagamento", "pulli versiya"),
    ("funzione", "funksiya"), ("interfaccia", "interfeys"), ("compatibile", "mos keladigan"),
    ("bug", "xatolik (dastur)"), ("segnalare un problema", "muammoni bildirmoq"),
    ("assistenza tecnica", "texnik yordam"), ("manuale", "qo'llanma"),
    ("scorciatoia", "tezkor tugma"), ("modalità scura", "tungi rejim")],
   [("Devo aggiornare l'applicazione.", "Ilovani yangilashim kerak."),
    ("C'è un bug nell'ultima versione.", "So'nggi versiyada xatolik bor.")]),
  ("Comprare online", "Onlayn xarid",
   [("negozio online", "onlayn do'kon"), ("carrello (online)", "savat"),
    ("ordine (online)", "buyurtma (onlayn)"), ("codice sconto", "chegirma kodi"),
    ("spedizione gratuita", "bepul yetkazib berish"), ("tempi di consegna", "yetkazib berish muddati"),
    ("tracking", "kuzatuv raqami"), ("reso", "qaytarish"), ("rimborso (online)", "pulni qaytarish (onlayn)"),
    ("garanzia (prodotto)", "mahsulot kafolati"), ("recensione (prodotto)", "mahsulot sharhi"),
    ("valutazione (stelle)", "yulduzli baho"), ("venditore", "sotuvchi (onlayn)"),
    ("prodotto originale", "asl mahsulot"), ("contraffatto", "qalbaki"),
    ("pagamento sicuro", "xavfsiz to'lov"), ("carta salvata", "saqlangan karta"),
    ("fattura", "hisob-faktura"), ("assistenza post-vendita", "sotuvdan keyingi xizmat"),
    ("confronto prezzi", "narxlarni solishtirish"), ("acquisto impulsivo", "o'ylamay qilingan xarid")],
   [("Ho chiesto il reso del prodotto.", "Mahsulotni qaytarishni so'radim."),
    ("La spedizione è gratuita sopra i 50 euro.", "50 yevrodan yuqori xaridda yetkazish bepul.")]),
  ("Quando la tecnologia non va", "Texnika ishlamaganda",
   [("schermo nero", "qora ekran"), ("blocco (device)", "qotib qolish"),
    ("rallentamento", "sekinlashuv"), ("surriscaldamento", "qizib ketish"),
    ("batteria scarica", "batareya o'tirgan"), ("memoria piena", "xotira to'lgan"),
    ("file corrotto", "buzilgan fayl"), ("dati persi", "yo'qolgan ma'lumot"),
    ("recuperare (dati)", "ma'lumotni tiklamoq"), ("formattare", "formatlamoq"),
    ("ripristinare", "tiklash (tizimni)"), ("assistenza (riparazione)", "ta'mirlash xizmati"),
    ("preventivo", "narx taxmini"), ("pezzo di ricambio", "ehtiyot qism"),
    ("riparazione costosa", "qimmat ta'mir"), ("sostituire il dispositivo", "qurilmani almashtirmoq"),
    ("obsoleto", "eskirgan"), ("compatibilità", "moslik"), ("perdere i contatti", "kontaktlarni yo'qotmoq"),
    ("copia di sicurezza", "zaxira nusxa (fayl)"), ("riprovare più tardi", "keyinroq urinib ko'rmoq")],
   [("Il telefono si è bloccato di nuovo.", "Telefon yana qotib qoldi."),
    ("Ho perso tutti i contatti.", "Barcha kontaktlarimni yo'qotdim.")]),
 ],
}
