# -*- coding: utf-8 -*-
# B1 — vocabulary packs, units 5-8.

EXTRA = {
 "b1u5": [
  ("Il clima", "Iqlim",
   [("riscaldamento globale", "global isish"), ("effetto serra", "issiqxona effekti"),
    ("emissioni", "chiqindi gazlar"), ("anidride carbonica", "karbonat angidrid"),
    ("temperatura media", "o'rtacha harorat"), ("ondata di calore", "jazirama to'lqini"),
    ("gelo", "qahraton"), ("alluvione", "suv toshqini"), ("frana", "ko'chki"),
    ("incendio", "yong'in"), ("uragano", "quyun"), ("ghiacciaio", "muzlik"),
    ("livello del mare", "dengiz sathi"), ("desertificazione", "cho'llanish"),
    ("stagione secca", "quruq mavsum"), ("precipitazioni", "yog'ingarchilik"),
    ("previsione meteo", "ob-havo bashorati"), ("clima estremo", "keskin iqlim"),
    ("adattamento", "moslashuv (iqlimga)"), ("mitigazione", "ta'sirni yumshatish"),
    ("accordo sul clima", "iqlim kelishuvi")],
   [("Le emissioni devono diminuire.", "Chiqindi gazlar kamayishi kerak."),
    ("L'estate scorsa c'è stata un'ondata di calore.", "O'tgan yozda jazirama to'lqini bo'ldi.")]),
  ("Energia", "Energiya",
   [("energia solare", "quyosh energiyasi"), ("energia eolica", "shamol energiyasi"),
    ("idroelettrico", "gidroelektr"), ("nucleare", "yadro energiyasi"),
    ("carbone", "ko'mir"), ("petrolio", "neft"), ("gas naturale", "tabiiy gaz"),
    ("pannello solare", "quyosh paneli"), ("turbina", "turbina"), ("rete elettrica", "elektr tarmog'i"),
    ("consumo energetico", "energiya iste'moli"), ("efficienza energetica", "energiya samaradorligi"),
    ("isolamento (casa)", "issiqlik izolyatsiyasi"), ("bolletta alta", "yuqori hisob"),
    ("blackout", "elektr uzilishi"), ("risparmio energetico", "energiya tejash"),
    ("fonte pulita", "toza manba"), ("fonte fossile", "qazilma manba"),
    ("batteria (accumulo)", "akkumulyator"), ("veicolo elettrico", "elektromobil"),
    ("colonnina di ricarica", "zaryadlash shoxobchasi")],
   [("Abbiamo installato pannelli solari.", "Biz quyosh panellarini o'rnatdik."),
    ("Il consumo energetico è calato.", "Energiya iste'moli kamaydi.")]),
  ("Rifiuti e riciclo", "Chiqindi va qayta ishlash",
   [("raccolta differenziata", "saralab yig'ish"), ("bidone", "chiqindi konteyneri"),
    ("organico", "organik chiqindi"), ("indifferenziato", "aralash chiqindi"),
    ("imballaggio", "o'rov"), ("monouso", "bir martalik"), ("riutilizzabile", "qayta ishlatiladigan"),
    ("biodegradabile", "biologik parchalanadigan"), ("discarica", "chiqindixona"),
    ("inceneritore", "yondirish zavodi"), ("compost", "kompost"),
    ("spreco alimentare", "oziq-ovqat isrofi"), ("microplastiche", "mikroplastik"),
    ("inquinamento dell'acqua", "suv ifloslanishi"), ("inquinamento dell'aria", "havo ifloslanishi"),
    ("smog", "tutun-tuman"), ("rumore (inquinamento)", "shovqin ifloslanishi"),
    ("pulizia dei parchi", "bog'larni tozalash"), ("multa ambientale", "ekologik jarima"),
    ("educazione ambientale", "ekologik tarbiya"), ("impronta ecologica", "ekologik iz")],
   [("Qui si fa la raccolta differenziata.", "Bu yerda chiqindi saralab yig'iladi."),
    ("Riduciamo lo spreco alimentare.", "Oziq-ovqat isrofini kamaytiraylik.")]),
  ("Città sostenibile", "Barqaror shahar",
   [("mobilità sostenibile", "barqaror transport"), ("zona pedonale", "piyodalar zonasi"),
    ("corsia preferenziale", "maxsus yo'lak"), ("car sharing", "avtomobil almashish"),
    ("monopattino", "samokat"), ("trasporto elettrico", "elektr transport"),
    ("area verde", "yashil maydon"), ("orto urbano", "shahar bog'chasi"),
    ("tetto verde", "yashil tom"), ("illuminazione pubblica", "ko'cha yoritgichi"),
    ("acqua potabile", "ichimlik suvi"), ("fognatura", "kanalizatsiya"),
    ("riqualificazione", "obodonlashtirish"), ("edificio efficiente", "energiya tejamkor bino"),
    ("urbanistica", "shaharsozlik"), ("densità abitativa", "aholi zichligi"),
    ("periferia degradata", "qarovsiz chekka"), ("spazio pubblico", "jamoat maydoni"),
    ("accessibilità", "qulaylik (nogironlar uchun)"), ("barriera architettonica", "me'moriy to'siq"),
    ("piano regolatore", "bosh reja")],
   [("La zona pedonale è stata ampliata.", "Piyodalar zonasi kengaytirildi."),
    ("Servono più aree verdi.", "Ko'proq yashil maydon kerak.")]),
  ("Società e cittadinanza", "Jamiyat va fuqarolik",
   [("cittadino", "fuqaro"), ("comunità locale", "mahalliy jamoa"),
    ("partecipazione", "ishtirok"), ("assemblea", "yig'in"), ("petizione", "murojaat (imzo)"),
    ("referendum", "referendum"), ("elezioni", "saylov"), ("voto (elezioni)", "ovoz"),
    ("candidato (elezioni)", "nomzod (saylov)"), ("sindaco", "hokim"),
    ("consiglio comunale", "shahar kengashi"), ("amministrazione pubblica", "davlat boshqaruvi"),
    ("servizio pubblico", "davlat xizmati"), ("tassa (comune)", "mahalliy soliq"),
    ("regolamento", "nizom"), ("divieto", "taqiq"), ("permesso (autorizzazione)", "ruxsatnoma"),
    ("associazione", "uyushma"), ("iniziativa", "tashabbus"), ("dibattito pubblico (b1)", "ommaviy muhokama"),
    ("opinione pubblica (b1)", "jamoatchilik fikri")],
   [("Ho firmato una petizione.", "Men murojaatga imzo qo'ydim."),
    ("Le elezioni sono a giugno.", "Saylov iyunda bo'ladi.")]),
  ("Diritti e doveri", "Huquq va burchlar",
   [("diritto (giuridico)", "huquq (qonuniy)"), ("dovere (obbligo)", "majburiyat"),
    ("libertà", "erkinlik"), ("uguaglianza", "tenglik (huquqiy)"), ("giustizia sociale", "ijtimoiy adolat"),
    ("discriminazione (b1)", "kamsitish (b1)"), ("parità di genere", "gender tengligi"),
    ("diritto al lavoro", "mehnat huquqi"), ("diritto allo studio", "ta'lim huquqi"),
    ("diritto alla salute", "salomatlik huquqi"), ("tutela dei minori", "bolalar himoyasi"),
    ("diritti degli anziani", "keksalar huquqlari"), ("disabilità", "nogironlik"),
    ("inclusione", "integratsiya (ijtimoiy)"), ("minoranza", "ozchilik"),
    ("rispetto delle regole", "qoidalarga rioya"), ("legge (norma)", "qonun (me'yor)"),
    ("tribunale (b1)", "sud organi"), ("avvocato (b1)", "advokat (huquqshunos)"),
    ("denuncia (legale)", "shikoyat arizasi"), ("sanzione", "jazo chorasi")],
   [("Tutti hanno diritto allo studio.", "Hammaning ta'lim olish huquqi bor."),
    ("È vietato dalla legge.", "Bu qonun bilan taqiqlangan.")]),
  ("Disuguaglianze", "Tengsizliklar",
   [("povertà (b1)", "muhtojlik"), ("ricchezza", "boylik"), ("classe sociale", "ijtimoiy qatlam"),
    ("reddito basso", "past daromad"), ("disoccupazione", "ishsizlik"),
    ("lavoro precario", "beqaror ish"), ("costo della vita", "turmush qiymati"),
    ("accesso alle cure", "tibbiy yordamga imkon"), ("abbandono scolastico (b1)", "o'qishni tashlash"),
    ("emarginazione", "chetlatilish"), ("senzatetto", "uy-joysiz"),
    ("aiuto sociale", "ijtimoiy yordam"), ("sussidio", "nafaqa (yordam puli)"),
    ("mensa sociale", "xayriya oshxonasi"), ("banco alimentare", "oziq-ovqat jamg'armasi"),
    ("divario", "tafovut"), ("opportunità (sociale)", "ijtimoiy imkoniyat"),
    ("mobilità sociale", "ijtimoiy o'sish"), ("stereotipo", "qoliplangan fikr"),
    ("pregiudizio (b1)", "noto'g'ri qarash"), ("solidarietà (b1)", "hamdardlik")],
   [("Il divario tra ricchi e poveri è cresciuto.", "Boy va kambag'al o'rtasidagi tafovut ortdi."),
    ("Molti giovani hanno un lavoro precario.", "Ko'p yoshlar beqaror ishda ishlaydi.")]),
  ("Dare una mano", "Ko'mak berish",
   [("volontario (persona)", "ko'ngilli"), ("associazione di volontariato", "ko'ngillilar uyushmasi"),
    ("donazione", "xayriya"), ("raccolta fondi", "mablag' yig'ish"), ("beneficenza", "ehson"),
    ("adottare (causa)", "qo'llab-quvvatlamoq"), ("sostenere una causa", "maqsadni himoya qilmoq"),
    ("sensibilizzare", "e'tiborni qaratmoq"), ("campagna", "tashviqot"),
    ("manifestazione", "namoyish"), ("protesta", "norozilik"), ("firma (petizione)", "imzo (murojaat)"),
    ("impegno civile", "fuqarolik faolligi"), ("lavoro di comunità", "hashar"),
    ("aiuto reciproco", "o'zaro yordam"), ("dare il buon esempio", "ibrat bo'lmoq"),
    ("piccolo gesto", "kichik yaxshilik"), ("fare la differenza", "o'zgarish yasamoq"),
    ("gratitudine (aiuto)", "minnatdorchilik (yordam)"), ("rete di sostegno", "ko'mak tarmog'i"),
    ("responsabilità collettiva", "umumiy mas'uliyat")],
   [("Faccio volontariato il sabato.", "Shanba kuni ko'ngilli bo'lib ishlayman."),
    ("Anche un piccolo gesto conta.", "Kichik yaxshilik ham ahamiyatli.")]),
 ],

 "b1u6": [
  ("Sentimenti profondi", "Chuqur tuyg'ular",
   [("affetto", "mehr"), ("tenerezza", "hurmat-e'zoz"), ("passione", "ehtiros"),
    ("attaccamento", "bog'lanish"), ("distacco", "sovuqlik"), ("indifferenza", "befarqlik"),
    ("gelosia (b1)", "rashk (kuchli)"), ("possessività", "egalik hissi"),
    ("insicurezza", "ishonchsizlik"), ("vulnerabilità", "himoyasizlik"),
    ("empatia", "hamdardlik (his qilish)"), ("comprensione", "tushunish"),
    ("accettazione", "qabul qilish"), ("rifiuto (sentimento)", "rad etilish"),
    ("abbandono", "tashlab ketilish"), ("nostalgia (b1)", "sog'inch (chuqur)"),
    ("rimorso", "vijdon azobi"), ("perdono", "kechirim"), ("rancore", "kek"),
    ("riconciliazione", "yarashuv"), ("pace interiore", "ichki osoyishtalik")],
   [("Provo molto affetto per lei.", "Unga katta mehrim bor."),
    ("Ho bisogno di pace interiore.", "Menga ichki osoyishtalik kerak.")]),
  ("L'amicizia vera", "Chin do'stlik",
   [("amico stretto", "yaqin do'st"), ("conoscente", "tanish"), ("compagnia", "davra"),
    ("legame profondo", "chuqur rishta"), ("lealtà", "sadoqat"), ("complicità", "hamfikrlik"),
    ("segreto condiviso", "sir (ikkovga tegishli)"), ("confidenza", "sirdoshlik"),
    ("consiglio sincero", "samimiy maslahat"), ("presenza", "yonida bo'lish"),
    ("assenza", "yo'qlik"), ("distanza (amicizia)", "uzoqlik (do'stlik)"),
    ("ritrovarsi", "qayta topishmoq"), ("allontanarsi", "uzoqlashmoq"),
    ("delusione (amico)", "do'stdan ko'ngil qolishi"), ("chiarimento (amicizia)", "gaplashib olish"),
    ("scusarsi con un amico", "do'stdan uzr so'ramoq"), ("ricucire", "munosabatni tiklamoq"),
    ("amicizia di lunga data", "ko'p yillik do'stlik"), ("fare amicizia", "do'stlashmoq"),
    ("amico d'infanzia (b1)", "bolalikdan do'st")],
   [("È un'amicizia di lunga data.", "Bu ko'p yillik do'stlik."),
    ("Abbiamo avuto un chiarimento.", "Biz gaplashib oldik.")]),
  ("Amore e coppia", "Sevgi va juftlik",
   [("innamoramento", "oshiq bo'lish"), ("attrazione", "o'ziga tortish"),
    ("appuntamento (romantico)", "uchrashuv (romantik)"), ("relazione seria", "jiddiy munosabat"),
    ("convivenza", "birga yashash"), ("fidanzamento", "unashtiruv"),
    ("proposta di matrimonio", "turmush qurish taklifi"), ("fedeltà", "vafodorlik"),
    ("tradimento (coppia)", "xiyonat"), ("crisi di coppia", "munosabatdagi inqiroz"),
    ("terapia di coppia", "juftlik uchun maslahat"), ("separazione", "ajralib yashash"),
    ("divorzio (b1)", "ajrim"), ("single", "yolg'iz (turmush qurmagan)"),
    ("famiglia allargata", "kengaygan oila"), ("suoceri", "qaynotalar"),
    ("gelosia in amore", "sevgidagi rashk"), ("compromesso (coppia)", "murosa (juftlik)"),
    ("progetti comuni", "umumiy rejalar"), ("anniversario (coppia)", "nikoh sanasi"),
    ("amore duraturo", "barqaror sevgi")],
   [("Stanno insieme da cinque anni.", "Ular besh yildan beri birga."),
    ("Abbiamo progetti comuni.", "Bizning umumiy rejalarimiz bor.")]),
  ("Conflitti", "Nizolar",
   [("discussione accesa", "qizg'in bahs"), ("litigare (b1)", "urishib qolmoq"),
    ("alzare la voce", "ovozini ko'tarmoq"), ("offesa", "haqorat"), ("silenzio (punizione)", "gaplashmay qo'yish"),
    ("fraintendimento (b1)", "noto'g'ri anglash"), ("accusare", "ayblamoq"),
    ("difendersi", "o'zini oqlamoq"), ("ammettere l'errore", "xatosini tan olmoq"),
    ("chiedere scusa sinceramente", "chin dildan uzr so'ramoq"), ("scusa accettata", "uzr qabul qilindi"),
    ("mettersi nei panni", "o'zini o'rniga qo'ymoq"), ("calmarsi", "tinchlanmoq"),
    ("prendersi una pausa", "biroz vaqt olmoq"), ("parlarne con calma", "bosiqlik bilan gaplashmoq"),
    ("trovare un accordo (b1)", "kelishuvga erishmoq"), ("mettere un punto", "nuqta qo'ymoq"),
    ("evitare il conflitto", "nizodan qochmoq"), ("affrontare il problema", "muammoni hal qilishga kirishmoq"),
    ("ferire (parole)", "so'z bilan xafa qilmoq"), ("riconciliarsi (b1)", "yarashib olmoq")],
   [("Parliamone con calma.", "Keling, bosiqlik bilan gaplashaylik."),
    ("Ha ammesso il suo errore.", "U xatosini tan oldi.")]),
  ("Dire come ti senti", "His-tuyg'uni aytish",
   [("esprimere", "ifodalamoq"), ("aprirsi", "ko'nglini ochmoq"), ("chiudersi", "ichiga yutmoq"),
    ("sfogarsi (b1)", "dardini to'kib solmoq"), ("piangere", "yig'lamoq"),
    ("ridere (b1)", "kulib yubormoq"), ("abbracciare", "quchoqlamoq"),
    ("consolare", "tasalli bermoq"), ("ascoltare (davvero)", "chin dildan tinglamoq"),
    ("giudicare", "hukm qilmoq"), ("non giudicare", "hukm qilmaslik"),
    ("dare spazio", "erkinlik bermoq"), ("stare vicino", "yonida bo'lmoq"),
    ("chiedere aiuto (emozioni)", "ruhiy yordam so'ramoq"), ("psicologo", "psixolog"),
    ("terapia (b1)", "psixologik maslahat"), ("parlarne", "bu haqda gapirmoq"),
    ("tenere dentro", "ichida saqlamoq"), ("sentirsi capito", "tushunilganini his qilmoq"),
    ("sentirsi solo", "o'zini yolg'iz his qilmoq"), ("bisogno di affetto", "mehrga ehtiyoj")],
   [("Ho bisogno di parlarne.", "Bu haqda gapirishim kerak."),
    ("Mi sono sentita capita.", "O'zimni tushunilgandek his qildim.")]),
  ("Fiducia", "Ishonch",
   [("fidarsi di qualcuno", "kimgadir ishonmoq"), ("meritare fiducia", "ishonchga loyiq bo'lmoq"),
    ("mantenere una promessa", "va'daga vafo qilmoq"), ("rompere una promessa", "va'dani buzmoq"),
    ("mentire (b1)", "aldamoq"), ("bugia", "yolg'on"), ("verità", "haqiqat"),
    ("sincerità (b1)", "samimiyat"), ("trasparenza (rapporti)", "ochiqlik"),
    ("segreto (mantenere)", "sirni saqlamoq"), ("tradire un segreto", "sirni oshkor qilmoq"),
    ("dubitare", "shubhalanmoq"), ("sospetto", "gumon"), ("gelosia infondata", "asossiz rashk"),
    ("ricostruire la fiducia", "ishonchni tiklamoq"), ("seconda possibilità", "ikkinchi imkoniyat"),
    ("perdere la fiducia", "ishonchni yo'qotmoq"), ("affidabile", "ishonchli (odam)"),
    ("inaffidabile", "ishonib bo'lmaydigan"), ("parola data", "berilgan so'z"),
    ("onestà", "halollik")],
   [("Mi fido ciecamente di te.", "Men senga ko'r-ko'rona ishonaman."),
    ("Ha mantenuto la promessa.", "U va'dasiga vafo qildi.")]),
  ("Famiglia e ruoli", "Oila va rollar",
   [("genitore single", "yolg'iz ota yoki ona"), ("figlio unico", "yakka farzand"),
    ("fratelli (insieme)", "aka-uka"), ("sorelle (insieme)", "opa-singil"),
    ("educazione (figli)", "tarbiya"), ("regola in famiglia", "oiladagi qoida"),
    ("punizione", "jazo (tarbiya)"), ("premio", "rag'bat"), ("indipendenza (figli)", "mustaqillik"),
    ("adolescente", "o'smir"), ("ribellione", "qarshilik (o'smir)"),
    ("dialogo in famiglia", "oiladagi suhbat"), ("tempo insieme", "birga o'tkazilgan vaqt"),
    ("nonni (ruolo)", "buvi-bobo (rol)"), ("prendersi cura", "g'amxo'rlik qilmoq"),
    ("anziano in casa", "uydagi keksa"), ("responsabilità familiare", "oilaviy mas'uliyat"),
    ("tradizione di famiglia", "oilaviy an'ana"), ("riunione di famiglia", "oilaviy yig'in"),
    ("litigio in famiglia", "oiladagi janjal"), ("sostegno dei genitori", "ota-ona ko'magi")],
   [("Passiamo poco tempo insieme.", "Biz birga kam vaqt o'tkazamiz."),
    ("Mi prendo cura di mia nonna.", "Men buvimga g'amxo'rlik qilaman.")]),
  ("Sostenere qualcuno", "Kimnidir qo'llash",
   [("incoraggiare", "dalda bermoq"), ("motivare", "ruhlantirmoq"),
    ("essere presente", "hozir bo'lmoq"), ("offrire aiuto", "yordam taklif qilmoq"),
    ("accompagnare", "hamrohlik qilmoq"), ("proteggere", "asramoq"),
    ("difendere qualcuno", "kimnidir himoya qilmoq"), ("fare un complimento", "maqtov aytmoq"),
    ("ringraziare di cuore", "chin dildan minnatdorchilik"), ("apprezzare", "qadrlamoq"),
    ("valorizzare", "qadriga yetmoq"), ("rispettare i tempi", "vaqtini hurmat qilmoq"),
    ("non insistere", "qistamaslik"), ("chiedere permesso", "ruxsat so'ramoq"),
    ("mantenere le distanze", "masofa saqlamoq"), ("rispettare i confini", "chegarani hurmat qilmoq"),
    ("celebrare insieme", "birga nishonlamoq"), ("condividere la gioia", "quvonchni baham ko'rmoq"),
    ("condividere il dolore", "g'amni baham ko'rmoq"), ("esserci sempre", "doim yonida bo'lmoq"),
    ("gesto gentile", "xayrli ish")],
   [("Grazie per esserci sempre.", "Doim yonimda bo'lganing uchun rahmat."),
    ("Mi ha incoraggiata molto.", "U meni juda dalda berdi.")]),
 ],

 "b1u7": [
  ("Feste e riti", "Bayram va marosimlar",
   [("rito", "marosim"), ("cerimonia", "tantana"), ("usanza (b1)", "urf"),
    ("tradizione popolare", "xalq an'anasi"), ("festa religiosa", "diniy bayram"),
    ("festa nazionale", "milliy bayram"), ("digiuno (rito)", "ro'za tutish"),
    ("preghiera", "ibodat"), ("benedizione", "duo"), ("processione", "yurish (marosim)"),
    ("costume tradizionale", "milliy libos"), ("danza rituale", "marosim raqsi"),
    ("canto tradizionale", "an'anaviy qo'shiq"), ("dono rituale", "marosim sovg'asi"),
    ("banchetto (festa)", "katta ziyofat"), ("invitati (festa)", "mehmonlar (bayram)"),
    ("padrone di casa (festa)", "to'y egasi"), ("augurio tradizionale", "an'anaviy tilak"),
    ("fuochi d'artificio", "mushakbozlik"), ("decorazione", "bezak"), ("ricorrenza", "sana (bayram)")],
   [("È una tradizione molto antica.", "Bu juda qadimiy an'ana."),
    ("Tutta la famiglia si riunisce per la festa.", "Bayramga butun oila yig'iladi.")]),
  ("Cucina tradizionale", "An'anaviy taomlar",
   [("piatto nazionale", "milliy taom"), ("ricetta antica", "qadimiy retsept"),
    ("ingrediente segreto", "sirli masalliq"), ("impasto", "xamir"),
    ("stendere la pasta", "xamir yoymoq"), ("cuocere al forno", "tandirda pishirmoq"),
    ("cuocere a vapore", "bug'da pishirmoq"), ("far marinare", "marinadga qo'ymoq"),
    ("condire", "ziravor solmoq"), ("servire caldo", "issiq holda tortmoq"),
    ("porzione abbondante", "to'kin ulush"), ("pane fatto in casa", "uy noni"),
    ("zuppa densa", "quyuq sho'rva"), ("dolce tipico", "milliy shirinlik"),
    ("tè verde", "ko'k choy"), ("tavola imbandita", "bezatilgan dasturxon"),
    ("mangiare con le mani", "qo'l bilan yemoq"), ("ricetta di famiglia (b1)", "avloddan qolgan retsept"),
    ("cucinare insieme", "birga ovqat tayyorlamoq"), ("profumo di casa", "uy hidi"),
    ("sapore dell'infanzia", "bolalik ta'mi")],
   [("Questa è la ricetta di mia nonna.", "Bu buvimning retsepti."),
    ("Il plov si serve caldo.", "Palov issiq holda tortiladi.")]),
  ("Ospitalità", "Mehmondo'stlik",
   [("ospite d'onore", "aziz mehmon"), ("accogliere", "kutib olmoq"),
    ("far accomodare", "joylashtirmoq"), ("offrire il tè", "choy tutmoq"),
    ("servire per primo", "avval tortmoq"), ("posto d'onore", "to'r"),
    ("togliersi le scarpe", "oyoq kiyimni yechmoq"), ("portare un dono", "sovg'a bilan bormoq"),
    ("rifiutare educatamente", "odob bilan rad etmoq"), ("insistere (ospite)", "qistamoq"),
    ("assaggiare tutto", "hammasidan tatib ko'rmoq"), ("complimentarsi con la cuoca", "oshpazni maqtamoq"),
    ("ringraziare l'ospite", "mehmonga rahmat aytmoq"), ("accompagnare alla porta", "kuzatib qo'ymoq"),
    ("invito a cena", "kechki taomga taklif"), ("visita improvvisa", "kutilmagan tashrif"),
    ("preparare la casa", "uyni tayyorlamoq"), ("sedersi per terra", "yerga o'tirmoq"),
    ("dividere il pane", "nonni bo'lishmoq"), ("brindisi (b1)", "qadah so'zi (b1)"),
    ("dovere di ospitalità", "mehmondo'stlik burchi")],
   [("Da noi l'ospite è sacro.", "Bizda mehmon aziz."),
    ("Si tolgono le scarpe all'ingresso.", "Kiraverishda oyoq kiyim yechiladi.")]),
  ("Artigianato e mestieri", "Hunarmandchilik",
   [("maestro artigiano", "usta hunarmand"), ("bottega", "ustaxona"), ("apprendista", "shogird"),
    ("telaio", "dastgoh"), ("tessere", "to'qimoq"), ("filo (tessuto)", "ip"),
    ("ricamare", "kashta tikmoq"), ("intagliare", "o'ymakorlik qilmoq"),
    ("modellare (argilla)", "loydan yasamoq"), ("cuocere (ceramica)", "kuydirmoq (sopol)"),
    ("smalto", "sir (sopol)"), ("motivo decorativo", "naqsh"), ("simmetria", "simmetriya"),
    ("fatto a mano", "qo'lda ishlangan"), ("pezzo unico", "yagona nusxa"),
    ("laboratorio (artigiano)", "ustaxona (kichik)"), ("mestiere tradizionale", "an'anaviy kasb"),
    ("tramandare", "avlodlarga yetkazmoq"), ("materia prima", "xomashyo"),
    ("mercato dell'artigianato", "hunarmandlar bozori"), ("prezzo giusto", "haqqoniy narx")],
   [("Questi tappeti sono fatti a mano.", "Bu gilamlar qo'lda to'qilgan."),
    ("Il mestiere si tramanda di padre in figlio.", "Kasb otadan bolaga o'tadi.")]),
  ("Musica e danza", "Musiqa va raqs",
   [("strumento tradizionale", "milliy cholg'u"), ("melodia (b1)", "ohang"),
    ("ritmo", "ritm"), ("voce (cantante)", "ovoz (xonanda)"), ("coro", "xor"),
    ("orchestra", "orkestr"), ("concerto tradizionale", "an'anaviy konsert"),
    ("danza popolare", "xalq raqsi"), ("passo di danza", "raqs harakati"),
    ("battere le mani", "qarsak chalmoq"), ("festival", "festival"),
    ("palco (b1)", "sahna (katta)"), ("prova (spettacolo)", "mashq (spektakl)"),
    ("costume di scena", "sahna kiyimi"), ("pubblico entusiasta", "olqishlagan tomoshabin"),
    ("bis", "takror chiqish"), ("registrazione", "yozuv"), ("album", "albom"),
    ("testo della canzone", "qo'shiq so'zlari"), ("significato (canzone)", "ma'no (qo'shiq)"),
    ("tramontare (tradizione)", "unutilib ketmoq")],
   [("Suona uno strumento tradizionale.", "U milliy cholg'u chaladi."),
    ("Il pubblico ha chiesto il bis.", "Tomoshabinlar takror chiqishni so'radi.")]),
  ("Credenze e proverbi", "E'tiqod va maqollar",
   [("proverbio", "maqol"), ("modo di dire (b1)", "ibora"), ("saggezza popolare", "xalq donishmandligi"),
    ("superstizione", "irim"), ("portafortuna", "tumor"), ("malocchio", "ko'z tegishi"),
    ("scaramanzia", "irim qilish"), ("sogno (interpretare)", "tush ta'biri"),
    ("destino", "taqdir"), ("fortuna (destino)", "nasiba"), ("benedizione dei genitori", "ota-ona duosi"),
    ("rispetto per gli anziani", "keksalarga hurmat"), ("consiglio degli anziani", "keksalar maslahati"),
    ("racconto popolare", "xalq hikoyasi"), ("leggenda", "afsona"), ("eroe (leggenda)", "qahramon (afsona)"),
    ("morale (proverbio)", "maqolning mag'zi"), ("insegnamento antico", "qadimiy o'git"),
    ("generazione", "avlod"), ("valore (culturale)", "qadriyat"), ("identità culturale", "madaniy o'ziga xoslik")],
   [("C'è un proverbio che dice così.", "Shunday deydigan bir maqol bor."),
    ("La benedizione dei genitori è importante.", "Ota-ona duosi muhim.")]),
  ("Storia e patrimonio", "Tarix va meros",
   [("patrimonio culturale", "madaniy meros"), ("monumento", "yodgorlik"),
    ("sito archeologico", "arxeologik yodgorlik"), ("scavo", "qazishma"),
    ("reperto", "topilma"), ("museo (collezione)", "muzey to'plami"),
    ("restauro (b1)", "ta'mirlash ishlari"), ("conservazione", "asrash"),
    ("via della seta", "Ipak yo'li"), ("carovana", "karvon"), ("mercante", "savdogar"),
    ("impero", "imperiya"), ("dinastia", "sulola"), ("epoca", "davr"),
    ("secolo (b1)", "asr (davr)"), ("antenato", "ajdod"), ("discendente", "avlod (naslli)"),
    ("guerra", "urush"), ("pace (storia)", "tinchlik"), ("indipendenza (storia)", "mustaqillik"),
    ("memoria storica", "tarixiy xotira")],
   [("Samarcanda era sulla via della seta.", "Samarqand Ipak yo'lida bo'lgan."),
    ("È patrimonio culturale dell'umanità.", "Bu insoniyatning madaniy merosi.")]),
  ("Tra due culture", "Ikki madaniyat orasida",
   [("scambio culturale", "madaniy almashuv"), ("integrarsi", "moslashib ketmoq"),
    ("mantenere le radici", "ildizlarni saqlamoq"), ("seconda lingua", "ikkinchi til"),
    ("bilingue", "ikki tilli"), ("accento (parlare)", "talaffuz ohangi"),
    ("shock culturale", "madaniy zarba"), ("abitudine diversa", "boshqacha odat"),
    ("regola non scritta", "yozilmagan qoida"), ("gesto (significato)", "imo-ishora ma'nosi"),
    ("distanza personale", "shaxsiy masofa"), ("puntualità (cultura)", "vaqtga munosabat"),
    ("formalità", "rasmiyatchilik"), ("familiarità", "yaqinlik (muomalada)"),
    ("umorismo (culturale)", "hazil (madaniy)"), ("tabù (b1)", "taqiqli mavzu"),
    ("curiosità verso l'altro", "boshqaga qiziqish"), ("rispetto delle differenze", "farqlarni hurmat qilish"),
    ("stereotipo culturale", "madaniy qolip"), ("sentirsi a casa", "o'zini uydagidek his qilmoq"),
    ("appartenere", "mansub bo'lmoq")],
   [("All'inizio è stato uno shock culturale.", "Avvaliga bu madaniy zarba bo'ldi."),
    ("Voglio mantenere le mie radici.", "Ildizlarimni saqlab qolmoqchiman.")]),
 ],

 "b1u8": [
  ("Documenti e uffici", "Hujjat va idoralar",
   [("carta d'identità", "shaxsiy guvohnoma"), ("codice fiscale (b1)", "soliq raqami"),
    ("certificato di nascita", "tug'ilganlik guvohnomasi"), ("stato civile", "oilaviy holat"),
    ("residenza (b1)", "ro'yxatdagi manzil"), ("domicilio", "yashash manzili"),
    ("marca da bollo", "davlat boji markasi"), ("autocertificazione", "o'zi tasdiqlagan ariza"),
    ("copia autenticata", "notarial nusxa"), ("traduzione giurata", "rasmiy tarjima"),
    ("apostille", "apostil"), ("modulo online (b1)", "onlayn shakl"),
    ("appuntamento allo sportello", "navbat olish"), ("numero di pratica", "ish raqami"),
    ("ufficio competente", "tegishli idora"), ("orario di apertura (b1)", "qabul vaqti"),
    ("rilascio", "berilishi (hujjat)"), ("rinnovo", "yangilash"), ("scadenza (documento)", "amal muddati"),
    ("smarrimento", "yo'qotish (hujjat)"), ("duplicato", "dublikat")],
   [("Devo rinnovare la carta d'identità.", "Shaxsiy guvohnomani yangilashim kerak."),
    ("Serve una traduzione giurata.", "Rasmiy tarjima kerak.")]),
  ("Banca e finanze", "Bank va moliya",
   [("conto corrente (b1)", "joriy hisob"), ("IBAN", "hisob raqami (IBAN)"),
    ("bonifico (b1)", "pul o'tkazma"), ("addebito", "hisobdan yechish"),
    ("accredito", "hisobga tushish"), ("estratto conto", "hisob ko'chirmasi"),
    ("saldo disponibile", "mavjud qoldiq"), ("scoperto", "manfiy qoldiq"),
    ("carta di debito", "debet karta"), ("carta di credito (b1)", "kredit karta (b1)"),
    ("rata mensile", "oylik to'lov (kredit)"), ("tasso di interesse", "foiz stavkasi"),
    ("mutuo (b1)", "uy krediti"), ("prestito personale", "shaxsiy kredit"),
    ("garante", "kafil"), ("risparmio (conto)", "jamg'arma hisobi"),
    ("investimento (b1)", "sarmoya"), ("commissione bancaria", "bank komissiyasi"),
    ("home banking", "onlayn bank"), ("blocco della carta", "kartani bloklash"),
    ("bancomat", "bankomat")],
   [("Ho fatto un bonifico ieri.", "Kecha pul o'tkazma qildim."),
    ("Qual è il tasso di interesse?", "Foiz stavkasi qancha?")]),
  ("Assicurazioni", "Sug'urta",
   [("polizza", "sug'urta shartnomasi"), ("premio (assicurazione)", "sug'urta to'lovi"),
    ("copertura", "sug'urta qamrovi"), ("franchigia", "shartli to'lov"),
    ("sinistro", "sug'urta hodisasi"), ("risarcimento", "tovon"), ("perizia", "ekspertiza"),
    ("responsabilità civile", "fuqarolik javobgarligi"), ("assicurazione auto", "avto sug'urta"),
    ("assicurazione casa", "uy sug'urtasi"), ("assicurazione viaggio (b1)", "sayohat sug'urtasi (b1)"),
    ("assicurazione vita", "hayot sug'urtasi"), ("scadenza polizza", "polis muddati"),
    ("rinnovo automatico", "avtomatik yangilanish"), ("disdetta (polizza)", "shartnomani bekor qilish"),
    ("clausola", "shart (band)"), ("esclusione", "istisno holat"),
    ("denuncia del sinistro", "hodisa haqida xabar"), ("documentazione (sinistro)", "hujjatlar to'plami"),
    ("tempi di rimborso", "tovon muddati"), ("compagnia assicurativa", "sug'urta kompaniyasi")],
   [("La polizza scade a marzo.", "Polis muddati martda tugaydi."),
    ("Ho denunciato il sinistro ieri.", "Hodisa haqida kecha xabar berdim.")]),
  ("Casa e utenze", "Uy va kommunal xizmatlar",
   [("allacciamento", "ulanish (xizmatga)"), ("contatore", "hisoblagich"),
    ("lettura del contatore", "hisoblagich ko'rsatkichi"), ("consumo mensile", "oylik sarf"),
    ("tariffa", "tarif"), ("fornitore (energia)", "ta'minotchi"),
    ("cambio fornitore", "ta'minotchini almashtirish"), ("bolletta arretrata", "qarzdor hisob"),
    ("sollecito", "eslatma (to'lov)"), ("rateizzazione", "bo'lib to'lash"),
    ("distacco (servizio)", "xizmatdan uzish"), ("riattivazione", "qayta ulash"),
    ("manutenzione", "texnik xizmat"), ("guasto (impianto)", "tizim nosozligi"),
    ("tecnico (intervento)", "usta chaqirish"), ("preventivo (b1)", "smeta"),
    ("condominio", "ko'p qavatli uy jamoasi"), ("amministratore (condominio)", "uy boshqaruvchisi"),
    ("spese comuni", "umumiy xarajatlar (uy)"), ("assemblea condominiale", "uy yig'ilishi"),
    ("regolamento condominiale", "uy qoidalari")],
   [("La bolletta è arrivata più alta del solito.", "Hisob odatdagidan yuqori keldi."),
    ("Ho chiesto la rateizzazione.", "Bo'lib to'lashni so'radim.")]),
  ("Sanità pubblica", "Sog'liqni saqlash tizimi",
   [("tessera sanitaria", "tibbiy karta"), ("medico di base", "oilaviy shifokor"),
    ("specialista", "mutaxassis shifokor"), ("visita specialistica", "mutaxassis ko'rigi"),
    ("prenotazione (visita)", "navbat olish (ko'rik)"), ("lista d'attesa", "navbat ro'yxati"),
    ("ticket (sanità)", "xizmat haqi"), ("esenzione (ticket)", "to'lovdan ozod"),
    ("ricetta medica", "retsept (dori)"), ("farmaco generico", "generik dori"),
    ("pronto soccorso (b1)", "shoshilinch tibbiy yordam"), ("codice (triage)", "shoshilinchlik darajasi"),
    ("ricovero", "kasalxonaga yotqizish"), ("dimissioni (ospedale)", "kasalxonadan chiqish"),
    ("cartella clinica", "kasallik tarixi"), ("referto", "tibbiy xulosa"),
    ("vaccinazione", "emlash"), ("screening", "profilaktik tekshiruv"),
    ("consenso informato", "ogohlangan rozilik"), ("secondo parere", "ikkinchi fikr"),
    ("assistenza domiciliare", "uyda parvarish")],
   [("Ho prenotato una visita specialistica.", "Mutaxassis ko'rigiga navbat oldim."),
    ("La lista d'attesa è lunga.", "Navbat ro'yxati uzun.")]),
  ("Trasporti e regole", "Transport va qoidalar",
   [("abbonamento (trasporti)", "chipta obunasi"), ("tessera (trasporti)", "transport kartasi"),
    ("controllore", "nazoratchi"), ("multa (trasporti)", "jarima (transport)"),
    ("senza biglietto", "chiptasiz"), ("linea (autobus)", "yo'nalish (avtobus)"),
    ("capolinea", "oxirgi bekat"), ("coincidenza (trasporti)", "ulanish reysi"),
    ("orario invernale", "qishki jadval"), ("sciopero (b1)", "ish tashlash"),
    ("servizio sostitutivo", "muqobil xizmat"), ("zona tariffaria", "tarif zonasi"),
    ("limite di velocità", "tezlik chegarasi"), ("divieto di sosta", "to'xtash taqiqlangan"),
    ("zona a traffico limitato", "harakat cheklangan hudud"), ("patente ritirata", "guvohnoma olib qo'yilishi"),
    ("punti della patente", "guvohnoma ballari"), ("revisione (auto)", "texnik ko'rik"),
    ("assicurazione obbligatoria", "majburiy sug'urta"), ("incidente (verbale)", "hodisa dalolatnomasi"),
    ("soccorso stradale", "yo'l yordami")],
   [("Ho preso una multa per divieto di sosta.", "Noto'g'ri to'xtaganim uchun jarima oldim."),
    ("Domani c'è uno sciopero dei trasporti.", "Ertaga transport ish tashlashi bo'ladi.")]),
  ("Reclami e ricorsi", "Shikoyat va e'tirozlar",
   [("reclamo scritto", "yozma shikoyat"), ("ricorso", "e'tiroz arizasi"),
    ("termine (scadenza legale)", "qonuniy muddat"), ("protocollo", "qayd raqami"),
    ("risposta ufficiale", "rasmiy javob"), ("silenzio dell'amministrazione", "idoraning javobsizligi"),
    ("ufficio reclami", "shikoyatlar bo'limi"), ("responsabile del procedimento", "ish yurituvchi"),
    ("prova d'acquisto", "xarid isboti"), ("documentazione allegata", "ilova qilingan hujjatlar"),
    ("richiesta di rimborso", "tovon talabi"), ("risarcimento danni", "zarar qoplash"),
    ("conciliazione", "murosaga kelish"), ("arbitrato", "hakamlik"),
    ("avvocato (consulenza)", "yuridik maslahat"), ("spese legali", "sud xarajatlari"),
    ("causa (legale)", "sud ishi"), ("sentenza", "sud qarori"),
    ("appello", "apellyatsiya"), ("esito (pratica)", "natija (ish)"), ("archiviazione", "ishni yopish")],
   [("Ho presentato un reclamo scritto.", "Yozma shikoyat topshirdim."),
    ("Non ho ancora ricevuto risposta ufficiale.", "Hali rasmiy javob olmadim.")]),
  ("Diritti del consumatore", "Iste'molchi huquqlari",
   [("garanzia legale", "qonuniy kafolat"), ("diritto di recesso", "shartnomadan chiqish huquqi"),
    ("quattordici giorni", "o'n to'rt kun"), ("prodotto difettoso", "nuqsonli mahsulot"),
    ("sostituzione (prodotto)", "mahsulotni almashtirish"), ("riparazione gratuita", "bepul ta'mir"),
    ("pubblicità ingannevole", "aldamchi reklama"), ("clausola vessatoria", "adolatsiz shart"),
    ("contratto capestro", "og'ir shartnoma"), ("costi nascosti", "yashirin xarajatlar"),
    ("preventivo scritto", "yozma smeta"), ("fattura (b1)", "hisob-faktura (b1)"),
    ("scontrino fiscale", "kassa cheki"), ("tutela del consumatore", "iste'molchi himoyasi"),
    ("associazione dei consumatori", "iste'molchilar uyushmasi"),
    ("segnalazione", "xabar berish (nazoratga)"), ("sanzione (azienda)", "kompaniyaga jarima"),
    ("trasparenza (prezzi)", "narx shaffofligi"), ("condizioni contrattuali", "shartnoma shartlari"),
    ("lettura del contratto", "shartnomani o'qish"), ("firma consapevole", "ongli imzo")],
   [("Ho esercitato il diritto di recesso.", "Shartnomadan chiqish huquqimdan foydalandim."),
    ("Conserva sempre lo scontrino.", "Kassa chekini doim saqlang.")]),
 ],
}
