# -*- coding: utf-8 -*-
# A1 — themed vocabulary packs. Each becomes an extra lesson inside its unit, so the
# course reaches the CEFR A1 band (500-1000 words) without diluting the core lessons.
# (titolo it, titolo uz, [vocaboli], [frasi])

EXTRA = {
 "a1u1": [
  ("Cortesia", "Odob qoidalari",
   [("benvenuto", "xush kelibsiz"), ("certo", "albatta"), ("va bene", "mayli"),
    ("d'accordo", "kelishdik"), ("un attimo", "bir daqiqa"), ("aspetta", "kut"),
    ("ascolta", "eshit"), ("guarda", "qara"), ("auguri", "tabriklayman"),
    ("buon appetito", "yoqimli ishtaha"), ("buon viaggio", "oq yo'l"),
    ("buona fortuna", "omad tilayman"), ("mi dispiace", "afsusdaman"),
    ("non importa", "muhim emas"), ("nessun problema", "muammo yo'q"),
    ("volentieri", "bajonidil")],
   [("Un attimo, per favore.", "Bir daqiqa, iltimos."),
    ("Benvenuti a casa nostra!", "Uyimizga xush kelibsiz!")]),
  ("Le domande", "So'roq so'zlar",
   [("chi", "kim"), ("che cosa", "nima"), ("dove", "qayer"), ("quando", "qachon"),
    ("perché", "nega"), ("come", "qanday"), ("quanto", "qancha"), ("quale", "qaysi"),
    ("quanti", "nechta"), ("di chi", "kimning"), ("con chi", "kim bilan"),
    ("da dove", "qayerdan"), ("dove (moto)", "qayerga"), ("davvero?", "rostdanmi?"),
    ("vero?", "shundaymi?"), ("come mai", "nima uchun")],
   [("Chi è quella persona?", "U odam kim?"),
    ("Quando arrivi?", "Qachon kelasan?")]),
  ("Parole utili", "Foydali so'zlar",
   [("anche", "ham"), ("solo", "faqat"), ("e", "va"), ("ma", "lekin"), ("o", "yoki"),
    ("quindi", "shuning uchun"), ("tutto", "hamma narsa"), ("niente", "hech narsa"),
    ("qualcosa", "biror narsa"), ("qualcuno", "kimdir"), ("nessuno", "hech kim"),
    ("ognuno", "har kim"), ("altro", "boshqa"), ("questo", "bu"), ("quello", "o'sha"),
    ("uguale", "xuddi shunday")],
   [("Voglio solo un caffè.", "Men faqat qahva xohlayman."),
    ("Non ho capito niente.", "Men hech narsa tushunmadim.")]),
  ("Paesi e lingue", "Mamlakatlar va tillar",
   [("mondo", "dunyo"), ("Russia", "Rossiya"), ("Turchia", "Turkiya"),
    ("Germania", "Germaniya"), ("Francia", "Fransiya"), ("Spagna", "Ispaniya"),
    ("Inghilterra", "Angliya"), ("America", "Amerika"), ("Cina", "Xitoy"),
    ("russo (lingua)", "rus tili"), ("inglese (lingua)", "ingliz tili"),
    ("turco (lingua)", "turk tili"), ("straniero (agg.)", "xorijiy"),
    ("nazionalità", "millat"), ("capitale (città)", "poytaxt shahar"),
    ("bandiera", "bayroq")],
   [("Parlo anche inglese.", "Men ingliz tilida ham gapiraman."),
    ("Lui viene dalla Turchia.", "U Turkiyadan keladi.")]),
 ],

 "a1u2": [
  ("Parenti", "Qarindoshlar",
   [("zia", "xola"), ("cugino", "amakivachcha"), ("nipote (di nonni)", "nevara"),
    ("suocero", "qaynota"), ("cognato", "qaynog'a"), ("fratello minore", "uka"),
    ("sorella minore", "singil"), ("figli", "bolalar"), ("famiglia grande", "katta oila"),
    ("parente", "qarindosh"), ("vedova", "beva"), ("orfano", "yetim"),
    ("sposi", "kelin-kuyov"), ("sposa", "kelin"), ("sposo", "kuyov"),
    ("madrina", "enaga")],
   [("Ho molti cugini.", "Mening ko'p amakivachchalarim bor."),
    ("Mia zia vive a Bukhara.", "Xolam Buxoroda yashaydi.")]),
  ("L'aspetto", "Tashqi ko'rinish",
   [("capelli", "soch"), ("occhi", "ko'zlar"), ("viso", "yuz"), ("naso", "burun"),
    ("barba", "soqol"), ("baffi", "mo'ylov"), ("magro", "ozg'in"), ("grasso", "semiz"),
    ("forte (fisico)", "baquvvat"), ("debole", "kuchsiz"), ("biondo", "sariq sochli"),
    ("bruno", "qora sochli"), ("carino", "shirin"), ("brutto", "xunuk"),
    ("elegante", "zamonaviy"), ("sorriso", "tabassum")],
   [("Ha i capelli lunghi.", "Uning sochi uzun."),
    ("Che bel sorriso!", "Qanday chiroyli tabassum!")]),
  ("Il carattere", "Fe'l-atvor",
   [("buono (persona)", "yaxshi odam"), ("cattivo", "yomon"), ("timido", "uyatchan"),
    ("socievole", "kirishimli"), ("onesto", "halol"), ("bugiardo", "yolg'onchi"),
    ("paziente", "sabrli"), ("nervoso", "asabiy"), ("calmo", "bosiq"),
    ("curioso", "qiziquvchan"), ("pigro", "dangasa"), ("lavoratore", "mehnatkash"),
    ("coraggioso", "jasur"), ("timoroso", "qo'rqoq"), ("simpatico (persona)", "suhbatdosh"),
    ("educato", "odobli")],
   [("Mia sorella è molto paziente.", "Opam juda sabrli."),
    ("Non essere pigro!", "Dangasa bo'lma!")]),
  ("Come mi sento", "Kayfiyat",
   [("triste", "xafa"), ("arrabbiato", "jahli chiqqan"), ("sorpreso", "hayron"),
    ("annoiato", "zerikkan"), ("preoccupato", "xavotirli"), ("tranquillo", "xotirjam"),
    ("emozionato", "hayajonlangan"), ("solo (sentirsi)", "yolg'iz"),
    ("malato (sentirsi)", "betob"), ("affamato", "och"), ("assetato", "chanqagan"),
    ("assonnato", "uyqusi kelgan"), ("contento", "mamnun"), ("nervoso (teso)", "hayajonda"),
    ("sicuro di sé", "ishonchli"), ("confuso", "chalkash")],
   [("Oggi sono un po' triste.", "Bugun biroz xafaman."),
    ("Sei arrabbiato con me?", "Mendan jahling chiqdimi?")]),
 ],

 "a1u3": [
  ("Fino a mille", "Minggacha",
   [("dodici", "o'n ikki"), ("tredici", "o'n uch"), ("quattordici", "o'n to'rt"),
    ("sedici", "o'n olti"), ("diciassette", "o'n yetti"), ("diciotto", "o'n sakkiz"),
    ("diciannove", "o'n to'qqiz"), ("sessanta", "oltmish"), ("settanta", "yetmish"),
    ("ottanta", "sakson"), ("novanta", "to'qson"), ("duecento", "ikki yuz"),
    ("cinquecento", "besh yuz"), ("duemila", "ikki ming"), ("milione", "million"),
    ("zero", "nol")],
   [("Costa duecento euro.", "Ikki yuz yevro turadi."),
    ("Siamo nel duemilaventicinque.", "Hozir ikki ming yigirma beshinchi yil.")]),
  ("I mesi", "Oylar",
   [("gennaio", "yanvar"), ("febbraio", "fevral"), ("marzo", "mart"), ("aprile", "aprel"),
    ("maggio", "may"), ("giugno", "iyun"), ("luglio", "iyul"), ("agosto", "avgust"),
    ("settembre", "sentabr"), ("ottobre", "oktabr"), ("novembre", "noyabr"),
    ("dicembre", "dekabr"), ("data", "sana"), ("calendario", "taqvim"),
    ("anno nuovo", "yangi yil"), ("secolo", "asr")],
   [("Il mio compleanno è a maggio.", "Tug'ilgan kunim mayda."),
    ("Che data è oggi?", "Bugun qaysi sana?")]),
  ("Quando?", "Qachon?",
   [("stamattina", "bugun ertalab"), ("stasera", "bugun kechqurun"), ("stanotte", "bugun tunda"),
    ("dopodomani", "indinga"), ("l'altro ieri", "avvalgi kuni"), ("presto (fra poco)", "tez orada"),
    ("più tardi", "keyinroq"), ("prima (di)", "…dan oldin"), ("dopo (di)", "…dan keyin"),
    ("durante", "davomida"), ("fino a", "…gacha"), ("da (tempo)", "…dan beri"),
    ("ogni tanto", "vaqti-vaqti bilan"), ("tutto il giorno", "kun bo'yi"),
    ("questa settimana", "shu hafta"), ("l'anno prossimo", "kelasi yil")],
   [("Ci vediamo più tardi.", "Keyinroq ko'rishamiz."),
    ("Studio tutto il giorno.", "Kun bo'yi o'qiyman.")]),
  ("Quanto?", "Qancha?",
   [("molti", "ko'p"), ("pochi", "kam"), ("alcuni", "ba'zilar"), ("abbastanza", "yetarli"),
    ("troppo", "juda ko'p"), ("più", "ortiq"), ("meno", "kamroq"), ("metà", "yarim"),
    ("paio", "juft"), ("pezzo", "bo'lak"), ("chilo", "kilo"), ("litro", "litr"),
    ("scatola", "quti"), ("bottiglia", "shisha"), ("porzione", "ulush"), ("vuoto", "bo'sh")],
   [("Ho pochi soldi.", "Mening kam pulim bor."),
    ("Un chilo di mele, per favore.", "Bir kilo olma, iltimos.")]),
 ],

 "a1u4": [
  ("Frutta e verdura", "Meva va sabzavot",
   [("pera", "nok"), ("pesca", "shaftoli"), ("albicocca", "o'rik"), ("ciliegia", "gilos"),
    ("melone", "qovun"), ("anguria", "tarvuz"), ("melagrana", "anor"), ("fico", "anjir"),
    ("limone", "limon"), ("carota", "sabzi"), ("patata", "kartoshka"), ("cetriolo", "bodring"),
    ("aglio", "sarimsoq"), ("peperone", "qalampir"), ("zucca", "qovoq"), ("verdura fresca", "ko'kat")],
   [("Compro tre chili di uva.", "Uch kilo uzum sotib olaman."),
    ("Le albicocche sono dolci.", "O'riklar shirin.")]),
  ("In cucina", "Oshxonada",
   [("piatto (oggetto)", "likopcha"), ("tazza", "piyola"), ("cucchiaio", "qoshiq"),
    ("forchetta", "vilka"), ("coltello", "pichoq"), ("pentola", "qozon"),
    ("padella", "tova"), ("forno", "pech"), ("fornello", "gaz plita"),
    ("tovagliolo", "salfetka"), ("tovaglia", "dasturxon"), ("bollire", "qaynatmoq"),
    ("friggere", "qovurmoq"), ("tagliare", "kesmoq"), ("mescolare", "aralashtirmoq"),
    ("assaggiare", "tatib ko'rmoq")],
   [("Passami un coltello.", "Menga pichoq uzat."),
    ("L'acqua bolle.", "Suv qaynayapti.")]),
  ("Carne, pane e latticini", "Go'sht, non va sut mahsulotlari",
   [("pollo", "tovuq"), ("manzo", "mol go'shti"), ("agnello", "qo'y go'shti"),
    ("pesce", "baliq"), ("uovo", "tuxum"), ("formaggio", "pishloq"), ("burro", "sariyog'"),
    ("yogurt", "qatiq"), ("panna acida", "smetana"), ("farina", "un"), ("olio", "yog'"),
    ("sale", "tuz"), ("pepe", "qalampir (ziravor)"), ("miele", "asal"),
    ("marmellata", "murabbo"), ("pane caldo", "issiq non")],
   [("Non mangio carne.", "Men go'sht yemayman."),
    ("Passami il sale, per favore.", "Tuzni uzat, iltimos.")]),
  ("I pasti", "Ovqatlar",
   [("pranzo (pasto)", "tushlik"), ("spuntino", "yengil taom"), ("antipasto", "gazak"),
    ("primo piatto", "birinchi taom"), ("secondo", "ikkinchi taom"), ("porzione grande", "katta ulush"),
    ("affamato (essere)", "qorni och"), ("sazio", "to'q"), ("gustoso", "lazzatli"),
    ("insipido", "bemaza"), ("acido", "nordon"), ("amaro", "achchiq (taxir)"),
    ("caldo (cibo)", "issiq taom"), ("freddo (cibo)", "sovuq taom"),
    ("fatto in casa", "uyda tayyorlangan"), ("ricetta di famiglia", "oilaviy retsept")],
   [("Questo piatto è delizioso.", "Bu taom juda lazzatli."),
    ("Sono sazia, grazie.", "To'ydim, rahmat.")]),
 ],

 "a1u5": [
  ("Le stanze", "Xonalar",
   [("ingresso", "dahliz"), ("corridoio", "yo'lak"), ("soggiorno", "mehmonxona"),
    ("balcone", "balkon"), ("terrazza", "ayvon"), ("cantina", "yerto'la"),
    ("soffitta", "chordoq"), ("scala", "zina"), ("ascensore", "lift"),
    ("tetto", "tom"), ("muro", "devor"), ("pavimento", "pol"), ("soffitto", "shift"),
    ("cortile", "hovli"), ("cancello", "darvoza"), ("citofono", "eshik qo'ng'irog'i")],
   [("Il bagno è in fondo al corridoio.", "Hammom yo'lakning oxirida."),
    ("Saliamo con l'ascensore.", "Liftda chiqamiz.")]),
  ("In bagno", "Hammomda",
   [("sapone", "sovun"), ("asciugamano (bagno)", "sochiq"), ("spazzolino", "tish cho'tkasi"),
    ("dentifricio", "tish pastasi"), ("pettine", "taroq"), ("shampoo", "shampun"),
    ("rasoio", "ustara"), ("profumo", "atir"), ("lavandino", "rakovina"),
    ("acqua calda", "issiq suv"), ("acqua fredda", "sovuq suv"), ("pulito", "toza"),
    ("asciutto", "quruq"), ("bagnato", "ho'l"), ("specchio (bagno)", "ko'zgu"),
    ("carta igienica", "tualet qog'ozi")],
   [("Non c'è acqua calda.", "Issiq suv yo'q."),
    ("Dov'è il sapone?", "Sovun qayerda?")]),
  ("Elettrodomestici", "Maishiy texnika",
   [("lavatrice", "kir yuvish mashinasi"), ("forno a microonde", "mikroto'lqinli pech"),
    ("bollitore", "choynak (elektr)"), ("aspirapolvere", "changyutgich"),
    ("ventilatore", "ventilyator"), ("condizionatore", "konditsioner"),
    ("stufa", "isitgich"), ("ferro da stiro", "dazmol"), ("presa", "rozetka"),
    ("interruttore", "vyklyuchatel"), ("cavo", "sim"), ("accendere", "yoqmoq"),
    ("spegnere", "o'chirmoq"), ("funzionare", "ishlamoq"), ("guasto (agg.)", "ishlamayapti"),
    ("caricabatterie", "quvvatlagich")],
   [("Accendi il condizionatore.", "Konditsionerni yoq."),
    ("La lavatrice non funziona.", "Kir yuvish mashinasi ishlamayapti.")]),
  ("I vestiti", "Kiyimlar",
   [("camicia", "ko'ylak (erkak)"), ("maglietta", "futbolka"), ("maglione", "sviter"),
    ("pantaloni", "shim"), ("gonna", "yubka"), ("vestito (abito)", "libos"),
    ("giacca", "kurtka"), ("cappotto", "palto"), ("cappello", "shapka"),
    ("sciarpa", "sharf"), ("guanti", "qo'lqop"), ("calzini", "paypoq"),
    ("cintura", "kamar"), ("zaino", "ryukzak"), ("indossare", "kiymoq"),
    ("togliersi", "yechmoq")],
   [("Fa freddo, metti il cappotto.", "Sovuq, paltoni kiy."),
    ("Questa gonna è troppo lunga.", "Bu yubka juda uzun.")]),
 ],

 "a1u6": [
  ("I negozi", "Do'konlar",
   [("panetteria", "nonvoyxona"), ("macelleria", "qassobxona"), ("pasticceria", "shirinlik do'koni"),
    ("libreria", "kitob do'koni"), ("edicola", "gazeta kiosk"), ("parrucchiere", "sartaroshxona"),
    ("supermercato (negozio)", "do'kon (katta)"), ("centro commerciale", "savdo markazi"),
    ("bancarella", "rasta"), ("vetrina", "vitrina"), ("scaffale", "javon"),
    ("commesso (negozio)", "sotuvchi yigit"), ("cliente (negozio)", "xaridor"),
    ("aperto", "ochiq"), ("chiuso", "yopiq"), ("orario (negozio)", "ish vaqti (do'kon)")],
   [("Il negozio è chiuso la domenica.", "Do'kon yakshanba kuni yopiq."),
    ("Vado in panetteria.", "Men nonvoyxonaga boraman.")]),
  ("Edifici e servizi", "Binolar va xizmatlar",
   [("posta", "pochta"), ("chiesa", "cherkov"), ("moschea (edificio)", "masjid"),
    ("biblioteca (edificio)", "kutubxona binosi"), ("teatro", "teatr"),
    ("stadio", "stadion"), ("piscina", "basseyn"), ("palestra", "sport zali"),
    ("commissariato", "politsiya bo'limi"), ("municipio", "hokimiyat"),
    ("università (edificio)", "universitet binosi"), ("asilo", "bog'cha"),
    ("mercato coperto", "yopiq bozor"), ("fontana", "favvora"), ("statua", "haykal"),
    ("parcheggio", "to'xtash joyi")],
   [("La posta è vicino al municipio.", "Pochta hokimiyat yonida."),
    ("Andiamo in piscina domani.", "Ertaga basseynga boramiz.")]),
  ("Per strada", "Ko'chada",
   [("marciapiede", "piyodalar yo'li"), ("incrocio", "chorraha"), ("rotonda", "aylanma"),
    ("striscia pedonale", "piyoda o'tish joyi"), ("cartello", "belgi"),
    ("direzione", "yo'nalish"), ("vicolo", "tor ko'cha"), ("viale", "xiyobon"),
    ("traffico (strada)", "harakat"), ("autista (taxi)", "taksi haydovchisi"),
    ("passaggio", "o'tish"), ("fermarsi", "to'xtamoq"), ("aspettare (bus)", "kutib turmoq"),
    ("salire (bus)", "avtobusga chiqmoq"), ("scendere (bus)", "avtobusdan tushmoq"),
    ("perdere (il bus)", "o'tkazib yubormoq")],
   [("Attraversa sulle strisce.", "Piyoda o'tish joyidan o't."),
    ("Il bus si ferma qui.", "Avtobus shu yerda to'xtaydi.")]),
  ("Soldi", "Pul",
   [("banconota", "pul qog'ozi"), ("moneta", "tanga"), ("resto", "qaytim"),
    ("portafoglio", "hamyon"), ("contanti", "naqd pul"), ("carta (di pagamento)", "to'lov kartasi"),
    ("scontrino", "chek"), ("costo", "narxi"), ("gratis", "bepul"),
    ("caro (costoso)", "bahosi baland"), ("a buon mercato", "arzonroq"),
    ("pagare", "to'lamoq"), ("prestare", "qarz bermoq"), ("restituire", "qaytarmoq"),
    ("risparmiare (soldi)", "pul yig'moq"), ("spendere", "sarflamoq")],
   [("Ha il resto di cinquanta?", "Ellikdan qaytim bormi?"),
    ("Pago in contanti.", "Naqd pul bilan to'layman.")]),
 ],

 "a1u7": [
  ("Verbi di ogni giorno", "Kundalik fe'llar",
   [("fare", "qilmoq"), ("dare", "bermoq"), ("prendere", "olmoq"), ("mettere", "qo'ymoq"),
    ("aprire", "ochmoq"), ("chiudere", "yopmoq"), ("entrare", "kirmoq"), ("uscire (fuori)", "tashqariga chiqmoq"),
    ("sedersi", "o'tirmoq"), ("alzarsi (in piedi)", "turmoq"), ("camminare (andare a piedi)", "piyoda yurmoq"),
    ("correre (verbo)", "yugurib bormoq"), ("portare", "olib bormoq"), ("cercare", "qidirmoq"),
    ("trovare", "topmoq"), ("perdere", "yo'qotmoq")],
   [("Apri la finestra, per favore.", "Derazani och, iltimos."),
    ("Non trovo le chiavi.", "Kalitlarni topa olmayapman.")]),
  ("A scuola e al lavoro", "Maktab va ishda",
   [("aula", "sinfxona"), ("lavagna", "doska"), ("quaderno", "daftar"), ("matita", "qalam"),
    ("gomma", "o'chirg'ich"), ("zaino (scuola)", "maktab sumkasi"), ("banco", "parta"),
    ("compagno di classe", "sinfdosh"), ("preside", "direktor"), ("esercizio", "mashq"),
    ("errore", "xato"), ("risposta", "javob"), ("domanda (scuola)", "savol"),
    ("voto (scuola)", "baho"), ("intervallo", "tanaffus (maktab)"), ("iscrizione", "ro'yxat")],
   [("Scrivi sul quaderno.", "Daftarga yoz."),
    ("Non capisco questo esercizio.", "Bu mashqni tushunmayapman.")]),
  ("In casa, ogni giorno", "Uyda, har kuni",
   [("svegliare", "uyg'otmoq"), ("preparare", "tayyorlamoq"), ("chiamare (al telefono)", "telefon qilmoq"),
    ("aiutare (in casa)", "uy ishida yordam bermoq"), ("ordinare (in ordine)", "tartibga solmoq"),
    ("buttare", "tashlamoq"), ("chiudere a chiave", "qulflamoq"), ("annaffiare", "sug'ormoq"),
    ("riparare (casa)", "ta'mirlamoq"), ("appendere", "ilmoq"), ("piegare", "buklamoq"),
    ("asciugare", "quritmoq"), ("bagnare", "ho'llamoq"), ("rompere", "sindirmoq"),
    ("perdere tempo", "vaqtni behuda sarflamoq"), ("sbrigarsi", "shoshilmoq")],
   [("Mi sveglio da sola.", "Men o'zim uyg'onaman."),
    ("Sbrigati, siamo in ritardo!", "Shoshil, kechikyapmiz!")]),
  ("Avverbi di tempo", "Vaqt ravishlari",
   [("subito (adesso)", "hoziroq"), ("piano (lentamente)", "sekin"), ("velocemente", "tez"),
    ("insieme (con altri)", "birgalikda"), ("da solo", "yolg'iz o'zi"), ("di nuovo", "qaytadan"),
    ("finalmente", "nihoyat"), ("all'improvviso (subito)", "birdan"), ("di solito (abituale)", "odatdagidek"),
    ("per esempio", "masalan"), ("almeno", "hech bo'lmaganda"), ("circa", "taxminan"),
    ("esattamente", "aniq"), ("quasi", "deyarli"), ("appena (poco fa)", "endigina"),
    ("ancora una volta", "yana bir bor")],
   [("Parla più piano, per favore.", "Sekinroq gapiring, iltimos."),
    ("Finalmente sei arrivato!", "Nihoyat yetib kelding!")]),
 ],

 "a1u8": [
  ("Sport", "Sport turlari",
   [("pallavolo", "voleybol"), ("pallacanestro", "basketbol"), ("tennis", "tennis"),
    ("lotta", "kurash"), ("scacchi", "shaxmat"), ("ciclismo", "velosport"),
    ("squadra (sport)", "jamoa (sport)"), ("partita", "o'yin"), ("gara", "musobaqa"),
    ("vincere", "yutmoq"), ("perdere (gara)", "yutqazmoq"), ("allenamento (sport)", "mashg'ulot"),
    ("allenatore", "murabbiy"), ("campo (sportivo)", "maydon (sport)"), ("palla", "to'p"),
    ("tifoso", "muxlis")],
   [("Chi ha vinto la partita?", "O'yinni kim yutdi?"),
    ("Gioco a pallavolo il martedì.", "Seshanba kuni voleybol o'ynayman.")]),
  ("Musica e arte", "Musiqa va san'at",
   [("canzone", "qo'shiq"), ("cantante", "xonanda"), ("chitarra", "gitara"),
    ("pianoforte", "pianino"), ("tamburo", "doira"), ("dutar", "dutor"),
    ("concerto (evento)", "konsert (tadbir)"), ("ballo", "raqs"), ("quadro", "surat (rasm)"),
    ("colore (arte)", "bo'yoq"), ("fotografia", "fotosurat"), ("macchina fotografica", "fotoapparat"),
    ("teatro (spettacolo)", "spektakl"), ("biglietto (spettacolo)", "tomosha chiptasi"),
    ("artista", "san'atkor"), ("hobby", "mashg'ulot")],
   [("Mi piace questa canzone.", "Menga bu qo'shiq yoqadi."),
    ("Suona il dutar molto bene.", "U dutorni juda yaxshi chaladi.")]),
  ("La natura", "Tabiat",
   [("fiume", "daryo"), ("lago", "ko'l"), ("collina", "tepalik"), ("valle", "vodiy"),
    ("bosco", "o'rmon"), ("campo (agricolo)", "dala"), ("fiore", "gul"), ("erba", "o't"),
    ("foglia", "barg"), ("pietra", "tosh"), ("sabbia", "qum"), ("terra", "tuproq"),
    ("stella", "yulduz"), ("luna", "oy (osmon)"), ("aria", "havo"), ("fuoco", "olov")],
   [("Andiamo al fiume domenica.", "Yakshanba kuni daryoga boramiz."),
    ("Che bei fiori!", "Qanday chiroyli gullar!")]),
  ("Animali", "Hayvonlar",
   [("cane", "it"), ("gatto", "mushuk"), ("cavallo", "ot"), ("asino", "eshak"),
    ("mucca", "sigir"), ("pecora", "qo'y"), ("gallina", "tovuq (jonzot)"), ("uccello", "qush"),
    ("cammello", "tuya"), ("topo", "sichqon"), ("pesce (animale)", "baliq (jonzot)"),
    ("insetto", "hasharot"), ("ape", "asalari"), ("lupo", "bo'ri"), ("volpe", "tulki"),
    ("animale domestico", "uy hayvoni")],
   [("Ho un gatto nero.", "Mening qora mushugim bor."),
    ("I cammelli vivono nel deserto.", "Tuyalar cho'lda yashaydi.")]),
 ],
}
