# -*- coding: utf-8 -*-
# B2 — vocabulary packs, units 1-3 (CEFR band 4000-8000 cumulative words).

EXTRA = {
 "b2u1": [
  ("La retorica", "Notiqlik san'ati",
   [("eloquenza", "notiqlik"), ("oratore", "notiq"), ("discorso (orazione)", "nutq (ma'ruza)"),
    ("enfasi", "urg'u"), ("pausa retorica", "ta'sirli pauza"), ("domanda retorica", "ritorik savol"),
    ("metafora (b2)", "metafora (ko'chma ma'no)"), ("analogia", "o'xshatish"),
    ("iperbole", "bo'rttirish"), ("ripetizione (stile)", "takror (uslub)"),
    ("climax", "kuchaytirish"), ("aneddoto (discorso)", "hikoyacha (nutqda)"),
    ("apertura (discorso)", "kirish qismi"), ("chiusura (discorso)", "yakuniy qism"),
    ("filo conduttore", "asosiy yo'nalish"), ("tono persuasivo", "ishontiruvchi ohang"),
    ("linguaggio del corpo", "tana tili"), ("contatto visivo", "ko'z bilan aloqa"),
    ("carisma", "jozibadorlik"), ("credibilità (oratore)", "notiq ishonchi"),
    ("impatto (discorso)", "nutq ta'siri")],
   [("Ha usato una metafora molto efficace.", "U juda ta'sirli metafora ishlatdi."),
    ("Il contatto visivo aumenta la credibilità.", "Ko'z bilan aloqa ishonchni oshiradi.")]),
  ("Struttura di un'argomentazione", "Dalillash tuzilmasi",
   [("premessa (b2)", "asos (muqaddima)"), ("assunto", "qabul qilingan fikr"),
    ("ipotesi di partenza", "boshlang'ich faraz"), ("corollario", "natija (mantiqiy)"),
    ("deduzione", "deduksiya"), ("induzione", "induksiya"), ("inferenza", "xulosa chiqarish"),
    ("coerenza", "izchillik"), ("incoerenza", "izchilsizlik"), ("rigore", "qat'iylik"),
    ("approssimazione", "taxminiylik"), ("precisazione", "aniqlashtirish"),
    ("obiezione preventiva", "oldindan e'tirozga javob"), ("controargomento", "qarshi dalil"),
    ("sintesi finale", "yakuniy xulosa"), ("tesi centrale", "markaziy fikr"),
    ("sviluppo (argomento)", "fikrni rivojlantirish"), ("digressione", "chekinish (mavzudan)"),
    ("esempio pertinente", "o'rinli misol"), ("dato rilevante", "muhim ko'rsatkich"),
    ("conclusione convincente", "ishonarli xulosa")],
   [("La sua argomentazione manca di coerenza.", "Uning dalillashida izchillik yetishmaydi."),
    ("Partiamo da un'ipotesi di partenza chiara.", "Aniq boshlang'ich farazdan yo'lga chiqaylik.")]),
  ("Confutare con metodo", "Uslubiy rad etish",
   [("smentire (b2)", "asossizligini ko'rsatmoq"), ("confutazione", "rad etish"),
    ("contestare", "e'tiroz bildirmoq (rasmiy)"), ("mettere in discussione", "shubha ostiga olmoq"),
    ("ridimensionare (b2)", "ahamiyatini pasaytirmoq"), ("relativizzare", "nisbiylashtirmoq"),
    ("distinguere", "farqlamoq"), ("sfumare", "yumshatib aytmoq"),
    ("riformulare", "boshqacha ifodalamoq"), ("chiedere chiarimenti", "izoh so'ramoq"),
    ("individuare una falla", "kamchilikni topmoq"), ("errore di logica", "mantiqiy xato"),
    ("prova insufficiente", "yetarsiz dalil"), ("fonte dubbia", "shubhali manba"),
    ("conflitto d'interessi", "manfaatlar to'qnashuvi"), ("pregiudizio metodologico", "uslubiy xatolik"),
    ("campione non rappresentativo", "vakillik qilmaydigan namuna"),
    ("correlazione", "bog'liqlik"), ("causalità", "sababiy bog'liqlik"),
    ("coincidenza", "tasodif"), ("scetticismo", "shubhachilik")],
   [("Correlazione non significa causalità.", "Bog'liqlik sababiy bog'liqlikni anglatmaydi."),
    ("Ha individuato una falla nel ragionamento.", "U mulohazadagi kamchilikni topdi.")]),
  ("Negoziare ad alto livello", "Yuqori darajadagi muzokara",
   [("trattativa serrata", "keskin muzokara"), ("posta in gioco", "xavf ostidagi manfaat"),
    ("margine di manovra", "harakat erkinligi"), ("linea rossa", "qizil chiziq"),
    ("concessione", "yon berish"), ("contropartita", "evaziga beriladigan narsa"),
    ("pacchetto (offerta)", "taklif to'plami"), ("clausola (b2)", "shartnoma bandi"),
    ("vincolo (b2)", "majburiy shart"), ("scadenza (negoziato)", "kelishuv muddati"),
    ("stallo", "boshi berk ko'cha"), ("sbloccare", "muzdan chiqarmoq"),
    ("mediatore", "vositachi"), ("firmatario", "imzolovchi tomon"),
    ("intesa preliminare", "dastlabki kelishuv"), ("accordo vincolante", "majburiy kelishuv"),
    ("recesso (accordo)", "kelishuvdan chiqish"), ("rinegoziare", "qayta muzokara qilmoq"),
    ("buona fede", "vijdonan"), ("reciprocità", "o'zaro tenglik"),
    ("win-win", "ikki tomon uchun foydali")],
   [("Su questo punto c'è una linea rossa.", "Bu masalada qizil chiziq bor."),
    ("Abbiamo raggiunto un'intesa preliminare.", "Dastlabki kelishuvga erishdik.")]),
  ("Linguaggio formale", "Rasmiy uslub",
   [("in merito a", "…ga doir"), ("ai sensi di", "…ga muvofiq"), ("in conformità", "muvofiq ravishda"),
    ("pertanto", "shu sababli"), ("qualora", "agar shunday bo'lsa"), ("laddove", "…joyda (rasmiy)"),
    ("suddetto", "yuqorida qayd etilgan"), ("in allegato", "ilova tarzida"),
    ("si comunica che", "ma'lum qilinadiki"), ("si richiede", "so'ralmoqda"),
    ("si dispone", "belgilanadi"), ("con la presente", "mazkur xat orqali"),
    ("in via preliminare", "dastlabki tarzda"), ("in via definitiva", "yakuniy tarzda"),
    ("salvo diversa indicazione", "boshqacha ko'rsatilmagan bo'lsa"),
    ("fatto salvo", "bundan mustasno"), ("a titolo di esempio", "misol tariqasida"),
    ("per quanto riguarda", "…ga kelsak"), ("in ogni caso (formale)", "har qanday holatda"),
    ("resta inteso che", "shu narsa aniqki"), ("distinti saluti", "hurmat ila")],
   [("In merito alla sua richiesta, le comunico quanto segue.", "So'rovingizga doir quyidagilarni ma'lum qilaman."),
    ("Resta inteso che i costi sono a carico vostro.", "Shu narsa aniqki, xarajatlar siz tomondan qoplanadi.")]),
  ("Trappole del ragionamento", "Mulohaza tuzoqlari",
   [("attacco personale", "shaxsga o'tish"), ("generalizzazione affrettata", "shoshma-shosharlik bilan umumlashtirish"),
    ("falso dilemma", "soxta tanlov"), ("appello all'autorità", "obro'ga tayanish"),
    ("appello alle emozioni", "tuyg'ularga urg'u"), ("argomento circolare", "aylanma dalil"),
    ("cherry picking", "qulay ma'lumotni tanlash"), ("uomo di paglia", "soxta raqib fikri"),
    ("pendio scivoloso", "zanjirli xulosa"), ("luogo comune", "kundalik qolip"),
    ("mezza verità", "yarim haqiqat"), ("omissione", "tushirib qoldirish"),
    ("manipolazione (b2)", "ong bilan o'ynash"), ("propaganda (b2)", "targ'ibot (yo'naltirilgan)"),
    ("distorsione", "buzib ko'rsatish"), ("esagerazione", "bo'rttirib yuborish"),
    ("semplificazione eccessiva", "haddan ortiq soddalashtirish"),
    ("bias di conferma", "o'z fikrini tasdiqlash moyilligi"),
    ("effetto gregge", "olomon ta'siri"), ("pensiero critico (b2)", "tanqidiy tafakkur"),
    ("verifica indipendente", "mustaqil tekshiruv")],
   [("È un classico falso dilemma.", "Bu klassik soxta tanlov."),
    ("Attenzione al bias di conferma.", "O'z fikrini tasdiqlash moyiligidan ehtiyot bo'ling.")]),
  ("Mediare tra posizioni", "Qarashlar o'rtasida vositachilik",
   [("moderare (dibattito)", "muhokamani boshqarmoq"), ("dare la parola", "so'z bermoq"),
    ("togliere la parola", "so'zni to'xtatmoq"), ("riassumere le posizioni", "tomonlarni jamlamoq"),
    ("evidenziare i punti comuni", "umumiy nuqtalarni ko'rsatmoq"),
    ("isolare il disaccordo", "kelishmovchilikni ajratmoq"), ("abbassare i toni", "ohangni pasaytirmoq"),
    ("riportare al tema", "mavzuga qaytarmoq"), ("dare spazio a tutti", "hammaga imkon bermoq"),
    ("equilibrio (dibattito)", "muvozanat (munozara)"), ("imparzialità", "xolislik"),
    ("neutralità", "betaraflik"), ("ascolto reciproco", "o'zaro tinglash"),
    ("rispetto dei turni", "navbatga rioya"), ("tempo assegnato", "ajratilgan vaqt"),
    ("replica", "javob so'zi"), ("controreplica", "qayta javob"),
    ("chiusura del dibattito", "muhokama yakuni"), ("verbalizzare", "bayonga kiritmoq"),
    ("punto di caduta", "murosa nuqtasi"), ("consenso", "umumiy rozilik")],
   [("Cerchiamo di evidenziare i punti comuni.", "Keling, umumiy nuqtalarni ko'rsataylik."),
    ("Il moderatore ha abbassato i toni.", "Boshlovchi ohangni pasaytirdi.")]),
  ("Parlare in pubblico", "Omma oldida nutq",
   [("platea", "zal (tinglovchilar)"), ("ansia da palcoscenico", "sahna hayajoni"),
    ("respirazione", "nafas nazorati"), ("postura (oratore)", "notiq turishi"),
    ("gestualità", "imo-ishoralar"), ("proiezione della voce", "ovoz kuchi"),
    ("velocità del parlato", "gapirish tezligi"), ("chiarezza espositiva", "bayon aniqligi"),
    ("supporto visivo", "ko'rgazmali vosita"), ("slide", "slayd (taqdimot)"),
    ("scaletta", "reja (nutq)"), ("tempo a disposizione (b2)", "ajratilgan vaqt (nutq)"),
    ("domande dal pubblico", "zaldan savollar"), ("gestire l'imprevisto", "kutilmaganni boshqarmoq"),
    ("interazione", "o'zaro muloqot"), ("coinvolgere", "jalb qilmoq"),
    ("mantenere l'attenzione", "e'tiborni ushlab turmoq"), ("battuta (rompere il ghiaccio)", "muzni sindiruvchi hazil"),
    ("messaggio chiave", "asosiy xabar"), ("chiusura efficace", "ta'sirli yakun"),
    ("applausi", "qarsaklar")],
   [("Ha gestito bene le domande dal pubblico.", "U zaldan kelgan savollarni yaxshi uddaladi."),
    ("Il messaggio chiave deve restare uno.", "Asosiy xabar bitta bo'lib qolishi kerak.")]),
  ("Sfumature del dire", "Aytishning nozikliklari",
   [("affermare con cautela", "ehtiyotkorlik bilan aytmoq"), ("lasciare intendere", "ishora qilmoq"),
    ("alludere", "kinoya bilan aytmoq"), ("sottintendere", "nazarda tutmoq"),
    ("insinuare", "shama qilmoq"), ("precisare (b2)", "aniqlik kiritib aytmoq"),
    ("ammorbidire", "yumshatmoq (gapni)"), ("rafforzare (b2)", "kuchaytirib aytmoq"),
    ("ribadire", "qayta ta'kidlamoq"), ("smorzare", "so'ndirmoq (bahsni)"),
    ("prendere le distanze", "o'zini chetga olmoq"), ("astenersi dal commentare", "izohdan tiyilmoq"),
    ("riservarsi", "keyinga qoldirmoq (fikrni)"), ("non escludere", "istisno qilmaslik"),
    ("limitarsi a dire", "shuni aytish bilan cheklanmoq"), ("in confidenza", "sirdoshlik bilan"),
    ("ufficiosamente", "norasmiy ravishda"), ("ufficialmente", "rasmiy ravishda"),
    ("a titolo personale", "shaxsiy fikr sifatida"), ("senza mezzi termini (b2)", "ochiqdan-ochiq"),
    ("giri di parole", "gapni aylantirish")],
   [("Non escludo che sia vero.", "Rost bo'lishini istisno qilmayman."),
    ("Parliamone senza giri di parole.", "Gapni aylantirmay gaplashaylik.")]),
  ("Citare e riferire", "Iqtibos va bayon",
   [("citare", "iqtibos keltirmoq"), ("citazione", "iqtibos"), ("virgolette", "qo'shtirnoq"),
    ("fonte primaria", "birlamchi manba"), ("fonte secondaria", "ikkilamchi manba"),
    ("riferire (parole)", "so'zlarni yetkazmoq"), ("parafrasare", "boshqa so'z bilan aytmoq"),
    ("riassunto (testo)", "qisqacha bayon"), ("estratto", "parcha"), ("nota a piè di pagina", "izoh (sahifa ostida)"),
    ("bibliografia", "adabiyotlar ro'yxati"), ("plagio", "plagiat"),
    ("attribuire", "muallifligini ko'rsatmoq"), ("secondo l'autore", "muallifning fikricha"),
    ("come sostiene", "…ta'kidlaganidek"), ("a detta di", "…ning aytishicha"),
    ("stando a quanto riportato", "xabarlarga ko'ra"), ("fuori contesto", "kontekstdan uzilgan"),
    ("interpretazione errata", "noto'g'ri talqin"), ("traduzione fedele", "aniq tarjima"),
    ("fedeltà al testo", "matnga sodiqlik")],
   [("Questa citazione è fuori contesto.", "Bu iqtibos kontekstdan uzilgan."),
    ("Secondo l'autore, il fenomeno è recente.", "Muallifning fikricha, bu hodisa yangi.")]),
  ("Concedere e riservare", "Yon berish va shart qo'yish",
   [("ammesso che", "faraz qilaylik"), ("posto che", "shuni hisobga olsak"),
    ("a patto che", "shu shart bilan"), ("purché", "faqat shunda"),
    ("a meno che", "agar …bo'lmasa"), ("salvo che", "…dan tashqari"),
    ("anche ammettendo", "hatto tan olganda ham"), ("pur riconoscendo", "e'tirof etgan holda"),
    ("se non altro", "hech bo'lmaganda"), ("quanto meno", "eng kamida (b2)"),
    ("in parte (concessione)", "ma'lum darajada"), ("entro certi limiti", "muayyan chegarada"),
    ("con riserva", "ehtiyot shart bilan"), ("con le dovute eccezioni", "tegishli istisnolar bilan"),
    ("in linea di principio", "tamoyil jihatidan"), ("in casi eccezionali", "istisno hollarda"),
    ("di norma", "odatda (qoida bo'yicha)"), ("in via eccezionale", "istisno tariqasida"),
    ("fino a prova contraria", "aksi isbotlanmaguncha"), ("salvo imprevisti", "kutilmagan hol bo'lmasa"),
    ("con il beneficio del dubbio", "shubha foydasiga")],
   [("Accetto, a patto che sia per iscritto.", "Yozma bo'lishi sharti bilan roziman."),
    ("Pur riconoscendo il problema, non è urgente.", "Muammoni tan olgan holda, u shoshilinch emas.")]),
 ],

 "b2u2": [
  ("Macroeconomia", "Makroiqtisodiyot",
   [("prodotto interno lordo", "yalpi ichki mahsulot"), ("crescita economica", "iqtisodiy o'sish"),
    ("recessione", "turg'unlik"), ("ripresa", "tiklanish"), ("stagnazione", "sustlik"),
    ("deflazione", "deflyatsiya"), ("potere d'acquisto (b2)", "sotib olish qobiliyati (b2)"),
    ("tasso di cambio", "valyuta kursi"), ("valuta", "valyuta"), ("svalutazione", "qadrsizlanish"),
    ("debito pubblico", "davlat qarzi"), ("deficit", "taqchillik"), ("surplus", "ortiqcha"),
    ("bilancia commerciale", "savdo balansi"), ("esportazioni", "eksport"),
    ("importazioni", "import"), ("dazio", "boj"), ("politica monetaria", "pul-kredit siyosati"),
    ("banca centrale", "markaziy bank"), ("tasso di riferimento", "asosiy stavka"),
    ("indicatore economico", "iqtisodiy ko'rsatkich")],
   [("L'inflazione erode il potere d'acquisto.", "Inflyatsiya sotib olish qobiliyatini yeydi."),
    ("La banca centrale ha alzato i tassi.", "Markaziy bank stavkalarni oshirdi.")]),
  ("Mercato del lavoro", "Mehnat bozori",
   [("occupazione", "bandlik"), ("tasso di disoccupazione", "ishsizlik darajasi"),
    ("forza lavoro", "ishchi kuchi"), ("manodopera", "mehnat resursi"),
    ("qualificato", "malakali"), ("non qualificato", "malakasiz"),
    ("riqualificazione", "qayta tayyorlash"), ("automazione (lavoro)", "avtomatlashtirish (ish)"),
    ("delocalizzazione", "ishlab chiqarishni ko'chirish"), ("lavoro sommerso", "norasmiy ish"),
    ("contratto atipico", "nostandart shartnoma"), ("precariato", "beqaror bandlik"),
    ("salario minimo", "eng kam ish haqi"), ("divario salariale", "maosh tafovuti"),
    ("produttività (b2)", "mehnat unumdorligi"), ("orario ridotto", "qisqartirilgan ish vaqti"),
    ("smart working", "masofaviy bandlik"), ("mobilità del lavoro", "mehnat harakatchanligi"),
    ("fuga di cervelli", "miya oqimi"), ("immigrazione economica", "iqtisodiy migratsiya"),
    ("welfare aziendale", "xodimlar farovonligi")],
   [("Il tasso di disoccupazione è sceso.", "Ishsizlik darajasi pasaydi."),
    ("La fuga di cervelli è un problema serio.", "Miya oqimi jiddiy muammo.")]),
  ("Fare impresa", "Tadbirkorlik yuritish",
   [("impresa individuale", "yakka tartibdagi tadbirkor"), ("società (azienda)", "jamiyat (korxona)"),
    ("socio", "ta'sischi"), ("quota", "ulush"), ("capitale sociale", "ustav kapitali"),
    ("statuto", "nizom (korxona)"), ("consiglio di amministrazione", "kuzatuv kengashi"),
    ("assemblea dei soci", "ta'sischilar yig'ilishi"), ("utile", "sof foyda"),
    ("perdita d'esercizio", "yillik zarar"), ("fatturato annuo", "yillik aylanma"),
    ("margine", "foyda ulushi"), ("costo fisso", "doimiy xarajat"), ("costo variabile", "o'zgaruvchan xarajat"),
    ("punto di pareggio", "zararsizlik nuqtasi"), ("liquidità", "likvidlik"),
    ("flusso di cassa", "pul oqimi"), ("investitore", "investor"),
    ("quota di mercato", "bozor ulushi"), ("concorrente", "raqobatchi"), ("fallimento", "bankrotlik")],
   [("Il fatturato annuo è cresciuto del dieci per cento.", "Yillik aylanma o'n foizga oshdi."),
    ("Abbiamo raggiunto il punto di pareggio.", "Zararsizlik nuqtasiga yetdik.")]),
  ("Finanza", "Moliya",
   [("azione (borsa)", "aksiya"), ("obbligazione", "obligatsiya"), ("borsa valori", "fond birjasi"),
    ("rendimento", "daromadlilik"), ("rischio d'investimento", "sarmoya xavfi"),
    ("diversificare", "turlantirmoq"), ("portafoglio (investimenti)", "sarmoya portfeli"),
    ("dividendo", "dividend"), ("speculazione", "chayqovchilik"), ("bolla", "pufak (moliyaviy)"),
    ("crollo", "qulash (birja)"), ("volatilità", "o'zgaruvchanlik"),
    ("fondo d'investimento", "investitsiya fondi"), ("interesse composto", "murakkab foiz"),
    ("inflazione attesa", "kutilayotgan inflyatsiya"), ("liquidità di mercato", "bozor likvidligi"),
    ("credito (bancario)", "bank krediti"), ("insolvenza", "to'lov qobiliyatsizligi"),
    ("garanzia (finanza)", "moliyaviy kafolat"), ("valutazione (azienda)", "kompaniya bahosi"),
    ("due diligence", "chuqur tekshiruv")],
   [("È importante diversificare il portafoglio.", "Sarmoya portfelini turlantirish muhim."),
    ("La volatilità è aumentata molto.", "O'zgaruvchanlik keskin oshdi.")]),
  ("Commercio", "Savdo",
   [("grossista", "ulgurji sotuvchi"), ("dettagliante", "chakana sotuvchi"),
    ("catena di fornitura", "ta'minot zanjiri"), ("logistica", "logistika"),
    ("magazzino (scorte)", "zaxira ombori"), ("inventario", "inventarizatsiya"),
    ("ordine minimo", "eng kam buyurtma"), ("listino prezzi", "narxlar ro'yxati"),
    ("sconto quantità", "hajmga chegirma"), ("condizioni di pagamento", "to'lov shartlari"),
    ("termini di consegna", "yetkazib berish shartlari"), ("trasporto merci", "yuk tashish"),
    ("dogana (commercio)", "bojxona (savdo)"), ("certificato d'origine", "kelib chiqish sertifikati"),
    ("contratto di fornitura", "ta'minot shartnomasi"), ("penale", "jarima (shartnoma)"),
    ("resa della merce", "mahsulotni qaytarish"), ("qualità garantita", "kafolatlangan sifat"),
    ("campione (merce)", "namuna (tovar)"), ("esclusiva", "eksklyuziv huquq"),
    ("franchising", "franshiza")],
   [("Le condizioni di pagamento sono a trenta giorni.", "To'lov shartlari o'ttiz kunlik."),
    ("La catena di fornitura si è interrotta.", "Ta'minot zanjiri uzildi.")]),
  ("Conti e fisco", "Hisob va soliqlar",
   [("bilancio (azienda)", "balans (korxona)"), ("stato patrimoniale", "moliyaviy holat"),
    ("conto economico", "daromadlar hisoboti"), ("ammortamento", "amortizatsiya"),
    ("ricavo", "tushum"), ("spesa deducibile", "hisobdan chiqariladigan xarajat"),
    ("imposta", "soliq (to'lov)"), ("IVA", "QQS"), ("aliquota", "soliq stavkasi"),
    ("dichiarazione dei redditi", "daromad deklaratsiyasi"), ("evasione fiscale", "soliqdan qochish"),
    ("elusione", "soliqni chetlab o'tish"), ("controllo fiscale", "soliq tekshiruvi"),
    ("sanzione fiscale", "soliq jarimasi"), ("rimborso fiscale", "soliq qaytarilishi"),
    ("partita IVA", "soliq to'lovchi raqami"), ("regime forfettario", "soddalashtirilgan tartib"),
    ("fattura elettronica", "elektron hisob-faktura"), ("commercialista", "buxgalter-maslahatchi"),
    ("scadenza fiscale", "soliq muddati"), ("busta paga", "ish haqi varaqasi")],
   [("Ho presentato la dichiarazione dei redditi.", "Daromad deklaratsiyasini topshirdim."),
    ("L'aliquota è cambiata quest'anno.", "Soliq stavkasi bu yil o'zgardi.")]),
  ("Startup e innovazione", "Startap va innovatsiya",
   [("idea imprenditoriale", "biznes g'oya"), ("modello di business", "biznes model"),
    ("piano industriale", "biznes reja"), ("prototipo (b2)", "dastlabki namuna"),
    ("validazione", "g'oyani sinash"), ("mercato di riferimento", "maqsadli bozor"),
    ("scalabilità", "kengaytiruvchanlik"), ("investitore privato", "xususiy investor"),
    ("capitale di rischio", "tavakkal sarmoya"), ("finanziamento seed", "boshlang'ich moliyalash"),
    ("incubatore", "inkubator"), ("acceleratore", "akselerator"), ("pitch (presentazione)", "qisqa taqdimot"),
    ("brevetto (b2)", "ixtiro patenti"), ("proprietà intellettuale", "intellektual mulk"),
    ("concorrenza agguerrita", "keskin raqobat"), ("vantaggio competitivo", "raqobat ustunligi"),
    ("crescita rapida", "jadal o'sish"), ("fallire velocemente", "tez xatoga uchramoq"),
    ("pivot (cambio)", "yo'nalishni burish"), ("uscita (exit)", "biznesdan chiqish")],
   [("Il modello di business non è scalabile.", "Biznes model kengaytirib bo'lmaydigan."),
    ("Hanno chiuso un round di finanziamento.", "Ular moliyalash bosqichini yakunladi.")]),
  ("Diritto del lavoro", "Mehnat huquqi",
   [("codice del lavoro", "mehnat kodeksi"), ("contratto collettivo (b2)", "jamoa shartnomasi (b2)"),
    ("categoria (inquadramento)", "toifa (lavozim)"), ("mansioni (contratto)", "vazifalar doirasi"),
    ("periodo di preavviso", "ogohlantirish muddati"), ("giusta causa", "asosli sabab"),
    ("licenziamento illegittimo", "noqonuniy ishdan bo'shatish"), ("reintegro", "ishga tiklash"),
    ("indennità di licenziamento", "ishdan bo'shash nafaqasi"), ("cassa integrazione", "vaqtinchalik ish to'xtatish"),
    ("congedo parentale", "bola parvarishi ta'tili"), ("maternità", "tug'ruq ta'tili"),
    ("malattia professionale", "kasb kasalligi"), ("infortunio sul lavoro", "ishdagi jarohat"),
    ("ispezione (lavoro)", "mehnat inspeksiyasi"), ("rappresentante sindacale", "kasaba vakili"),
    ("contrattazione", "shartnoma muzokarasi"), ("sciopero legittimo", "qonuniy ish tashlash"),
    ("molestie sul lavoro", "ish joyidagi tazyiq"), ("pari opportunità", "teng imkoniyatlar"),
    ("tutela legale (lavoro)", "huquqiy himoya (mehnat)")],
   [("Il licenziamento è stato dichiarato illegittimo.", "Ishdan bo'shatish noqonuniy deb topildi."),
    ("Ha chiesto il congedo parentale.", "U bola parvarishi ta'tilini so'radi.")]),
  ("Quando l'economia va male", "Iqtisod yomonlashganda",
   [("crisi economica", "iqtisodiy inqiroz"), ("contrazione", "qisqarish"),
    ("taglio dei costi", "xarajatlarni qisqartirish"), ("ristrutturazione", "qayta tashkil etish"),
    ("esuberi", "ortiqcha xodimlar"), ("chiusura (azienda)", "korxona yopilishi"),
    ("liquidazione", "tugatish (korxona)"), ("debito insostenibile", "ko'tarib bo'lmas qarz"),
    ("insolvenza (b2)", "to'lovga qobiliyatsizlik"), ("piano di rientro", "qarzni qoplash rejasi"),
    ("aiuti di stato", "davlat yordami"), ("incentivo", "rag'bat (moliyaviy)"),
    ("sussidio (economia)", "subsidiya"), ("austerità", "tejamkorlik siyosati"),
    ("riforma strutturale", "tarkibiy islohot"), ("fiducia dei consumatori", "iste'molchilar ishonchi"),
    ("calo dei consumi", "iste'mol pasayishi"), ("prezzi alle stelle", "narxlar keskin oshishi"),
    ("mercato in sofferenza", "qiynalayotgan bozor"), ("ripresa lenta", "sust tiklanish"),
    ("prospettive incerte", "noaniq istiqbollar")],
   [("L'azienda ha annunciato esuberi.", "Kompaniya ortiqcha xodimlar haqida e'lon qildi."),
    ("Le prospettive restano incerte.", "Istiqbollar noaniqligicha qolmoqda.")]),
  ("Marketing", "Marketing",
   [("target (pubblico)", "maqsadli auditoriya"), ("posizionamento", "bozordagi o'rin"),
    ("marchio", "brend"), ("immagine del marchio", "brend qiyofasi"),
    ("campagna pubblicitaria", "reklama kampaniyasi"), ("slogan", "shior"),
    ("canale di vendita", "savdo kanali"), ("promozione", "aksiya (savdo)"),
    ("fidelizzazione", "mijozni ushlab qolish"), ("passaparola", "og'izdan og'izga"),
    ("analisi di mercato", "bozor tahlili"), ("segmento", "segment"),
    ("bisogno del cliente", "mijoz ehtiyoji"), ("proposta di valore", "qiymat taklifi"),
    ("prezzo competitivo", "raqobatbardosh narx"), ("lancio (prodotto)", "mahsulot taqdimoti"),
    ("ciclo di vita del prodotto", "mahsulot hayot sikli"), ("feedback dei clienti", "mijozlar fikri"),
    ("reputazione (azienda)", "kompaniya obro'si"), ("crisi di immagine", "obro' inqirozi"),
    ("pubblicità responsabile", "mas'uliyatli reklama")],
   [("Abbiamo rivisto il posizionamento del marchio.", "Brendning bozordagi o'rnini qayta ko'rib chiqdik."),
    ("Il passaparola funziona meglio della pubblicità.", "Og'izdan og'izga reklamadan yaxshiroq ishlaydi.")]),
  ("Soldi e scelte personali", "Pul va shaxsiy tanlovlar",
   [("budget personale", "shaxsiy byudjet"), ("entrate", "kirimlar"), ("uscite", "chiqimlar"),
    ("spesa superflua", "keraksiz xarajat"), ("fondo di emergenza", "zaxira jamg'arma"),
    ("obiettivo di risparmio", "jamg'arish maqsadi"), ("indebitarsi", "qarzga botmoq"),
    ("rata insostenibile", "ko'tarib bo'lmas to'lov"), ("rinegoziare il mutuo", "kreditni qayta ko'rib chiqmoq"),
    ("acquisto consapevole", "ongli xarid"), ("qualità-prezzo", "narx-sifat nisbati"),
    ("investire in formazione", "ta'limga sarmoya"), ("previdenza", "pensiya jamg'armasi"),
    ("eredità", "meros"), ("donazione (soldi)", "hadya (pul)"), ("tassa di successione", "meros solig'i"),
    ("tenore di vita", "turmush darajasi"), ("vivere sopra le proprie possibilità", "imkoniyatdan ortiq yashash"),
    ("sobrietà", "kamtarona turmush"), ("indipendenza economica", "moliyaviy mustaqillik"),
    ("pianificazione a lungo termine", "uzoq muddatli rejalashtirish")],
   [("Sto costruendo un fondo di emergenza.", "Zaxira jamg'arma yig'yapman."),
    ("Vivono sopra le proprie possibilità.", "Ular imkoniyatidan ortiq yashashyapti.")]),
 ],

 "b2u3": [
  ("Il metodo scientifico", "Ilmiy metod",
   [("osservazione", "kuzatish"), ("ipotesi verificabile", "tekshiriladigan faraz"),
    ("variabile", "o'zgaruvchi"), ("gruppo di controllo", "nazorat guruhi"),
    ("campione casuale", "tasodifiy namuna"), ("misurazione", "o'lchash"),
    ("errore sperimentale", "tajriba xatosi"), ("margine di errore", "xatolik chegarasi"),
    ("riproducibilità", "takrorlanuvchanlik"), ("revisione paritaria", "hamkasblar taqrizi"),
    ("pubblicazione scientifica", "ilmiy nashr"), ("rivista specializzata", "ixtisoslashgan jurnal"),
    ("citazione (scientifica)", "ilmiy iqtibos"), ("metodologia (b2)", "tadqiqot uslubi"),
    ("protocollo", "bayonnoma (tadqiqot)"), ("evidenza scientifica", "ilmiy dalil"),
    ("consenso scientifico", "ilmiy konsensus"), ("teoria", "nazariya"),
    ("legge scientifica", "ilmiy qonun"), ("modello (scientifico)", "ilmiy model"),
    ("simulazione", "simulyatsiya")],
   [("I risultati devono essere riproducibili.", "Natijalar takrorlanadigan bo'lishi kerak."),
    ("Esiste un ampio consenso scientifico.", "Keng ilmiy konsensus mavjud.")]),
  ("Salute pubblica", "Jamoat salomatligi",
   [("epidemiologia", "epidemiologiya"), ("contagio", "yuqish"), ("incidenza", "kasallanish darajasi"),
    ("mortalità", "o'lim darajasi"), ("immunità", "immunitet"), ("anticorpo", "antitana"),
    ("agente patogeno", "kasallik qo'zg'atuvchisi"), ("quarantena", "karantin"),
    ("isolamento (malattia)", "izolyatsiya"), ("distanziamento", "masofa saqlash"),
    ("tracciamento dei contatti", "aloqalarni kuzatish"), ("campagna vaccinale", "emlash kampaniyasi"),
    ("copertura vaccinale", "emlash qamrovi"), ("effetto avverso", "nojo'ya oqibat"),
    ("sperimentazione clinica", "klinik sinov"), ("placebo", "platsebo"),
    ("terapia intensiva", "reanimatsiya"), ("posti letto", "o'rin-joylar soni"),
    ("personale sanitario", "tibbiyot xodimlari"), ("prevenzione primaria", "birlamchi profilaktika"),
    ("sanità territoriale", "hududiy tibbiyot")],
   [("La copertura vaccinale è aumentata.", "Emlash qamrovi ortdi."),
    ("Il tracciamento dei contatti è stato decisivo.", "Aloqalarni kuzatish hal qiluvchi bo'ldi.")]),
  ("Corpo e biologia", "Tana va biologiya",
   [("cellula", "hujayra"), ("tessuto (biologia)", "to'qima"), ("organo", "a'zo"),
    ("sistema immunitario", "immunitet tizimi"), ("metabolismo", "modda almashinuvi"),
    ("ormone", "gormon"), ("enzima", "ferment"), ("proteina", "oqsil"),
    ("carboidrato", "uglevod"), ("grasso (nutriente)", "yog' (ozuqa)"),
    ("gene", "gen"), ("DNA", "DNK"), ("mutazione", "mutatsiya"), ("ereditarietà", "irsiyat"),
    ("evoluzione", "evolyutsiya"), ("specie", "tur (biologik)"), ("ecosistema", "ekotizim"),
    ("biodiversità", "biologik xilma-xillik"), ("microbo", "mikrob"),
    ("batterio", "bakteriya"), ("antibiotico", "antibiotik")],
   [("Il sistema immunitario reagisce subito.", "Immunitet tizimi darhol javob beradi."),
    ("La biodiversità è in calo.", "Biologik xilma-xillik kamaymoqda.")]),
  ("Fisica e spazio", "Fizika va koinot",
   [("energia (fisica)", "energiya (fizika)"), ("forza", "kuch"), ("massa", "massa"),
    ("gravità", "tortishish kuchi"), ("velocità della luce", "yorug'lik tezligi"),
    ("particella", "zarracha"), ("atomo", "atom"), ("radiazione", "nurlanish"),
    ("onda", "to'lqin"), ("frequenza", "chastota"), ("temperatura assoluta", "mutlaq harorat"),
    ("pressione (fisica)", "bosim (fizika)"), ("orbita", "orbita"), ("satellite", "sun'iy yo'ldosh"),
    ("sonda", "kosmik zond"), ("telescopio", "teleskop"), ("galassia", "galaktika"),
    ("buco nero", "qora tuynuk"), ("universo", "koinot"), ("missione spaziale", "kosmik missiya"),
    ("astronauta", "kosmonavt")],
   [("Il telescopio ha osservato una galassia lontana.", "Teleskop uzoq galaktikani kuzatdi."),
    ("La missione spaziale durerà due anni.", "Kosmik missiya ikki yil davom etadi.")]),
  ("Intelligenza artificiale", "Sun'iy intellekt",
   [("apprendimento automatico", "mashinaviy o'rganish"), ("rete neurale", "neyron tarmoq"),
    ("addestramento", "o'qitish (model)"), ("dati di addestramento", "o'quv ma'lumotlari"),
    ("modello linguistico", "til modeli"), ("previsione (modello)", "bashorat (model)"),
    ("accuratezza", "aniqlik darajasi"), ("errore sistematico", "tizimli xato"),
    ("bias algoritmico", "algoritmik yonbosish"), ("trasparenza (algoritmi)", "algoritm shaffofligi"),
    ("spiegabilità", "tushuntirib berish imkoni"), ("supervisione umana", "inson nazorati"),
    ("automazione decisionale", "avtomatik qaror qabul qilish"), ("riconoscimento facciale", "yuzni tanish"),
    ("generazione di testo", "matn yaratish"), ("assistente virtuale", "virtual yordamchi"),
    ("robotica", "robototexnika"), ("sostituzione del lavoro", "ishning o'rnini bosish"),
    ("nuove professioni", "yangi kasblar"), ("regolamentazione (IA)", "SI tartibga solinishi"),
    ("responsabilità algoritmica", "algoritmik javobgarlik")],
   [("Il modello è stato addestrato su dati pubblici.", "Model ochiq ma'lumotlarda o'qitilgan."),
    ("Serve sempre una supervisione umana.", "Inson nazorati doim zarur.")]),
  ("Dati e statistica", "Ma'lumot va statistika",
   [("campione statistico", "statistik namuna"), ("popolazione (statistica)", "bosh to'plam"),
    ("media", "o'rtacha qiymat"), ("mediana", "mediana"), ("deviazione standard", "standart chetlanish"),
    ("distribuzione", "taqsimot"), ("probabilità (statistica)", "ehtimollik"),
    ("significatività", "ahamiyatlilik"), ("tendenza", "tendensiya"), ("anomalia", "anomaliya"),
    ("grafico a barre", "ustunli diagramma"), ("grafico a torta", "doiraviy diagramma"),
    ("serie storica", "vaqt qatori"), ("indicatore (dati)", "ko'rsatkich (ma'lumot)"),
    ("dato grezzo", "xom ma'lumot"), ("elaborazione", "qayta ishlash"),
    ("visualizzazione dei dati", "ma'lumotlarni vizuallashtirish"), ("interpretazione (dati)", "ma'lumot talqini"),
    ("dato fuorviante", "chalg'ituvchi ma'lumot"), ("trasparenza dei dati", "ma'lumot shaffofligi"),
    ("anonimizzazione", "anonimlashtirish")],
   [("La deviazione standard è molto alta.", "Standart chetlanish juda yuqori."),
    ("Il grafico può essere fuorviante.", "Diagramma chalg'ituvchi bo'lishi mumkin.")]),
  ("Etica della ricerca", "Tadqiqot etikasi",
   [("etica (b2)", "axloq (ilmiy)"), ("comitato etico", "axloqiy komissiya"),
    ("consenso informato (b2)", "ogohlangan rozilik (b2)"), ("riservatezza", "maxfiylik (tadqiqot)"),
    ("conflitto d'interessi (b2)", "manfaatlar to'qnashuvi (b2)"), ("finanziamento privato", "xususiy moliyalash"),
    ("indipendenza della ricerca", "tadqiqot mustaqilligi"), ("integrità", "halollik (ilmiy)"),
    ("falsificazione dei dati", "ma'lumotni soxtalashtirish"), ("ritrattazione", "maqolani qaytarib olish"),
    ("sperimentazione animale", "hayvonlarda sinov"), ("alternative etiche", "axloqiy muqobil"),
    ("rischio-beneficio", "xavf va foyda nisbati"), ("principio di precauzione", "ehtiyotkorlik tamoyili"),
    ("dual use", "ikki yoqlama qo'llash"), ("responsabilità dello scienziato", "olim mas'uliyati"),
    ("divulgazione responsabile", "mas'uliyatli tushuntirish"), ("accesso aperto", "ochiq kirish"),
    ("proprietà dei dati", "ma'lumot egaligi"), ("brevettabilità", "patentlash imkoni"),
    ("bene comune", "umumiy manfaat")],
   [("Lo studio è stato approvato dal comitato etico.", "Tadqiqot axloqiy komissiya tomonidan ma'qullandi."),
    ("Bisogna valutare il rapporto rischio-beneficio.", "Xavf va foyda nisbatini baholash kerak.")]),
  ("Clima e scienza", "Iqlim va fan",
   [("modello climatico", "iqlim modeli"), ("scenario di emissione", "chiqindi stsenariysi"),
    ("neutralità carbonica", "uglerod neytralligi"), ("cattura del carbonio", "uglerodni ushlash"),
    ("transizione energetica", "energetik o'tish"), ("rinnovabile (fonte)", "qayta tiklanuvchi manba"),
    ("efficienza (energetica)", "energiya samaradorligi (b2)"), ("consumo pro capite", "aholi jon boshiga iste'mol"),
    ("impatto ambientale", "atrof-muhitga ta'sir"), ("valutazione d'impatto", "ta'sirni baholash"),
    ("ecosistema fragile", "nozik ekotizim"), ("specie a rischio", "yo'qolib borayotgan tur"),
    ("deforestazione", "o'rmonlarning kesilishi"), ("erosione", "yemirilish"),
    ("scarsità d'acqua", "suv tanqisligi"), ("agricoltura sostenibile", "barqaror dehqonchilik"),
    ("economia circolare", "aylanma iqtisodiyot"), ("compensazione (CO2)", "chiqindini qoplash"),
    ("obiettivo climatico", "iqlim maqsadi"), ("monitoraggio ambientale", "ekologik monitoring"),
    ("resilienza", "bardoshlilik")],
   [("L'obiettivo è la neutralità carbonica entro il 2050.", "Maqsad — 2050-yilgacha uglerod neytralligi."),
    ("La scarsità d'acqua colpisce la regione.", "Suv tanqisligi mintaqaga ta'sir qilmoqda.")]),
  ("Finanziare la ricerca", "Tadqiqotni moliyalash",
   [("bando di ricerca", "grant tanlovi"), ("progetto di ricerca", "ilmiy loyiha"),
    ("finanziamento pubblico", "davlat moliyalashi"), ("fondo europeo", "yevropa jamg'armasi"),
    ("borsa di ricerca", "ilmiy stipendiya"), ("dottorato", "doktorantura"),
    ("ricercatore", "tadqiqotchi"), ("laboratorio (ricerca)", "ilmiy laboratoriya"),
    ("attrezzatura", "jihozlar"), ("costo del progetto", "loyiha qiymati"),
    ("rendicontazione", "hisobot berish"), ("collaborazione internazionale", "xalqaro hamkorlik"),
    ("gruppo di ricerca", "tadqiqot guruhi"), ("supervisore (accademico)", "ilmiy rahbar"),
    ("pubblicare (risultati)", "natijalarni e'lon qilmoq"), ("congresso", "anjuman"),
    ("poster (congresso)", "plakat (anjuman)"), ("premio scientifico", "ilmiy mukofot"),
    ("valutazione (progetto)", "loyihani baholash"), ("impatto della ricerca", "tadqiqot ta'siri"),
    ("trasferimento tecnologico", "texnologiya transferi")],
   [("Abbiamo vinto un bando di ricerca.", "Grant tanlovida g'olib bo'ldik."),
    ("Presenterò i risultati al congresso.", "Natijalarni anjumanda taqdim etaman.")]),
  ("Spiegare la scienza", "Fanni tushuntirish",
   [("divulgazione", "ommabop bayon"), ("linguaggio accessibile", "tushunarli til"),
    ("semplificare senza distorcere", "buzmasdan soddalashtirmoq"), ("analogia efficace", "ta'sirli o'xshatish"),
    ("esempio quotidiano", "kundalik misol"), ("curiosità scientifica", "ilmiy qiziqish"),
    ("scetticismo sano", "sog'lom shubha"), ("bufala", "yolg'on xabar (ilmiy)"),
    ("pseudoscienza", "soxta fan"), ("verifica dei fatti", "faktlarni tekshirish"),
    ("esperto (fonte)", "mutaxassis (manba)"), ("opinione non qualificata", "malakasiz fikr"),
    ("titolo fuorviante", "chalg'ituvchi sarlavha"), ("riassunto divulgativo", "ommabop qisqacha"),
    ("infografica", "infografika"), ("documentario", "hujjatli film"),
    ("museo della scienza", "fan muzeyi"), ("laboratorio didattico", "o'quv laboratoriyasi"),
    ("alfabetizzazione scientifica", "ilmiy savodxonlik"), ("dibattito informato", "ongli munozara"),
    ("fiducia nella scienza", "fanga ishonch")],
   [("Bisogna semplificare senza distorcere.", "Buzmasdan soddalashtirish kerak."),
    ("La fiducia nella scienza è fondamentale.", "Fanga ishonch juda muhim.")]),
  ("Tecnologie emergenti", "Yangi texnologiyalar",
   [("innovazione dirompente", "inqilobiy innovatsiya"), ("prototipazione rapida", "tez prototiplash"),
    ("stampa 3D", "3D bosib chiqarish"), ("realtà virtuale", "virtual voqelik"),
    ("realtà aumentata", "kengaytirilgan voqelik"), ("internet delle cose", "buyumlar interneti"),
    ("sensore", "sensor"), ("connettività", "ulanish imkoniyati"), ("rete 5G", "5G tarmog'i"),
    ("calcolo quantistico", "kvant hisoblash"), ("blockchain", "blokcheyn"),
    ("criptovaluta", "kriptovalyuta"), ("veicolo autonomo", "avtonom transport"),
    ("drone", "dron"), ("biotecnologia", "biotexnologiya"), ("nanotecnologia", "nanotexnologiya"),
    ("materiali avanzati", "ilg'or materiallar"), ("energia di fusione", "termoyadro energiyasi"),
    ("adozione (tecnologia)", "texnologiyani qabul qilish"), ("obsolescenza", "eskirish"),
    ("impatto sociale (tecnologia)", "texnologiyaning ijtimoiy ta'siri")],
   [("La stampa 3D ha ridotto i costi di prototipazione.", "3D bosib chiqarish prototip xarajatini kamaytirdi."),
    ("L'adozione della tecnologia è ancora lenta.", "Texnologiyani qabul qilish hali sust.")]),
 ],
}
