# -*- coding: utf-8 -*-
# B2 — vocabulary packs, units 7-8.

EXTRA = {
 "b2u7": [
  ("Salute mentale", "Ruhiy salomatlik",
   [("benessere psicologico", "ruhiy farovonlik"), ("disturbo d'ansia", "xavotir buzilishi"),
    ("attacco di panico", "vahima xurujlari"), ("depressione", "depressiya"),
    ("umore (stato)", "kayfiyat holati"), ("sbalzi d'umore", "kayfiyat o'zgarishi"),
    ("isolamento sociale", "ijtimoiy yakkalanish"), ("solitudine (b2)", "yolg'izlik hissi"),
    ("autostima (b2)", "o'z-o'zini qadrlash"), ("perfezionismo", "mukammallikka intilish"),
    ("senso di colpa", "aybdorlik tuyg'usi"), ("resilienza (psicologica)", "ruhiy bardosh"),
    ("meccanismo di difesa", "himoya mexanizmi"), ("trauma", "ruhiy jarohat"),
    ("elaborare (emozione)", "his-tuyg'uni qayta ishlamoq"), ("stigma (b2)", "salbiy tamg'a"),
    ("chiedere aiuto (b2)", "yordamga murojaat qilmoq"), ("rete di supporto", "qo'llab-quvvatlash tarmog'i"),
    ("consapevolezza di sé", "o'zini anglash"), ("equilibrio emotivo", "hissiy muvozanat"),
    ("prevenzione (salute mentale)", "ruhiy profilaktika")],
   [("Chiedere aiuto non è un segno di debolezza.", "Yordam so'rash zaiflik alomati emas."),
    ("Lo stigma impedisce a molti di curarsi.", "Salbiy tamg'a ko'pchilikni davolanishdan to'xtatadi.")]),
  ("Terapia e strumenti", "Terapiya va vositalar",
   [("psicoterapia", "psixoterapiya"), ("psicologo clinico", "klinik psixolog"),
    ("psichiatra", "psixiatr"), ("seduta", "seans"), ("percorso terapeutico", "davolanish yo'li"),
    ("colloquio iniziale", "dastlabki suhbat"), ("obiettivo terapeutico", "terapevtik maqsad"),
    ("terapia cognitiva", "kognitiv terapiya"), ("gruppo di supporto", "yordam guruhi"),
    ("diario emotivo", "his-tuyg'u kundaligi"), ("respirazione guidata", "nafas mashqi"),
    ("meditazione", "meditatsiya"), ("mindfulness", "hushyor diqqat"),
    ("rilassamento muscolare", "mushaklarni bo'shashtirish"), ("gestione dei pensieri", "fikrlarni boshqarish"),
    ("pensiero automatico", "avtomatik fikr"), ("ristrutturazione cognitiva", "fikrni qayta qurish"),
    ("farmaco (psichiatrico)", "psixiatrik dori"), ("effetto collaterale (b2)", "nojo'ya ta'sir (b2)"),
    ("ricaduta", "qaytalanish"), ("progresso graduale", "bosqichma-bosqich yaxshilanish")],
   [("Ha iniziato un percorso terapeutico.", "U davolanish yo'lini boshladi."),
    ("La mindfulness aiuta a gestire i pensieri.", "Hushyor diqqat fikrlarni boshqarishga yordam beradi.")]),
  ("Il sonno", "Uyqu",
   [("igiene del sonno", "uyqu gigiyenasi"), ("ritmo circadiano", "sutkalik ritm"),
    ("fase REM", "REM bosqichi"), ("sonno profondo (b2)", "chuqur uyqu bosqichi"),
    ("addormentarsi", "uyquga ketmoq"), ("risvegli notturni", "tunda uyg'onish"),
    ("insonnia cronica", "surunkali uyqusizlik"), ("apnea", "uyquda nafas to'xtashi"),
    ("russare", "xurrak otmoq"), ("sonnifero", "uxlatuvchi dori"),
    ("luce blu", "ko'k yorug'lik"), ("schermo prima di dormire", "uyqudan oldin ekran"),
    ("caffeina", "kofein"), ("orario regolare", "muntazam tartib"),
    ("riposino", "kunduzgi uyqu"), ("stanchezza mentale", "aqliy charchoq"),
    ("recupero (sonno)", "uyquni tiklash"), ("qualità del sonno", "uyqu sifati"),
    ("ambiente buio", "qorong'i muhit"), ("temperatura della stanza", "xona harorati"),
    ("rituale serale", "kechki odat")],
   [("L'igiene del sonno è fondamentale.", "Uyqu gigiyenasi juda muhim."),
    ("Evita gli schermi prima di dormire.", "Uyqudan oldin ekrandan qoching.")]),
  ("Nutrirsi bene", "To'g'ri ovqatlanish",
   [("dieta equilibrata", "muvozanatli parhez"), ("apporto calorico", "kaloriya miqdori"),
    ("macronutriente", "makronutrient"), ("micronutriente", "mikronutrient"),
    ("fibra", "tola (ozuqa)"), ("zucchero raffinato", "tozalangan shakar"),
    ("grassi saturi", "to'yingan yog'lar"), ("olio d'oliva", "zaytun moyi"),
    ("cereali integrali", "butun donli mahsulot"), ("legumi", "dukkakli ekinlar"),
    ("proteine vegetali", "o'simlik oqsili"), ("porzione consigliata", "tavsiya etilgan ulush"),
    ("etichetta nutrizionale", "ozuqaviy yorliq"), ("cibo processato", "qayta ishlangan ovqat"),
    ("cibo di stagione", "mavsumiy mahsulot"), ("filiera corta", "qisqa yetkazib berish zanjiri"),
    ("intolleranza", "chidamsizlik (ovqatga)"), ("celiachia", "glyutenga chidamsizlik"),
    ("vegetariano (b2)", "vegetarian (b2)"), ("vegano", "vegan"), ("idratazione", "suv balansi")],
   [("Leggo sempre l'etichetta nutrizionale.", "Men doim ozuqaviy yorliqni o'qiyman."),
    ("Riduci i cibi processati.", "Qayta ishlangan ovqatni kamaytir.")]),
  ("Allenarsi", "Mashq qilish",
   [("attività aerobica", "aerob mashq"), ("allenamento di forza", "kuch mashqi"),
    ("flessibilità (corpo)", "egiluvchanlik"), ("mobilità articolare", "bo'g'im harakatchanligi"),
    ("riscaldamento (b2)", "isinish mashqi"), ("defaticamento", "sovish mashqi"),
    ("ripetizione (esercizio)", "takror (mashq)"), ("serie", "seriya (mashq)"),
    ("carico progressivo", "bosqichma-bosqich yuk"), ("sovraccarico", "haddan ortiq yuk"),
    ("infortunio (b2)", "sport jarohati"), ("riabilitazione", "reabilitatsiya"),
    ("fisioterapista", "fizioterapevt"), ("frequenza cardiaca", "yurak urishi chastotasi"),
    ("resistenza (b2)", "chidamlilik (b2)"), ("massa muscolare", "mushak massasi"),
    ("metabolismo basale", "asosiy modda almashinuvi"), ("riposo attivo", "faol dam"),
    ("costanza (b2)", "muntazamlik"), ("motivazione (sport)", "sportdagi ishtiyoq"),
    ("obiettivo realistico", "real maqsad")],
   [("Il riposo attivo aiuta il recupero.", "Faol dam tiklanishga yordam beradi."),
    ("Meglio la costanza dell'intensità.", "Shiddatdan ko'ra muntazamlik afzal.")]),
  ("Vita e lavoro", "Hayot va ish",
   [("confine tra vita e lavoro", "ish va hayot chegarasi"), ("reperibilità", "doim aloqada bo'lish"),
    ("diritto alla disconnessione", "aloqadan uzilish huquqi"), ("carico mentale", "aqliy yuk"),
    ("multitasking (b2)", "bir vaqtda ko'p ish"), ("concentrazione", "diqqatni jamlash"),
    ("distrazione", "chalg'ish"), ("procrastinazione", "ishni cho'zish"),
    ("gestione delle priorità", "ustuvorliklarni boshqarish"), ("delegare (b2)", "vakolat topshirmoq"),
    ("dire di no", "yo'q deya olish"), ("confini sani", "sog'lom chegaralar"),
    ("pausa rigenerante", "tiklovchi tanaffus"), ("routine sostenibile", "barqaror tartib"),
    ("lavoro ibrido", "gibrid ish"), ("settimana corta", "qisqa ish haftasi"),
    ("burnout (b2)", "kasbiy kuyish"), ("recupero psicofisico", "ruhiy-jismoniy tiklanish"),
    ("ferie vere", "haqiqiy ta'til"), ("hobby rigenerante", "quvvat beruvchi mashg'ulot"),
    ("soddisfazione di vita", "hayotdan qoniqish")],
   [("Ho imparato a dire di no.", "Yo'q deyishni o'rgandim."),
    ("Il diritto alla disconnessione è importante.", "Aloqadan uzilish huquqi muhim.")]),
  ("Relazioni e benessere", "Munosabat va farovonlik",
   [("qualità delle relazioni", "munosabatlar sifati"), ("supporto emotivo", "hissiy qo'llab-quvvatlash"),
    ("ascolto empatico", "hamdardlik bilan tinglash"), ("comunicazione assertiva", "aniq va hurmatli muloqot"),
    ("aggressività", "tajovuzkorlik"), ("passività", "loqaydlik"),
    ("bisogni personali", "shaxsiy ehtiyojlar"), ("limite (personale)", "shaxsiy chegara"),
    ("dipendenza affettiva", "hissiy qaramlik"), ("autonomia (relazione)", "munosabatdagi mustaqillik"),
    ("tempo di qualità", "sifatli birga bo'lish"), ("gratitudine (b2)", "shukronalik"),
    ("perdono (b2)", "kechira olish"), ("conflitto costruttivo", "quruvchi nizo"),
    ("distanza emotiva", "hissiy uzoqlik"), ("riavvicinamento", "yaqinlashuv"),
    ("amicizia adulta", "kattalar do'stligi"), ("rete sociale", "ijtimoiy doira"),
    ("senso di appartenenza", "mansublik tuyg'usi"), ("solitudine scelta", "ixtiyoriy yolg'izlik"),
    ("benessere condiviso", "umumiy farovonlik")],
   [("La comunicazione assertiva evita molti conflitti.", "Aniq va hurmatli muloqot ko'p nizolarning oldini oladi."),
    ("Il tempo di qualità conta più della quantità.", "Sifatli birga bo'lish miqdordan muhimroq.")]),
  ("Abitudini e cambiamento", "Odat va o'zgarish",
   [("abitudine consolidata", "mustahkamlangan odat"), ("innesco", "turtki"),
    ("ricompensa", "rag'bat (odat)"), ("catena di abitudini", "odatlar zanjiri"),
    ("piccolo passo", "kichik qadam"), ("costanza quotidiana", "kundalik izchillik"),
    ("monitoraggio (abitudine)", "kuzatib borish"), ("ricaduta (abitudine)", "eski odatga qaytish"),
    ("autocontrollo", "o'zini tuta bilish"), ("forza di volontà", "iroda kuchi"),
    ("ambiente favorevole", "qulay muhit"), ("rimuovere l'ostacolo", "to'siqni olib tashlamoq"),
    ("obiettivo misurabile", "o'lchanadigan maqsad"), ("progresso visibile", "ko'rinadigan o'sish"),
    ("ricompensa immediata", "tezkor rag'bat"), ("beneficio a lungo termine", "uzoq muddatli foyda"),
    ("identità (abitudine)", "o'zlikni o'zgartirish"), ("routine mattutina", "ertalabki tartib"),
    ("disciplina", "intizom"), ("flessibilità (abitudine)", "moslashuvchanlik (odat)"),
    ("celebrare i progressi", "yutuqlarni nishonlash")],
   [("Bastano piccoli passi quotidiani.", "Kundalik kichik qadamlar yetarli."),
    ("L'ambiente favorevole aiuta più della forza di volontà.", "Qulay muhit iroda kuchidan ko'ra ko'proq yordam beradi.")]),
  ("Casa e benessere", "Uy va farovonlik",
   [("ordine (ambiente)", "tartib (muhit)"), ("disordine", "tartibsizlik"),
    ("decluttering", "ortiqchadan qutulish"), ("spazio funzionale", "qulay makon"),
    ("luce naturale", "tabiiy yorug'lik"), ("aria pulita", "toza havo"),
    ("piante da interno", "uy o'simliklari"), ("rumore domestico", "uydagi shovqin"),
    ("isolamento acustico", "tovush izolyatsiyasi"), ("temperatura ideale", "qulay harorat"),
    ("umidità", "namlik"), ("ergonomia", "ergonomika"), ("postazione di lavoro", "ish joyi (uy)"),
    ("sedia ergonomica", "ergonomik stul"), ("pausa dallo schermo", "ekrandan tanaffus"),
    ("angolo relax", "dam olish burchagi"), ("profumo di casa (b2)", "uydagi yoqimli hid"),
    ("routine di pulizia", "tozalash tartibi"), ("manutenzione regolare", "muntazam parvarish"),
    ("sicurezza domestica", "uy xavfsizligi"), ("comfort", "qulaylik")],
   [("La luce naturale migliora l'umore.", "Tabiiy yorug'lik kayfiyatni yaxshilaydi."),
    ("Ho creato un angolo relax.", "Dam olish burchagini yaratdim.")]),
  ("Invecchiare bene", "Sog'lom qarish",
   [("terza età", "keksalik davri"), ("autonomia (anziani)", "mustaqillik (keksalarda)"),
    ("prevenzione (anziani)", "profilaktika (keksalar)"), ("attività cognitiva", "aqliy faoliyat"),
    ("memoria (allenare)", "xotirani mashq qilish"), ("socialità", "muloqotda bo'lish"),
    ("mobilità (anziani)", "harakatchanlik (keksa)"), ("caduta (rischio)", "yiqilish xavfi"),
    ("alimentazione adeguata", "mos ovqatlanish"), ("controlli periodici", "muntazam ko'riklar"),
    ("farmaci multipli", "ko'p dori qabul qilish"), ("caregiver", "parvarishlovchi"),
    ("assistenza domiciliare (b2)", "uyda parvarish (b2)"), ("casa di riposo", "keksalar uyi"),
    ("qualità di vita", "hayot sifati"), ("dignità", "qadr-qimmat"),
    ("progetti dopo la pensione", "nafaqadan keyingi rejalar"), ("nonni e nipoti", "buvi-bobo va nevaralar"),
    ("trasmettere esperienza", "tajribani yetkazish"), ("attività di volontariato", "ko'ngilli faoliyat"),
    ("invecchiamento attivo", "faol qarish")],
   [("L'invecchiamento attivo migliora la qualità di vita.", "Faol qarish hayot sifatini yaxshilaydi."),
    ("Mia nonna fa attività di volontariato.", "Buvim ko'ngilli faoliyat bilan shug'ullanadi.")]),
 ],

 "b2u8": [
  ("Candidature accademiche", "Akademik nomzodlik",
   [("ammissione (università)", "qabul (universitet)"), ("requisiti linguistici", "til talablari"),
    ("certificato di lingua", "til sertifikati"), ("media dei voti", "o'rtacha baho"),
    ("trascrizione dei voti", "baholar ko'chirmasi"), ("equipollenza", "tenglashtirish (diplom)"),
    ("lettera di intenti", "niyat xati"), ("proposta di ricerca", "tadqiqot taklifi"),
    ("supervisore potenziale", "bo'lajak ilmiy rahbar"), ("colloquio di selezione", "saralash suhbati"),
    ("graduatoria (b2)", "reyting jadvali"), ("lista d'attesa (b2)", "kutish ro'yxati"),
    ("iscrizione (formale)", "rasmiy ro'yxatdan o'tish"), ("tassa d'iscrizione", "ro'yxat to'lovi"),
    ("esenzione (tasse)", "to'lovdan ozod qilish"), ("alloggio studentesco", "talabalar turar joyi"),
    ("assicurazione studenti", "talabalar sug'urtasi"), ("visto per studio", "o'quv vizasi"),
    ("permesso di soggiorno (b2)", "yashash ruxsatnomasi (b2)"), ("scadenza improrogabile", "o'zgarmas muddat"),
    ("documentazione completa", "to'liq hujjatlar to'plami")],
   [("Ho ottenuto l'esenzione dalle tasse.", "To'lovdan ozod qilinishga erishdim."),
    ("La scadenza è improrogabile.", "Muddat o'zgartirilmaydi.")]),
  ("Ricerca e tesi", "Tadqiqot va diplom ishi",
   [("argomento di tesi", "diplom mavzusi"), ("domanda di ricerca", "tadqiqot savoli"),
    ("stato dell'arte", "mavzu bo'yicha holat"), ("rassegna della letteratura", "adabiyotlar sharhi"),
    ("quadro teorico", "nazariy asos"), ("raccolta dati", "ma'lumot yig'ish"),
    ("questionario", "so'rovnoma"), ("intervista (ricerca)", "tadqiqot intervyusi"),
    ("analisi qualitativa", "sifat tahlili"), ("analisi quantitativa", "miqdoriy tahlil"),
    ("risultati preliminari", "dastlabki natijalar"), ("discussione (tesi)", "muhokama (ish)"),
    ("limiti dello studio", "tadqiqot cheklovlari"), ("prospettive future", "kelgusi istiqbollar"),
    ("appendice", "ilova (ish)"), ("scadenza di consegna", "topshirish muddati"),
    ("revisione (tesi)", "qayta ko'rib chiqish"), ("correzione di bozze", "tahrir"),
    ("discussione finale (laurea)", "himoya"), ("commissione (laurea)", "himoya komissiyasi"),
    ("titolo conseguito", "olingan daraja")],
   [("Devo ancora scrivere la rassegna della letteratura.", "Adabiyotlar sharhini hali yozishim kerak."),
    ("La discussione finale è a luglio.", "Himoya iyulda bo'ladi.")]),
  ("Presentare in pubblico", "Ilmiy taqdimot",
   [("relatore (convegno)", "ma'ruzachi"), ("abstract", "annotatsiya"),
    ("call for papers", "maqolalar qabuli"), ("sessione", "sessiya"), ("keynote", "asosiy ma'ruza"),
    ("tempo di presentazione", "ma'ruza vaqti"), ("slide efficace", "ta'sirli slayd"),
    ("grafico chiaro", "tushunarli grafik"), ("conclusione sintetica", "qisqa xulosa"),
    ("domande e risposte", "savol-javob"), ("obiezione (pubblico)", "zaldan e'tiroz"),
    ("risposta puntuale", "aniq javob"), ("non lo so (ammettere)", "bilmayman (tan olmoq)"),
    ("approfondire dopo", "keyinroq muhokama qilmoq"), ("networking (evento)", "aloqalar o'rnatish"),
    ("biglietto da visita", "tashrif qog'ozi"), ("contatto utile", "foydali tanishuv"),
    ("collaborazione futura", "kelgusi hamkorlik"), ("atti del convegno", "anjuman to'plami"),
    ("moderatore (sessione)", "sessiya boshlovchisi"), ("feedback dei colleghi", "hamkasblar fikri")],
   [("Il mio abstract è stato accettato.", "Annotatsiyam qabul qilindi."),
    ("Se non lo so, lo ammetto e approfondisco dopo.", "Bilmasam, tan olaman va keyinroq o'rganaman.")]),
  ("Costruire relazioni professionali", "Kasbiy aloqalar",
   [("rete professionale", "kasbiy tarmoq"), ("contatto iniziale", "dastlabki aloqa"),
    ("presentarsi (professionale)", "o'zini tanishtirmoq (rasmiy)"), ("scambio di contatti", "aloqa almashish"),
    ("follow-up", "keyingi murojaat"), ("email di ringraziamento", "minnatdorchilik xati"),
    ("raccomandazione (b2)", "tavsiyanoma (b2)"), ("referenza", "kafolatnoma"),
    ("mentorship", "ustozlik"), ("collaborazione informale", "norasmiy hamkorlik"),
    ("comunità professionale", "kasbiy jamoa"), ("associazione di categoria", "soha uyushmasi"),
    ("evento di settore", "soha tadbiri"), ("visibilità professionale", "kasbiy tanilish"),
    ("profilo online (lavoro)", "kasbiy onlayn profil"), ("portfolio", "portfolio"),
    ("reputazione professionale", "kasbiy obro'"), ("opportunità nascoste", "yashirin imkoniyatlar"),
    ("passaparola professionale", "kasbiy tavsiya"), ("cortesia professionale", "kasbiy odob"),
    ("mantenere i contatti", "aloqani saqlab qolmoq")],
   [("Ho mandato un'email di ringraziamento.", "Minnatdorchilik xati yubordim."),
    ("Molte opportunità sono nascoste.", "Ko'p imkoniyatlar yashirin.")]),
  ("Trasferirsi davvero", "Haqiqatan ko'chish",
   [("preparativi", "tayyorgarlik ishlari"), ("trasloco internazionale", "xalqaro ko'chish"),
    ("spedire i bagagli", "yuklarni jo'natish"), ("chiudere le utenze", "xizmatlarni yopish"),
    ("disdire il contratto (casa)", "uy shartnomasini bekor qilish"), ("cambio di residenza", "manzilni o'zgartirish"),
    ("apertura conto (estero)", "chet elda hisob ochish"), ("codice identificativo", "identifikatsiya raqami"),
    ("registrazione all'anagrafe", "aholi ro'yxatiga qo'shilish"), ("medico di base (estero)", "chet eldagi oilaviy shifokor"),
    ("scuola per i figli", "bolalar uchun maktab"), ("trasporto pubblico (nuovo)", "yangi shahar transporti"),
    ("costo della vita (confronto)", "turmush qiymati taqqosi"), ("stipendio netto (estero)", "qo'lga tegadigan maosh (chet el)"),
    ("tassazione (estero)", "soliqlar (chet el)"), ("contributi (estero)", "badallar (chet el)"),
    ("assicurazione obbligatoria (b2)", "majburiy sug'urta (b2)"), ("rete di connazionali", "vatandoshlar doirasi"),
    ("primo mese", "birinchi oy"), ("spese iniziali", "boshlang'ich xarajatlar"),
    ("piano B", "zaxira reja")],
   [("Le spese iniziali sono state più alte del previsto.", "Boshlang'ich xarajatlar kutilganidan yuqori bo'ldi."),
    ("Conviene avere sempre un piano B.", "Doim zaxira reja bo'lgani ma'qul.")]),
  ("Burocrazia all'estero", "Chet eldagi rasmiyatchilik",
   [("ufficio immigrazione", "migratsiya idorasi"), ("appuntamento obbligatorio", "majburiy navbat"),
    ("modulo in lingua", "mahalliy tildagi ariza"), ("traduzione asseverata", "tasdiqlangan tarjima"),
    ("legalizzazione", "legallashtirish"), ("apostille (b2)", "apostil (b2)"),
    ("permesso in rinnovo", "yangilanayotgan ruxsat"), ("ricevuta provvisoria", "vaqtinchalik tilxat"),
    ("silenzio-assenso", "javobsizlik roziligi"), ("integrazione dei documenti", "hujjatlarni to'ldirish"),
    ("verifica dei requisiti", "talablarni tekshirish"), ("colloquio in ufficio", "idoradagi suhbat"),
    ("interprete", "tarjimon (og'zaki)"), ("delega (procura)", "ishonchnoma"),
    ("marca da bollo (b2)", "davlat boji (b2)"), ("pagamento telematico", "onlayn to'lov"),
    ("ricorso amministrativo", "ma'muriy shikoyat"), ("tempi lunghi", "cho'ziladigan muddatlar"),
    ("sportello dedicato", "maxsus oyna"), ("assistenza legale", "yuridik yordam"),
    ("pazienza necessaria", "zarur sabr")],
   [("Ho ricevuto una ricevuta provvisoria.", "Menga vaqtinchalik tilxat berishdi."),
    ("I tempi sono più lunghi del previsto.", "Muddatlar kutilganidan cho'zilyapti.")]),
  ("Lingua e integrazione", "Til va moslashuv",
   [("competenza linguistica", "til bilish darajasi"), ("livello certificato", "tasdiqlangan daraja"),
    ("esame di lingua", "til imtihoni"), ("comprensione orale", "tinglab tushunish"),
    ("produzione scritta", "yozma nutq"), ("fluidità", "ravonlik"),
    ("accento straniero", "chet el talaffuzi"), ("gergo locale", "mahalliy jargon"),
    ("dialetto", "sheva"), ("registro informale (b2)", "norasmiy uslub (b2)"),
    ("malinteso linguistico", "til tufayli tushunmovchilik"), ("chiedere di ripetere", "takrorlashni so'ramoq"),
    ("parlare lentamente", "sekin gapirishni so'ramoq"), ("prendere appunti (lingua)", "yangi so'zlarni yozib olmoq"),
    ("immersione", "til muhitiga sho'ng'ish"), ("scambio linguistico", "til almashinuvi"),
    ("tandem", "tandem (til mashqi)"), ("corso serale", "kechki kurs"),
    ("progresso linguistico", "tildagi o'sish"), ("plateau", "to'xtab qolgan daraja"),
    ("fiducia nel parlare", "gapirishga ishonch")],
   [("Sono arrivata a un plateau linguistico.", "Tilda to'xtab qolgan darajaga yetdim."),
    ("L'immersione accelera tutto.", "Til muhiti hammasini tezlashtiradi.")]),
  ("Colloqui internazionali", "Xalqaro suhbatlar",
   [("colloquio in inglese", "ingliz tilidagi suhbat"), ("fuso orario (colloquio)", "vaqt farqi (suhbat)"),
    ("colloquio online", "onlayn suhbat"), ("prova tecnica", "texnik sinov"),
    ("case study", "amaliy vaziyat"), ("domanda comportamentale", "xulq-atvor savoli"),
    ("esempio concreto (colloquio)", "aniq misol (suhbat)"), ("punto di forza (b2)", "kuchli tomon (b2)"),
    ("area di miglioramento", "yaxshilash kerak bo'lgan jihat"), ("aspettative salariali", "maosh kutilmalari"),
    ("pacchetto retributivo", "to'lov paketi"), ("relocation", "ko'chirish yordami"),
    ("periodo di inserimento", "moslashuv davri"), ("riferimenti (referenze)", "tavsiyachilar"),
    ("controproposta (offerta)", "qarshi taklif (ish)"), ("accettare l'offerta", "taklifni qabul qilmoq"),
    ("declinare con garbo", "odob bilan rad etmoq"), ("data di inizio", "boshlash sanasi"),
    ("contratto internazionale", "xalqaro shartnoma"), ("diritto applicabile", "amal qiluvchi qonun"),
    ("cultura aziendale", "korporativ madaniyat")],
   [("Quali sono le vostre aspettative salariali?", "Maosh bo'yicha kutilmalaringiz qanday?"),
    ("Ho declinato l'offerta con garbo.", "Taklifni odob bilan rad etdim.")]),
  ("Lavorare nel mondo", "Dunyo bo'ylab ishlash",
   [("team internazionale", "xalqaro jamoa"), ("lingua di lavoro", "ish tili"),
    ("differenza culturale (lavoro)", "ishdagi madaniy farq"), ("gerarchia (cultura)", "ierarxiya (madaniyat)"),
    ("comunicazione diretta", "to'g'ridan-to'g'ri muloqot"), ("comunicazione indiretta", "bilvosita muloqot"),
    ("puntualità (culture)", "vaqtga munosabat (madaniyat)"), ("scadenze flessibili", "moslashuvchan muddatlar"),
    ("riunione tra fusi orari", "vaqt mintaqalari aro yig'ilish"), ("asincrono", "asinxron ish"),
    ("documentazione scritta", "yozma hujjatlashtirish"), ("trasparenza (team)", "jamoadagi ochiqlik"),
    ("fiducia a distanza", "masofadagi ishonch"), ("onboarding", "yangi xodimni kiritish"),
    ("mentore internazionale", "xalqaro ustoz"), ("mobilità interna", "ichki lavozim almashinuvi"),
    ("distacco (lavoro estero)", "chet elga yuborilish"), ("visto di lavoro", "ishchi vizasi"),
    ("doppia tassazione", "ikki tomonlama soliq"), ("previdenza internazionale", "xalqaro pensiya"),
    ("rientro in patria", "vatanga qaytish")],
   [("Lavoro in un team internazionale.", "Men xalqaro jamoada ishlayman."),
    ("La comunicazione asincrona funziona bene.", "Asinxron muloqot yaxshi ishlaydi.")]),
  ("Bilanci e ritorni", "Xulosa va qaytish",
   [("bilancio personale (b2)", "shaxsiy yakun"), ("aspettative e realtà", "kutilma va haqiqat"),
    ("guadagno (esperienza)", "tajriba yutug'i"), ("prezzo pagato", "to'langan baho"),
    ("distanza dalla famiglia", "oiladan uzoqlik"), ("videochiamate settimanali", "haftalik videoqo'ng'iroq"),
    ("visite a casa", "uyga tashriflar"), ("nostalgia gestibile", "boshqarsa bo'ladigan sog'inch"),
    ("nuove radici", "yangi ildizlar"), ("doppia appartenenza", "ikki tomonga mansublik"),
    ("scelta consapevole", "ongli tanlov"), ("ripensamento", "fikrdan qaytish"),
    ("rientro definitivo", "butunlay qaytish"), ("reinserimento", "qayta moslashuv"),
    ("competenze acquisite", "orttirilgan ko'nikmalar"), ("valore sul mercato", "bozordagi qiymat"),
    ("rete internazionale", "xalqaro tarmoq"), ("prospettiva più ampia", "kengroq nuqtai nazar"),
    ("gratitudine per il percorso", "bosib o'tilgan yo'lga minnatdorlik"),
    ("consiglio a chi parte", "ketayotganlarga maslahat"), ("prossimo capitolo", "keyingi bosqich")],
   [("Il bilancio personale è positivo.", "Shaxsiy yakun ijobiy."),
    ("Ho acquisito una prospettiva più ampia.", "Men kengroq nuqtai nazarga ega bo'ldim.")]),
 ],
}
