# -*- coding: utf-8 -*-
# A2 — themed vocabulary packs (CEFR band 1000-2000 cumulative words).

EXTRA = {
 "a2u1": [
  ("Verbi al passato", "O'tgan zamon fe'llari",
   [("nascere", "tug'ilmoq"), ("morire", "vafot etmoq"), ("crescere (bambino)", "ulg'aymoq"),
    ("trasferirsi (casa)", "ko'chib o'tmoq"), ("conoscersi", "tanishmoq"), ("separarsi (coppia)", "ajralishmoq"),
    ("diplomarsi", "maktabni tugatmoq"), ("cambiare lavoro", "ish almashtirmoq"),
    ("smettere", "tashlamoq (odatni)"), ("iniziare (a fare)", "boshlab yubormoq"),
    ("continuare", "davom ettirmoq"), ("succedere (accadere)", "ro'y bermoq"),
    ("diventare", "bo'lmoq (aylanmoq)"), ("rimanere", "qolib ketmoq"),
    ("tornare indietro", "orqaga qaytmoq"), ("decidere (passato)", "qaror qabul qilmoq")],
   [("Sono nata a Roma.", "Men Rimda tug'ilganman."),
    ("Ci siamo conosciuti all'università.", "Biz universitetda tanishganmiz.")]),
  ("Eventi della vita", "Hayot voqealari",
   [("nascita", "tug'ilish"), ("matrimonio (evento)", "nikoh to'yi"), ("divorzio", "ajralish"),
    ("trasloco", "ko'chish"), ("funerale", "dafn marosimi"), ("anniversario", "yubiley"),
    ("laurea (evento)", "bitiruv"), ("primo giorno", "birinchi kun"),
    ("incontro (evento)", "uchrashuv (tadbir)"), ("addio", "vidolashuv"),
    ("ritorno", "qaytish"), ("partenza (persona)", "jo'nab ketish"),
    ("cambiamento", "o'zgarish"), ("occasione (evento)", "munosabat"),
    ("festa di compleanno", "tug'ilgan kun bazmi"), ("regalo di nozze", "to'y sovg'asi")],
   [("Il matrimonio è stato bellissimo.", "To'y juda chiroyli bo'ldi."),
    ("Domani è il nostro anniversario.", "Ertaga bizning yubileyimiz.")]),
  ("Ricordi d'infanzia", "Bolalik xotiralari",
   [("giocattolo", "o'yinchoq"), ("bambola", "qo'g'irchoq"), ("altalena", "arg'imchoq"),
    ("fiaba", "ertak"), ("nonna (racconto)", "buvijon"), ("cortile (gioco)", "hovli (o'yin)"),
    ("vicini (infanzia)", "qo'shnilar"), ("scuola elementare (ricordo)", "boshlang'ich sinf"),
    ("maestra", "birinchi o'qituvchi"), ("amico d'infanzia", "bolalikdagi do'st"),
    ("vacanze estive", "yozgi ta'til"), ("villaggio dei nonni", "buvimning qishlog'i"),
    ("bicicletta (infanzia)", "bolalar velosipedi"), ("paura del buio", "qorong'udan qo'rquv"),
    ("dolce preferito", "sevimli shirinlik"), ("ricordo felice", "quvonchli xotira")],
   [("Da bambina avevo una bambola.", "Bolaligimda qo'g'irchog'im bor edi."),
    ("La nonna raccontava fiabe.", "Buvim ertak aytib berardi.")]),
  ("Raccontare in ordine", "Ketma-ketlik",
   [("prima di tutto", "avvalo"), ("poi (dopo)", "so'ngra"), ("intanto", "shu orada"),
    ("mentre", "…ayotganda"), ("appena (subito dopo)", "…ishi bilanoq"),
    ("dopo poco", "biroz o'tib"), ("il giorno dopo", "ertasi kuni"),
    ("qualche tempo fa", "bir qancha vaqt oldin"), ("da piccolo", "kichkinaligida"),
    ("all'epoca", "o'sha paytlarda"), ("in quel momento", "o'sha lahzada"),
    ("da quel giorno", "o'sha kundan boshlab"), ("in seguito", "keyinchalik"),
    ("alla fine (concl.)", "oxir-oqibat"), ("per la prima volta", "birinchi marta"),
    ("l'ultima volta", "oxirgi marta")],
   [("Prima di tutto, ti racconto l'inizio.", "Avvalo, boshlanishini aytib beraman."),
    ("Il giorno dopo è tornato.", "Ertasi kuni u qaytib keldi.")]),
 ],

 "a2u2": [
  ("In aeroporto", "Aeroportda",
   [("check-in", "ro'yxatdan o'tish"), ("carta d'imbarco", "chiqish taloni"),
    ("gate", "chiqish darvozasi"), ("decollo", "uchish"), ("atterraggio", "qo'nish"),
    ("bagaglio a mano", "qo'l yuki"), ("valigia grande", "katta chamadon"),
    ("controllo sicurezza", "xavfsizlik nazorati"), ("passeggero", "yo'lovchi"),
    ("equipaggio", "ekipaj"), ("posto vicino al finestrino", "deraza yonidagi joy"),
    ("cintura di sicurezza", "xavfsizlik kamari"), ("volo diretto", "to'g'ridan-to'g'ri parvoz"),
    ("scalo", "oraliq to'xtash"), ("cancellato", "bekor qilingan"), ("imbarco", "bortga chiqish")],
   [("Il volo è stato cancellato.", "Parvoz bekor qilindi."),
    ("Ho solo un bagaglio a mano.", "Menda faqat qo'l yuki bor.")]),
  ("In auto", "Mashinada",
   [("patente", "haydovchilik guvohnomasi"), ("benzina", "benzin"), ("distributore", "yoqilg'i shoxobchasi"),
    ("motore", "dvigatel"), ("ruota", "g'ildirak"), ("freno", "tormoz"), ("volante", "rul"),
    ("cintura (auto)", "kamar"), ("autostrada", "avtomagistral"), ("pedaggio", "yo'l to'lovi"),
    ("velocità", "tezlik"), ("multa", "jarima"), ("incidente stradale", "yo'l-transport hodisasi"),
    ("meccanico", "usta"), ("guidare", "haydamoq"), ("noleggiare", "ijaraga olmoq")],
   [("Ho preso una multa.", "Men jarima oldim."),
    ("Dobbiamo fare benzina.", "Benzin quyishimiz kerak.")]),
  ("Dove dormire", "Qayerda tunash",
   [("ostello", "yotoqxona"), ("pensione", "mehmon uyi"), ("casa in affitto", "ijaraga uy"),
    ("camera doppia", "ikki kishilik xona"), ("letto singolo", "bir kishilik karavot"),
    ("vista", "manzara (deradazan)"), ("piano (albergo)", "qavat (mehmonxona)"),
    ("recensione", "sharh"), ("prezzo a notte", "bir kechalik narx"),
    ("caparra", "oldindan to'lov"), ("check-out", "xonani bo'shatish"),
    ("servizio in camera", "xonaga xizmat"), ("pulizia (servizio)", "tozalash xizmati"),
    ("chiave elettronica", "elektron kalit"), ("cassaforte", "seyf"), ("reception (banco)", "qabul stoli")],
   [("Avete una camera con vista?", "Manzarali xona bormi?"),
    ("A che ora è il check-out?", "Xonani soat nechada bo'shatish kerak?")]),
  ("Souvenir e bagagli", "Sovg'alar va yuklar",
   [("souvenir", "esdalik sovg'asi"), ("cartolina", "otkritka"), ("magnete", "magnit"),
    ("artigianato (oggetto)", "hunarmandchilik buyumi"), ("tappeto piccolo", "kichik gilam"),
    ("spezie", "ziravorlar"), ("dolci tipici", "milliy shirinliklar"),
    ("imballare", "o'rab qo'ymoq"), ("fragile", "mo'rt"), ("pesare (bagaglio)", "yukni tortmoq"),
    ("peso", "og'irlik"), ("limite (bagaglio)", "yuk chegarasi"),
    ("dogana (controllo)", "bojxona nazorati"), ("dichiarare", "deklaratsiya qilmoq"),
    ("regalo per amici", "do'stlarga sovg'a"), ("ricordo (oggetto)", "esdalik")],
   [("Ho comprato dei souvenir.", "Men esdalik sovg'alar sotib oldim."),
    ("Attenzione, è fragile.", "Ehtiyot bo'ling, mo'rt.")]),
 ],

 "a2u3": [
  ("Il corpo in dettaglio", "Tana a'zolari",
   [("braccio", "qo'l (yelkadan)"), ("gamba", "oyoq (son)"), ("ginocchio", "tizza"),
    ("gomito", "tirsak"), ("spalla", "yelka"), ("collo", "bo'yin"), ("dito", "barmoq"),
    ("unghia", "tirnoq"), ("pelle", "teri"), ("osso", "suyak"), ("sangue", "qon"),
    ("polmone", "o'pka"), ("fegato", "jigar"), ("rene", "buyrak"), ("cervello", "miya"),
    ("muscolo", "mushak")],
   [("Mi fa male il ginocchio.", "Tizzam og'riyapti."),
    ("Ho un taglio sul dito.", "Barmog'im kesilgan.")]),
  ("I sintomi", "Alomatlar",
   [("nausea", "ko'ngil aynishi"), ("vertigini", "bosh aylanishi"), ("brividi", "titroq"),
    ("starnuto", "aksirish"), ("naso chiuso", "burun bitishi"), ("mal di denti", "tish og'rig'i"),
    ("bruciore", "achishish"), ("gonfiore", "shish"), ("ferita", "yara"),
    ("livido", "ko'karish"), ("frattura", "sinish"), ("prurito", "qichishish"),
    ("stanchezza forte", "kuchli holsizlik"), ("insonnia", "uyqusizlik"),
    ("pressione (sanguigna)", "qon bosimi"), ("respiro corto", "nafas qisishi")],
   [("Ho le vertigini.", "Boshim aylanyapti."),
    ("Non riesco a dormire.", "Uxlay olmayapman.")]),
  ("Emergenze", "Favqulodda holatlar",
   [("ambulanza", "tez yordam"), ("pronto soccorso", "shoshilinch yordam bo'limi"),
    ("infermiere", "hamshira (erkak)"), ("barella", "zambil"), ("urgente (medico)", "shoshilinch"),
    ("operazione", "operatsiya"), ("iniezione", "ukol"), ("analisi", "tahlil"),
    ("radiografia", "rentgen"), ("gesso", "gips"), ("benda", "bint"),
    ("allergia grave", "og'ir allergiya"), ("svenire", "hushidan ketmoq"),
    ("chiamare aiuto", "yordam chaqirmoq"), ("numero di emergenza", "favqulodda raqam"),
    ("assicurazione sanitaria", "tibbiy sug'urta")],
   [("Chiamate un'ambulanza!", "Tez yordam chaqiring!"),
    ("Devo fare delle analisi.", "Tahlil topshirishim kerak.")]),
  ("Stare bene ogni giorno", "Kundalik salomatlik",
   [("vitamina", "vitamin"), ("verdura cruda", "xom sabzavot"), ("acqua a sufficienza", "yetarli suv"),
    ("passeggiata quotidiana", "kundalik sayr"), ("riposo", "dam"), ("sonno profondo", "chuqur uyqu"),
    ("fumo", "chekish"), ("smettere di fumare", "chekishni tashlash"),
    ("peso forma", "me'yordagi vazn"), ("controllo medico", "tibbiy ko'rik"),
    ("respirare bene", "chuqur nafas olmoq"), ("rilassarsi", "bo'shashmoq"),
    ("postura corretta", "to'g'ri o'tirish"), ("igiene", "gigiyena"),
    ("lavarsi le mani", "qo'l yuvmoq"), ("mascherina", "niqob")],
   [("Bevo due litri d'acqua al giorno.", "Kuniga ikki litr suv ichaman."),
    ("Ha smesso di fumare l'anno scorso.", "U o'tgan yili chekishni tashladi.")]),
 ],

 "a2u4": [
  ("Altre professioni", "Yana kasblar",
   [("architetto", "arxitektor"), ("programmatore", "dasturchi"), ("contabile", "buxgalter"),
    ("segretaria", "kotiba"), ("traduttore", "tarjimon"), ("elettricista", "elektrik"),
    ("falegname", "duradgor"), ("sarto", "tikuvchi"), ("parrucchiera", "sartarosh ayol"),
    ("agricoltore", "dehqon"), ("pastore", "cho'pon"), ("poliziotto", "politsiyachi"),
    ("pompiere", "o't o'chiruvchi"), ("cameriera", "ofitsiant ayol"),
    ("guida turistica (persona)", "gid"), ("libero professionista", "erkin ishlovchi")],
   [("Mio fratello fa il programmatore.", "Akam dasturchi bo'lib ishlaydi."),
    ("Cerco un elettricista.", "Men elektrik qidiryapman.")]),
  ("Strumenti di lavoro", "Ish qurollari",
   [("scrivania", "ish stoli"), ("stampante", "printer"), ("schermo (lavoro)", "monitor"),
    ("tastiera (lavoro)", "klaviatura (ish)"), ("agenda (lavoro)", "ish kundaligi"),
    ("cartella", "papka"), ("archivio", "arxiv"), ("timbro (ufficio)", "muhr (idora)"),
    ("firma (documento)", "imzo (hujjat)"), ("fotocopia", "nusxa"),
    ("telefono fisso", "statsionar telefon"), ("badge", "propusk"),
    ("chiave dell'ufficio", "ofis kaliti"), ("attrezzo", "asbob"),
    ("guanti da lavoro", "ish qo'lqoplari"), ("divisa", "forma (ish kiyimi)")],
   [("La stampante non funziona.", "Printer ishlamayapti."),
    ("Metti i documenti in questa cartella.", "Hujjatlarni shu papkaga soling.")]),
  ("Le materie", "O'quv fanlari",
   [("matematica", "matematika"), ("storia", "tarix"), ("geografia", "geografiya"),
    ("fisica", "fizika"), ("chimica", "kimyo"), ("biologia", "biologiya"),
    ("letteratura", "adabiyot"), ("lingua straniera", "chet tili"),
    ("informatica", "informatika"), ("economia (materia)", "iqtisod (fan)"),
    ("diritto", "huquqshunoslik"), ("medicina (studi)", "tibbiyot (ta'lim)"),
    ("arte (materia)", "san'at (fan)"), ("educazione fisica", "jismoniy tarbiya"),
    ("musica (materia)", "musiqa (fan)"), ("filosofia", "falsafa")],
   [("La mia materia preferita è la storia.", "Sevimli fanim — tarix."),
    ("Studio informatica all'università.", "Universitetda informatika o'qiyman.")]),
  ("Giornata in ufficio", "Ofisdagi kun",
   [("riunione breve", "qisqa yig'ilish"), ("ordine del giorno (punto)", "kun tartibidagi masala"),
    ("relazione (documento)", "hisobot"), ("presentazione (lavoro)", "taqdimot (ish)"),
    ("collega nuovo", "yangi hamkasb"), ("turno", "smena"), ("straordinari", "qo'shimcha soatlar"),
    ("permesso (giorno)", "ruxsat kuni"), ("malattia (assenza)", "kasallik varaqasi"),
    ("timbrare", "kelishni qayd etmoq"), ("mensa", "oshxona (ish joyida)"),
    ("pausa caffè", "qahva tanaffusi"), ("obiettivo mensile", "oylik maqsad"),
    ("scadenza vicina", "yaqin muddat"), ("urgenza", "shoshilinchlik"),
    ("fine settimana lavorativa", "ish haftasining oxiri")],
   [("Ho una riunione alle dieci.", "Soat o'nda yig'ilishim bor."),
    ("Oggi ho fatto due ore di straordinario.", "Bugun ikki soat qo'shimcha ishladim.")]),
 ],

 "a2u5": [
  ("Le pulizie", "Tozalash ishlari",
   [("scopa", "supurgi"), ("secchio", "chelak"), ("straccio", "latta"),
    ("detersivo", "yuvish vositasi"), ("spugna", "gubka"), ("guanti di gomma", "rezina qo'lqop"),
    ("polvere", "chang"), ("macchia", "dog'"), ("spazzatura (sacco)", "axlat xaltasi"),
    ("riciclare (casa)", "saralab tashlamoq"), ("lavare i vetri", "oynani yuvmoq"),
    ("passare l'aspirapolvere", "chang yutmoq"), ("cambiare le lenzuola", "choyshabni almashtirmoq"),
    ("stendere", "yoyib qo'ymoq"), ("piegare i panni", "kiyimni buklamoq"),
    ("mettere in ordine", "joy-joyiga qo'ymoq")],
   [("Devo passare l'aspirapolvere.", "Chang yutishim kerak."),
    ("C'è una macchia sul tappeto.", "Gilamda dog' bor.")]),
  ("Piccole riparazioni", "Mayda ta'mirlar",
   [("martello", "bolg'a"), ("chiodo", "mix"), ("vite", "vint"), ("cacciavite", "otvyortka"),
    ("scala (attrezzo)", "narvon"), ("colla", "yelim"), ("nastro adesivo", "skotch"),
    ("lampadina", "lampochka"), ("rubinetto", "jo'mrak"), ("tubo", "quvur"),
    ("serratura", "qulf"), ("chiave inglese", "gayka kaliti"), ("avvitare", "burab qo'ymoq"),
    ("aggiustare", "tuzatib qo'ymoq"), ("sostituire (pezzo)", "almashtirib qo'ymoq"),
    ("gocciolare", "tomchilamoq")],
   [("Il rubinetto gocciola.", "Jo'mrak tomchilayapti."),
    ("Devo cambiare la lampadina.", "Lampochkani almashtirishim kerak.")]),
  ("Traslocare", "Ko'chish",
   [("scatolone", "katta quti"), ("furgone", "yuk mashinasi"), ("trasloco (giorno)", "ko'chish kuni"),
    ("mobili (insieme)", "mebel (to'plam)"), ("smontare", "qismlarga ajratmoq"),
    ("montare", "yig'moq"), ("caricare", "yuklamoq"), ("scaricare", "tushirmoq"),
    ("sistemare", "joylashtirmoq"), ("vicino nuovo", "yangi qo'shni"),
    ("quartiere nuovo", "yangi mahalla"), ("indirizzo nuovo", "yangi manzil"),
    ("chiavi nuove", "yangi kalitlar"), ("deposito", "ombor"),
    ("aiuto degli amici", "do'stlarning yordami"), ("festa di inaugurazione", "yangi uy bazmi")],
   [("Sabato facciamo il trasloco.", "Shanba kuni ko'chamiz."),
    ("Mi aiuti a caricare le scatole?", "Qutilarni yuklashga yordam berasanmi?")]),
  ("Casa e contratti", "Uy va shartnomalar",
   [("proprietario", "uy egasi (mulkdor)"), ("inquilino", "ijarachi"),
    ("contratto d'affitto", "ijara shartnomasi"), ("cauzione", "garov puli"),
    ("spese condominiali", "umumiy xarajatlar"), ("bolletta della luce", "elektr hisobi"),
    ("bolletta del gas", "gaz hisobi"), ("acqua (bolletta)", "suv hisobi"),
    ("riscaldamento centralizzato", "markaziy isitish"), ("ammobiliato", "mebelli"),
    ("disdire", "bekor qilmoq (shartnoma)"), ("rinnovare (contratto)", "yangilamoq (shartnoma)"),
    ("pagamento mensile", "oylik to'lov"), ("ritardo nel pagamento", "to'lovdagi kechikish"),
    ("garanzia (casa)", "kafolat (uy)"), ("agenzia immobiliare", "ko'chmas mulk agentligi")],
   [("Quanto è la cauzione?", "Garov puli qancha?"),
    ("L'appartamento è ammobiliato.", "Kvartira mebelli.")]),
 ],

 "a2u6": [
  ("Materiali", "Materiallar",
   [("legno", "yog'och"), ("metallo", "metall"), ("ferro", "temir"), ("oro", "oltin"),
    ("argento", "kumush"), ("vetro", "shisha (material)"), ("plastica (materiale)", "plastmassa"),
    ("carta (materiale)", "qog'oz (material)"), ("cotone", "paxta"), ("lana", "jun"),
    ("pelle (materiale)", "charm"), ("seta (materiale)", "ipak (material)"),
    ("gomma (materiale)", "rezina"), ("cemento", "sement"), ("mattone", "g'isht"),
    ("marmo", "marmar")],
   [("È fatto di legno.", "Bu yog'ochdan qilingan."),
    ("Preferisco il cotone alla lana.", "Men junga qaraganda paxtani afzal ko'raman.")]),
  ("Forme e superfici", "Shakl va yuza",
   [("triangolo", "uchburchak"), ("cerchio", "doira"), ("linea", "chiziq"),
    ("punto", "nuqta"), ("angolo (forma)", "burchak (shakl)"), ("bordo", "chekka"),
    ("centro (posizione)", "o'rta"), ("liscio", "silliq"), ("ruvido", "g'adir-budir"),
    ("morbido", "yumshoq"), ("duro", "qattiq"), ("sottile", "yupqa"), ("spesso (agg.)", "qalin"),
    ("profondo", "chuqur"), ("piatto (agg.)", "tekis"), ("appuntito", "o'tkir uchli")],
   [("La superficie è molto liscia.", "Yuzasi juda silliq."),
    ("Serve un tavolo rotondo.", "Dumaloq stol kerak.")]),
  ("Qualità e difetti", "Sifat va nuqsonlar",
   [("nuovo di zecca", "yap-yangi"), ("usato", "ishlatilgan"), ("di qualità", "sifatli"),
    ("scadente", "sifatsiz"), ("resistente", "mustahkam"), ("delicato", "nozik"),
    ("comodo", "qulay"), ("scomodo", "noqulay"), ("pratico", "amaliy"),
    ("inutile", "keraksiz"), ("utile (oggetto)", "asqotadigan"), ("raro", "kam uchraydigan"),
    ("comune", "keng tarqalgan"), ("originale (oggetto)", "asl"), ("falso", "soxta"),
    ("di seconda mano", "ikkinchi qo'l")],
   [("Questa borsa è molto resistente.", "Bu sumka juda mustahkam."),
    ("L'ho comprato di seconda mano.", "Buni ikkinchi qo'ldan sotib oldim.")]),
  ("Il contrario di…", "Qarama-qarshi ma'no",
   [("pieno", "to'la"), ("leggero (peso)", "yengil (og'irlik)"), ("rumoroso (luogo)", "shovqinli joy"),
    ("silenzioso", "jimjit"), ("luminoso", "yorug'"), ("buio", "qorong'i"),
    ("pulito (luogo)", "toza joy"), ("sporco (luogo)", "kir joy"), ("caldo (clima)", "iliq"),
    ("fresco (clima)", "salqin"), ("vicino (agg.)", "yaqin"), ("lontano (agg.)", "uzoq"),
    ("veloce (agg.)", "tezkor"), ("lento", "sust"), ("facile", "oson"), ("difficile", "qiyin")],
   [("La stanza è troppo buia.", "Xona juda qorong'i."),
    ("È stato più facile del previsto.", "Kutilganidan oson bo'ldi.")]),
 ],

 "a2u7": [
  ("Decidere", "Qaror qilish",
   [("scegliere", "tanlamoq"), ("preferire", "afzal ko'rmoq"), ("rifiutare", "rad etmoq"),
    ("accettare", "qabul qilmoq"), ("rimandare (decisione)", "kechiktirmoq"),
    ("pensarci su", "o'ylab ko'rmoq"), ("chiedere consiglio", "maslahat so'ramoq"),
    ("essere sicuro", "ishonch hosil qilmoq"), ("dubbio", "shubha"), ("scelta", "tanlov"),
    ("opzione", "variant"), ("vantaggio (scelta)", "yutuq"), ("svantaggio (scelta)", "salbiy tomon"),
    ("conseguenza (scelta)", "natija (qaror)"), ("cambiare idea", "fikrini o'zgartirmoq"),
    ("prendere tempo", "vaqt olmoq")],
   [("Non riesco a scegliere.", "Tanlay olmayapman."),
    ("Ho cambiato idea.", "Fikrimni o'zgartirdim.")]),
  ("Speranze e paure", "Umid va qo'rquvlar",
   [("speranza", "umid"), ("desiderio (forte)", "kuchli istak"), ("ambizione", "intilish"),
    ("timore", "hadik"), ("dubbio (futuro)", "ikkilanish"), ("fiducia (in sé)", "o'ziga ishonch"),
    ("fallire", "muvaffaqiyatsizlikka uchramoq"), ("riprovare", "qayta urinmoq"),
    ("arrendersi", "taslim bo'lmoq"), ("insistere (provare)", "qat'iyat ko'rsatmoq"),
    ("sogno nel cassetto", "ko'ngildagi orzu"), ("aspettativa", "kutilma"),
    ("delusione (futuro)", "umidsizlik"), ("motivazione (personale)", "ishtiyoq"),
    ("determinazione", "qat'iyat"), ("realizzare un sogno", "orzuni ro'yobga chiqarmoq")],
   [("Spero di riuscirci.", "Uddalashga umid qilaman."),
    ("Non mi arrendo mai.", "Men hech qachon taslim bo'lmayman.")]),
  ("Ostacoli", "To'siqlar",
   [("problema (pratico)", "muammo (amaliy)"), ("difficoltà", "qiyinchilik"),
    ("mancanza di tempo", "vaqt yetishmasligi"), ("mancanza di soldi", "pul yetishmasligi"),
    ("distanza", "masofa"), ("burocrazia (ostacolo)", "qog'ozbozlik"),
    ("permesso necessario", "kerakli ruxsat"), ("documento mancante", "yetishmayotgan hujjat"),
    ("costo alto", "yuqori narx"), ("tempo di attesa", "kutish vaqti"),
    ("cambiare piano", "rejani o'zgartirmoq"), ("trovare una soluzione", "yechim topmoq"),
    ("chiedere aiuto (problema)", "yordam so'ramoq"), ("superare (difficoltà)", "yengib o'tmoq"),
    ("rinviare (piano)", "keyinga surmoq"), ("rinunciare", "voz kechmoq")],
   [("Il problema principale è il tempo.", "Asosiy muammo — vaqt."),
    ("Abbiamo trovato una soluzione.", "Biz yechim topdik.")]),
  ("Parlare del futuro", "Kelajak haqida",
   [("fra un mese", "bir oydan keyin"), ("fra poco", "yaqinda"), ("presto o tardi", "ertami-kechmi"),
    ("un giorno", "bir kun kelib"), ("in futuro", "kelajakda"), ("a lungo termine (a2)", "uzoq muddatda"),
    ("temporaneo", "vaqtinchalik"), ("definitivo", "doimiy"), ("previsione (futuro)", "taxmin"),
    ("programma (piano)", "dastur"), ("progetto personale", "shaxsiy loyiha"),
    ("obiettivo dell'anno", "yillik maqsad"), ("passo successivo", "keyingi qadam"),
    ("prepararsi", "tayyorgarlik ko'rmoq"), ("organizzare", "uyushtirmoq"),
    ("aspettare con ansia", "intiqlik bilan kutmoq")],
   [("Fra un mese cambio casa.", "Bir oydan keyin uy almashtiraman."),
    ("Un giorno andrò in Italia.", "Bir kun kelib Italiyaga boraman.")]),
 ],

 "a2u8": [
  ("Telefono e internet", "Telefon va internet",
   [("videochiamata", "videoqo'ng'iroq"), ("chiamata persa", "javobsiz qo'ng'iroq"),
    ("segreteria telefonica", "avtojavob"), ("credito (telefono)", "balans"),
    ("ricaricare (telefono)", "hisobni to'ldirmoq"), ("wifi", "wifi"),
    ("dati mobili", "mobil internet"), ("segnale", "signal"), ("copertura", "qamrov"),
    ("chiamata internazionale", "xalqaro qo'ng'iroq"), ("prefisso", "kod (telefon)"),
    ("suoneria", "qo'ng'iroq ohangi"), ("silenzioso (telefono)", "ovozsiz rejim"),
    ("rubrica", "kontaktlar"), ("bloccare un numero", "raqamni bloklamoq"),
    ("aggiornare l'app", "ilovani yangilamoq")],
   [("Non ho segnale qui.", "Bu yerda signal yo'q."),
    ("Ti faccio una videochiamata.", "Senga videoqo'ng'iroq qilaman.")]),
  ("Posta e pacchi", "Pochta va pochtalar",
   [("lettera", "xat (qog'oz)"), ("busta", "konvert"), ("francobollo", "marka"),
    ("pacco", "posilka"), ("mittente", "jo'natuvchi"), ("destinatario", "qabul qiluvchi"),
    ("indirizzo completo", "to'liq manzil"), ("codice postale", "pochta indeksi"),
    ("spedire", "jo'natmoq"), ("consegna", "yetkazib berish"), ("corriere", "kuryer"),
    ("firma alla consegna", "qabul qilishda imzo"), ("raccomandata", "buyurtma xat"),
    ("ritirare (pacco)", "olib ketmoq"), ("tracciare", "kuzatib bormoq"),
    ("costo di spedizione", "jo'natish narxi")],
   [("Vorrei spedire questo pacco.", "Bu posilkani jo'natmoqchiman."),
    ("La consegna è prevista per domani.", "Yetkazib berish ertaga rejalashtirilgan.")]),
  ("Scrivere online", "Onlayn yozish",
   [("gruppo (chat)", "guruh"), ("messaggio vocale (chat)", "ovozli xabar (chat)"),
    ("emoji", "emoji"), ("foto (inviare)", "surat yubormoq"), ("video (inviare)", "video yubormoq"),
    ("link", "havola"), ("copiare", "nusxa olmoq"), ("incollare", "joylashtirmoq"),
    ("cancellare (messaggio)", "xabarni o'chirmoq"), ("rispondere subito", "darrov javob bermoq"),
    ("visualizzato", "ko'rildi"), ("online (stato)", "tarmoqda"),
    ("offline", "tarmoqdan tashqarida"), ("silenziare (chat)", "bildirishnomani o'chirmoq"),
    ("condividere (file)", "fayl ulashmoq"), ("password nuova", "yangi parol")],
   [("Ti ho mandato il link.", "Senga havolani yubordim."),
    ("Non ha ancora visualizzato.", "U hali ko'rmagan.")]),
  ("Reagire a quello che senti", "Munosabat bildirish",
   [("davvero!", "rostdan ham!"), ("che peccato", "afsus"), ("che bello!", "qanday yaxshi!"),
    ("che strano", "g'alati ekan"), ("non ci credo", "ishonmayman"),
    ("hai ragione", "sen haqsan"), ("non importa (reazione)", "zarari yo'q"),
    ("meno male", "yaxshiyamki"), ("purtroppo (reazione)", "afsuski (javob)"),
    ("mi raccomando", "ehtiyot bo'l"), ("stai tranquillo", "xotirjam bo'l"),
    ("congratulazioni", "qutlayman"), ("condoglianze", "bardam bo'ling"),
    ("in bocca al lupo (a2)", "omad bo'lsin"), ("grazie mille (forte)", "ming rahmat"),
    ("scusa tanto", "juda uzr")],
   [("Che peccato, mi dispiace!", "Afsus, juda achinaman!"),
    ("Congratulazioni per il lavoro nuovo!", "Yangi ish bilan qutlayman!")]),
 ],
}
