# -*- coding: utf-8 -*-
# Open questions Anorcha can ask, grouped by the unit whose vocabulary they use.
# They are never yes/no: the learner has to actually talk.
# (italiano, o'zbekcha)

GENERIC = {
 "a1": {
  "open": [("Ciao! Come stai oggi?", "Salom! Bugun qalaysan?"),
           ("Ciao! Che cosa fai adesso?", "Salom! Hozir nima qilyapsan?"),
           ("Ciao! Com'è andata la giornata?", "Salom! Kuning qanday o'tdi?")],
  "follow": [("Perché?", "Nega?"), ("E poi?", "Keyin-chi?"), ("Dimmi di più.", "Batafsilroq ayt."),
             ("Davvero? Racconta.", "Rostdanmi? Gapirib ber."), ("E tu?", "Sen-chi?")],
  "close": [("Grazie della chiacchierata! A presto.", "Suhbat uchun rahmat! Tez orada ko'rishguncha."),
            ("È stato bello parlare con te. Ciao!", "Sen bilan gaplashish yoqimli bo'ldi. Xayr!")],
 },
 "a2": {
  "open": [("Ciao! Che cosa hai fatto ieri?", "Salom! Kecha nima qilding?"),
           ("Ciao! Com'è andata la settimana?", "Salom! Hafta qanday o'tdi?"),
           ("Ciao! Che programmi hai per oggi?", "Salom! Bugunga qanday rejalaring bor?")],
  "follow": [("Perché proprio così?", "Nega aynan shunday?"), ("Com'è andata a finire?", "Oxiri nima bo'ldi?"),
             ("Fammi un esempio.", "Misol keltir."), ("E come ti sei sentito?", "O'zingni qanday his qilding?"),
             ("Lo rifaresti?", "Yana shunday qilarmiding?")],
  "close": [("Grazie! Mi hai raccontato un sacco di cose.", "Rahmat! Ko'p narsa aytib berding."),
            ("Bella chiacchierata, alla prossima!", "Yaxshi suhbat bo'ldi, keyingi safargacha!")],
 },
 "b1": {
  "open": [("Ciao! Di che cosa hai voglia di parlare oggi?", "Salom! Bugun nima haqda gaplashgming keladi?"),
           ("Ciao! Che cosa ti è successo di interessante?", "Salom! Qanday qiziq voqea bo'ldi?"),
           ("Ciao! Come va con i tuoi progetti?", "Salom! Rejalaring qanday ketyapti?")],
  "follow": [("Puoi spiegarti meglio?", "Buni kengroq tushuntira olasanmi?"),
             ("Che cosa ti fa pensare questo?", "Nega shunday deb o'ylaysan?"),
             ("Ci sono anche degli svantaggi?", "Kamchiliklari ham bormi?"),
             ("Come lo affronteresti?", "Buni qanday hal qilarding?"),
             ("Hai un esempio concreto?", "Aniq misoling bormi?")],
  "close": [("Grazie, mi hai dato da pensare. A presto!", "Rahmat, o'ylantirib qo'yding. Ko'rishguncha!"),
            ("Ottima conversazione. Continuiamo un'altra volta!", "Ajoyib suhbat. Boshqa safar davom ettiramiz!")],
 },
 "b2": {
  "open": [("Ciao! Partiamo da una domanda difficile, ti va?", "Salom! Qiyinroq savoldan boshlaymizmi?"),
           ("Ciao! Su che cosa hai cambiato idea ultimamente?", "Salom! Oxirgi paytlarda qaysi fikringni o'zgartirding?"),
           ("Ciao! Che cosa ti sta facendo riflettere in questo periodo?", "Salom! Shu kunlarda nima seni o'ylantiryapti?")],
  "follow": [("Su che dati ti basi?", "Qanday ma'lumotlarga tayanasan?"),
             ("Qualcuno potrebbe obiettare il contrario: che rispondi?", "Kimdir aksini aytishi mumkin: nima deysan?"),
             ("Riesci a sintetizzarlo in una frase?", "Buni bir jumlada ayta olasanmi?"),
             ("Quali sarebbero le conseguenze?", "Oqibatlari qanday bo'ladi?"),
             ("Dove sta il limite di questo ragionamento?", "Bu mulohazaning chegarasi qayerda?")],
  "close": [("Grazie per il confronto, è stato stimolante.", "Fikr almashganimiz uchun rahmat, juda qiziq bo'ldi."),
            ("Discussione davvero interessante. Alla prossima!", "Juda qiziqarli munozara bo'ldi. Keyingi safargacha!")],
 },
}

QUESTIONS = {
 # ---------------- A1 ----------------
 "a1u1": [("Come ti chiami?", "Isming nima?"),
          ("Di dove sei?", "Qayerliksan?"),
          ("Che lingue parli?", "Qaysi tillarda gapirasan?"),
          ("Quanti anni hai?", "Necha yoshdasan?"),
          ("Dove abiti adesso?", "Hozir qayerda yashaysan?"),
          ("Parlami un po' di te.", "O'zing haqingda gapirib ber."),
          ("Perché stai imparando questa lingua?", "Nega bu tilni o'rganyapsan?"),
          ("Come ti senti oggi e perché?", "Bugun o'zingni qanday his qilyapsan va nega?")],
 "a1u2": [("Chi c'è nella tua famiglia?", "Oilangda kimlar bor?"),
          ("Com'è tuo fratello o tua sorella?", "Akang yoki opang qanday odam?"),
          ("Chi ti somiglia di più in famiglia?", "Oilangda kimga ko'proq o'xshaysan?"),
          ("Descrivi il tuo migliore amico.", "Eng yaqin do'stingni tasvirlab ber."),
          ("Che carattere hai?", "Sening fe'ling qanday?"),
          ("Chi è la persona più importante per te?", "Sen uchun eng muhim odam kim?"),
          ("Com'era tua nonna o tuo nonno?", "Buving yoki boboyng qanday odam edi?"),
          ("Con chi passi più tempo?", "Ko'p vaqtni kim bilan o'tkazasan?")],
 "a1u3": [("Che ore sono adesso da te?", "Hozir sizda soat necha?"),
          ("A che ora ti alzi di solito?", "Odatda soat nechada turasan?"),
          ("Qual è il tuo giorno preferito della settimana? Perché?", "Haftaning qaysi kuni yoqadi? Nega?"),
          ("Quando è il tuo compleanno?", "Tug'ilgan kuning qachon?"),
          ("Quante ore dormi per notte?", "Kechasi necha soat uxlaysan?"),
          ("Che cosa fai di solito il sabato?", "Shanba kuni odatda nima qilasan?"),
          ("In che mese sei nato e com'è quel mese da te?", "Qaysi oyda tug'ilgansan, u oy sizda qanday bo'ladi?"),
          ("Quanto tempo studi ogni giorno?", "Har kuni qancha vaqt o'qiysan?")],
 "a1u4": [("Che cosa mangi di solito a colazione?", "Odatda nonushtaga nima yeysan?"),
          ("Qual è il tuo piatto preferito?", "Sevimli taoming qaysi?"),
          ("Che cosa hai mangiato ieri sera?", "Kecha kechqurun nima yeding?"),
          ("Sai cucinare? Che cosa?", "Ovqat pishira olasanmi? Nimani?"),
          ("Che frutta ti piace di più?", "Qaysi meva ko'proq yoqadi?"),
          ("Che cosa compri di solito al mercato?", "Bozordan odatda nima sotib olasan?"),
          ("Preferisci il tè o il caffè? Perché?", "Choynimi yoki qahvanimi afzal ko'rasan? Nega?"),
          ("Descrivimi un pasto di festa da voi.", "Sizdagi bayram dasturxonini tasvirlab ber.")],
 "a1u5": [("Com'è la tua casa?", "Uying qanday?"),
          ("Qual è la tua stanza preferita e perché?", "Qaysi xona yoqadi va nega?"),
          ("Che cosa c'è nella tua cucina?", "Oshxonangda nimalar bor?"),
          ("Che cosa tieni sempre in borsa?", "Sumkangda doim nima bo'ladi?"),
          ("Descrivi la stanza dove sei adesso.", "Hozir turgan xonangni tasvirlab ber."),
          ("Che cosa vorresti cambiare nella tua casa?", "Uyingda nimani o'zgartirmoqchisan?"),
          ("Dove tieni le chiavi di casa?", "Uy kalitlarini qayerda saqlaysan?"),
          ("Che vestiti metti quando fa freddo?", "Sovuqda qanday kiyim kiyasan?")],
 "a1u6": [("Com'è la città dove vivi?", "Yashayotgan shahring qanday?"),
          ("Che cosa c'è vicino a casa tua?", "Uying yaqinida nimalar bor?"),
          ("Come vai al lavoro o a scuola?", "Ishga yoki o'qishga qanday borasan?"),
          ("Dove fai la spesa di solito?", "Odatda qayerdan xarid qilasan?"),
          ("Qual è il posto più bello della tua città?", "Shahringdagi eng chiroyli joy qayer?"),
          ("Come si arriva dal centro a casa tua?", "Markazdan uyinggacha qanday boriladi?"),
          ("Ti piace fare shopping? Dove?", "Xarid qilish yoqadimi? Qayerda?"),
          ("Quanto costa un biglietto dell'autobus da voi?", "Sizda avtobus chiptasi qancha turadi?")],
 "a1u7": [("Descrivimi una tua giornata tipo.", "Odatdagi kuningni tasvirlab ber."),
          ("Che cosa fai appena ti svegli?", "Uyg'ongach birinchi nima qilasan?"),
          ("Che lavoro fai o che cosa studi?", "Nima ish qilasan yoki nima o'qiysan?"),
          ("Che cosa fai la sera prima di dormire?", "Kechqurun uxlashdan oldin nima qilasan?"),
          ("Che cosa fai ogni giorno senza eccezioni?", "Har kuni albatta nima qilasan?"),
          ("Che cosa non ti piace fare in casa?", "Uy ishlaridan nimani yoqtirmaysan?"),
          ("Quando trovi il tempo per studiare?", "O'qish uchun vaqtni qachon topasan?"),
          ("Che cosa hai fatto stamattina?", "Bugun ertalab nima qilding?")],
 "a1u8": [("Che cosa fai nel tempo libero?", "Bo'sh vaqtingda nima qilasan?"),
          ("Che tempo fa oggi da te?", "Bugun sizda ob-havo qanday?"),
          ("Qual è la tua stagione preferita? Perché?", "Sevimli fasling qaysi? Nega?"),
          ("Fai sport? Quale?", "Sport bilan shug'ullanasanmi? Qaysi turi?"),
          ("Che musica ti piace ascoltare?", "Qanday musiqa tinglashni yoqtirasan?"),
          ("Che cosa fai quando piove?", "Yomg'ir yog'ganda nima qilasan?"),
          ("Hai animali in casa? Parlamene.", "Uyingda hayvon bormi? Gapirib ber."),
          ("Che cosa faresti in una giornata libera perfetta?", "Mukammal bo'sh kunda nima qilarding?")],

 # ---------------- A2 ----------------
 "a2u1": [("Che cosa hai fatto lo scorso fine settimana?", "O'tgan dam olish kunlari nima qilding?"),
          ("Raccontami un ricordo della tua infanzia.", "Bolaligingdan bir xotirani aytib ber."),
          ("Dove sei cresciuto?", "Qayerda o'sgansan?"),
          ("Che cosa ti piaceva fare da bambino?", "Bolaligingda nima qilish yoqardi?"),
          ("Qual è stata la giornata più bella dell'anno scorso?", "O'tgan yilning eng yaxshi kuni qaysi bo'ldi?"),
          ("Com'è cambiata la tua vita negli ultimi anni?", "Oxirgi yillarda hayoting qanday o'zgardi?"),
          ("Raccontami come hai conosciuto il tuo migliore amico.", "Eng yaqin do'sting bilan qanday tanishganingni ayt."),
          ("Che cosa hai imparato di nuovo di recente?", "Yaqinda qanday yangi narsa o'rganding?")],
 "a2u2": [("Qual è stato il viaggio più bello che hai fatto?", "Eng yaxshi sayohating qaysi bo'ldi?"),
          ("Come preferisci viaggiare e perché?", "Qanday sayohat qilishni afzal ko'rasan va nega?"),
          ("Raccontami un problema che hai avuto in viaggio.", "Yo'lda bo'lgan bir muammoni aytib ber."),
          ("Che cosa metti sempre in valigia?", "Chamadonga doim nima solasan?"),
          ("Dove vorresti andare l'anno prossimo?", "Kelasi yili qayerga bormoqchisan?"),
          ("Preferisci l'albergo o la casa in affitto? Perché?", "Mehmonxonanimi yoki ijara uynimi afzal ko'rasan? Nega?"),
          ("Ti sei mai perso in una città nuova?", "Yangi shaharda adashib qolganmisan?"),
          ("Descrivi il posto più bello che hai visto.", "Ko'rgan eng go'zal joyingni tasvirlab ber.")],
 "a2u3": [("Come stai di salute in questo periodo?", "Shu kunlarda sog'liging qanday?"),
          ("Che cosa fai quando ti senti male?", "O'zingni yomon his qilganda nima qilasan?"),
          ("Raccontami l'ultima volta che sei andato dal medico.", "Oxirgi marta shifokorga qachon borganingni ayt."),
          ("Che cosa fai per stare in forma?", "Sog'lom bo'lish uchun nima qilasan?"),
          ("Dormi abbastanza? Racconta.", "Yetarli uxlaysanmi? Gapirib ber."),
          ("Che cosa ti stressa di più e come lo gestisci?", "Nima seni ko'proq charchatadi va qanday yengasan?"),
          ("Come si cura un raffreddore da voi?", "Sizda shamollashni qanday davolashadi?"),
          ("Che abitudine vorresti cambiare per stare meglio?", "Yaxshi his qilish uchun qaysi odatni o'zgartirmoqchisan?")],
 "a2u4": [("Che lavoro vorresti fare tra cinque anni?", "Besh yildan keyin qanday ish qilmoqchisan?"),
          ("Com'è una tua giornata di lavoro o di studio?", "Ish yoki o'qish kuning qanday o'tadi?"),
          ("Che cosa ti piace del tuo lavoro?", "Ishingda nima yoqadi?"),
          ("Raccontami del tuo primo lavoro.", "Birinchi ishing haqida gapirib ber."),
          ("Che materia ti piaceva a scuola?", "Maktabda qaysi fan yoqardi?"),
          ("Come ti organizzi quando hai troppo da fare?", "Ish ko'payib ketsa, qanday tartibga solasan?"),
          ("Preferisci lavorare da solo o in gruppo? Perché?", "Yolg'iz ishlashnimi yoki jamoadami? Nega?"),
          ("Che cosa diresti a un colloquio su di te?", "Suhbatda o'zing haqingda nima aytarding?")],
 "a2u5": [("Chi fa le faccende a casa tua?", "Uyingda yumushlarni kim qiladi?"),
          ("Qual è il lavoro di casa che odi di più?", "Qaysi uy ishini eng yomon ko'rasan?"),
          ("Hai mai avuto un problema in casa? Racconta.", "Uyda muammo bo'lganmi? Aytib ber."),
          ("Com'è vivere con altre persone?", "Boshqalar bilan yashash qanday?"),
          ("Che cosa compri ogni settimana?", "Har hafta nima sotib olasan?"),
          ("Come organizzi la spesa?", "Xaridni qanday rejalashtirasan?"),
          ("Descrivi la tua casa ideale.", "Orzuingdagi uyni tasvirlab ber."),
          ("Che regole ci sono in casa tua?", "Uyingda qanday qoidalar bor?")],
 "a2u6": [("Qual è il tuo colore preferito e perché?", "Sevimli rangin qaysi va nega?"),
          ("Descrivi un oggetto a cui tieni molto.", "Qadrli bir buyumingni tasvirlab ber."),
          ("Che differenza c'è tra la tua città e una città che hai visitato?", "Shahring va borgan boshqa shahar orasida qanday farq bor?"),
          ("Meglio una cosa economica o una di qualità? Perché?", "Arzonimi yoki sifatlimi? Nega?"),
          ("Che cosa compri online e che cosa in negozio?", "Nimani onlayn, nimani do'kondan olasan?"),
          ("Qual è la cosa più bella che hai comprato?", "Sotib olgan eng yaxshi narsang nima?"),
          ("Come descriveresti il tuo stile?", "O'z uslubingni qanday tasvirlarding?"),
          ("Confronta la vita in città e in campagna.", "Shahar va qishloq hayotini solishtir.")],
 "a2u7": [("Che progetti hai per quest'anno?", "Bu yilga qanday rejalaring bor?"),
          ("Che cosa farai se non funziona il tuo piano?", "Reja ishlamasa, nima qilasan?"),
          ("Qual è il tuo sogno più grande?", "Eng katta orzuing nima?"),
          ("Dove ti vedi tra dieci anni?", "O'n yildan keyin o'zingni qayerda ko'rasan?"),
          ("Che cosa vorresti imparare e perché?", "Nimani o'rganmoqchisan va nega?"),
          ("Che cosa ti impedisce di realizzare i tuoi piani?", "Rejalaringni amalga oshirishga nima to'sqinlik qiladi?"),
          ("Come decidi quando hai due possibilità?", "Ikki imkoniyat bo'lsa, qanday qaror qilasan?"),
          ("Che cosa faresti se avessi un mese libero?", "Bir oy bo'sh vaqting bo'lsa, nima qilarding?")],
 "a2u8": [("Preferisci chiamare o scrivere? Perché?", "Qo'ng'iroqnimi yoki yozishnimi afzal ko'rasan? Nega?"),
          ("Quanto tempo passi al telefono?", "Telefonda qancha vaqt o'tkazasan?"),
          ("Come chiedi aiuto quando non capisci?", "Tushunmaganingda qanday yordam so'raysan?"),
          ("Raccontami di una telefonata importante che hai fatto.", "Muhim bir telefon suhbatingni aytib ber."),
          ("Che cosa scrivi in un messaggio di auguri?", "Tabrik xabarida nima yozasan?"),
          ("Come ti scusi quando sbagli?", "Xato qilganingda qanday uzr so'raysan?"),
          ("Che cosa fai se qualcuno parla troppo veloce?", "Kimdir juda tez gapirsa, nima qilasan?"),
          ("Come si ringrazia bene nella tua lingua?", "Sening tilingda qanday qilib chiroyli rahmat aytiladi?")],
}

QUESTIONS.update({
 # ---------------- B1 ----------------
 "b1u1": [("Qual è un'opinione che difendi sempre?", "Doim himoya qiladigan fikring qanday?"),
          ("Su che cosa non sei mai d'accordo con i tuoi amici?", "Do'stlaring bilan nimada kelisholmaysan?"),
          ("Come convinci qualcuno che ha torto?", "Nohaq odamni qanday ishontirasan?"),
          ("Meglio dire sempre la verità o a volte tacere?", "Doim rostini aytish kerakmi yoki ba'zan sukut saqlash?"),
          ("Che cosa pensi dei social network?", "Ijtimoiy tarmoqlar haqida nima deb o'ylaysan?"),
          ("Qual è secondo te il problema più urgente della tua città?", "Shahringdagi eng dolzarb muammo nima?"),
          ("Ti è mai capitato di cambiare idea? Racconta.", "Fikringni o'zgartirganmisan? Aytib ber."),
          ("Come si fa a discutere senza litigare?", "Janjallashmasdan qanday bahslashish mumkin?")],
 "b1u2": [("Raccontami l'esperienza più strana che hai vissuto.", "Boshingdan kechgan eng g'alati voqeani aytib ber."),
          ("Qual è stato il momento più bello dell'anno scorso?", "O'tgan yilning eng yaxshi damlari qaysi edi?"),
          ("Raccontami una volta in cui hai avuto paura.", "Qo'rqqan bir paytingni aytib ber."),
          ("C'è un viaggio che ti ha cambiato? Perché?", "Seni o'zgartirgan sayohat bormi? Nega?"),
          ("Raccontami un imprevisto e come l'hai risolto.", "Kutilmagan hodisani va uni qanday hal qilganingni ayt."),
          ("Qual è la storia più divertente che sai raccontare?", "Aytib bera oladigan eng kulgili voqeang qaysi?"),
          ("Che cosa rifaresti e che cosa no?", "Nimani qaytadan qilarding, nimani esa yo'q?"),
          ("Descrivi un posto che ricordi nei minimi dettagli.", "Mayda tafsilotlarigacha eslaydigan joyingni tasvirlab ber.")],
 "b1u3": [("Che cosa cerchi in un lavoro?", "Ishdan nima izlaysan?"),
          ("Qual è la parte più difficile del tuo lavoro?", "Ishingning eng qiyin tomoni nima?"),
          ("Come gestisci un collega difficile?", "Qiyin hamkasb bilan qanday ish tutasan?"),
          ("Preferiresti guadagnare di più o avere più tempo libero?", "Ko'proq maoshnimi yoki ko'proq bo'sh vaqtnimi tanlarding?"),
          ("Che cosa diresti per chiedere un aumento?", "Maosh oshirishni so'rash uchun nima derding?"),
          ("Come ti prepari a un colloquio importante?", "Muhim suhbatga qanday tayyorlanasan?"),
          ("Il lavoro da remoto è meglio o peggio? Perché?", "Masofaviy ish yaxshiroqmi yoki yomonroq? Nega?"),
          ("Che competenza vorresti sviluppare quest'anno?", "Bu yil qaysi ko'nikmani rivojlantirmoqchisan?")],
 "b1u4": [("Quanto tempo passi online ogni giorno?", "Har kuni internetda qancha vaqt o'tkazasan?"),
          ("La tecnologia ci ha reso più liberi o più schiavi?", "Texnologiya bizni erkinroq qildimi yoki qulroqmi?"),
          ("Come verifichi se una notizia è vera?", "Xabar rostligini qanday tekshirasan?"),
          ("Che app non potresti eliminare e perché?", "Qaysi ilovani o'chira olmaysan va nega?"),
          ("Che cosa pensi dell'intelligenza artificiale?", "Sun'iy intellekt haqida nima deb o'ylaysan?"),
          ("Ti è mai successo un guaio con la tecnologia?", "Texnika bilan bog'liq muammo bo'lganmi?"),
          ("I bambini dovrebbero usare lo smartphone? Da che età?", "Bolalar smartfon ishlatishi kerakmi? Necha yoshdan?"),
          ("Come proteggi i tuoi dati personali?", "Shaxsiy ma'lumotlaringni qanday himoya qilasan?")],
 "b1u5": [("Che cosa fai concretamente per l'ambiente?", "Atrof-muhit uchun amalda nima qilasan?"),
          ("La tua città è vivibile? Che cosa manca?", "Shahring yashash uchun qulaymi? Nima yetishmaydi?"),
          ("Chi dovrebbe risolvere il problema dei rifiuti?", "Chiqindi muammosini kim hal qilishi kerak?"),
          ("Faresti volontariato? In che campo?", "Ko'ngilli bo'lib ishlarmiding? Qaysi sohada?"),
          ("Che cosa cambieresti nella tua società?", "Jamiyatingda nimani o'zgartirarding?"),
          ("Il trasporto pubblico da voi come funziona?", "Sizda jamoat transporti qanday ishlaydi?"),
          ("Quanto conta il parere della comunità dove vivi?", "Yashaydigan joyingda jamoa fikri qanchalik muhim?"),
          ("Che cosa faresti con un piccolo budget per il tuo quartiere?", "Mahalling uchun kichik mablag' bo'lsa, nima qilarding?")],
 "b1u6": [("Che cosa rende un'amicizia solida?", "Do'stlikni nima mustahkam qiladi?"),
          ("Come reagisci quando qualcuno ti delude?", "Kimdir ko'nglingni qoldirsa, qanday munosabatda bo'lasan?"),
          ("È facile per te esprimere i sentimenti?", "His-tuyg'ularingni ifodalash osonmi?"),
          ("Raccontami di una riconciliazione importante.", "Muhim bir yarashuvni aytib ber."),
          ("Che consiglio daresti a chi sta attraversando un periodo difficile?", "Qiyin damlarni boshdan kechirayotganga qanday maslahat berarding?"),
          ("Quanto è importante la fiducia in una relazione?", "Munosabatda ishonch qanchalik muhim?"),
          ("Come si mantiene un'amicizia a distanza?", "Uzoqdagi do'stlikni qanday saqlash mumkin?"),
          ("Che cosa ti fa arrabbiare di più e perché?", "Nima seni ko'proq jahlingni chiqaradi va nega?")],
 "b1u7": [("Qual è la festa più importante da voi? Come si festeggia?", "Sizdagi eng muhim bayram qaysi? Qanday nishonlanadi?"),
          ("Che tradizione della tua famiglia ti piace di più?", "Oilangdagi qaysi an'ana ko'proq yoqadi?"),
          ("Com'è l'ospitalità nel tuo paese?", "Yurtingda mehmondo'stlik qanday?"),
          ("C'è un piatto tradizionale che sai preparare?", "Tayyorlay oladigan milliy taoming bormi?"),
          ("Che cosa ti ha sorpreso di un'altra cultura?", "Boshqa madaniyatda nima seni hayratlantirdi?"),
          ("Quale usanza del tuo paese spiegheresti a uno straniero?", "Chet ellikka qaysi urf-odatni tushuntirarding?"),
          ("Le tradizioni vanno conservate o possono cambiare?", "An'analar saqlanishi kerakmi yoki o'zgarishi mumkinmi?"),
          ("Qual è un proverbio che usi spesso?", "Tez-tez ishlatadigan maqoling qaysi?")],
 "b1u8": [("Raccontami l'ultima volta che hai avuto a che fare con la burocrazia.", "Oxirgi marta rasmiyatchilik bilan qanday to'qnash kelganingni ayt."),
          ("Come faresti un reclamo per un servizio scadente?", "Sifatsiz xizmat uchun qanday shikoyat qilarding?"),
          ("Che documenti servono da voi per affittare una casa?", "Sizda uy ijaraga olish uchun qanday hujjatlar kerak?"),
          ("Ti fidi delle banche? Perché?", "Banklarga ishonasanmi? Nega?"),
          ("Che cosa faresti se ti rubassero il portafoglio?", "Hamyoning o'g'irlansa, nima qilarding?"),
          ("Come si risolve un problema con un'azienda?", "Kompaniya bilan muammoni qanday hal qilasan?"),
          ("Qual è il servizio pubblico che funziona meglio da voi?", "Sizda qaysi davlat xizmati yaxshi ishlaydi?"),
          ("Che cosa consiglieresti a chi arriva nel tuo paese?", "Yurtingga endi kelgan odamga nima maslahat berarding?")],

 # ---------------- B2 ----------------
 "b2u1": [("Convincimi che la tua città è il posto migliore in cui vivere.", "Shahring yashash uchun eng yaxshi joy ekaniga meni ishontir."),
          ("Qual è un'idea diffusa che secondo te è sbagliata?", "Keng tarqalgan qaysi fikr sening nazaringda noto'g'ri?"),
          ("Come distingui un argomento solido da uno debole?", "Kuchli dalilni zaifidan qanday ajratasan?"),
          ("È giusto cambiare idea in pubblico?", "Omma oldida fikrni o'zgartirish to'g'rimi?"),
          ("Come negozieresti una cosa importante?", "Muhim narsani qanday muzokara qilarding?"),
          ("Che cosa rende un discorso davvero convincente?", "Nutqni nima haqiqatan ishonarli qiladi?"),
          ("Quando è meglio tacere invece di discutere?", "Qachon bahslashgandan ko'ra jim turgan ma'qul?"),
          ("Difendi un'opinione che non condividi: ce la fai?", "O'zing qo'shilmaydigan fikrni himoya qila olasanmi?")],
 "b2u2": [("Che cosa pensi dell'aumento dei prezzi?", "Narxlarning o'sishi haqida nima deysan?"),
          ("Il lavoro precario è inevitabile?", "Beqaror bandlik muqarrarmi?"),
          ("Avvieresti un'attività tua? Quale?", "O'z biznesingni ocharmiding? Qanaqasini?"),
          ("Meglio uno stipendio sicuro o un rischio con più guadagno?", "Kafolatli maoshmi yoki daromadi ko'p tavakkalmi?"),
          ("Come si gestisce un budget familiare?", "Oila byudjetini qanday boshqarasan?"),
          ("L'automazione distruggerà posti di lavoro?", "Avtomatlashtirish ish o'rinlarini yo'q qiladimi?"),
          ("Che cosa dovrebbe fare lo stato per i giovani?", "Davlat yoshlar uchun nima qilishi kerak?"),
          ("Il successo economico è merito o fortuna?", "Iqtisodiy muvaffaqiyat mehnatningmi yoki omadningmi?")],
 "b2u3": [("Ti fidi della scienza? Sempre?", "Fanga ishonasanmi? Doimmi?"),
          ("Come spiegheresti l'intelligenza artificiale a un bambino?", "Sun'iy intellektni bolaga qanday tushuntirarding?"),
          ("Quali rischi vedi nella tecnologia di oggi?", "Bugungi texnologiyada qanday xavflarni ko'rasan?"),
          ("La ricerca dovrebbe essere finanziata dallo stato o dai privati?", "Tadqiqotni davlatmi yoki xususiy sektormi moliyalashi kerak?"),
          ("Che scoperta vorresti vedere nella tua vita?", "Hayotingda qanday kashfiyotni ko'rmoqchisan?"),
          ("Come si riconosce una notizia pseudoscientifica?", "Soxta ilmiy xabarni qanday tanish mumkin?"),
          ("L'uomo dovrebbe colonizzare altri pianeti?", "Inson boshqa sayyoralarni o'zlashtirishi kerakmi?"),
          ("Quanto conta l'etica nella ricerca?", "Tadqiqotda axloq qanchalik muhim?")],
 "b2u4": [("Qual è il film o il libro che ti ha segnato di più?", "Senga eng ko'p ta'sir qilgan film yoki kitob qaysi?"),
          ("L'arte deve piacere o deve far pensare?", "San'at yoqishi kerakmi yoki o'ylantirishi?"),
          ("Fammi una recensione di qualcosa che hai visto di recente.", "Yaqinda ko'rgan narsangga taqriz ber."),
          ("La traduzione può rendere davvero la poesia?", "Tarjima she'r ta'sirini bera oladimi?"),
          ("Che cosa distingue un classico da un successo passeggero?", "Klassikani o'tkinchi mashhurlikdan nima ajratadi?"),
          ("Chi decide che cosa è arte?", "Nima san'at ekanini kim hal qiladi?"),
          ("Preferisci il cinema o il teatro? Argomenta.", "Kinonimi yoki teatrnimi afzal ko'rasan? Asosla."),
          ("Un'opera può essere separata dal suo autore?", "Asarni muallifidan ajratib bo'ladimi?")],
 "b2u5": [("Che cosa significa davvero integrarsi?", "Moslashish aslida nimani anglatadi?"),
          ("La scuola prepara alla vita reale?", "Maktab hayotga tayyorlaydimi?"),
          ("Quanto è libera l'informazione oggi?", "Bugun axborot qanchalik erkin?"),
          ("Che cosa spinge una persona a emigrare?", "Odamni chet elga ketishga nima undaydi?"),
          ("Come si combatte la disuguaglianza?", "Tengsizlikka qanday qarshi kurashiladi?"),
          ("La tua generazione sta meglio o peggio della precedente?", "Sening avloding oldingisidan yaxshiroq yashayaptimi?"),
          ("Che ruolo dovrebbero avere i giovani in politica?", "Siyosatda yoshlar qanday rol o'ynashi kerak?"),
          ("Come cambieresti il sistema sanitario?", "Sog'liqni saqlash tizimini qanday o'zgartirarding?")],
 "b2u6": [("Racconta una figuraccia con ironia.", "Bir noqulay holatni hazil bilan aytib ber."),
          ("Qual è un modo di dire della tua lingua difficile da tradurre?", "Tilingdagi tarjima qilish qiyin bo'lgan ibora qaysi?"),
          ("Quando usi il registro formale e quando quello informale?", "Qachon rasmiy, qachon norasmiy uslubda gapirasan?"),
          ("Come si fa a dire una cosa spiacevole con garbo?", "Yoqimsiz gapni qanday odob bilan aytish mumkin?"),
          ("L'ironia si capisce sempre? Racconta un equivoco.", "Kinoya doim tushuniladimi? Bir tushunmovchilikni ayt."),
          ("Che cosa fa ridere nella tua cultura?", "Sening madaniyatingda nima kulgili hisoblanadi?"),
          ("Spiegami un proverbio della tua lingua.", "Tilingdagi bir maqolni tushuntir."),
          ("Quando è meglio essere diretti e quando no?", "Qachon to'g'ridan-to'g'ri gapirgan yaxshi, qachon yo'q?")],
 "b2u7": [("Come tieni l'equilibrio tra lavoro e vita privata?", "Ish va shaxsiy hayot muvozanatini qanday saqlaysan?"),
          ("Che cosa fai quando sei sotto pressione?", "Bosim ostida qolganingda nima qilasan?"),
          ("Parlare di salute mentale è ancora un tabù?", "Ruhiy salomatlik haqida gapirish hali ham taqiqli mavzumi?"),
          ("Qual è l'abitudine che ti ha cambiato la vita?", "Hayotingni o'zgartirgan odat qaysi?"),
          ("Come si costruisce una routine che dura?", "Uzoq davom etadigan tartibni qanday qurish mumkin?"),
          ("Dormire, mangiare o muoversi: che cosa curi di più?", "Uyqu, ovqat yoki harakat: qaysi biriga ko'proq e'tibor berasan?"),
          ("Che consiglio daresti per invecchiare bene?", "Sog'lom qarish uchun qanday maslahat berarding?"),
          ("Come stacchi davvero dal lavoro?", "Ishdan qanday qilib butunlay uzilasan?")],
 "b2u8": [("Che cosa ti spinge a studiare o lavorare all'estero?", "Chet elda o'qish yoki ishlashga nima undaydi?"),
          ("Qual è la difficoltà più grande per chi si trasferisce?", "Ko'chib kelgan odam uchun eng katta qiyinchilik nima?"),
          ("Presentati come faresti a un colloquio internazionale.", "Xalqaro suhbatdagidek o'zingni tanishtir."),
          ("Come si costruisce una rete professionale da zero?", "Noldan kasbiy tarmoqni qanday quriladi?"),
          ("Che cosa hai imparato vivendo tra due culture?", "Ikki madaniyat orasida yashab nima o'rganding?"),
          ("Torneresti a vivere nel tuo paese? Perché?", "Yurtingga qaytib yasharmiding? Nega?"),
          ("Come presenteresti un progetto a un pubblico esigente?", "Talabchan auditoriyaga loyihani qanday taqdim etarding?"),
          ("Che consiglio daresti a chi parte domani?", "Ertaga yo'lga chiqadigan odamga qanday maslahat berarding?")],
})
